/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty0_ParseError lyr_ty0_ParseError;
typedef struct lyr_ty1_ParseErrorKind lyr_ty1_ParseErrorKind;
typedef struct lyr_ty2_ParseErrorKind_Empty lyr_ty2_ParseErrorKind_Empty;
typedef struct lyr_ty3_ParseErrorKind_Invalid lyr_ty3_ParseErrorKind_Invalid;
typedef struct lyr_ty4_ParseErrorKind_Overflow lyr_ty4_ParseErrorKind_Overflow;
typedef struct lyr_vt_ty5 lyr_vt_ty5;
const char lyr_ifid_ty5[] = "std.core.Error";
typedef struct lyr_ty6_Ordering lyr_ty6_Ordering;
typedef struct lyr_ty7_Ordering_Less lyr_ty7_Ordering_Less;
typedef struct lyr_ty8_Ordering_Equal lyr_ty8_Ordering_Equal;
typedef struct lyr_ty9_Ordering_Greater lyr_ty9_Ordering_Greater;
typedef struct lyr_ty10_Exception lyr_ty10_Exception;
typedef struct lyr_vt_ty11 lyr_vt_ty11;
const char lyr_ifid_ty11[] = "std.core.Hasher";
typedef struct lyr_ty12_Sip lyr_ty12_Sip;
typedef struct lyr_ty13_DefaultHasher lyr_ty13_DefaultHasher;
typedef struct lyr_ty14_FixedHasher lyr_ty14_FixedHasher;
typedef struct lyr_ty15_Fnv1a64 lyr_ty15_Fnv1a64;
struct lyr_ty2_ParseErrorKind_Empty {
    uint8_t lyr_unit;
};
struct lyr_ty3_ParseErrorKind_Invalid {
    uint8_t lyr_unit;
};
struct lyr_ty4_ParseErrorKind_Overflow {
    uint8_t lyr_unit;
};
struct lyr_ty1_ParseErrorKind { uint32_t tag; };
_Static_assert(sizeof(lyr_ty1_ParseErrorKind) == 4, "layout of lyr_ty1_ParseErrorKind");
struct lyr_ty0_ParseError {
    lyr_ty1_ParseErrorKind f_kind;
};
struct lyr_vt_ty5 {
    const LyrDesc *desc;
    void (*s0)(LyrIface);
    void (*s1)(LyrIface);
};
struct lyr_ty7_Ordering_Less {
    uint8_t lyr_unit;
};
struct lyr_ty8_Ordering_Equal {
    uint8_t lyr_unit;
};
struct lyr_ty9_Ordering_Greater {
    uint8_t lyr_unit;
};
struct lyr_ty6_Ordering { uint32_t tag; };
_Static_assert(sizeof(lyr_ty6_Ordering) == 4, "layout of lyr_ty6_Ordering");
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface5;
struct lyr_ty10_Exception {
    LyrObj header;
    LyrStr *f_text;
    lyr_opt_iface5 f_inner;
};
_Static_assert(sizeof(lyr_ty10_Exception) == 40, "layout of lyr_ty10_Exception");
_Static_assert(offsetof(lyr_ty10_Exception, f_text) == 8, "layout of lyr_ty10_Exception");
_Static_assert(offsetof(lyr_ty10_Exception, f_inner) == 16, "layout of lyr_ty10_Exception");
static const uint64_t lyr_refmap_ty10[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty10_Exception = { sizeof(lyr_ty10_Exception), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty10, "std.core.Exception", NULL };
struct lyr_vt_ty11 {
    const LyrDesc *desc;
    void (*s0)(LyrIface);
    void (*s1)(LyrIface);
    void (*s2)(LyrIface);
    void (*s3)(LyrIface);
    void (*s4)(LyrIface);
};
struct lyr_ty12_Sip {
    uint64_t f_v0;
    uint64_t f_v1;
    uint64_t f_v2;
    uint64_t f_v3;
    uint64_t f_tail;
    int64_t f_pending;
    int64_t f_length;
};
struct lyr_ty13_DefaultHasher {
    lyr_ty12_Sip f_state;
};
struct lyr_ty14_FixedHasher {
    lyr_ty12_Sip f_state;
};
struct lyr_ty15_Fnv1a64 {
    uint64_t f_state;
};

/* module-level bindings */
double lyr_g0_float_infinity = 0;
double lyr_g1_float_nan = 0;
float lyr_g2_float32_infinity = 0;
float lyr_g3_float32_nan = 0;
uint64_t lyr_g4_emptyGroup = 0;
uint64_t lyr_g5_lowBits = 0;
uint64_t lyr_g6_highBits = 0;

/* string literals */
static const LyrStaticStr(7) lyr_lit0 = LYR_STR_INIT("alias ");
static const LyrStaticStr(7) lyr_lit1 = LYR_STR_INIT("widen ");
static const LyrStaticStr(6) lyr_lit2 = LYR_STR_INIT("wrap ");
static const LyrStaticStr(2) lyr_lit3 = LYR_STR_INIT(" ");
static const LyrStaticStr(5) lyr_lit4 = LYR_STR_INIT("sat ");
static const LyrStaticStr(7) lyr_lit5 = LYR_STR_INIT("trunc ");
static const LyrStaticStr(6) lyr_lit6 = LYR_STR_INIT("char ");
static const LyrStaticStr(3) lyr_lit7 = LYR_STR_INIT("ok");
static const LyrStaticStr(3) lyr_lit8 = LYR_STR_INIT("no");
static const LyrStaticStr(5) lyr_lit9 = LYR_STR_INIT("shl ");
static const LyrStaticStr(8) lyr_lit10 = LYR_STR_INIT("wrapop ");
static const LyrStaticStr(7) lyr_lit11 = LYR_STR_INIT("swrap ");
static const LyrStaticStr(7) lyr_lit12 = LYR_STR_INIT("float ");
static const LyrStaticStr(6) lyr_lit13 = LYR_STR_INIT("fdiv ");
static const LyrStaticStr(5) lyr_lit14 = LYR_STR_INIT("f32 ");
static const LyrStaticStr(5) lyr_lit15 = LYR_STR_INIT("cmp ");
static const LyrStaticStr(5) lyr_lit16 = LYR_STR_INIT("big ");

/* prototypes */
int64_t lyr_main_widen16(int16_t l0_x);
int16_t lyr_main_takeUint8(uint8_t l0_x);
int64_t lyr_main_shl(int64_t l0_a, int64_t l1_b);
int64_t lyr_main_shr(int64_t l0_a, int64_t l1_b);
uint8_t lyr_main_shrU8(uint8_t l0_a, uint8_t l1_b);
uint8_t lyr_main_addWrapU8(uint8_t l0_a, uint8_t l1_b);
uint8_t lyr_main_subWrapU8(uint8_t l0_a, uint8_t l1_b);
uint8_t lyr_main_mulWrapU8(uint8_t l0_a, uint8_t l1_b);
int8_t lyr_main_addWrapI8(int8_t l0_a, int8_t l1_b);
int8_t lyr_main_subWrapI8(int8_t l0_a, int8_t l1_b);
double lyr_main_fadd(double l0_a, double l1_b);
double lyr_main_fsub(double l0_a, double l1_b);
double lyr_main_fdiv(double l0_a, double l1_b);
double lyr_main_frem(double l0_a, double l1_b);
float lyr_main_f32add(float l0_a, float l1_b);
int8_t lyr_main_toI8(double l0_x);
uint8_t lyr_main_toU8(double l0_x);
int64_t lyr_main_toInt(double l0_x);
LYR_NOINLINE int64_t lyr_main_main(void);
void lyr__globals__9ee5f9b5(void);
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b);
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b);

#line 19 "programs/arith.lyr"
int64_t lyr_main_widen16(int16_t l0_x) {
    int16_t t0 = 0;
    int64_t t1 = 0;
bb0:;
#line 19
    t0 = l0_x;
#line 19
    t1 = (int64_t)t0;
#line 19
    return t1;
}

#line 20 "programs/arith.lyr"
int16_t lyr_main_takeUint8(uint8_t l0_x) {
    uint8_t t0 = 0;
    int16_t t1 = 0;
bb0:;
#line 20
    t0 = l0_x;
#line 20
    t1 = (int16_t)t0;
#line 20
    return t1;
}

#line 21 "programs/arith.lyr"
int64_t lyr_main_shl(int64_t l0_a, int64_t l1_b) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    int64_t t2 = 0;
bb0:;
#line 21
    t0 = l0_a;
#line 21
    t1 = l1_b;
#line 21
    t2 = LYR_CHECKED_SHL(int64_t, uint64_t, 64, t0, t1);
#line 21
    return t2;
}

#line 22 "programs/arith.lyr"
int64_t lyr_main_shr(int64_t l0_a, int64_t l1_b) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    int64_t t2 = 0;
bb0:;
#line 22
    t0 = l0_a;
#line 22
    t1 = l1_b;
#line 22
    t2 = LYR_CHECKED_SHR(int64_t, uint64_t, 64, t0, t1);
#line 22
    return t2;
}

#line 23 "programs/arith.lyr"
uint8_t lyr_main_shrU8(uint8_t l0_a, uint8_t l1_b) {
    uint8_t t0 = 0;
    uint8_t t1 = 0;
    uint8_t t2 = 0;
bb0:;
#line 23
    t0 = l0_a;
#line 23
    t1 = l1_b;
#line 23
    t2 = LYR_CHECKED_SHR(uint8_t, uint8_t, 8, t0, t1);
#line 23
    return t2;
}

#line 24 "programs/arith.lyr"
uint8_t lyr_main_addWrapU8(uint8_t l0_a, uint8_t l1_b) {
    uint8_t t0 = 0;
    uint8_t t1 = 0;
    uint8_t t2 = 0;
bb0:;
#line 24
    t0 = l0_a;
#line 24
    t1 = l1_b;
#line 24
    t2 = LYR_WRAP_ADD(uint8_t, uint8_t, t0, t1);
#line 24
    return t2;
}

#line 25 "programs/arith.lyr"
uint8_t lyr_main_subWrapU8(uint8_t l0_a, uint8_t l1_b) {
    uint8_t t0 = 0;
    uint8_t t1 = 0;
    uint8_t t2 = 0;
bb0:;
#line 25
    t0 = l0_a;
#line 25
    t1 = l1_b;
#line 25
    t2 = LYR_WRAP_SUB(uint8_t, uint8_t, t0, t1);
#line 25
    return t2;
}

#line 26 "programs/arith.lyr"
uint8_t lyr_main_mulWrapU8(uint8_t l0_a, uint8_t l1_b) {
    uint8_t t0 = 0;
    uint8_t t1 = 0;
    uint8_t t2 = 0;
bb0:;
#line 26
    t0 = l0_a;
#line 26
    t1 = l1_b;
#line 26
    t2 = LYR_WRAP_MUL(uint8_t, uint8_t, t0, t1);
#line 26
    return t2;
}

#line 27 "programs/arith.lyr"
int8_t lyr_main_addWrapI8(int8_t l0_a, int8_t l1_b) {
    int8_t t0 = 0;
    int8_t t1 = 0;
    int8_t t2 = 0;
bb0:;
#line 27
    t0 = l0_a;
#line 27
    t1 = l1_b;
#line 27
    t2 = LYR_WRAP_ADD(int8_t, uint8_t, t0, t1);
#line 27
    return t2;
}

#line 28 "programs/arith.lyr"
int8_t lyr_main_subWrapI8(int8_t l0_a, int8_t l1_b) {
    int8_t t0 = 0;
    int8_t t1 = 0;
    int8_t t2 = 0;
bb0:;
#line 28
    t0 = l0_a;
#line 28
    t1 = l1_b;
#line 28
    t2 = LYR_WRAP_SUB(int8_t, uint8_t, t0, t1);
#line 28
    return t2;
}

#line 29 "programs/arith.lyr"
double lyr_main_fadd(double l0_a, double l1_b) {
    double t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 29
    t0 = l0_a;
#line 29
    t1 = l1_b;
#line 29
    t2 = (t0 + t1);
#line 29
    return t2;
}

#line 30 "programs/arith.lyr"
double lyr_main_fsub(double l0_a, double l1_b) {
    double t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 30
    t0 = l0_a;
#line 30
    t1 = l1_b;
#line 30
    t2 = (t0 - t1);
#line 30
    return t2;
}

#line 31 "programs/arith.lyr"
double lyr_main_fdiv(double l0_a, double l1_b) {
    double t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 31
    t0 = l0_a;
#line 31
    t1 = l1_b;
#line 31
    t2 = (t0 / t1);
#line 31
    return t2;
}

#line 32 "programs/arith.lyr"
double lyr_main_frem(double l0_a, double l1_b) {
    double t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 32
    t0 = l0_a;
#line 32
    t1 = l1_b;
#line 32
    t2 = fmod(t0, t1);
#line 32
    return t2;
}

#line 33 "programs/arith.lyr"
float lyr_main_f32add(float l0_a, float l1_b) {
    float t0 = 0;
    float t1 = 0;
    float t2 = 0;
bb0:;
#line 33
    t0 = l0_a;
#line 33
    t1 = l1_b;
#line 33
    t2 = (t0 + t1);
#line 33
    return t2;
}

#line 34 "programs/arith.lyr"
int8_t lyr_main_toI8(double l0_x) {
    double t0 = 0;
    int8_t t1 = 0;
bb0:;
#line 34
    t0 = l0_x;
#line 34
    t1 = lyr_f64_to_i8((double)t0);
#line 34
    return t1;
}

#line 35 "programs/arith.lyr"
uint8_t lyr_main_toU8(double l0_x) {
    double t0 = 0;
    uint8_t t1 = 0;
bb0:;
#line 35
    t0 = l0_x;
#line 35
    t1 = lyr_f64_to_u8((double)t0);
#line 35
    return t1;
}

#line 36 "programs/arith.lyr"
int64_t lyr_main_toInt(double l0_x) {
    double t0 = 0;
    int64_t t1 = 0;
bb0:;
#line 36
    t0 = l0_x;
#line 36
    t1 = lyr_f64_to_i64((double)t0);
#line 36
    return t1;
}

#line 39 "programs/arith.lyr"
LYR_NOINLINE int64_t lyr_main_main(void) {
    int64_t l0_a = 0;
    int64_t l1_b = 0;
    int8_t l2_small = 0;
    int16_t l3_bigger = 0;
    uint8_t l4_u = 0;
    int8_t l5_w1 = 0;
    uint8_t l6_w2 = 0;
    uint8_t l7_w3 = 0;
    double l8_nan = 0;
    uint32_t l9_c = 0;
    uint32_t l10_code = 0;
    uint32_t l11_back = 0;
    uint8_t l12_ordered = 0;
    uint8_t l13__and0 = 0;
    LyrStr *l14__if1 = NULL;
    float l15_tenth = 0;
    double l16_sum32 = 0;
    uint8_t l17_lt = 0;
    uint8_t l18_negZero = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    LyrStr *t2 = NULL;
    int64_t t3 = 0;
    LyrStr *t4 = NULL;
    LyrStr *t5 = NULL;
    int8_t t6 = 0;
    int8_t t7 = 0;
    int16_t t8 = 0;
    uint8_t t9 = 0;
    LyrStr *t10 = NULL;
    int16_t t11 = 0;
    int64_t t12 = 0;
    uint8_t t13 = 0;
    int16_t t14 = 0;
    int64_t t15 = 0;
    int64_t t16 = 0;
    LyrStr *t17 = NULL;
    LyrStr *t18 = NULL;
    int64_t t19 = 0;
    int8_t t20 = 0;
    int64_t t21 = 0;
    uint8_t t22 = 0;
    int64_t t23 = 0;
    uint8_t t24 = 0;
    LyrStr *t25 = NULL;
    int8_t t26 = 0;
    int64_t t27 = 0;
    LyrStr *t28 = NULL;
    LyrStr *t29 = NULL;
    LyrStr *t30 = NULL;
    LyrStr *t31 = NULL;
    uint8_t t32 = 0;
    uint64_t t33 = 0;
    LyrStr *t34 = NULL;
    LyrStr *t35 = NULL;
    LyrStr *t36 = NULL;
    LyrStr *t37 = NULL;
    uint8_t t38 = 0;
    uint64_t t39 = 0;
    LyrStr *t40 = NULL;
    LyrStr *t41 = NULL;
    double t42 = 0;
    double t43 = 0;
    double t44 = 0;
    LyrStr *t45 = NULL;
    double t46 = 0;
    int8_t t47 = 0;
    int64_t t48 = 0;
    LyrStr *t49 = NULL;
    LyrStr *t50 = NULL;
    LyrStr *t51 = NULL;
    LyrStr *t52 = NULL;
    double t53 = 0;
    double t54 = 0;
    int8_t t55 = 0;
    int64_t t56 = 0;
    LyrStr *t57 = NULL;
    LyrStr *t58 = NULL;
    LyrStr *t59 = NULL;
    LyrStr *t60 = NULL;
    double t61 = 0;
    int64_t t62 = 0;
    LyrStr *t63 = NULL;
    LyrStr *t64 = NULL;
    LyrStr *t65 = NULL;
    LyrStr *t66 = NULL;
    double t67 = 0;
    uint8_t t68 = 0;
    uint64_t t69 = 0;
    LyrStr *t70 = NULL;
    LyrStr *t71 = NULL;
    LyrStr *t72 = NULL;
    double t73 = 0;
    double t74 = 0;
    int64_t t75 = 0;
    LyrStr *t76 = NULL;
    LyrStr *t77 = NULL;
    LyrStr *t78 = NULL;
    LyrStr *t79 = NULL;
    double t80 = 0;
    int64_t t81 = 0;
    LyrStr *t82 = NULL;
    LyrStr *t83 = NULL;
    uint32_t t84 = 0;
    uint32_t t85 = 0;
    uint32_t t86 = 0;
    int64_t t87 = 0;
    uint32_t t88 = 0;
    uint32_t t89 = 0;
    uint32_t t90 = 0;
    uint32_t t91 = 0;
    uint8_t t92 = 0;
    uint32_t t93 = 0;
    uint32_t t94 = 0;
    uint8_t t95 = 0;
    uint8_t t96 = 0;
    LyrStr *t97 = NULL;
    uint32_t t98 = 0;
    uint64_t t99 = 0;
    LyrStr *t100 = NULL;
    LyrStr *t101 = NULL;
    LyrStr *t102 = NULL;
    LyrStr *t103 = NULL;
    uint32_t t104 = 0;
    LyrStr *t105 = NULL;
    LyrStr *t106 = NULL;
    LyrStr *t107 = NULL;
    LyrStr *t108 = NULL;
    uint8_t t109 = 0;
    LyrStr *t110 = NULL;
    LyrStr *t111 = NULL;
    LyrStr *t112 = NULL;
    LyrStr *t113 = NULL;
    LyrStr *t114 = NULL;
    int64_t t115 = 0;
    int64_t t116 = 0;
    int64_t t117 = 0;
    LyrStr *t118 = NULL;
    LyrStr *t119 = NULL;
    LyrStr *t120 = NULL;
    LyrStr *t121 = NULL;
    int64_t t122 = 0;
    int64_t t123 = 0;
    int64_t t124 = 0;
    LyrStr *t125 = NULL;
    LyrStr *t126 = NULL;
    LyrStr *t127 = NULL;
    LyrStr *t128 = NULL;
    uint8_t t129 = 0;
    uint8_t t130 = 0;
    uint8_t t131 = 0;
    uint64_t t132 = 0;
    LyrStr *t133 = NULL;
    LyrStr *t134 = NULL;
    LyrStr *t135 = NULL;
    uint8_t t136 = 0;
    uint8_t t137 = 0;
    uint8_t t138 = 0;
    uint64_t t139 = 0;
    LyrStr *t140 = NULL;
    LyrStr *t141 = NULL;
    LyrStr *t142 = NULL;
    LyrStr *t143 = NULL;
    uint8_t t144 = 0;
    uint8_t t145 = 0;
    uint8_t t146 = 0;
    uint64_t t147 = 0;
    LyrStr *t148 = NULL;
    LyrStr *t149 = NULL;
    LyrStr *t150 = NULL;
    LyrStr *t151 = NULL;
    uint8_t t152 = 0;
    uint8_t t153 = 0;
    uint8_t t154 = 0;
    uint64_t t155 = 0;
    LyrStr *t156 = NULL;
    LyrStr *t157 = NULL;
    LyrStr *t158 = NULL;
    int8_t t159 = 0;
    int8_t t160 = 0;
    int8_t t161 = 0;
    int64_t t162 = 0;
    LyrStr *t163 = NULL;
    LyrStr *t164 = NULL;
    LyrStr *t165 = NULL;
    LyrStr *t166 = NULL;
    int8_t t167 = 0;
    int8_t t168 = 0;
    int8_t t169 = 0;
    int64_t t170 = 0;
    LyrStr *t171 = NULL;
    LyrStr *t172 = NULL;
    LyrStr *t173 = NULL;
    double t174 = 0;
    double t175 = 0;
    double t176 = 0;
    LyrStr *t177 = NULL;
    LyrStr *t178 = NULL;
    LyrStr *t179 = NULL;
    LyrStr *t180 = NULL;
    double t181 = 0;
    double t182 = 0;
    double t183 = 0;
    LyrStr *t184 = NULL;
    LyrStr *t185 = NULL;
    LyrStr *t186 = NULL;
    LyrStr *t187 = NULL;
    double t188 = 0;
    double t189 = 0;
    double t190 = 0;
    LyrStr *t191 = NULL;
    LyrStr *t192 = NULL;
    LyrStr *t193 = NULL;
    LyrStr *t194 = NULL;
    double t195 = 0;
    double t196 = 0;
    double t197 = 0;
    LyrStr *t198 = NULL;
    LyrStr *t199 = NULL;
    LyrStr *t200 = NULL;
    double t201 = 0;
    double t202 = 0;
    double t203 = 0;
    LyrStr *t204 = NULL;
    LyrStr *t205 = NULL;
    LyrStr *t206 = NULL;
    LyrStr *t207 = NULL;
    double t208 = 0;
    double t209 = 0;
    double t210 = 0;
    double t211 = 0;
    LyrStr *t212 = NULL;
    LyrStr *t213 = NULL;
    LyrStr *t214 = NULL;
    LyrStr *t215 = NULL;
    double t216 = 0;
    LyrStr *t217 = NULL;
    LyrStr *t218 = NULL;
    float t219 = 0;
    float t220 = 0;
    float t221 = 0;
    float t222 = 0;
    double t223 = 0;
    LyrStr *t224 = NULL;
    float t225 = 0;
    double t226 = 0;
    LyrStr *t227 = NULL;
    LyrStr *t228 = NULL;
    LyrStr *t229 = NULL;
    LyrStr *t230 = NULL;
    double t231 = 0;
    LyrStr *t232 = NULL;
    LyrStr *t233 = NULL;
    double t234 = 0;
    double t235 = 0;
    uint8_t t236 = 0;
    double t237 = 0;
    double t238 = 0;
    double t239 = 0;
    double t240 = 0;
    double t241 = 0;
    uint8_t t242 = 0;
    LyrStr *t243 = NULL;
    uint8_t t244 = 0;
    LyrStr *t245 = NULL;
    LyrStr *t246 = NULL;
    LyrStr *t247 = NULL;
    LyrStr *t248 = NULL;
    uint8_t t249 = 0;
    uint8_t t250 = 0;
    LyrStr *t251 = NULL;
    LyrStr *t252 = NULL;
    LyrStr *t253 = NULL;
    int64_t t254 = 0;
    LyrStr *t255 = NULL;
    LyrStr *t256 = NULL;
    LyrStr *t257 = NULL;
    LyrStr *t258 = NULL;
    double t259 = 0;
    LyrStr *t260 = NULL;
    LyrStr *t261 = NULL;
    int64_t t262 = 0;
bb0:;
#line 39
    t0 = (int64_t)INT64_C(42);
#line 39
    l0_a = t0;
#line 40
    t1 = l0_a;
#line 40
    l1_b = t1;
#line 41
    t2 = (LyrStr *)&lyr_lit0;
#line 41
    t3 = l1_b;
#line 41
    t4 = lyr_str_from_int(t3);
#line 41
    t5 = lyr_str_concat(t2, t4);
#line 41
    lyr_println(t5);
#line 43
    t6 = (int8_t)INT64_C(100);
#line 43
    l2_small = t6;
#line 44
    t7 = l2_small;
#line 44
    t8 = (int16_t)t7;
#line 44
    l3_bigger = t8;
#line 45
    t9 = (uint8_t)UINT64_C(200);
#line 45
    l4_u = t9;
#line 46
    t10 = (LyrStr *)&lyr_lit1;
#line 46
    t11 = l3_bigger;
#line 46
    t12 = lyr_main_widen16(t11);
#line 46
    t13 = l4_u;
#line 46
    t14 = lyr_main_takeUint8(t13);
#line 46
    t15 = lyr_main_widen16(t14);
#line 46
    t16 = LYR_CHECKED_ADD(t12, t15);
#line 46
    t17 = lyr_str_from_int(t16);
#line 46
    t18 = lyr_str_concat(t10, t17);
#line 46
    lyr_println(t18);
#line 48
    t19 = (int64_t)INT64_C(128);
#line 48
    t20 = (int8_t)t19;
#line 48
    l5_w1 = t20;
#line 49
    t21 = (int64_t)INT64_C(-1);
#line 49
    t22 = (uint8_t)t21;
#line 49
    l6_w2 = t22;
#line 50
    t23 = (int64_t)INT64_C(256);
#line 50
    t24 = (uint8_t)t23;
#line 50
    l7_w3 = t24;
#line 51
    t25 = (LyrStr *)&lyr_lit2;
#line 51
    t26 = l5_w1;
#line 51
    t27 = (int64_t)t26;
#line 51
    t28 = lyr_str_from_int(t27);
#line 51
    t29 = lyr_str_concat(t25, t28);
#line 51
    t30 = (LyrStr *)&lyr_lit3;
#line 51
    t31 = lyr_str_concat(t29, t30);
#line 51
    t32 = l6_w2;
#line 51
    t33 = (uint64_t)t32;
#line 51
    t34 = lyr_str_from_uint(t33);
#line 51
    t35 = lyr_str_concat(t31, t34);
#line 51
    t36 = (LyrStr *)&lyr_lit3;
#line 51
    t37 = lyr_str_concat(t35, t36);
#line 51
    t38 = l7_w3;
#line 51
    t39 = (uint64_t)t38;
#line 51
    t40 = lyr_str_from_uint(t39);
#line 51
    t41 = lyr_str_concat(t37, t40);
#line 51
    lyr_println(t41);
#line 53
    t42 = (double)0.0;
#line 53
    t43 = (double)0.0;
#line 53
    t44 = lyr_main_fdiv(t42, t43);
#line 53
    l8_nan = t44;
#line 54
    t45 = (LyrStr *)&lyr_lit4;
#line 54
    t46 = (double)1000.0;
#line 54
    t47 = lyr_main_toI8(t46);
#line 54
    t48 = (int64_t)t47;
#line 54
    t49 = lyr_str_from_int(t48);
#line 54
    t50 = lyr_str_concat(t45, t49);
#line 54
    t51 = (LyrStr *)&lyr_lit3;
#line 54
    t52 = lyr_str_concat(t50, t51);
#line 54
    t53 = (double)1000.0;
#line 54
    t54 = (-t53);
#line 54
    t55 = lyr_main_toI8(t54);
#line 54
    t56 = (int64_t)t55;
#line 54
    t57 = lyr_str_from_int(t56);
#line 54
    t58 = lyr_str_concat(t52, t57);
#line 54
    t59 = (LyrStr *)&lyr_lit3;
#line 54
    t60 = lyr_str_concat(t58, t59);
#line 54
    t61 = l8_nan;
#line 54
    t62 = lyr_main_toInt(t61);
#line 54
    t63 = lyr_str_from_int(t62);
#line 54
    t64 = lyr_str_concat(t60, t63);
#line 54
    t65 = (LyrStr *)&lyr_lit3;
#line 54
    t66 = lyr_str_concat(t64, t65);
#line 54
    t67 = (double)300.0;
#line 54
    t68 = lyr_main_toU8(t67);
#line 54
    t69 = (uint64_t)t68;
#line 54
    t70 = lyr_str_from_uint(t69);
#line 54
    t71 = lyr_str_concat(t66, t70);
#line 54
    lyr_println(t71);
#line 55
    t72 = (LyrStr *)&lyr_lit5;
#line 55
    t73 = (double)3.9;
#line 55
    t74 = (-t73);
#line 55
    t75 = lyr_main_toInt(t74);
#line 55
    t76 = lyr_str_from_int(t75);
#line 55
    t77 = lyr_str_concat(t72, t76);
#line 55
    t78 = (LyrStr *)&lyr_lit3;
#line 55
    t79 = lyr_str_concat(t77, t78);
#line 55
    t80 = (double)3.9;
#line 55
    t81 = lyr_main_toInt(t80);
#line 55
    t82 = lyr_str_from_int(t81);
#line 55
    t83 = lyr_str_concat(t79, t82);
#line 55
    lyr_println(t83);
#line 57
    t84 = (uint32_t)65;
#line 57
    l9_c = t84;
#line 58
    t85 = l9_c;
#line 58
    t86 = (uint32_t)t85;
#line 58
    l10_code = t86;
#line 59
    t87 = (int64_t)INT64_C(65);
#line 59
    t88 = (uint32_t)t87;
#line 59
    t89 = LYR_CHAR_FROM_U32(t88);
#line 59
    l11_back = t89;
#line 60
    t90 = (uint32_t)98;
#line 60
    t91 = (uint32_t)97;
#line 60
    t92 = (uint8_t)(t90 > t91);
#line 60
    l13__and0 = t92;
#line 60
    if (t92) goto bb1; else goto bb2;
bb1:;
#line 60
    t93 = l11_back;
#line 60
    t94 = l9_c;
#line 60
    t95 = (uint8_t)(t93 == t94);
#line 60
    l13__and0 = t95;
#line 60
    goto bb2;
bb2:;
#line 60
    t96 = l13__and0;
#line 60
    l12_ordered = t96;
#line 61
    t97 = (LyrStr *)&lyr_lit6;
#line 61
    t98 = l10_code;
#line 61
    t99 = (uint64_t)t98;
#line 61
    t100 = lyr_str_from_uint(t99);
#line 61
    t101 = lyr_str_concat(t97, t100);
#line 61
    t102 = (LyrStr *)&lyr_lit3;
#line 61
    t103 = lyr_str_concat(t101, t102);
#line 61
    t104 = l11_back;
#line 61
    t105 = lyr_str_from_char(t104);
#line 61
    t106 = lyr_str_concat(t103, t105);
#line 61
    t107 = (LyrStr *)&lyr_lit3;
#line 61
    t108 = lyr_str_concat(t106, t107);
#line 61
    t109 = l12_ordered;
#line 61
    if (t109) goto bb3; else goto bb4;
bb3:;
#line 61
    t110 = (LyrStr *)&lyr_lit7;
#line 61
    l14__if1 = t110;
#line 61
    goto bb5;
bb4:;
#line 61
    t111 = (LyrStr *)&lyr_lit8;
#line 61
    l14__if1 = t111;
#line 61
    goto bb5;
bb5:;
#line 61
    t112 = l14__if1;
#line 61
    t113 = lyr_str_concat(t108, t112);
#line 61
    lyr_println(t113);
#line 63
    t114 = (LyrStr *)&lyr_lit9;
#line 63
    t115 = (int64_t)INT64_C(1);
#line 63
    t116 = (int64_t)INT64_C(3);
#line 63
    t117 = lyr_main_shl(t115, t116);
#line 63
    t118 = lyr_str_from_int(t117);
#line 63
    t119 = lyr_str_concat(t114, t118);
#line 63
    t120 = (LyrStr *)&lyr_lit3;
#line 63
    t121 = lyr_str_concat(t119, t120);
#line 63
    t122 = (int64_t)INT64_C(-8);
#line 63
    t123 = (int64_t)INT64_C(3);
#line 63
    t124 = lyr_main_shr(t122, t123);
#line 63
    t125 = lyr_str_from_int(t124);
#line 63
    t126 = lyr_str_concat(t121, t125);
#line 63
    t127 = (LyrStr *)&lyr_lit3;
#line 63
    t128 = lyr_str_concat(t126, t127);
#line 63
    t129 = (uint8_t)UINT64_C(255);
#line 63
    t130 = (uint8_t)UINT64_C(0);
#line 63
    t131 = lyr_main_shrU8(t129, t130);
#line 63
    t132 = (uint64_t)t131;
#line 63
    t133 = lyr_str_from_uint(t132);
#line 63
    t134 = lyr_str_concat(t128, t133);
#line 63
    lyr_println(t134);
#line 64
    t135 = (LyrStr *)&lyr_lit10;
#line 64
    t136 = (uint8_t)UINT64_C(255);
#line 64
    t137 = (uint8_t)UINT64_C(1);
#line 64
    t138 = lyr_main_addWrapU8(t136, t137);
#line 64
    t139 = (uint64_t)t138;
#line 64
    t140 = lyr_str_from_uint(t139);
#line 64
    t141 = lyr_str_concat(t135, t140);
#line 64
    t142 = (LyrStr *)&lyr_lit3;
#line 64
    t143 = lyr_str_concat(t141, t142);
#line 64
    t144 = (uint8_t)UINT64_C(0);
#line 64
    t145 = (uint8_t)UINT64_C(1);
#line 64
    t146 = lyr_main_subWrapU8(t144, t145);
#line 64
    t147 = (uint64_t)t146;
#line 64
    t148 = lyr_str_from_uint(t147);
#line 64
    t149 = lyr_str_concat(t143, t148);
#line 64
    t150 = (LyrStr *)&lyr_lit3;
#line 64
    t151 = lyr_str_concat(t149, t150);
#line 64
    t152 = (uint8_t)UINT64_C(129);
#line 64
    t153 = (uint8_t)UINT64_C(129);
#line 64
    t154 = lyr_main_mulWrapU8(t152, t153);
#line 64
    t155 = (uint64_t)t154;
#line 64
    t156 = lyr_str_from_uint(t155);
#line 64
    t157 = lyr_str_concat(t151, t156);
#line 64
    lyr_println(t157);
#line 65
    t158 = (LyrStr *)&lyr_lit11;
#line 65
    t159 = (int8_t)INT64_C(127);
#line 65
    t160 = (int8_t)INT64_C(1);
#line 65
    t161 = lyr_main_addWrapI8(t159, t160);
#line 65
    t162 = (int64_t)t161;
#line 65
    t163 = lyr_str_from_int(t162);
#line 65
    t164 = lyr_str_concat(t158, t163);
#line 65
    t165 = (LyrStr *)&lyr_lit3;
#line 65
    t166 = lyr_str_concat(t164, t165);
#line 65
    t167 = (int8_t)INT64_C(128);
#line 65
    t168 = (int8_t)INT64_C(1);
#line 65
    t169 = lyr_main_subWrapI8(t167, t168);
#line 65
    t170 = (int64_t)t169;
#line 65
    t171 = lyr_str_from_int(t170);
#line 65
    t172 = lyr_str_concat(t166, t171);
#line 65
    lyr_println(t172);
#line 67
    t173 = (LyrStr *)&lyr_lit12;
#line 67
    t174 = (double)1.0;
#line 67
    t175 = (double)0.5;
#line 67
    t176 = lyr_main_fadd(t174, t175);
#line 67
    t177 = lyr_str_from_float(t176);
#line 67
    t178 = lyr_str_concat(t173, t177);
#line 67
    t179 = (LyrStr *)&lyr_lit3;
#line 67
    t180 = lyr_str_concat(t178, t179);
#line 67
    t181 = (double)4.0;
#line 67
    t182 = (double)2.0;
#line 67
    t183 = lyr_main_fdiv(t181, t182);
#line 67
    t184 = lyr_str_from_float(t183);
#line 67
    t185 = lyr_str_concat(t180, t184);
#line 67
    t186 = (LyrStr *)&lyr_lit3;
#line 67
    t187 = lyr_str_concat(t185, t186);
#line 67
    t188 = (double)0.3;
#line 67
    t189 = (double)0.2;
#line 67
    t190 = lyr_main_fsub(t188, t189);
#line 67
    t191 = lyr_str_from_float(t190);
#line 67
    t192 = lyr_str_concat(t187, t191);
#line 67
    t193 = (LyrStr *)&lyr_lit3;
#line 67
    t194 = lyr_str_concat(t192, t193);
#line 67
    t195 = (double)3.0;
#line 67
    t196 = (double)2.5;
#line 67
    t197 = lyr_main_frem(t195, t196);
#line 67
    t198 = lyr_str_from_float(t197);
#line 67
    t199 = lyr_str_concat(t194, t198);
#line 67
    lyr_println(t199);
#line 68
    t200 = (LyrStr *)&lyr_lit13;
#line 68
    t201 = (double)1.0;
#line 68
    t202 = (double)0.0;
#line 68
    t203 = lyr_main_fdiv(t201, t202);
#line 68
    t204 = lyr_str_from_float(t203);
#line 68
    t205 = lyr_str_concat(t200, t204);
#line 68
    t206 = (LyrStr *)&lyr_lit3;
#line 68
    t207 = lyr_str_concat(t205, t206);
#line 68
    t208 = (double)1.0;
#line 68
    t209 = (-t208);
#line 68
    t210 = (double)0.0;
#line 68
    t211 = lyr_main_fdiv(t209, t210);
#line 68
    t212 = lyr_str_from_float(t211);
#line 68
    t213 = lyr_str_concat(t207, t212);
#line 68
    t214 = (LyrStr *)&lyr_lit3;
#line 68
    t215 = lyr_str_concat(t213, t214);
#line 68
    t216 = l8_nan;
#line 68
    t217 = lyr_str_from_float(t216);
#line 68
    t218 = lyr_str_concat(t215, t217);
#line 68
    lyr_println(t218);
#line 69
    t219 = (float)0.10000000149011612;
#line 69
    l15_tenth = t219;
#line 70
    t220 = l15_tenth;
#line 70
    t221 = (float)0.20000000298023224;
#line 70
    t222 = lyr_main_f32add(t220, t221);
#line 70
    t223 = (double)t222;
#line 70
    l16_sum32 = t223;
#line 71
    t224 = (LyrStr *)&lyr_lit14;
#line 71
    t225 = l15_tenth;
#line 71
    t226 = (double)t225;
#line 71
    t227 = lyr_str_from_float(t226);
#line 71
    t228 = lyr_str_concat(t224, t227);
#line 71
    t229 = (LyrStr *)&lyr_lit3;
#line 71
    t230 = lyr_str_concat(t228, t229);
#line 71
    t231 = l16_sum32;
#line 71
    t232 = lyr_str_from_float(t231);
#line 71
    t233 = lyr_str_concat(t230, t232);
#line 71
    lyr_println(t233);
#line 72
    t234 = (double)1.5;
#line 72
    t235 = (double)2.5;
#line 72
    t236 = (uint8_t)(t234 < t235);
#line 72
    l17_lt = t236;
#line 73
    t237 = (double)0.0;
#line 73
    t238 = (double)0.0;
#line 73
    t239 = lyr_main_fsub(t237, t238);
#line 73
    t240 = (double)0.0;
#line 73
    t241 = (-t240);
#line 73
    t242 = (uint8_t)(t239 == t241);
#line 73
    l18_negZero = t242;
#line 74
    t243 = (LyrStr *)&lyr_lit15;
#line 74
    t244 = l17_lt;
#line 74
    t245 = lyr_str_from_bool(t244);
#line 74
    t246 = lyr_str_concat(t243, t245);
#line 74
    t247 = (LyrStr *)&lyr_lit3;
#line 74
    t248 = lyr_str_concat(t246, t247);
#line 74
    t249 = l18_negZero;
#line 74
    t250 = (uint8_t)!t249;
#line 74
    t251 = lyr_str_from_bool(t250);
#line 74
    t252 = lyr_str_concat(t248, t251);
#line 74
    lyr_println(t252);
#line 75
    t253 = (LyrStr *)&lyr_lit16;
#line 75
    t254 = (int64_t)INT64_C(9007199254740993);
#line 75
    t255 = lyr_str_from_int(t254);
#line 75
    t256 = lyr_str_concat(t253, t255);
#line 75
    t257 = (LyrStr *)&lyr_lit3;
#line 75
    t258 = lyr_str_concat(t256, t257);
#line 75
    t259 = (double)1E+21;
#line 75
    t260 = lyr_str_from_float(t259);
#line 75
    t261 = lyr_str_concat(t258, t260);
#line 75
    lyr_println(t261);
#line 76
    t262 = (int64_t)INT64_C(0);
#line 76
    return t262;
}

#line 1375 "stdlib5/std/core.lyr"
void lyr__globals__9ee5f9b5(void) {
    uint64_t t0 = 0;
    double t1 = 0;
    uint64_t t2 = 0;
    double t3 = 0;
    uint64_t t4 = 0;
    float t5 = 0;
    uint64_t t6 = 0;
    float t7 = 0;
    uint64_t t8 = 0;
    uint64_t t9 = 0;
    uint64_t t10 = 0;
bb0:;
#line 1375
    t0 = (uint64_t)UINT64_C(9218868437227405312);
#line 1375
    t1 = lyr_std_core__extend__float_fromBits_3825afc5(t0);
#line 1375
    lyr_g0_float_infinity = t1;
#line 1376
    t2 = (uint64_t)UINT64_C(9221120237041090560);
#line 1376
    t3 = lyr_std_core__extend__float_fromBits_3825afc5(t2);
#line 1376
    lyr_g1_float_nan = t3;
#line 1396
    t4 = (uint64_t)UINT64_C(2139095040);
#line 1396
    t5 = lyr_std_core__extend__float32_fromBits_bc3641ce(t4);
#line 1396
    lyr_g2_float32_infinity = t5;
#line 1397
    t6 = (uint64_t)UINT64_C(2143289344);
#line 1397
    t7 = lyr_std_core__extend__float32_fromBits_bc3641ce(t6);
#line 1397
    lyr_g3_float32_nan = t7;
#line 14 "stdlib5/std/collections.lyr"
    t8 = (uint64_t)UINT64_C(9259542123273814144);
#line 14
    lyr_g4_emptyGroup = t8;
#line 15
    t9 = (uint64_t)UINT64_C(72340172838076673);
#line 15
    lyr_g5_lowBits = t9;
#line 16
    t10 = (uint64_t)UINT64_C(9259542123273814144);
#line 16
    lyr_g6_highBits = t10;
    return;
}

#line 1382 "stdlib5/std/core.lyr"
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b) {
    uint64_t t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 1382
    t0 = l0_b;
#line 1372
    t1 = (double)0.0;
#line 1382
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1382
    return t2;
}

#line 1403 "stdlib5/std/core.lyr"
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b) {
    uint64_t t0 = 0;
    float t1 = 0;
    float t2 = 0;
bb0:;
#line 1403
    t0 = l0_b;
#line 1393
    t1 = (float)0.0;
#line 1403
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1403
    return t2;
}


/* the program */
static int64_t lyr_entry(void) { lyr__globals__9ee5f9b5(); return lyr_main_main(); }
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_entry); }
