/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty0_Color lyr_ty0_Color;
typedef struct lyr_ty1_Point lyr_ty1_Point;
typedef struct lyr_ty2_ParseError lyr_ty2_ParseError;
typedef struct lyr_ty3_ParseErrorKind lyr_ty3_ParseErrorKind;
typedef struct lyr_ty4_ParseErrorKind_Empty lyr_ty4_ParseErrorKind_Empty;
typedef struct lyr_ty5_ParseErrorKind_Invalid lyr_ty5_ParseErrorKind_Invalid;
typedef struct lyr_ty6_ParseErrorKind_Overflow lyr_ty6_ParseErrorKind_Overflow;
typedef struct lyr_vt_ty7 lyr_vt_ty7;
const char lyr_ifid_ty7[] = "std.core.Error";
typedef struct lyr_ty8_Ordering lyr_ty8_Ordering;
typedef struct lyr_ty9_Ordering_Less lyr_ty9_Ordering_Less;
typedef struct lyr_ty10_Ordering_Equal lyr_ty10_Ordering_Equal;
typedef struct lyr_ty11_Ordering_Greater lyr_ty11_Ordering_Greater;
typedef struct lyr_ty12_Exception lyr_ty12_Exception;
typedef struct lyr_vt_ty13 lyr_vt_ty13;
const char lyr_ifid_ty13[] = "std.core.Hasher";
typedef struct lyr_ty14_Chars lyr_ty14_Chars;
typedef struct lyr_ty15_Sip lyr_ty15_Sip;
typedef struct lyr_ty16_DefaultHasher lyr_ty16_DefaultHasher;
typedef struct lyr_ty17_FixedHasher lyr_ty17_FixedHasher;
typedef struct lyr_ty18_Fnv1a64 lyr_ty18_Fnv1a64;
struct lyr_ty0_Color {
    int64_t f_v;
};
struct lyr_ty1_Point {
    int64_t f_x;
    int64_t f_y;
};
struct lyr_ty4_ParseErrorKind_Empty {
    uint8_t lyr_unit;
};
struct lyr_ty5_ParseErrorKind_Invalid {
    uint8_t lyr_unit;
};
struct lyr_ty6_ParseErrorKind_Overflow {
    uint8_t lyr_unit;
};
struct lyr_ty3_ParseErrorKind { uint32_t tag; };
_Static_assert(sizeof(lyr_ty3_ParseErrorKind) == 4, "layout of lyr_ty3_ParseErrorKind");
struct lyr_ty2_ParseError {
    lyr_ty3_ParseErrorKind f_kind;
};
struct lyr_vt_ty7 {
    const LyrDesc *desc;
    void (*s0)(LyrIface);
    void (*s1)(LyrIface);
};
struct lyr_ty9_Ordering_Less {
    uint8_t lyr_unit;
};
struct lyr_ty10_Ordering_Equal {
    uint8_t lyr_unit;
};
struct lyr_ty11_Ordering_Greater {
    uint8_t lyr_unit;
};
struct lyr_ty8_Ordering { uint32_t tag; };
_Static_assert(sizeof(lyr_ty8_Ordering) == 4, "layout of lyr_ty8_Ordering");
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface7;
struct lyr_ty12_Exception {
    LyrObj header;
    LyrStr *f_text;
    lyr_opt_iface7 f_inner;
};
_Static_assert(sizeof(lyr_ty12_Exception) == 40, "layout of lyr_ty12_Exception");
_Static_assert(offsetof(lyr_ty12_Exception, f_text) == 8, "layout of lyr_ty12_Exception");
_Static_assert(offsetof(lyr_ty12_Exception, f_inner) == 16, "layout of lyr_ty12_Exception");
static const uint64_t lyr_refmap_ty12[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty12_Exception = { sizeof(lyr_ty12_Exception), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty12, "std.core.Exception", NULL };
struct lyr_vt_ty13 {
    const LyrDesc *desc;
    void (*s0)(LyrIface);
    void (*s1)(LyrIface);
    void (*s2)(LyrIface);
    void (*s3)(LyrIface);
    void (*s4)(LyrIface);
};
struct lyr_ty14_Chars {
    LyrStr *f_s;
    int64_t f_at;
};
struct lyr_ty15_Sip {
    uint64_t f_v0;
    uint64_t f_v1;
    uint64_t f_v2;
    uint64_t f_v3;
    uint64_t f_tail;
    int64_t f_pending;
    int64_t f_length;
};
struct lyr_ty16_DefaultHasher {
    lyr_ty15_Sip f_state;
};
struct lyr_ty17_FixedHasher {
    lyr_ty15_Sip f_state;
};
struct lyr_ty18_Fnv1a64 {
    uint64_t f_state;
};
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
const LyrDesc lyr_desc_arr_i64 = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY, sizeof(int64_t), 0, NULL, "int[]", NULL };

/* module-level bindings */
double lyr_g0_float_infinity = 0;
double lyr_g1_float_nan = 0;
float lyr_g2_float32_infinity = 0;
float lyr_g3_float32_nan = 0;
uint64_t lyr_g4_emptyGroup = 0;
uint64_t lyr_g5_lowBits = 0;
uint64_t lyr_g6_highBits = 0;

/* string literals */
static const LyrStaticStr(7) lyr_lit0 = LYR_STR_INIT("arity ");
static const LyrStaticStr(2) lyr_lit1 = LYR_STR_INIT(" ");
static const LyrStaticStr(7) lyr_lit2 = LYR_STR_INIT("named ");
static const LyrStaticStr(9) lyr_lit3 = LYR_STR_INIT("default ");
static const LyrStaticStr(8) lyr_lit4 = LYR_STR_INIT("params ");
static const LyrStaticStr(9) lyr_lit5 = LYR_STR_INIT("factory ");

/* prototypes */
int64_t lyr_main_connect(int64_t l0_host, int64_t l1_port, int64_t l2_retries);
int64_t lyr_main_span(int64_t l0_from, int64_t l1_to, int64_t l2_step);
int64_t lyr_main_sum(int64_t l0_base, LyrArr *l1_xs);
LYR_NOINLINE int64_t lyr_main_main(void);
lyr_ty0_Color lyr_main_Color_of_1_7f597b30(int64_t l0_hex);
lyr_ty0_Color lyr_main_Color_of_3_81597e56(int64_t l0_r, int64_t l1_g, int64_t l2_b);
lyr_ty1_Point lyr_main_Point_new_2_0f8b3375(int64_t l0_x, int64_t l1_y);
lyr_ty1_Point lyr_main_Point_new_1_0c8b2ebc(int64_t l0_d);
void lyr__globals__9ee5f9b5(void);
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b);
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b);

#line 23 "programs/calls.lyr"
int64_t lyr_main_connect(int64_t l0_host, int64_t l1_port, int64_t l2_retries) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    int64_t t2 = 0;
    int64_t t3 = 0;
    int64_t t4 = 0;
bb0:;
#line 23
    t0 = l0_host;
#line 23
    t1 = l1_port;
#line 23
    t2 = LYR_CHECKED_ADD(t0, t1);
#line 23
    t3 = l2_retries;
#line 23
    t4 = LYR_CHECKED_ADD(t2, t3);
#line 23
    return t4;
}

#line 24 "programs/calls.lyr"
int64_t lyr_main_span(int64_t l0_from, int64_t l1_to, int64_t l2_step) {
    int64_t t0 = 0;
bb0:;
#line 24
    t0 = l2_step;
#line 24
    return t0;
}

#line 26 "programs/calls.lyr"
int64_t lyr_main_sum(int64_t l0_base, LyrArr *l1_xs) {
    int64_t l2_s = 0;
    int64_t l3__range0 = 0;
    int64_t l4__last1 = 0;
    int64_t l5_i = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    LyrArr *t2 = NULL;
    int64_t t3 = 0;
    int64_t t4 = 0;
    int64_t t5 = 0;
    uint8_t t6 = 0;
    int64_t t7 = 0;
    LyrArr *t8 = NULL;
    int64_t t9 = 0;
    int64_t t10 = 0;
    int64_t t11 = 0;
    int64_t t12 = 0;
    int64_t t13 = 0;
    int64_t t14 = 0;
    int64_t t15 = 0;
bb0:;
#line 26
    t0 = l0_base;
#line 26
    l2_s = t0;
#line 27
    t1 = (int64_t)INT64_C(0);
#line 27
    t2 = l1_xs;
#line 27
    t3 = t2->len;
#line 27
    l3__range0 = t1;
#line 27
    l4__last1 = t3;
#line 27
    goto bb1;
bb1:;
#line 27
    t4 = l3__range0;
#line 27
    t5 = l4__last1;
#line 27
    t6 = (uint8_t)(t4 < t5);
#line 27
    if (t6) goto bb2; else goto bb4;
bb2:;
#line 27
    l5_i = t4;
#line 27
    t7 = l2_s;
#line 27
    t8 = l1_xs;
#line 27
    t9 = l5_i;
#line 27
    LYR_CHECK_INDEX(t9, t8->len); t10 = LYR_ARR_DATA(t8, int64_t)[t9];
#line 27
    t11 = LYR_CHECKED_ADD(t7, t10);
#line 27
    l2_s = t11;
#line 27
    goto bb3;
bb3:;
#line 27
    t12 = l3__range0;
#line 27
    t13 = (int64_t)INT64_C(1);
#line 27
    t14 = LYR_CHECKED_ADD(t12, t13);
#line 27
    l3__range0 = t14;
#line 27
    goto bb1;
bb4:;
#line 28
    t15 = l2_s;
#line 28
    return t15;
}

#line 32 "programs/calls.lyr"
LYR_NOINLINE int64_t lyr_main_main(void) {
    int64_t l0_a = 0;
    int64_t l1_b = 0;
    int64_t l2_c = 0;
    lyr_ty1_Point l3_p = {0};
    LyrStr *t0 = NULL;
    int64_t t1 = 0;
    lyr_ty0_Color t2_s = {0};
    lyr_ty0_Color *t2 = &t2_s;
    int64_t t3 = 0;
    LyrStr *t4 = NULL;
    LyrStr *t5 = NULL;
    int64_t t6 = 0;
    int64_t t7 = 0;
    int64_t t8 = 0;
    lyr_ty0_Color t9_s = {0};
    lyr_ty0_Color *t9 = &t9_s;
    int64_t t10 = 0;
    LyrStr *t11 = NULL;
    LyrStr *t12 = NULL;
    int64_t t13 = 0;
    int64_t t14 = 0;
    int64_t t15 = 0;
    lyr_ty0_Color t16_s = {0};
    lyr_ty0_Color *t16 = &t16_s;
    int64_t t17 = 0;
    LyrStr *t18 = NULL;
    LyrStr *t19 = NULL;
    LyrStr *t20 = NULL;
    LyrStr *t21 = NULL;
    LyrStr *t22 = NULL;
    LyrStr *t23 = NULL;
    int64_t t24 = 0;
    int64_t t25 = 0;
    int64_t t26 = 0;
    int64_t t27 = 0;
    int64_t t28 = 0;
    int64_t t29 = 0;
    int64_t t30 = 0;
    int64_t t31 = 0;
    int64_t t32 = 0;
    int64_t t33 = 0;
    int64_t t34 = 0;
    int64_t t35 = 0;
    LyrStr *t36 = NULL;
    int64_t t37 = 0;
    LyrStr *t38 = NULL;
    LyrStr *t39 = NULL;
    int64_t t40 = 0;
    LyrStr *t41 = NULL;
    LyrStr *t42 = NULL;
    int64_t t43 = 0;
    LyrStr *t44 = NULL;
    LyrStr *t45 = NULL;
    LyrStr *t46 = NULL;
    LyrStr *t47 = NULL;
    LyrStr *t48 = NULL;
    LyrStr *t49 = NULL;
    LyrStr *t50 = NULL;
    int64_t t51 = 0;
    int64_t t52 = 0;
    int64_t t53 = 0;
    int64_t t54 = 0;
    int64_t t55 = 0;
    LyrStr *t56 = NULL;
    LyrStr *t57 = NULL;
    int64_t t58 = 0;
    int64_t t59 = 0;
    int64_t t60 = 0;
    int64_t t61 = 0;
    LyrStr *t62 = NULL;
    LyrStr *t63 = NULL;
    int64_t t64 = 0;
    int64_t t65 = 0;
    int64_t t66 = 0;
    int64_t t67 = 0;
    int64_t t68 = 0;
    LyrStr *t69 = NULL;
    LyrStr *t70 = NULL;
    LyrStr *t71 = NULL;
    LyrStr *t72 = NULL;
    LyrStr *t73 = NULL;
    LyrStr *t74 = NULL;
    LyrStr *t75 = NULL;
    int64_t t76 = 0;
    int64_t t77 = 0;
    int64_t t78 = 0;
    LyrArr *t79 = NULL;
    int64_t t80 = 0;
    LyrStr *t81 = NULL;
    LyrStr *t82 = NULL;
    int64_t t83 = 0;
    LyrArr *t84 = NULL;
    int64_t t85 = 0;
    LyrStr *t86 = NULL;
    LyrStr *t87 = NULL;
    LyrStr *t88 = NULL;
    LyrStr *t89 = NULL;
    int64_t t90 = 0;
    int64_t t91 = 0;
    lyr_ty1_Point t92_s = {0};
    lyr_ty1_Point *t92 = &t92_s;
    LyrStr *t93 = NULL;
    lyr_ty1_Point t94_s = {0};
    lyr_ty1_Point *t94 = &t94_s;
    int64_t t95 = 0;
    lyr_ty1_Point t96_s = {0};
    lyr_ty1_Point *t96 = &t96_s;
    int64_t t97 = 0;
    int64_t t98 = 0;
    LyrStr *t99 = NULL;
    LyrStr *t100 = NULL;
    int64_t t101 = 0;
    lyr_ty1_Point t102_s = {0};
    lyr_ty1_Point *t102 = &t102_s;
    int64_t t103 = 0;
    LyrStr *t104 = NULL;
    LyrStr *t105 = NULL;
    LyrStr *t106 = NULL;
    LyrStr *t107 = NULL;
    int64_t t108 = 0;
bb0:;
#line 32
    t0 = (LyrStr *)&lyr_lit0;
#line 32
    t1 = (int64_t)INT64_C(7);
#line 32
    t2_s = lyr_main_Color_of_1_7f597b30(t1); t2 = &t2_s;
#line 32
    t3 = t2->f_v;
#line 32
    t4 = lyr_str_from_int(t3);
#line 32
    t5 = (LyrStr *)&lyr_lit1;
#line 32
    t6 = (int64_t)INT64_C(0);
#line 32
    t7 = (int64_t)INT64_C(3);
#line 32
    t8 = (int64_t)INT64_C(0);
#line 32
    t9_s = lyr_main_Color_of_3_81597e56(t6, t7, t8); t9 = &t9_s;
#line 32
    t10 = t9->f_v;
#line 32
    t11 = lyr_str_from_int(t10);
#line 32
    t12 = (LyrStr *)&lyr_lit1;
#line 32
    t13 = (int64_t)INT64_C(3);
#line 32
    t14 = (int64_t)INT64_C(3);
#line 32
    t15 = (int64_t)INT64_C(0);
#line 32
    t16_s = lyr_main_Color_of_3_81597e56(t13, t14, t15); t16 = &t16_s;
#line 32
    t17 = t16->f_v;
#line 32
    t18 = lyr_str_from_int(t17);
#line 32
    t19 = lyr_str_concat(t0, t4);
#line 32
    t20 = lyr_str_concat(t19, t5);
#line 32
    t21 = lyr_str_concat(t20, t11);
#line 32
    t22 = lyr_str_concat(t21, t12);
#line 32
    t23 = lyr_str_concat(t22, t18);
#line 32
    lyr_println(t23);
#line 33
    t24 = (int64_t)INT64_C(1);
#line 33
    t25 = (int64_t)INT64_C(0);
#line 33
    t26 = (int64_t)INT64_C(0);
#line 33
    t27 = lyr_main_connect(t24, t25, t26);
#line 33
    l0_a = t27;
#line 34
    t28 = (int64_t)INT64_C(2);
#line 34
    t29 = (int64_t)INT64_C(0);
#line 34
    t30 = (int64_t)INT64_C(0);
#line 34
    t31 = lyr_main_connect(t28, t29, t30);
#line 34
    l1_b = t31;
#line 35
    t32 = (int64_t)INT64_C(3);
#line 35
    t33 = (int64_t)INT64_C(0);
#line 35
    t34 = (int64_t)INT64_C(0);
#line 35
    t35 = lyr_main_connect(t32, t33, t34);
#line 35
    l2_c = t35;
#line 36
    t36 = (LyrStr *)&lyr_lit2;
#line 36
    t37 = l0_a;
#line 36
    t38 = lyr_str_from_int(t37);
#line 36
    t39 = (LyrStr *)&lyr_lit1;
#line 36
    t40 = l1_b;
#line 36
    t41 = lyr_str_from_int(t40);
#line 36
    t42 = (LyrStr *)&lyr_lit1;
#line 36
    t43 = l2_c;
#line 36
    t44 = lyr_str_from_int(t43);
#line 36
    t45 = lyr_str_concat(t36, t38);
#line 36
    t46 = lyr_str_concat(t45, t39);
#line 36
    t47 = lyr_str_concat(t46, t41);
#line 36
    t48 = lyr_str_concat(t47, t42);
#line 36
    t49 = lyr_str_concat(t48, t44);
#line 36
    lyr_println(t49);
#line 37
    t50 = (LyrStr *)&lyr_lit3;
#line 37
    t51 = (int64_t)INT64_C(5);
#line 24
    t52 = (int64_t)INT64_C(10);
#line 24
    t53 = LYR_CHECKED_ADD(t51, t52);
#line 24
    t54 = LYR_CHECKED_SUB(t53, t51);
#line 37
    t55 = lyr_main_span(t51, t53, t54);
#line 37
    t56 = lyr_str_from_int(t55);
#line 37
    t57 = (LyrStr *)&lyr_lit1;
#line 37
    t58 = (int64_t)INT64_C(5);
#line 37
    t59 = (int64_t)INT64_C(7);
#line 24
    t60 = LYR_CHECKED_SUB(t59, t58);
#line 37
    t61 = lyr_main_span(t58, t59, t60);
#line 37
    t62 = lyr_str_from_int(t61);
#line 37
    t63 = (LyrStr *)&lyr_lit1;
#line 37
    t64 = (int64_t)INT64_C(5);
#line 24
    t65 = (int64_t)INT64_C(10);
#line 24
    t66 = LYR_CHECKED_ADD(t64, t65);
#line 37
    t67 = (int64_t)INT64_C(3);
#line 37
    t68 = lyr_main_span(t64, t66, t67);
#line 37
    t69 = lyr_str_from_int(t68);
#line 37
    t70 = lyr_str_concat(t50, t56);
#line 37
    t71 = lyr_str_concat(t70, t57);
#line 37
    t72 = lyr_str_concat(t71, t62);
#line 37
    t73 = lyr_str_concat(t72, t63);
#line 37
    t74 = lyr_str_concat(t73, t69);
#line 37
    lyr_println(t74);
#line 38
    t75 = (LyrStr *)&lyr_lit4;
#line 38
    t76 = (int64_t)INT64_C(1);
#line 38
    t77 = (int64_t)INT64_C(2);
#line 38
    t78 = (int64_t)INT64_C(3);
#line 38
    t79 = lyr_alloc_array(&lyr_desc_arr_i64, 2); LYR_ARR_DATA(t79, int64_t)[0] = t77; LYR_ARR_DATA(t79, int64_t)[1] = t78;
#line 38
    t80 = lyr_main_sum(t76, t79);
#line 38
    t81 = lyr_str_from_int(t80);
#line 38
    t82 = (LyrStr *)&lyr_lit1;
#line 38
    t83 = (int64_t)INT64_C(3);
#line 38
    t84 = lyr_alloc_array(&lyr_desc_arr_i64, 0);
#line 38
    t85 = lyr_main_sum(t83, t84);
#line 38
    t86 = lyr_str_from_int(t85);
#line 38
    t87 = lyr_str_concat(t75, t81);
#line 38
    t88 = lyr_str_concat(t87, t82);
#line 38
    t89 = lyr_str_concat(t88, t86);
#line 38
    lyr_println(t89);
#line 39
    t90 = (int64_t)INT64_C(1);
#line 39
    t91 = (int64_t)INT64_C(2);
#line 39
    t92_s = lyr_main_Point_new_2_0f8b3375(t90, t91); t92 = &t92_s;
#line 39
    l3_p = *t92;
#line 40
    t93 = (LyrStr *)&lyr_lit5;
#line 40
    t94 = &l3_p;
#line 40
    t95 = t94->f_x;
#line 40
    t96 = &l3_p;
#line 40
    t97 = t96->f_y;
#line 40
    t98 = LYR_CHECKED_ADD(t95, t97);
#line 40
    t99 = lyr_str_from_int(t98);
#line 40
    t100 = (LyrStr *)&lyr_lit1;
#line 40
    t101 = (int64_t)INT64_C(4);
#line 40
    t102_s = lyr_main_Point_new_1_0c8b2ebc(t101); t102 = &t102_s;
#line 40
    t103 = t102->f_y;
#line 40
    t104 = lyr_str_from_int(t103);
#line 40
    t105 = lyr_str_concat(t93, t99);
#line 40
    t106 = lyr_str_concat(t105, t100);
#line 40
    t107 = lyr_str_concat(t106, t104);
#line 40
    lyr_println(t107);
#line 41
    t108 = (int64_t)INT64_C(0);
#line 41
    return t108;
}

#line 12 "programs/calls.lyr"
lyr_ty0_Color lyr_main_Color_of_1_7f597b30(int64_t l0_hex) {
    int64_t t0 = 0;
    lyr_ty0_Color t1_s = {0};
    lyr_ty0_Color *t1 = &t1_s;
bb0:;
#line 12
    t0 = l0_hex;
#line 12
    t1_s = (lyr_ty0_Color){0}; t1 = &t1_s;
#line 12
    t1->f_v = t0;
#line 12
    return *t1;
}

#line 13 "programs/calls.lyr"
lyr_ty0_Color lyr_main_Color_of_3_81597e56(int64_t l0_r, int64_t l1_g, int64_t l2_b) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    int64_t t2 = 0;
    int64_t t3 = 0;
    int64_t t4 = 0;
    int64_t t5 = 0;
    int64_t t6 = 0;
    int64_t t7 = 0;
    int64_t t8 = 0;
    lyr_ty0_Color t9_s = {0};
    lyr_ty0_Color *t9 = &t9_s;
bb0:;
#line 13
    t0 = l0_r;
#line 13
    t1 = (int64_t)INT64_C(16);
#line 13
    t2 = LYR_CHECKED_MUL(t0, t1);
#line 13
    t3 = l1_g;
#line 13
    t4 = (int64_t)INT64_C(4);
#line 13
    t5 = LYR_CHECKED_MUL(t3, t4);
#line 13
    t6 = LYR_CHECKED_ADD(t2, t5);
#line 13
    t7 = l2_b;
#line 13
    t8 = LYR_CHECKED_ADD(t6, t7);
#line 13
    t9_s = (lyr_ty0_Color){0}; t9 = &t9_s;
#line 13
    t9->f_v = t8;
#line 13
    return *t9;
}

#line 19 "programs/calls.lyr"
lyr_ty1_Point lyr_main_Point_new_2_0f8b3375(int64_t l0_x, int64_t l1_y) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    lyr_ty1_Point t2_s = {0};
    lyr_ty1_Point *t2 = &t2_s;
bb0:;
#line 19
    t0 = l0_x;
#line 19
    t1 = l1_y;
#line 19
    t2_s = (lyr_ty1_Point){0}; t2 = &t2_s;
#line 19
    t2->f_x = t0;
#line 19
    t2->f_y = t1;
#line 19
    return *t2;
}

#line 20 "programs/calls.lyr"
lyr_ty1_Point lyr_main_Point_new_1_0c8b2ebc(int64_t l0_d) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    lyr_ty1_Point t2_s = {0};
    lyr_ty1_Point *t2 = &t2_s;
bb0:;
#line 20
    t0 = l0_d;
#line 20
    t1 = l0_d;
#line 20
    t2_s = (lyr_ty1_Point){0}; t2 = &t2_s;
#line 20
    t2->f_x = t0;
#line 20
    t2->f_y = t1;
#line 20
    return *t2;
}

#line 1387 "stdlib5/std/core.lyr"
void lyr__globals__9ee5f9b5(void) {
    uint64_t t0 = 0;
    double t1 = 0;
    uint64_t t2 = 0;
    double t3 = 0;
    uint64_t t4 = 0;
    float t5 = 0;
    uint64_t t6 = 0;
    float t7 = 0;
    uint64_t t8 = 0;
    uint64_t t9 = 0;
    uint64_t t10 = 0;
bb0:;
#line 1387
    t0 = (uint64_t)UINT64_C(9218868437227405312);
#line 1387
    t1 = lyr_std_core__extend__float_fromBits_3825afc5(t0);
#line 1387
    lyr_g0_float_infinity = t1;
#line 1388
    t2 = (uint64_t)UINT64_C(9221120237041090560);
#line 1388
    t3 = lyr_std_core__extend__float_fromBits_3825afc5(t2);
#line 1388
    lyr_g1_float_nan = t3;
#line 1408
    t4 = (uint64_t)UINT64_C(2139095040);
#line 1408
    t5 = lyr_std_core__extend__float32_fromBits_bc3641ce(t4);
#line 1408
    lyr_g2_float32_infinity = t5;
#line 1409
    t6 = (uint64_t)UINT64_C(2143289344);
#line 1409
    t7 = lyr_std_core__extend__float32_fromBits_bc3641ce(t6);
#line 1409
    lyr_g3_float32_nan = t7;
#line 247 "stdlib5/std/collections.lyr"
    t8 = (uint64_t)UINT64_C(9259542123273814144);
#line 247
    lyr_g4_emptyGroup = t8;
#line 248
    t9 = (uint64_t)UINT64_C(72340172838076673);
#line 248
    lyr_g5_lowBits = t9;
#line 249
    t10 = (uint64_t)UINT64_C(9259542123273814144);
#line 249
    lyr_g6_highBits = t10;
    return;
}

#line 1394 "stdlib5/std/core.lyr"
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b) {
    uint64_t t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 1394
    t0 = l0_b;
#line 1384
    t1 = (double)0.0;
#line 1394
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1394
    return t2;
}

#line 1415 "stdlib5/std/core.lyr"
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b) {
    uint64_t t0 = 0;
    float t1 = 0;
    float t2 = 0;
bb0:;
#line 1415
    t0 = l0_b;
#line 1405
    t1 = (float)0.0;
#line 1415
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1415
    return t2;
}


/* the program */
static int64_t lyr_entry(void) { lyr__globals__9ee5f9b5(); return lyr_main_main(); }
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_entry); }
