/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_std_core_StringBuilder lyr_ty_std_core_StringBuilder;
typedef struct lyr_ty_app_main_P lyr_ty_app_main_P;
typedef struct lyr_ty_app_main_Cell lyr_ty_app_main_Cell;
typedef struct lyr_ty_app_main_Holder lyr_ty_app_main_Holder;
typedef struct lyr_ty_0_env_std_io_flushed__86bc19d2 lyr_ty_0_env_std_io_flushed__86bc19d2;
typedef struct lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc;
typedef struct lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6;
typedef struct lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b;
struct lyr_ty_std_core_StringBuilder {
    LyrObj header;
    LyrArr *f_bytes;
    int64_t f_count;
};
_Static_assert(sizeof(lyr_ty_std_core_StringBuilder) == 24, "layout of lyr_ty_std_core_StringBuilder");
_Static_assert(offsetof(lyr_ty_std_core_StringBuilder, f_bytes) == 8, "layout of lyr_ty_std_core_StringBuilder");
_Static_assert(offsetof(lyr_ty_std_core_StringBuilder, f_count) == 16, "layout of lyr_ty_std_core_StringBuilder");
static const uint64_t lyr_refmap_ty_std_core_StringBuilder[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty_std_core_StringBuilder = { sizeof(lyr_ty_std_core_StringBuilder), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_std_core_StringBuilder, "std.core.StringBuilder", NULL };
struct lyr_ty_app_main_P {
    int64_t f_x;
    int64_t f_y;
};
struct lyr_ty_app_main_Cell {
    LyrObj header;
    int64_t f_v;
};
_Static_assert(sizeof(lyr_ty_app_main_Cell) == 16, "layout of lyr_ty_app_main_Cell");
_Static_assert(offsetof(lyr_ty_app_main_Cell, f_v) == 8, "layout of lyr_ty_app_main_Cell");
const LyrDesc lyr_desc_ty_app_main_Cell = { sizeof(lyr_ty_app_main_Cell), 0, 0, 0, NULL, "app.main.Cell", NULL };
struct lyr_ty_app_main_Holder {
    LyrArr *f_items;
    int64_t f_n;
};
struct lyr_ty_0_env_std_io_flushed__86bc19d2 {
    LyrObj header;
    int64_t f_stream;
};
_Static_assert(sizeof(lyr_ty_0_env_std_io_flushed__86bc19d2) == 16, "layout of lyr_ty_0_env_std_io_flushed__86bc19d2");
_Static_assert(offsetof(lyr_ty_0_env_std_io_flushed__86bc19d2, f_stream) == 8, "layout of lyr_ty_0_env_std_io_flushed__86bc19d2");
const LyrDesc lyr_desc_ty_0_env_std_io_flushed__86bc19d2 = { sizeof(lyr_ty_0_env_std_io_flushed__86bc19d2), 0, 0, 0, NULL, "<env:std.io.flushed>", NULL };
struct lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc {
    LyrObj header;
    LyrArr *f_xs;
    int64_t f_m;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc) == 24, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, f_xs) == 8, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, f_m) == 16, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
static const uint64_t lyr_refmap_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc = { sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, "<env:std.core.repeatArray<app.main.Cell>>", NULL };
struct lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 {
    LyrObj header;
    LyrArr *f_xs;
    int64_t f_m;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6) == 24, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, f_xs) == 8, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, f_m) == 16, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
static const uint64_t lyr_refmap_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 = { sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, "<env:std.core.repeatArray<app.main.Holder>>", NULL };
struct lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b {
    LyrObj header;
    LyrArr *f_xs;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b) == 16, "layout of lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b");
_Static_assert(offsetof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b, f_xs) == 8, "layout of lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b");
static const uint64_t lyr_refmap_ty_0_env_std_core_cloneArray_int___2e4e7f9b[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty_0_env_std_core_cloneArray_int___2e4e7f9b = { sizeof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_0_env_std_core_cloneArray_int___2e4e7f9b, "<env:std.core.cloneArray<int>>", NULL };
typedef struct { int64_t value; uint8_t has; } lyr_opt_i64;
typedef struct { lyr_ty_app_main_P value; uint8_t has; } lyr_opt_ty10_app_main_P;
typedef struct { uint8_t *ptr; int64_t len; } lyr_slice_u8;
_Static_assert(sizeof(lyr_slice_u8) == 16, "layout of lyr_slice_u8");
typedef struct { int64_t (*fn)(void *, LyrErr **); void *env; } lyr_fn_to_i64;
_Static_assert(sizeof(lyr_fn_to_i64) == 16, "layout of lyr_fn_to_i64");
typedef struct { lyr_ty_app_main_Cell * (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ref13_app_main_Cell;
_Static_assert(sizeof(lyr_fn_i64_to_ref13_app_main_Cell) == 16, "layout of lyr_fn_i64_to_ref13_app_main_Cell");
typedef struct { lyr_ty_app_main_Holder (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ty15_app_main_Holder;
_Static_assert(sizeof(lyr_fn_i64_to_ty15_app_main_Holder) == 16, "layout of lyr_fn_i64_to_ty15_app_main_Holder");
typedef struct { int64_t (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_i64;
_Static_assert(sizeof(lyr_fn_i64_to_i64) == 16, "layout of lyr_fn_i64_to_i64");
_Static_assert(sizeof(lyr_ty_app_main_Cell *) == 8, "layout of app.main.Cell[]");
static const uint64_t lyr_refmap_arr_ref13_app_main_Cell[] = { UINT64_C(0x1) };
const LyrDesc lyr_desc_arr_ref13_app_main_Cell = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY | LYR_DESC_HAS_REFS, sizeof(lyr_ty_app_main_Cell *), 1, lyr_refmap_arr_ref13_app_main_Cell, "app.main.Cell[]", NULL };
_Static_assert(sizeof(lyr_ty_app_main_Holder) == 16, "layout of app.main.Holder[]");
static const uint64_t lyr_refmap_arr_ty15_app_main_Holder[] = { UINT64_C(0x1) };
const LyrDesc lyr_desc_arr_ty15_app_main_Holder = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY | LYR_DESC_HAS_REFS, sizeof(lyr_ty_app_main_Holder), 1, lyr_refmap_arr_ty15_app_main_Holder, "app.main.Holder[]", NULL };
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
const LyrDesc lyr_desc_arr_i64 = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY, sizeof(int64_t), 0, NULL, "int[]", NULL };
_Static_assert(sizeof(uint8_t) == 1, "layout of u8[]");
const LyrDesc lyr_desc_arr_u8 = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY, sizeof(uint8_t), 0, NULL, "u8[]", NULL };

/* string literals */
static const LyrStaticStr(5) lyr_lit0 = LYR_STR_INIT("opt ");
static const LyrStaticStr(2) lyr_lit1 = LYR_STR_INIT(" ");
static const LyrStaticStr(7) lyr_lit2 = LYR_STR_INIT("mixed ");
static const LyrStaticStr(8) lyr_lit3 = LYR_STR_INIT("struct ");
static const LyrStaticStr(8) lyr_lit4 = LYR_STR_INIT("repeat ");
static const LyrStaticStr(8) lyr_lit5 = LYR_STR_INIT("nested ");
static const LyrStaticStr(5) lyr_lit6 = LYR_STR_INIT("true");
static const LyrStaticStr(6) lyr_lit7 = LYR_STR_INIT("false");

/* prototypes */
LYR_NOINLINE int64_t lyr_app_main_main(void);
lyr_ty_std_core_StringBuilder * lyr_std_core_fstringStart(int64_t l0_room);
LyrStr * lyr_std_core_fstringEnd(lyr_ty_std_core_StringBuilder *l0_out);
void lyr_std_core_fstringText(lyr_ty_std_core_StringBuilder * *l0_out, lyr_slice_u8 l1_text);
void lyr_std_core_fstringInt(lyr_ty_std_core_StringBuilder * *l0_out, int64_t l1_value);
void lyr_std_core_fstringBool(lyr_ty_std_core_StringBuilder * *l0_out, uint8_t l1_value);
void lyr_std_core_StringBuilder_appendStr(lyr_ty_std_core_StringBuilder *l0_this, lyr_slice_u8 l1_s);
void lyr_std_core_StringBuilder_putInt(lyr_ty_std_core_StringBuilder *l0_this, int64_t l1_v);
lyr_ty_std_core_StringBuilder * lyr_std_core_StringBuilder_sized(int64_t l0_room);
LyrStr * lyr_std_core_StringBuilder_toString(lyr_ty_std_core_StringBuilder *l0_this);
void lyr_std_core_StringBuilder_reserve(lyr_ty_std_core_StringBuilder *l0_this, int64_t l1_n);
void lyr_std_io_put(int64_t l0_stream, lyr_slice_u8 l1_text);
void lyr_std_io_drop(int64_t l0_stream);
int64_t lyr_std_io_flushed(int64_t l0_stream);
int64_t lyr_std_io_onPool(lyr_fn_to_i64 l0_call);
void lyr_std_io_println_string__d598c8ee(LyrStr *l0_v);
uint8_t lyr_std_core_equalOptionals_int__f326e1e3(lyr_opt_i64 l0_a, lyr_opt_i64 l1_b);
uint8_t lyr_std_core_equalOptionals_app_main_P__492af87c(lyr_opt_ty10_app_main_P l0_a, lyr_opt_ty10_app_main_P l1_b);
LyrArr * lyr_std_core_repeatArray_app_main_Cell__85adea75(LyrArr *l0_xs, int64_t l1_n);
LyrArr * lyr_std_core_repeatArray_app_main_Holder__0f62b54f(LyrArr *l0_xs, int64_t l1_n);
uint8_t lyr_std_core__extend__Slice_uint8__isEmpty_6b51423e(lyr_slice_u8 l0_this);
int64_t lyr_std_io_flushed__lambda0__54d704ba(void *lyr_env, LyrErr **lyr_err);
void lyr__globals__9ee5f9b5(void);
LyrStr * lyr_std_core__extend__string_show_1c50ef57(LyrStr *l0_this);
uint8_t lyr_std_core__extend__int_equals_12f53381(int64_t l0_this, int64_t l1_o);
uint8_t lyr_app_main__extend__P_equals_f1e3d682(lyr_ty_app_main_P *l0_this, lyr_ty_app_main_P l1_o);
LyrArr * lyr_std_core_arrayOf_app_main_Cell__b07c39ad(int64_t l0_n, lyr_fn_i64_to_ref13_app_main_Cell l1_f);
lyr_ty_app_main_Cell * lyr_std_core_repeatArray_app_main_Cell___lambda7__8ed5daf1(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);
LyrArr * lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(int64_t l0_n, lyr_fn_i64_to_ty15_app_main_Holder l1_f);
lyr_ty_app_main_Holder lyr_std_core_repeatArray_app_main_Holder___lambda8__3dde6010(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);
lyr_ty_app_main_Cell * lyr_app_main__extend__Cell_clone_ea0d1aaa(lyr_ty_app_main_Cell *l0_this);
lyr_ty_app_main_Holder lyr_app_main__extend__Holder_clone_5e124274(lyr_ty_app_main_Holder *l0_this);
int64_t lyr_std_core__extend__int_clone_535f4ead(int64_t l0_this);
LyrArr * lyr_std_core_cloneArray_int__c18945da(LyrArr *l0_xs);
LyrArr * lyr_std_core_arrayOf_int__e7ec54de(int64_t l0_n, lyr_fn_i64_to_i64 l1_f);
int64_t lyr_std_core_cloneArray_int___lambda15__5355ad0d(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);

#line 11 "programs/cloning.lyr"
LYR_NOINLINE int64_t lyr_app_main_main(void) {
    lyr_opt_i64 l0_a = {0};
    lyr_opt_i64 l1_b = {0};
    lyr_opt_i64 l2_c = {0};
    lyr_opt_i64 l3_none = {0};
    lyr_ty_std_core_StringBuilder *l4__fstring = NULL;
    lyr_ty_std_core_StringBuilder *l5__fstring = NULL;
    lyr_opt_ty10_app_main_P l6_p = {0};
    lyr_opt_ty10_app_main_P l7_q = {0};
    lyr_opt_ty10_app_main_P l8_r = {0};
    lyr_ty_std_core_StringBuilder *l9__fstring = NULL;
    LyrArr *l10_cells = NULL;
    lyr_ty_std_core_StringBuilder *l11__fstring = NULL;
    LyrArr *l12_hs = NULL;
    lyr_ty_std_core_StringBuilder *l13__fstring = NULL;
    int64_t t0 = 0;
    lyr_opt_i64 t1_s = {0};
    lyr_opt_i64 *t1 = &t1_s;
    int64_t t2 = 0;
    lyr_opt_i64 t3_s = {0};
    lyr_opt_i64 *t3 = &t3_s;
    int64_t t4 = 0;
    lyr_opt_i64 t5_s = {0};
    lyr_opt_i64 *t5 = &t5_s;
    lyr_opt_i64 t6_s = {0};
    lyr_opt_i64 *t6 = &t6_s;
    int64_t t7 = 0;
    lyr_ty_std_core_StringBuilder *t8 = NULL;
    lyr_ty_std_core_StringBuilder * *t9 = NULL;
    LyrStr *t10 = NULL;
    int64_t t11 = 0;
    lyr_slice_u8 t12 = {0};
    int64_t t13 = 0;
    lyr_ty_std_core_StringBuilder * *t14 = NULL;
    lyr_opt_i64 t15_s = {0};
    lyr_opt_i64 *t15 = &t15_s;
    lyr_opt_i64 t16_s = {0};
    lyr_opt_i64 *t16 = &t16_s;
    uint8_t t17 = 0;
    lyr_ty_std_core_StringBuilder * *t18 = NULL;
    LyrStr *t19 = NULL;
    int64_t t20 = 0;
    lyr_slice_u8 t21 = {0};
    int64_t t22 = 0;
    lyr_ty_std_core_StringBuilder * *t23 = NULL;
    lyr_opt_i64 t24_s = {0};
    lyr_opt_i64 *t24 = &t24_s;
    lyr_opt_i64 t25_s = {0};
    lyr_opt_i64 *t25 = &t25_s;
    uint8_t t26 = 0;
    lyr_ty_std_core_StringBuilder * *t27 = NULL;
    LyrStr *t28 = NULL;
    int64_t t29 = 0;
    lyr_slice_u8 t30 = {0};
    int64_t t31 = 0;
    lyr_ty_std_core_StringBuilder * *t32 = NULL;
    lyr_opt_i64 t33_s = {0};
    lyr_opt_i64 *t33 = &t33_s;
    uint8_t t34 = 0;
    uint8_t t35 = 0;
    lyr_ty_std_core_StringBuilder * *t36 = NULL;
    LyrStr *t37 = NULL;
    int64_t t38 = 0;
    lyr_slice_u8 t39 = {0};
    int64_t t40 = 0;
    lyr_ty_std_core_StringBuilder * *t41 = NULL;
    lyr_opt_i64 t42_s = {0};
    lyr_opt_i64 *t42 = &t42_s;
    lyr_opt_i64 t43_s = {0};
    lyr_opt_i64 *t43 = &t43_s;
    uint8_t t44 = 0;
    lyr_ty_std_core_StringBuilder * *t45 = NULL;
    LyrStr *t46 = NULL;
    int64_t t47 = 0;
    lyr_slice_u8 t48 = {0};
    int64_t t49 = 0;
    lyr_ty_std_core_StringBuilder * *t50 = NULL;
    lyr_opt_i64 t51_s = {0};
    lyr_opt_i64 *t51 = &t51_s;
    lyr_opt_i64 t52_s = {0};
    lyr_opt_i64 *t52 = &t52_s;
    uint8_t t53 = 0;
    uint8_t t54 = 0;
    lyr_ty_std_core_StringBuilder * *t55 = NULL;
    LyrStr *t56 = NULL;
    int64_t t57 = 0;
    lyr_slice_u8 t58 = {0};
    int64_t t59 = 0;
    lyr_ty_std_core_StringBuilder * *t60 = NULL;
    lyr_opt_i64 t61_s = {0};
    lyr_opt_i64 *t61 = &t61_s;
    lyr_opt_i64 t62_s = {0};
    lyr_opt_i64 *t62 = &t62_s;
    uint8_t t63 = 0;
    uint8_t t64 = 0;
    lyr_ty_std_core_StringBuilder *t65 = NULL;
    LyrStr *t66 = NULL;
    int64_t t67 = 0;
    lyr_ty_std_core_StringBuilder *t68 = NULL;
    lyr_ty_std_core_StringBuilder * *t69 = NULL;
    LyrStr *t70 = NULL;
    int64_t t71 = 0;
    lyr_slice_u8 t72 = {0};
    int64_t t73 = 0;
    lyr_ty_std_core_StringBuilder * *t74 = NULL;
    lyr_opt_i64 t75_s = {0};
    lyr_opt_i64 *t75 = &t75_s;
    int64_t t76 = 0;
    lyr_opt_i64 t77_s = {0};
    lyr_opt_i64 *t77 = &t77_s;
    uint8_t t78 = 0;
    lyr_ty_std_core_StringBuilder * *t79 = NULL;
    LyrStr *t80 = NULL;
    int64_t t81 = 0;
    lyr_slice_u8 t82 = {0};
    int64_t t83 = 0;
    lyr_ty_std_core_StringBuilder * *t84 = NULL;
    lyr_opt_i64 t85_s = {0};
    lyr_opt_i64 *t85 = &t85_s;
    int64_t t86 = 0;
    lyr_opt_i64 t87_s = {0};
    lyr_opt_i64 *t87 = &t87_s;
    uint8_t t88 = 0;
    lyr_ty_std_core_StringBuilder * *t89 = NULL;
    LyrStr *t90 = NULL;
    int64_t t91 = 0;
    lyr_slice_u8 t92 = {0};
    int64_t t93 = 0;
    lyr_ty_std_core_StringBuilder * *t94 = NULL;
    int64_t t95 = 0;
    lyr_opt_i64 t96_s = {0};
    lyr_opt_i64 *t96 = &t96_s;
    lyr_opt_i64 t97_s = {0};
    lyr_opt_i64 *t97 = &t97_s;
    uint8_t t98 = 0;
    lyr_ty_std_core_StringBuilder *t99 = NULL;
    LyrStr *t100 = NULL;
    int64_t t101 = 0;
    int64_t t102 = 0;
    lyr_ty_app_main_P t103_s = {0};
    lyr_ty_app_main_P *t103 = &t103_s;
    lyr_opt_ty10_app_main_P t104_s = {0};
    lyr_opt_ty10_app_main_P *t104 = &t104_s;
    int64_t t105 = 0;
    int64_t t106 = 0;
    lyr_ty_app_main_P t107_s = {0};
    lyr_ty_app_main_P *t107 = &t107_s;
    lyr_opt_ty10_app_main_P t108_s = {0};
    lyr_opt_ty10_app_main_P *t108 = &t108_s;
    lyr_opt_ty10_app_main_P t109_s = {0};
    lyr_opt_ty10_app_main_P *t109 = &t109_s;
    int64_t t110 = 0;
    lyr_ty_std_core_StringBuilder *t111 = NULL;
    lyr_ty_std_core_StringBuilder * *t112 = NULL;
    LyrStr *t113 = NULL;
    int64_t t114 = 0;
    lyr_slice_u8 t115 = {0};
    int64_t t116 = 0;
    lyr_ty_std_core_StringBuilder * *t117 = NULL;
    lyr_opt_ty10_app_main_P t118_s = {0};
    lyr_opt_ty10_app_main_P *t118 = &t118_s;
    lyr_opt_ty10_app_main_P t119_s = {0};
    lyr_opt_ty10_app_main_P *t119 = &t119_s;
    uint8_t t120 = 0;
    lyr_ty_std_core_StringBuilder * *t121 = NULL;
    LyrStr *t122 = NULL;
    int64_t t123 = 0;
    lyr_slice_u8 t124 = {0};
    int64_t t125 = 0;
    lyr_ty_std_core_StringBuilder * *t126 = NULL;
    lyr_opt_ty10_app_main_P t127_s = {0};
    lyr_opt_ty10_app_main_P *t127 = &t127_s;
    lyr_opt_ty10_app_main_P t128_s = {0};
    lyr_opt_ty10_app_main_P *t128 = &t128_s;
    uint8_t t129 = 0;
    lyr_ty_std_core_StringBuilder *t130 = NULL;
    LyrStr *t131 = NULL;
    int64_t t132 = 0;
    lyr_ty_app_main_Cell *t133 = NULL;
    LyrArr *t134 = NULL;
    int64_t t135 = 0;
    LyrArr *t136 = NULL;
    LyrArr *t137 = NULL;
    int64_t t138 = 0;
    lyr_ty_app_main_Cell *t139 = NULL;
    int64_t t140 = 0;
    int64_t t141 = 0;
    lyr_ty_std_core_StringBuilder *t142 = NULL;
    lyr_ty_std_core_StringBuilder * *t143 = NULL;
    LyrStr *t144 = NULL;
    int64_t t145 = 0;
    lyr_slice_u8 t146 = {0};
    int64_t t147 = 0;
    lyr_ty_std_core_StringBuilder * *t148 = NULL;
    LyrArr *t149 = NULL;
    int64_t t150 = 0;
    lyr_ty_std_core_StringBuilder * *t151 = NULL;
    LyrStr *t152 = NULL;
    int64_t t153 = 0;
    lyr_slice_u8 t154 = {0};
    int64_t t155 = 0;
    lyr_ty_std_core_StringBuilder * *t156 = NULL;
    LyrArr *t157 = NULL;
    int64_t t158 = 0;
    lyr_ty_app_main_Cell *t159 = NULL;
    int64_t t160 = 0;
    lyr_ty_std_core_StringBuilder * *t161 = NULL;
    LyrStr *t162 = NULL;
    int64_t t163 = 0;
    lyr_slice_u8 t164 = {0};
    int64_t t165 = 0;
    lyr_ty_std_core_StringBuilder * *t166 = NULL;
    LyrArr *t167 = NULL;
    int64_t t168 = 0;
    lyr_ty_app_main_Cell *t169 = NULL;
    int64_t t170 = 0;
    lyr_ty_std_core_StringBuilder * *t171 = NULL;
    LyrStr *t172 = NULL;
    int64_t t173 = 0;
    lyr_slice_u8 t174 = {0};
    int64_t t175 = 0;
    lyr_ty_std_core_StringBuilder * *t176 = NULL;
    LyrArr *t177 = NULL;
    int64_t t178 = 0;
    lyr_ty_app_main_Cell *t179 = NULL;
    int64_t t180 = 0;
    int64_t t181 = 0;
    int64_t t182 = 0;
    lyr_ty_std_core_StringBuilder * *t183 = NULL;
    LyrStr *t184 = NULL;
    int64_t t185 = 0;
    lyr_slice_u8 t186 = {0};
    int64_t t187 = 0;
    lyr_ty_std_core_StringBuilder * *t188 = NULL;
    LyrArr *t189 = NULL;
    int64_t t190 = 0;
    lyr_ty_app_main_Cell *t191 = NULL;
    LyrArr *t192 = NULL;
    int64_t t193 = 0;
    lyr_ty_app_main_Cell *t194 = NULL;
    uint8_t t195 = 0;
    lyr_ty_std_core_StringBuilder *t196 = NULL;
    LyrStr *t197 = NULL;
    int64_t t198 = 0;
    int64_t t199 = 0;
    LyrArr *t200 = NULL;
    int64_t t201 = 0;
    lyr_ty_app_main_Holder t202_s = {0};
    lyr_ty_app_main_Holder *t202 = &t202_s;
    LyrArr *t203 = NULL;
    int64_t t204 = 0;
    LyrArr *t205 = NULL;
    LyrArr *t206 = NULL;
    int64_t t207 = 0;
    lyr_ty_app_main_Holder t208_s = {0};
    lyr_ty_app_main_Holder *t208 = &t208_s;
    LyrArr *t209 = NULL;
    int64_t t210 = 0;
    int64_t t211 = 0;
    int64_t t212 = 0;
    lyr_ty_std_core_StringBuilder *t213 = NULL;
    lyr_ty_std_core_StringBuilder * *t214 = NULL;
    LyrStr *t215 = NULL;
    int64_t t216 = 0;
    lyr_slice_u8 t217 = {0};
    int64_t t218 = 0;
    lyr_ty_std_core_StringBuilder * *t219 = NULL;
    LyrArr *t220 = NULL;
    int64_t t221 = 0;
    lyr_ty_std_core_StringBuilder * *t222 = NULL;
    LyrStr *t223 = NULL;
    int64_t t224 = 0;
    lyr_slice_u8 t225 = {0};
    int64_t t226 = 0;
    lyr_ty_std_core_StringBuilder * *t227 = NULL;
    LyrArr *t228 = NULL;
    int64_t t229 = 0;
    lyr_ty_app_main_Holder t230_s = {0};
    lyr_ty_app_main_Holder *t230 = &t230_s;
    int64_t t231 = 0;
    lyr_ty_std_core_StringBuilder * *t232 = NULL;
    LyrStr *t233 = NULL;
    int64_t t234 = 0;
    lyr_slice_u8 t235 = {0};
    int64_t t236 = 0;
    lyr_ty_std_core_StringBuilder * *t237 = NULL;
    LyrArr *t238 = NULL;
    int64_t t239 = 0;
    lyr_ty_app_main_Holder t240_s = {0};
    lyr_ty_app_main_Holder *t240 = &t240_s;
    LyrArr *t241 = NULL;
    int64_t t242 = 0;
    int64_t t243 = 0;
    LyrArr *t244 = NULL;
    int64_t t245 = 0;
    lyr_ty_app_main_Holder t246_s = {0};
    lyr_ty_app_main_Holder *t246 = &t246_s;
    LyrArr *t247 = NULL;
    int64_t t248 = 0;
    int64_t t249 = 0;
    int64_t t250 = 0;
    int64_t t251 = 0;
    int64_t t252 = 0;
    lyr_ty_std_core_StringBuilder *t253 = NULL;
    LyrStr *t254 = NULL;
    int64_t t255 = 0;
bb0:;
#line 11
    t0 = (int64_t)INT64_C(5);
#line 11
    t1_s = (lyr_opt_i64){ .value = t0, .has = 1 }; t1 = &t1_s;
#line 11
    l0_a = *t1;
#line 12
    t2 = (int64_t)INT64_C(5);
#line 12
    t3_s = (lyr_opt_i64){ .value = t2, .has = 1 }; t3 = &t3_s;
#line 12
    l1_b = *t3;
#line 13
    t4 = (int64_t)INT64_C(6);
#line 13
    t5_s = (lyr_opt_i64){ .value = t4, .has = 1 }; t5 = &t5_s;
#line 13
    l2_c = *t5;
#line 14
    t6_s = (lyr_opt_i64){0}; t6 = &t6_s;
#line 14
    l3_none = *t6;
#line 15
    t7 = (int64_t)INT64_C(129);
#line 15
    t8 = lyr_std_core_fstringStart(t7);
#line 15
    l4__fstring = t8;
#line 15
    t9 = &l4__fstring;
#line 15
    t10 = (LyrStr *)&lyr_lit0;
#line 15
    t11 = t10->len;
#line 15
    t13 = (int64_t)INT64_C(0);
#line 15
    LYR_CHECK_RANGE(t13, t11, t10->len); t12 = (lyr_slice_u8){ (uint8_t *)t10->bytes + t13, t11 - t13 };
#line 15
    lyr_std_core_fstringText(t9, t12);
#line 15
    t14 = &l4__fstring;
#line 15
    t15 = &l0_a;
#line 15
    t16 = &l1_b;
#line 15
    t17 = lyr_std_core_equalOptionals_int__f326e1e3(*t15, *t16);
#line 15
    lyr_std_core_fstringBool(t14, t17);
#line 15
    t18 = &l4__fstring;
#line 15
    t19 = (LyrStr *)&lyr_lit1;
#line 15
    t20 = t19->len;
#line 15
    t22 = (int64_t)INT64_C(0);
#line 15
    LYR_CHECK_RANGE(t22, t20, t19->len); t21 = (lyr_slice_u8){ (uint8_t *)t19->bytes + t22, t20 - t22 };
#line 15
    lyr_std_core_fstringText(t18, t21);
#line 15
    t23 = &l4__fstring;
#line 15
    t24 = &l0_a;
#line 15
    t25 = &l2_c;
#line 15
    t26 = lyr_std_core_equalOptionals_int__f326e1e3(*t24, *t25);
#line 15
    lyr_std_core_fstringBool(t23, t26);
#line 15
    t27 = &l4__fstring;
#line 15
    t28 = (LyrStr *)&lyr_lit1;
#line 15
    t29 = t28->len;
#line 15
    t31 = (int64_t)INT64_C(0);
#line 15
    LYR_CHECK_RANGE(t31, t29, t28->len); t30 = (lyr_slice_u8){ (uint8_t *)t28->bytes + t31, t29 - t31 };
#line 15
    lyr_std_core_fstringText(t27, t30);
#line 15
    t32 = &l4__fstring;
#line 15
    t33 = &l3_none;
#line 15
    t34 = t33->has;
#line 15
    t35 = (uint8_t)!t34;
#line 15
    lyr_std_core_fstringBool(t32, t35);
#line 15
    t36 = &l4__fstring;
#line 15
    t37 = (LyrStr *)&lyr_lit1;
#line 15
    t38 = t37->len;
#line 15
    t40 = (int64_t)INT64_C(0);
#line 15
    LYR_CHECK_RANGE(t40, t38, t37->len); t39 = (lyr_slice_u8){ (uint8_t *)t37->bytes + t40, t38 - t40 };
#line 15
    lyr_std_core_fstringText(t36, t39);
#line 15
    t41 = &l4__fstring;
#line 15
    t42 = &l0_a;
#line 15
    t43 = &l3_none;
#line 15
    t44 = lyr_std_core_equalOptionals_int__f326e1e3(*t42, *t43);
#line 15
    lyr_std_core_fstringBool(t41, t44);
#line 15
    t45 = &l4__fstring;
#line 15
    t46 = (LyrStr *)&lyr_lit1;
#line 15
    t47 = t46->len;
#line 15
    t49 = (int64_t)INT64_C(0);
#line 15
    LYR_CHECK_RANGE(t49, t47, t46->len); t48 = (lyr_slice_u8){ (uint8_t *)t46->bytes + t49, t47 - t49 };
#line 15
    lyr_std_core_fstringText(t45, t48);
#line 15
    t50 = &l4__fstring;
#line 15
    t51 = &l0_a;
#line 15
    t52 = &l2_c;
#line 15
    t53 = lyr_std_core_equalOptionals_int__f326e1e3(*t51, *t52);
#line 15
    t54 = (uint8_t)!t53;
#line 15
    lyr_std_core_fstringBool(t50, t54);
#line 15
    t55 = &l4__fstring;
#line 15
    t56 = (LyrStr *)&lyr_lit1;
#line 15
    t57 = t56->len;
#line 15
    t59 = (int64_t)INT64_C(0);
#line 15
    LYR_CHECK_RANGE(t59, t57, t56->len); t58 = (lyr_slice_u8){ (uint8_t *)t56->bytes + t59, t57 - t59 };
#line 15
    lyr_std_core_fstringText(t55, t58);
#line 15
    t60 = &l4__fstring;
#line 15
    t61 = &l0_a;
#line 15
    t62 = &l1_b;
#line 15
    t63 = lyr_std_core_equalOptionals_int__f326e1e3(*t61, *t62);
#line 15
    t64 = (uint8_t)!t63;
#line 15
    lyr_std_core_fstringBool(t60, t64);
#line 15
    t65 = l4__fstring;
#line 15
    t66 = lyr_std_core_fstringEnd(t65);
#line 15
    lyr_std_io_println_string__d598c8ee(t66);
#line 16
    t67 = (int64_t)INT64_C(68);
#line 16
    t68 = lyr_std_core_fstringStart(t67);
#line 16
    l5__fstring = t68;
#line 16
    t69 = &l5__fstring;
#line 16
    t70 = (LyrStr *)&lyr_lit2;
#line 16
    t71 = t70->len;
#line 16
    t73 = (int64_t)INT64_C(0);
#line 16
    LYR_CHECK_RANGE(t73, t71, t70->len); t72 = (lyr_slice_u8){ (uint8_t *)t70->bytes + t73, t71 - t73 };
#line 16
    lyr_std_core_fstringText(t69, t72);
#line 16
    t74 = &l5__fstring;
#line 16
    t75 = &l0_a;
#line 16
    t76 = (int64_t)INT64_C(5);
#line 16
    t77_s = (lyr_opt_i64){ .value = t76, .has = 1 }; t77 = &t77_s;
#line 16
    t78 = lyr_std_core_equalOptionals_int__f326e1e3(*t75, *t77);
#line 16
    lyr_std_core_fstringBool(t74, t78);
#line 16
    t79 = &l5__fstring;
#line 16
    t80 = (LyrStr *)&lyr_lit1;
#line 16
    t81 = t80->len;
#line 16
    t83 = (int64_t)INT64_C(0);
#line 16
    LYR_CHECK_RANGE(t83, t81, t80->len); t82 = (lyr_slice_u8){ (uint8_t *)t80->bytes + t83, t81 - t83 };
#line 16
    lyr_std_core_fstringText(t79, t82);
#line 16
    t84 = &l5__fstring;
#line 16
    t85 = &l0_a;
#line 16
    t86 = (int64_t)INT64_C(6);
#line 16
    t87_s = (lyr_opt_i64){ .value = t86, .has = 1 }; t87 = &t87_s;
#line 16
    t88 = lyr_std_core_equalOptionals_int__f326e1e3(*t85, *t87);
#line 16
    lyr_std_core_fstringBool(t84, t88);
#line 16
    t89 = &l5__fstring;
#line 16
    t90 = (LyrStr *)&lyr_lit1;
#line 16
    t91 = t90->len;
#line 16
    t93 = (int64_t)INT64_C(0);
#line 16
    LYR_CHECK_RANGE(t93, t91, t90->len); t92 = (lyr_slice_u8){ (uint8_t *)t90->bytes + t93, t91 - t93 };
#line 16
    lyr_std_core_fstringText(t89, t92);
#line 16
    t94 = &l5__fstring;
#line 16
    t95 = (int64_t)INT64_C(5);
#line 16
    t96_s = (lyr_opt_i64){ .value = t95, .has = 1 }; t96 = &t96_s;
#line 16
    t97 = &l0_a;
#line 16
    t98 = lyr_std_core_equalOptionals_int__f326e1e3(*t96, *t97);
#line 16
    lyr_std_core_fstringBool(t94, t98);
#line 16
    t99 = l5__fstring;
#line 16
    t100 = lyr_std_core_fstringEnd(t99);
#line 16
    lyr_std_io_println_string__d598c8ee(t100);
#line 17
    t101 = (int64_t)INT64_C(1);
#line 17
    t102 = (int64_t)INT64_C(2);
#line 17
    t103_s = (lyr_ty_app_main_P){0}; t103 = &t103_s;
#line 17
    t103->f_x = t101;
#line 17
    t103->f_y = t102;
#line 17
    t104_s = (lyr_opt_ty10_app_main_P){ .value = *t103, .has = 1 }; t104 = &t104_s;
#line 17
    l6_p = *t104;
#line 18
    t105 = (int64_t)INT64_C(1);
#line 18
    t106 = (int64_t)INT64_C(2);
#line 18
    t107_s = (lyr_ty_app_main_P){0}; t107 = &t107_s;
#line 18
    t107->f_x = t105;
#line 18
    t107->f_y = t106;
#line 18
    t108_s = (lyr_opt_ty10_app_main_P){ .value = *t107, .has = 1 }; t108 = &t108_s;
#line 18
    l7_q = *t108;
#line 19
    t109_s = (lyr_opt_ty10_app_main_P){0}; t109 = &t109_s;
#line 19
    l8_r = *t109;
#line 20
    t110 = (int64_t)INT64_C(48);
#line 20
    t111 = lyr_std_core_fstringStart(t110);
#line 20
    l9__fstring = t111;
#line 20
    t112 = &l9__fstring;
#line 20
    t113 = (LyrStr *)&lyr_lit3;
#line 20
    t114 = t113->len;
#line 20
    t116 = (int64_t)INT64_C(0);
#line 20
    LYR_CHECK_RANGE(t116, t114, t113->len); t115 = (lyr_slice_u8){ (uint8_t *)t113->bytes + t116, t114 - t116 };
#line 20
    lyr_std_core_fstringText(t112, t115);
#line 20
    t117 = &l9__fstring;
#line 20
    t118 = &l6_p;
#line 20
    t119 = &l7_q;
#line 20
    t120 = lyr_std_core_equalOptionals_app_main_P__492af87c(*t118, *t119);
#line 20
    lyr_std_core_fstringBool(t117, t120);
#line 20
    t121 = &l9__fstring;
#line 20
    t122 = (LyrStr *)&lyr_lit1;
#line 20
    t123 = t122->len;
#line 20
    t125 = (int64_t)INT64_C(0);
#line 20
    LYR_CHECK_RANGE(t125, t123, t122->len); t124 = (lyr_slice_u8){ (uint8_t *)t122->bytes + t125, t123 - t125 };
#line 20
    lyr_std_core_fstringText(t121, t124);
#line 20
    t126 = &l9__fstring;
#line 20
    t127 = &l6_p;
#line 20
    t128 = &l8_r;
#line 20
    t129 = lyr_std_core_equalOptionals_app_main_P__492af87c(*t127, *t128);
#line 20
    lyr_std_core_fstringBool(t126, t129);
#line 20
    t130 = l9__fstring;
#line 20
    t131 = lyr_std_core_fstringEnd(t130);
#line 20
    lyr_std_io_println_string__d598c8ee(t131);
#line 21
    t132 = (int64_t)INT64_C(1);
#line 21
    t133 = (lyr_ty_app_main_Cell *)lyr_alloc(&lyr_desc_ty_app_main_Cell);
#line 21
    t133->f_v = t132;
#line 21
    t134 = lyr_alloc_array(&lyr_desc_arr_ref13_app_main_Cell, 1); LYR_ARR_DATA(t134, lyr_ty_app_main_Cell *)[0] = t133;
#line 21
    t135 = (int64_t)INT64_C(3);
#line 21
    t136 = lyr_std_core_repeatArray_app_main_Cell__85adea75(t134, t135);
#line 21
    l10_cells = t136;
#line 22
    t137 = l10_cells;
#line 22
    t138 = (int64_t)INT64_C(0);
#line 22
    LYR_CHECK_INDEX(t138, t137->len); t139 = LYR_ARR_DATA(t137, lyr_ty_app_main_Cell *)[t138];
#line 22
    t140 = (int64_t)INT64_C(0);
#line 22
    t139->f_v = t140;
#line 23
    t141 = (int64_t)INT64_C(111);
#line 23
    t142 = lyr_std_core_fstringStart(t141);
#line 23
    l11__fstring = t142;
#line 23
    t143 = &l11__fstring;
#line 23
    t144 = (LyrStr *)&lyr_lit4;
#line 23
    t145 = t144->len;
#line 23
    t147 = (int64_t)INT64_C(0);
#line 23
    LYR_CHECK_RANGE(t147, t145, t144->len); t146 = (lyr_slice_u8){ (uint8_t *)t144->bytes + t147, t145 - t147 };
#line 23
    lyr_std_core_fstringText(t143, t146);
#line 23
    t148 = &l11__fstring;
#line 23
    t149 = l10_cells;
#line 23
    t150 = t149->len;
#line 23
    lyr_std_core_fstringInt(t148, t150);
#line 23
    t151 = &l11__fstring;
#line 23
    t152 = (LyrStr *)&lyr_lit1;
#line 23
    t153 = t152->len;
#line 23
    t155 = (int64_t)INT64_C(0);
#line 23
    LYR_CHECK_RANGE(t155, t153, t152->len); t154 = (lyr_slice_u8){ (uint8_t *)t152->bytes + t155, t153 - t155 };
#line 23
    lyr_std_core_fstringText(t151, t154);
#line 23
    t156 = &l11__fstring;
#line 23
    t157 = l10_cells;
#line 23
    t158 = (int64_t)INT64_C(1);
#line 23
    LYR_CHECK_INDEX(t158, t157->len); t159 = LYR_ARR_DATA(t157, lyr_ty_app_main_Cell *)[t158];
#line 23
    t160 = t159->f_v;
#line 23
    lyr_std_core_fstringInt(t156, t160);
#line 23
    t161 = &l11__fstring;
#line 23
    t162 = (LyrStr *)&lyr_lit1;
#line 23
    t163 = t162->len;
#line 23
    t165 = (int64_t)INT64_C(0);
#line 23
    LYR_CHECK_RANGE(t165, t163, t162->len); t164 = (lyr_slice_u8){ (uint8_t *)t162->bytes + t165, t163 - t165 };
#line 23
    lyr_std_core_fstringText(t161, t164);
#line 23
    t166 = &l11__fstring;
#line 23
    t167 = l10_cells;
#line 23
    t168 = (int64_t)INT64_C(0);
#line 23
    LYR_CHECK_INDEX(t168, t167->len); t169 = LYR_ARR_DATA(t167, lyr_ty_app_main_Cell *)[t168];
#line 23
    t170 = t169->f_v;
#line 23
    lyr_std_core_fstringInt(t166, t170);
#line 23
    t171 = &l11__fstring;
#line 23
    t172 = (LyrStr *)&lyr_lit1;
#line 23
    t173 = t172->len;
#line 23
    t175 = (int64_t)INT64_C(0);
#line 23
    LYR_CHECK_RANGE(t175, t173, t172->len); t174 = (lyr_slice_u8){ (uint8_t *)t172->bytes + t175, t173 - t175 };
#line 23
    lyr_std_core_fstringText(t171, t174);
#line 23
    t176 = &l11__fstring;
#line 23
    t177 = l10_cells;
#line 23
    t178 = (int64_t)INT64_C(2);
#line 23
    LYR_CHECK_INDEX(t178, t177->len); t179 = LYR_ARR_DATA(t177, lyr_ty_app_main_Cell *)[t178];
#line 23
    t180 = t179->f_v;
#line 23
    t181 = (int64_t)INT64_C(1);
#line 23
    t182 = LYR_CHECKED_SUB(t180, t181);
#line 23
    lyr_std_core_fstringInt(t176, t182);
#line 23
    t183 = &l11__fstring;
#line 23
    t184 = (LyrStr *)&lyr_lit1;
#line 23
    t185 = t184->len;
#line 23
    t187 = (int64_t)INT64_C(0);
#line 23
    LYR_CHECK_RANGE(t187, t185, t184->len); t186 = (lyr_slice_u8){ (uint8_t *)t184->bytes + t187, t185 - t187 };
#line 23
    lyr_std_core_fstringText(t183, t186);
#line 23
    t188 = &l11__fstring;
#line 23
    t189 = l10_cells;
#line 23
    t190 = (int64_t)INT64_C(1);
#line 23
    LYR_CHECK_INDEX(t190, t189->len); t191 = LYR_ARR_DATA(t189, lyr_ty_app_main_Cell *)[t190];
#line 23
    t192 = l10_cells;
#line 23
    t193 = (int64_t)INT64_C(1);
#line 23
    LYR_CHECK_INDEX(t193, t192->len); t194 = LYR_ARR_DATA(t192, lyr_ty_app_main_Cell *)[t193];
#line 23
    t195 = (uint8_t)(t191 == t194);
#line 23
    lyr_std_core_fstringBool(t188, t195);
#line 23
    t196 = l11__fstring;
#line 23
    t197 = lyr_std_core_fstringEnd(t196);
#line 23
    lyr_std_io_println_string__d598c8ee(t197);
#line 24
    t198 = (int64_t)INT64_C(1);
#line 24
    t199 = (int64_t)INT64_C(2);
#line 24
    t200 = lyr_alloc_array(&lyr_desc_arr_i64, 2); LYR_ARR_DATA(t200, int64_t)[0] = t198; LYR_ARR_DATA(t200, int64_t)[1] = t199;
#line 24
    t201 = (int64_t)INT64_C(5);
#line 24
    t202_s = (lyr_ty_app_main_Holder){0}; t202 = &t202_s;
#line 24
    LYR_WRITE_BARRIER(t202, &t202->f_items, t200);
#line 24
    t202->f_n = t201;
#line 24
    t203 = lyr_alloc_array(&lyr_desc_arr_ty15_app_main_Holder, 1); LYR_ARR_DATA(t203, lyr_ty_app_main_Holder)[0] = *t202;
#line 24
    t204 = (int64_t)INT64_C(2);
#line 24
    t205 = lyr_std_core_repeatArray_app_main_Holder__0f62b54f(t203, t204);
#line 24
    l12_hs = t205;
#line 25
    t206 = l12_hs;
#line 25
    t207 = (int64_t)INT64_C(0);
#line 25
    LYR_CHECK_INDEX(t207, t206->len); t208 = &LYR_ARR_DATA(t206, lyr_ty_app_main_Holder)[t207];
#line 25
    t209 = t208->f_items;
#line 25
    t210 = (int64_t)INT64_C(0);
#line 25
    t211 = (int64_t)INT64_C(0);
#line 25
    LYR_CHECK_INDEX(t210, t209->len); LYR_ARR_DATA(t209, int64_t)[t210] = t211;
#line 26
    t212 = (int64_t)INT64_C(69);
#line 26
    t213 = lyr_std_core_fstringStart(t212);
#line 26
    l13__fstring = t213;
#line 26
    t214 = &l13__fstring;
#line 26
    t215 = (LyrStr *)&lyr_lit5;
#line 26
    t216 = t215->len;
#line 26
    t218 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_RANGE(t218, t216, t215->len); t217 = (lyr_slice_u8){ (uint8_t *)t215->bytes + t218, t216 - t218 };
#line 26
    lyr_std_core_fstringText(t214, t217);
#line 26
    t219 = &l13__fstring;
#line 26
    t220 = l12_hs;
#line 26
    t221 = t220->len;
#line 26
    lyr_std_core_fstringInt(t219, t221);
#line 26
    t222 = &l13__fstring;
#line 26
    t223 = (LyrStr *)&lyr_lit1;
#line 26
    t224 = t223->len;
#line 26
    t226 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_RANGE(t226, t224, t223->len); t225 = (lyr_slice_u8){ (uint8_t *)t223->bytes + t226, t224 - t226 };
#line 26
    lyr_std_core_fstringText(t222, t225);
#line 26
    t227 = &l13__fstring;
#line 26
    t228 = l12_hs;
#line 26
    t229 = (int64_t)INT64_C(1);
#line 26
    LYR_CHECK_INDEX(t229, t228->len); t230 = &LYR_ARR_DATA(t228, lyr_ty_app_main_Holder)[t229];
#line 26
    t231 = t230->f_n;
#line 26
    lyr_std_core_fstringInt(t227, t231);
#line 26
    t232 = &l13__fstring;
#line 26
    t233 = (LyrStr *)&lyr_lit1;
#line 26
    t234 = t233->len;
#line 26
    t236 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_RANGE(t236, t234, t233->len); t235 = (lyr_slice_u8){ (uint8_t *)t233->bytes + t236, t234 - t236 };
#line 26
    lyr_std_core_fstringText(t232, t235);
#line 26
    t237 = &l13__fstring;
#line 26
    t238 = l12_hs;
#line 26
    t239 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_INDEX(t239, t238->len); t240 = &LYR_ARR_DATA(t238, lyr_ty_app_main_Holder)[t239];
#line 26
    t241 = t240->f_items;
#line 26
    t242 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_INDEX(t242, t241->len); t243 = LYR_ARR_DATA(t241, int64_t)[t242];
#line 26
    t244 = l12_hs;
#line 26
    t245 = (int64_t)INT64_C(1);
#line 26
    LYR_CHECK_INDEX(t245, t244->len); t246 = &LYR_ARR_DATA(t244, lyr_ty_app_main_Holder)[t245];
#line 26
    t247 = t246->f_items;
#line 26
    t248 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_INDEX(t248, t247->len); t249 = LYR_ARR_DATA(t247, int64_t)[t248];
#line 26
    t250 = (int64_t)INT64_C(1);
#line 26
    t251 = LYR_CHECKED_SUB(t249, t250);
#line 26
    t252 = LYR_CHECKED_ADD(t243, t251);
#line 26
    lyr_std_core_fstringInt(t237, t252);
#line 26
    t253 = l13__fstring;
#line 26
    t254 = lyr_std_core_fstringEnd(t253);
#line 26
    lyr_std_io_println_string__d598c8ee(t254);
#line 27
    t255 = (int64_t)INT64_C(0);
#line 27
    return t255;
}

#line 4455 "stdlib5/std/core.lyr"
lyr_ty_std_core_StringBuilder * lyr_std_core_fstringStart(int64_t l0_room) {
    int64_t t0 = 0;
    lyr_ty_std_core_StringBuilder *t1 = NULL;
bb0:;
#line 4455
    t0 = l0_room;
#line 4455
    t1 = lyr_std_core_StringBuilder_sized(t0);
#line 4455
    return t1;
}

#line 4459 "stdlib5/std/core.lyr"
LyrStr * lyr_std_core_fstringEnd(lyr_ty_std_core_StringBuilder *l0_out) {
    lyr_ty_std_core_StringBuilder *t0 = NULL;
    LyrStr *t1 = NULL;
bb0:;
#line 4459
    t0 = l0_out;
#line 4459
    t1 = lyr_std_core_StringBuilder_toString(t0);
#line 4459
    return t1;
}

#line 4463 "stdlib5/std/core.lyr"
void lyr_std_core_fstringText(lyr_ty_std_core_StringBuilder * *l0_out, lyr_slice_u8 l1_text) {
    lyr_ty_std_core_StringBuilder *t0 = NULL;
    lyr_ty_std_core_StringBuilder * *t1 = NULL;
    lyr_slice_u8 t2 = {0};
bb0:;
#line 4463
    t1 = l0_out;
#line 4463
    t0 = *t1;
#line 4463
    t2 = l1_text;
#line 4463
    lyr_std_core_StringBuilder_appendStr(t0, t2);
#line 4462
    return;
}

#line 4467 "stdlib5/std/core.lyr"
void lyr_std_core_fstringInt(lyr_ty_std_core_StringBuilder * *l0_out, int64_t l1_value) {
    lyr_ty_std_core_StringBuilder *t0 = NULL;
    lyr_ty_std_core_StringBuilder * *t1 = NULL;
    int64_t t2 = 0;
bb0:;
#line 4467
    t1 = l0_out;
#line 4467
    t0 = *t1;
#line 4467
    t2 = l1_value;
#line 4467
    lyr_std_core_StringBuilder_putInt(t0, t2);
#line 4466
    return;
}

#line 4483 "stdlib5/std/core.lyr"
void lyr_std_core_fstringBool(lyr_ty_std_core_StringBuilder * *l0_out, uint8_t l1_value) {
    lyr_slice_u8 l2__if0 = {0};
    lyr_ty_std_core_StringBuilder *t0 = NULL;
    lyr_ty_std_core_StringBuilder * *t1 = NULL;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    lyr_slice_u8 t5 = {0};
    int64_t t6 = 0;
    LyrStr *t7 = NULL;
    int64_t t8 = 0;
    lyr_slice_u8 t9 = {0};
    int64_t t10 = 0;
    lyr_slice_u8 t11 = {0};
bb0:;
#line 4483
    t1 = l0_out;
#line 4483
    t0 = *t1;
#line 4483
    t2 = l1_value;
#line 4483
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 4483
    t3 = (LyrStr *)&lyr_lit6;
#line 4483
    t4 = t3->len;
#line 4483
    t6 = (int64_t)INT64_C(0);
#line 4483
    LYR_CHECK_RANGE(t6, t4, t3->len); t5 = (lyr_slice_u8){ (uint8_t *)t3->bytes + t6, t4 - t6 };
#line 4483
    l2__if0 = t5;
#line 4483
    goto bb3;
bb2:;
#line 4483
    t7 = (LyrStr *)&lyr_lit7;
#line 4483
    t8 = t7->len;
#line 4483
    t10 = (int64_t)INT64_C(0);
#line 4483
    LYR_CHECK_RANGE(t10, t8, t7->len); t9 = (lyr_slice_u8){ (uint8_t *)t7->bytes + t10, t8 - t10 };
#line 4483
    l2__if0 = t9;
#line 4483
    goto bb3;
bb3:;
#line 4483
    t11 = l2__if0;
#line 4483
    lyr_std_core_StringBuilder_appendStr(t0, t11);
#line 4482
    return;
}

#line 2557 "stdlib5/std/core.lyr"
void lyr_std_core_StringBuilder_appendStr(lyr_ty_std_core_StringBuilder *l0_this, lyr_slice_u8 l1_s) {
    int64_t l2_n = 0;
    lyr_slice_u8 t0 = {0};
    int64_t t1 = 0;
    lyr_ty_std_core_StringBuilder *t2 = NULL;
    int64_t t3 = 0;
    lyr_ty_std_core_StringBuilder *t4 = NULL;
    LyrArr *t5 = NULL;
    lyr_ty_std_core_StringBuilder *t6 = NULL;
    int64_t t7 = 0;
    lyr_slice_u8 t8 = {0};
    lyr_ty_std_core_StringBuilder *t9 = NULL;
    lyr_ty_std_core_StringBuilder *t10 = NULL;
    int64_t t11 = 0;
    int64_t t12 = 0;
    int64_t t13 = 0;
bb0:;
#line 2557
    t0 = l1_s;
#line 2557
    t1 = LYR_VIEW_LEN(t0);
#line 2557
    l2_n = t1;
#line 2558
    t2 = l0_this;
#line 2558
    t3 = l2_n;
#line 2558
    lyr_std_core_StringBuilder_reserve(t2, t3);
#line 2559
    t4 = l0_this;
#line 2559
    t5 = t4->f_bytes;
#line 2559
    t6 = l0_this;
#line 2559
    t7 = t6->f_count;
#line 2559
    t8 = l1_s;
#line 2559
    LYR_BYTES_PUT_VIEW(t5, t7, t8);
#line 2560
    t9 = l0_this;
#line 2560
    t10 = l0_this;
#line 2560
    t11 = t10->f_count;
#line 2560
    t12 = l2_n;
#line 2560
    t13 = LYR_CHECKED_ADD(t11, t12);
#line 2560
    t9->f_count = t13;
#line 2556
    return;
}

#line 2565 "stdlib5/std/core.lyr"
void lyr_std_core_StringBuilder_putInt(lyr_ty_std_core_StringBuilder *l0_this, int64_t l1_v) {
    lyr_ty_std_core_StringBuilder *t0 = NULL;
    int64_t t1 = 0;
    lyr_ty_std_core_StringBuilder *t2 = NULL;
    lyr_ty_std_core_StringBuilder *t3 = NULL;
    int64_t t4 = 0;
    lyr_ty_std_core_StringBuilder *t5 = NULL;
    LyrArr *t6 = NULL;
    lyr_ty_std_core_StringBuilder *t7 = NULL;
    int64_t t8 = 0;
    int64_t t9 = 0;
    int64_t t10 = 0;
    int64_t t11 = 0;
bb0:;
#line 2565
    t0 = l0_this;
#line 2565
    t1 = (int64_t)INT64_C(20);
#line 2565
    lyr_std_core_StringBuilder_reserve(t0, t1);
#line 2566
    t2 = l0_this;
#line 2566
    t3 = l0_this;
#line 2566
    t4 = t3->f_count;
#line 2566
    t5 = l0_this;
#line 2566
    t6 = t5->f_bytes;
#line 2566
    t7 = l0_this;
#line 2566
    t8 = t7->f_count;
#line 2566
    t9 = l1_v;
#line 2566
    t10 = lyr_bytes_put_int(t6, t8, t9);
#line 2566
    t11 = LYR_CHECKED_ADD(t4, t10);
#line 2566
    t2->f_count = t11;
#line 2564
    return;
}

#line 2577 "stdlib5/std/core.lyr"
lyr_ty_std_core_StringBuilder * lyr_std_core_StringBuilder_sized(int64_t l0_room) {
    uint8_t l1_zero = 0;
    uint8_t t0 = 0;
    uint8_t t1 = 0;
    LyrArr *t2 = NULL;
    int64_t t3 = 0;
    LyrArr *t4 = NULL;
    int64_t t5 = 0;
    lyr_ty_std_core_StringBuilder *t6 = NULL;
bb0:;
#line 2577
    t0 = (uint8_t)UINT64_C(0);
#line 2577
    l1_zero = t0;
#line 2578
    t1 = l1_zero;
#line 2578
    t2 = lyr_alloc_array(&lyr_desc_arr_u8, 1); LYR_ARR_DATA(t2, uint8_t)[0] = t1;
#line 2578
    t3 = l0_room;
#line 2578
    t4 = lyr_arr_repeat(&lyr_desc_arr_u8, t2, t3);
#line 2578
    t5 = (int64_t)INT64_C(0);
#line 2578
    t6 = (lyr_ty_std_core_StringBuilder *)lyr_alloc(&lyr_desc_ty_std_core_StringBuilder);
#line 2578
    LYR_WRITE_BARRIER(t6, &t6->f_bytes, t4);
#line 2578
    t6->f_count = t5;
#line 2578
    return t6;
}

#line 2616 "stdlib5/std/core.lyr"
LyrStr * lyr_std_core_StringBuilder_toString(lyr_ty_std_core_StringBuilder *l0_this) {
    lyr_ty_std_core_StringBuilder *t0 = NULL;
    LyrArr *t1 = NULL;
    lyr_ty_std_core_StringBuilder *t2 = NULL;
    int64_t t3 = 0;
    LyrStr *t4 = NULL;
bb0:;
#line 2616
    t0 = l0_this;
#line 2616
    t1 = t0->f_bytes;
#line 2616
    t2 = l0_this;
#line 2616
    t3 = t2->f_count;
#line 2616
    t4 = lyr_str_from_byte_array(t1, t3);
#line 2616
    return t4;
}

#line 2626 "stdlib5/std/core.lyr"
void lyr_std_core_StringBuilder_reserve(lyr_ty_std_core_StringBuilder *l0_this, int64_t l1_n) {
    int64_t l2_need = 0;
    int64_t l3_room = 0;
    int64_t l4__if0 = 0;
    uint8_t l5_zero = 0;
    LyrArr *l6_grown = NULL;
    lyr_ty_std_core_StringBuilder *t0 = NULL;
    int64_t t1 = 0;
    int64_t t2 = 0;
    int64_t t3 = 0;
    int64_t t4 = 0;
    lyr_ty_std_core_StringBuilder *t5 = NULL;
    LyrArr *t6 = NULL;
    int64_t t7 = 0;
    uint8_t t8 = 0;
    lyr_ty_std_core_StringBuilder *t9 = NULL;
    LyrArr *t10 = NULL;
    int64_t t11 = 0;
    int64_t t12 = 0;
    uint8_t t13 = 0;
    int64_t t14 = 0;
    lyr_ty_std_core_StringBuilder *t15 = NULL;
    LyrArr *t16 = NULL;
    int64_t t17 = 0;
    int64_t t18 = 0;
    int64_t t19 = 0;
    int64_t t20 = 0;
    int64_t t21 = 0;
    int64_t t22 = 0;
    uint8_t t23 = 0;
    int64_t t24 = 0;
    int64_t t25 = 0;
    int64_t t26 = 0;
    uint8_t t27 = 0;
    uint8_t t28 = 0;
    LyrArr *t29 = NULL;
    int64_t t30 = 0;
    LyrArr *t31 = NULL;
    LyrArr *t32 = NULL;
    lyr_ty_std_core_StringBuilder *t33 = NULL;
    LyrArr *t34 = NULL;
    lyr_ty_std_core_StringBuilder *t35 = NULL;
    int64_t t36 = 0;
    lyr_ty_std_core_StringBuilder *t37 = NULL;
    LyrArr *t38 = NULL;
bb0:;
#line 2626
    t0 = l0_this;
#line 2626
    t1 = t0->f_count;
#line 2626
    t2 = l1_n;
#line 2626
    t3 = LYR_CHECKED_ADD(t1, t2);
#line 2626
    l2_need = t3;
#line 2627
    t4 = l2_need;
#line 2627
    t5 = l0_this;
#line 2627
    t6 = t5->f_bytes;
#line 2627
    t7 = t6->len;
#line 2627
    t8 = (uint8_t)(t4 <= t7);
#line 2627
    if (t8) goto bb1; else goto bb2;
bb1:;
#line 2628
    return;
bb2:;
#line 2630
    t9 = l0_this;
#line 2630
    t10 = t9->f_bytes;
#line 2630
    t11 = t10->len;
#line 2630
    t12 = (int64_t)INT64_C(0);
#line 2630
    t13 = (uint8_t)(t11 == t12);
#line 2630
    if (t13) goto bb3; else goto bb4;
bb3:;
#line 2630
    t14 = (int64_t)INT64_C(16);
#line 2630
    l4__if0 = t14;
#line 2630
    goto bb5;
bb4:;
#line 2630
    t15 = l0_this;
#line 2630
    t16 = t15->f_bytes;
#line 2630
    t17 = t16->len;
#line 2630
    t18 = (int64_t)INT64_C(2);
#line 2630
    t19 = LYR_CHECKED_MUL(t17, t18);
#line 2630
    l4__if0 = t19;
#line 2630
    goto bb5;
bb5:;
#line 2630
    t20 = l4__if0;
#line 2630
    l3_room = t20;
#line 2631
    goto bb6;
bb6:;
#line 2631
    t21 = l3_room;
#line 2631
    t22 = l2_need;
#line 2631
    t23 = (uint8_t)(t21 < t22);
#line 2631
    if (t23) goto bb7; else goto bb8;
bb7:;
#line 2632
    t24 = l3_room;
#line 2632
    t25 = (int64_t)INT64_C(2);
#line 2632
    t26 = LYR_CHECKED_MUL(t24, t25);
#line 2632
    l3_room = t26;
#line 2631
    goto bb6;
bb8:;
#line 2634
    t27 = (uint8_t)UINT64_C(0);
#line 2634
    l5_zero = t27;
#line 2635
    t28 = l5_zero;
#line 2635
    t29 = lyr_alloc_array(&lyr_desc_arr_u8, 1); LYR_ARR_DATA(t29, uint8_t)[0] = t28;
#line 2635
    t30 = l3_room;
#line 2635
    t31 = lyr_arr_repeat(&lyr_desc_arr_u8, t29, t30);
#line 2635
    l6_grown = t31;
#line 2636
    t32 = l6_grown;
#line 2636
    t33 = l0_this;
#line 2636
    t34 = t33->f_bytes;
#line 2636
    t35 = l0_this;
#line 2636
    t36 = t35->f_count;
#line 2636
    lyr_bytes_copy(t32, t34, t36);
#line 2637
    t37 = l0_this;
#line 2637
    t38 = l6_grown;
#line 2637
    LYR_WRITE_BARRIER(t37, &t37->f_bytes, t38);
#line 2625
    return;
}

#line 55 "stdlib5/std/io.lyr"
void lyr_std_io_put(int64_t l0_stream, lyr_slice_u8 l1_text) {
    lyr_slice_u8 l2_rest = {0};
    int64_t l3_answer = 0;
    lyr_slice_u8 t0 = {0};
    lyr_slice_u8 t1 = {0};
    lyr_slice_u8 t2 = {0};
    uint8_t t3 = 0;
    uint8_t t4 = 0;
    int64_t t5 = 0;
    lyr_slice_u8 t6 = {0};
    int64_t t7 = 0;
    int64_t t8 = 0;
    int64_t t9 = 0;
    int64_t t10 = 0;
    int64_t t11 = 0;
    uint8_t t12 = 0;
    int64_t t13 = 0;
    lyr_slice_u8 t14 = {0};
    int64_t t15 = 0;
    int64_t t16 = 0;
    int64_t t17 = 0;
    int64_t t18 = 0;
    lyr_slice_u8 t19 = {0};
bb0:;
#line 55
    t0 = l1_text;
#line 55
    t1 = LYR_VIEW_BYTES(t0);
#line 55
    l2_rest = t1;
#line 56
    goto bb1;
bb1:;
#line 56
    t2 = l2_rest;
#line 56
    t3 = lyr_std_core__extend__Slice_uint8__isEmpty_6b51423e(t2);
#line 56
    t4 = (uint8_t)!t3;
#line 56
    if (t4) goto bb2; else goto bb3;
bb2:;
#line 57
    t5 = l0_stream;
#line 57
    t6 = l2_rest;
#line 57
    t7 = LYR_CONSOLE_PUT(t5, t6);
#line 57
    l3_answer = t7;
#line 58
    t8 = l3_answer;
#line 58
    t9 = (int64_t)INT64_C(32);
#line 58
    t10 = LYR_CHECKED_SHR(int64_t, uint64_t, 64, t8, t9);
#line 58
    t11 = (int64_t)INT64_C(0);
#line 58
    t12 = (uint8_t)(t10 != t11);
#line 58
    if (t12) goto bb4; else goto bb5;
bb3:;
#line 54
    return;
bb4:;
#line 59
    t13 = l0_stream;
#line 59
    lyr_std_io_drop(t13);
#line 58
    goto bb5;
bb5:;
#line 61
    t14 = l2_rest;
#line 61
    t15 = l3_answer;
#line 61
    t16 = (int64_t)INT64_C(4294967295);
#line 61
    t17 = (int64_t)(t15 & t16);
#line 61
    t18 = t14.len;
#line 61
    LYR_CHECK_RANGE(t17, t18, t14.len); t19 = (lyr_slice_u8){ t14.ptr + t17, t18 - t17 };
#line 61
    l2_rest = t19;
#line 56
    goto bb1;
}

#line 69 "stdlib5/std/io.lyr"
void lyr_std_io_drop(int64_t l0_stream) {
    int64_t l1_answer = 0;
    uint8_t l2__and0 = 0;
    uint8_t l3__and1 = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    int64_t t2 = 0;
    int64_t t3 = 0;
    uint8_t t4 = 0;
    int64_t t5 = 0;
    int64_t t6 = 0;
    uint8_t t7 = 0;
    uint8_t t8 = 0;
    int64_t t9 = 0;
    int64_t t10 = 0;
    int64_t t11 = 0;
    int64_t t12 = 0;
    int64_t t13 = 0;
    uint8_t t14 = 0;
    uint8_t t15 = 0;
bb0:;
#line 69
    t0 = l0_stream;
#line 69
    t1 = lyr_std_io_flushed(t0);
#line 69
    l1_answer = t1;
#line 70
    t2 = l0_stream;
#line 70
    t3 = (int64_t)INT64_C(1);
#line 70
    t4 = (uint8_t)(t2 == t3);
#line 70
    l3__and1 = t4;
#line 70
    if (t4) goto bb1; else goto bb2;
bb1:;
#line 70
    t5 = l1_answer;
#line 70
    t6 = (int64_t)INT64_C(0);
#line 70
    t7 = (uint8_t)(t5 < t6);
#line 70
    l3__and1 = t7;
#line 70
    goto bb2;
bb2:;
#line 70
    t8 = l3__and1;
#line 70
    l2__and0 = t8;
#line 70
    if (t8) goto bb3; else goto bb4;
bb3:;
#line 70
    t9 = l1_answer;
#line 70
    t10 = LYR_CHECKED_SUB((int64_t)0, t9);
#line 70
    t11 = (int64_t)INT64_C(32);
#line 70
    t12 = LYR_CHECKED_SHR(int64_t, uint64_t, 64, t10, t11);
#line 70
    t13 = (int64_t)INT64_C(13);
#line 70
    t14 = (uint8_t)(t12 == t13);
#line 70
    l2__and0 = t14;
#line 70
    goto bb4;
bb4:;
#line 70
    t15 = l2__and0;
#line 70
    if (t15) goto bb5; else goto bb6;
bb5:;
#line 71
    lyr_console_gone();
#line 70
    goto bb6;
bb6:;
#line 68
    return;
}

#line 79 "stdlib5/std/io.lyr"
int64_t lyr_std_io_flushed(int64_t l0_stream) {
    int64_t t0 = 0;
    lyr_ty_0_env_std_io_flushed__86bc19d2 *t1 = NULL;
    lyr_fn_to_i64 t2 = {0};
    int64_t t3 = 0;
bb0:;
#line 79
    t0 = l0_stream;
#line 79
    t1 = (lyr_ty_0_env_std_io_flushed__86bc19d2 *)lyr_alloc(&lyr_desc_ty_0_env_std_io_flushed__86bc19d2);
#line 79
    t1->f_stream = t0;
#line 79
    t2 = (lyr_fn_to_i64){ lyr_std_io_flushed__lambda0__54d704ba, t1 };
#line 79
    t3 = lyr_std_io_onPool(t2);
#line 79
    return t3;
}

#line 244 "stdlib5/std/io.lyr"
int64_t lyr_std_io_onPool(lyr_fn_to_i64 l0_call) {
    uint8_t t0 = 0;
    lyr_fn_to_i64 t1 = {0};
    int64_t t2 = 0;
bb0:;
#line 244
    t0 = LYR_TASK_SCHEDULER_RUNS();
#line 244
    goto bb1;
bb1:;
#line 248
    t1 = l0_call;
#line 248
    t2 = t1.fn(t1.env, NULL);
#line 248
    return t2;
}

#line 79 "stdlib5/std/io.lyr"
int64_t lyr_std_io_flushed__lambda0__54d704ba(void *lyr_env, LyrErr **lyr_err) {
    lyr_ty_0_env_std_io_flushed__86bc19d2 *l0__env_ = (lyr_ty_0_env_std_io_flushed__86bc19d2 *)lyr_env;
    (void)lyr_err;
    lyr_ty_0_env_std_io_flushed__86bc19d2 *t0 = NULL;
    int64_t t1 = 0;
    int64_t t2 = 0;
bb0:;
#line 79
    t0 = l0__env_;
#line 79
    t1 = t0->f_stream;
#line 79
    t2 = lyr_console_flush(t1);
#line 79
    return t2;
}

void lyr__globals__9ee5f9b5(void) {
bb0:;
    return;
}

#line 656 "stdlib5/std/core.lyr"
LyrStr * lyr_std_core__extend__string_show_1c50ef57(LyrStr *l0_this) {
    LyrStr *t0 = NULL;
bb0:;
#line 656
    t0 = l0_this;
#line 656
    return t0;
}

#line 367 "stdlib5/std/core.lyr"
uint8_t lyr_std_core__extend__int_equals_12f53381(int64_t l0_this, int64_t l1_o) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
bb0:;
#line 367
    t0 = l0_this;
#line 367
    t1 = l1_o;
#line 367
    t2 = (uint8_t)(t0 == t1);
#line 367
    return t2;
}

#line 3 "<synthesized Equatable for app.main.P>"
uint8_t lyr_app_main__extend__P_equals_f1e3d682(lyr_ty_app_main_P *l0_this, lyr_ty_app_main_P l1_o) {
    uint8_t l2__and0 = 0;
    lyr_ty_app_main_P t0_s = {0};
    lyr_ty_app_main_P *t0 = &t0_s;
    int64_t t1 = 0;
    lyr_ty_app_main_P t2_s = {0};
    lyr_ty_app_main_P *t2 = &t2_s;
    int64_t t3 = 0;
    uint8_t t4 = 0;
    lyr_ty_app_main_P t5_s = {0};
    lyr_ty_app_main_P *t5 = &t5_s;
    int64_t t6 = 0;
    lyr_ty_app_main_P t7_s = {0};
    lyr_ty_app_main_P *t7 = &t7_s;
    int64_t t8 = 0;
    uint8_t t9 = 0;
    uint8_t t10 = 0;
bb0:;
#line 3
    t0 = l0_this;
#line 3
    t1 = t0->f_x;
#line 3
    t2 = &l1_o;
#line 3
    t3 = t2->f_x;
#line 3
    t4 = (uint8_t)(t1 == t3);
#line 3
    l2__and0 = t4;
#line 3
    if (t4) goto bb1; else goto bb2;
bb1:;
#line 4
    t5 = l0_this;
#line 4
    t6 = t5->f_y;
#line 4
    t7 = &l1_o;
#line 4
    t8 = t7->f_y;
#line 4
    t9 = (uint8_t)(t6 == t8);
#line 4
    l2__and0 = t9;
#line 4
    goto bb2;
bb2:;
#line 3
    t10 = l2__and0;
#line 3
    return t10;
}

#line 4 "<synthesized Clone for app.main.Cell>"
lyr_ty_app_main_Cell * lyr_app_main__extend__Cell_clone_ea0d1aaa(lyr_ty_app_main_Cell *l0_this) {
    lyr_ty_app_main_Cell *t0 = NULL;
    int64_t t1 = 0;
    int64_t t2 = 0;
    lyr_ty_app_main_Cell *t3 = NULL;
bb0:;
#line 4
    t0 = l0_this;
#line 4
    t1 = t0->f_v;
#line 4
    t2 = lyr_std_core__extend__int_clone_535f4ead(t1);
#line 3
    t3 = (lyr_ty_app_main_Cell *)lyr_alloc(&lyr_desc_ty_app_main_Cell);
#line 3
    t3->f_v = t2;
#line 3
    return t3;
}

#line 4 "<synthesized Clone for app.main.Holder>"
lyr_ty_app_main_Holder lyr_app_main__extend__Holder_clone_5e124274(lyr_ty_app_main_Holder *l0_this) {
    lyr_ty_app_main_Holder t0_s = {0};
    lyr_ty_app_main_Holder *t0 = &t0_s;
    LyrArr *t1 = NULL;
    LyrArr *t2 = NULL;
    lyr_ty_app_main_Holder t3_s = {0};
    lyr_ty_app_main_Holder *t3 = &t3_s;
    int64_t t4 = 0;
    int64_t t5 = 0;
    lyr_ty_app_main_Holder t6_s = {0};
    lyr_ty_app_main_Holder *t6 = &t6_s;
bb0:;
#line 4
    t0 = l0_this;
#line 4
    t1 = t0->f_items;
#line 4
    t2 = lyr_std_core_cloneArray_int__c18945da(t1);
#line 5
    t3 = l0_this;
#line 5
    t4 = t3->f_n;
#line 5
    t5 = lyr_std_core__extend__int_clone_535f4ead(t4);
#line 3
    t6_s = (lyr_ty_app_main_Holder){0}; t6 = &t6_s;
#line 3
    LYR_WRITE_BARRIER(t6, &t6->f_items, t2);
#line 3
    t6->f_n = t5;
#line 3
    return *t6;
}

#line 691 "stdlib5/std/core.lyr"
int64_t lyr_std_core__extend__int_clone_535f4ead(int64_t l0_this) {
    int64_t t0 = 0;
bb0:;
#line 691
    t0 = l0_this;
#line 691
    return t0;
}


/* the program */
static int64_t lyr_entry(void) { lyr__globals__9ee5f9b5(); return lyr_app_main_main(); }
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_entry); }

/* ==== unit: std.core.<extend>.Slice<uint8> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.<extend>.Slice<uint8>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct { uint8_t *ptr; int64_t len; } lyr_slice_u8;
_Static_assert(sizeof(lyr_slice_u8) == 16, "layout of lyr_slice_u8");

/* prototypes */
uint8_t lyr_std_core__extend__Slice_uint8__isEmpty_6b51423e(lyr_slice_u8 l0_this);

#line 3205 "stdlib5/std/core.lyr"
uint8_t lyr_std_core__extend__Slice_uint8__isEmpty_6b51423e(lyr_slice_u8 l0_this) {
    lyr_slice_u8 t0 = {0};
    int64_t t1 = 0;
    int64_t t2 = 0;
    uint8_t t3 = 0;
bb0:;
#line 3205
    t0 = l0_this;
#line 3205
    t1 = t0.len;
#line 3205
    t2 = (int64_t)INT64_C(0);
#line 3205
    t3 = (uint8_t)(t1 == t2);
#line 3205
    return t3;
}


/* ==== unit: std.core.arrayOf<app.main.Cell> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.arrayOf<app.main.Cell>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Cell lyr_ty_app_main_Cell;
struct lyr_ty_app_main_Cell {
    LyrObj header;
    int64_t f_v;
};
_Static_assert(sizeof(lyr_ty_app_main_Cell) == 16, "layout of lyr_ty_app_main_Cell");
_Static_assert(offsetof(lyr_ty_app_main_Cell, f_v) == 8, "layout of lyr_ty_app_main_Cell");
extern const LyrDesc lyr_desc_ty_app_main_Cell;
typedef struct { lyr_ty_app_main_Cell * (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ref13_app_main_Cell;
_Static_assert(sizeof(lyr_fn_i64_to_ref13_app_main_Cell) == 16, "layout of lyr_fn_i64_to_ref13_app_main_Cell");
_Static_assert(sizeof(lyr_ty_app_main_Cell *) == 8, "layout of app.main.Cell[]");
extern const LyrDesc lyr_desc_arr_ref13_app_main_Cell;

/* string literals */
static const LyrStaticStr(27) lyr_lit0 = LYR_STR_INIT("arrayOf: a negative length");

/* prototypes */
LyrArr * lyr_std_core_arrayOf_app_main_Cell__b07c39ad(int64_t l0_n, lyr_fn_i64_to_ref13_app_main_Cell l1_f);

#line 65 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_arrayOf_app_main_Cell__b07c39ad(int64_t l0_n, lyr_fn_i64_to_ref13_app_main_Cell l1_f) {
    lyr_ty_app_main_Cell *l2_first = NULL;
    LyrArr *l3_whole = NULL;
    int64_t l4_i = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    uint8_t t6 = 0;
    LyrArr *t7 = NULL;
    lyr_fn_i64_to_ref13_app_main_Cell t8 = {0};
    int64_t t9 = 0;
    lyr_ty_app_main_Cell *t10 = NULL;
    int64_t t11 = 0;
    lyr_ty_app_main_Cell *t12 = NULL;
    LyrArr *t13 = NULL;
    LyrArr *t14 = NULL;
    int64_t t15 = 0;
    int64_t t16 = 0;
    int64_t t17 = 0;
    uint8_t t18 = 0;
    LyrArr *t19 = NULL;
    int64_t t20 = 0;
    lyr_fn_i64_to_ref13_app_main_Cell t21 = {0};
    int64_t t22 = 0;
    lyr_ty_app_main_Cell *t23 = NULL;
    int64_t t24 = 0;
    int64_t t25 = 0;
    int64_t t26 = 0;
    LyrArr *t27 = NULL;
bb0:;
#line 65
    t0 = l0_n;
#line 65
    t1 = (int64_t)INT64_C(0);
#line 65
    t2 = (uint8_t)(t0 < t1);
#line 65
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 66
    t3 = (LyrStr *)&lyr_lit0;
#line 66
    lyr_panic_message(t3);
#line 66
    LYR_UNREACHABLE();
bb2:;
#line 68
    t4 = l0_n;
#line 68
    t5 = (int64_t)INT64_C(0);
#line 68
    t6 = (uint8_t)(t4 == t5);
#line 68
    if (t6) goto bb3; else goto bb4;
bb3:;
#line 69
    t7 = lyr_alloc_array(&lyr_desc_arr_ref13_app_main_Cell, 0);
#line 69
    return t7;
bb4:;
#line 74
    t8 = l1_f;
#line 74
    t9 = (int64_t)INT64_C(0);
#line 74
    t10 = t8.fn(t8.env, t9, NULL);
#line 74
    l2_first = t10;
#line 75
    t11 = l0_n;
#line 75
    t12 = l2_first;
#line 75
    t13 = lyr_alloc_array(&lyr_desc_arr_ref13_app_main_Cell, 1); LYR_ARR_DATA(t13, lyr_ty_app_main_Cell *)[0] = t12;
#line 75
    t14 = lyr_arr_repeat(&lyr_desc_arr_ref13_app_main_Cell, t13, t11);
#line 75
    l3_whole = t14;
#line 76
    t15 = (int64_t)INT64_C(1);
#line 76
    l4_i = t15;
#line 77
    goto bb5;
bb5:;
#line 77
    t16 = l4_i;
#line 77
    t17 = l0_n;
#line 77
    t18 = (uint8_t)(t16 < t17);
#line 77
    if (t18) goto bb6; else goto bb7;
bb6:;
#line 78
    t19 = l3_whole;
#line 78
    t20 = l4_i;
#line 78
    t21 = l1_f;
#line 78
    t22 = l4_i;
#line 78
    t23 = t21.fn(t21.env, t22, NULL);
#line 78
    LYR_CHECK_INDEX(t20, t19->len); LYR_WRITE_BARRIER(t19, &LYR_ARR_DATA(t19, lyr_ty_app_main_Cell *)[t20], t23);
#line 79
    t24 = l4_i;
#line 79
    t25 = (int64_t)INT64_C(1);
#line 79
    t26 = LYR_CHECKED_ADD(t24, t25);
#line 79
    l4_i = t26;
#line 77
    goto bb5;
bb7:;
#line 81
    t27 = l3_whole;
#line 81
    return t27;
}


/* ==== unit: std.core.arrayOf<app.main.Holder> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.arrayOf<app.main.Holder>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Holder lyr_ty_app_main_Holder;
struct lyr_ty_app_main_Holder {
    LyrArr *f_items;
    int64_t f_n;
};
typedef struct { lyr_ty_app_main_Holder (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ty15_app_main_Holder;
_Static_assert(sizeof(lyr_fn_i64_to_ty15_app_main_Holder) == 16, "layout of lyr_fn_i64_to_ty15_app_main_Holder");
_Static_assert(sizeof(lyr_ty_app_main_Holder) == 16, "layout of app.main.Holder[]");
extern const LyrDesc lyr_desc_arr_ty15_app_main_Holder;
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;

/* string literals */
static const LyrStaticStr(27) lyr_lit0 = LYR_STR_INIT("arrayOf: a negative length");

/* prototypes */
LyrArr * lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(int64_t l0_n, lyr_fn_i64_to_ty15_app_main_Holder l1_f);

#line 65 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(int64_t l0_n, lyr_fn_i64_to_ty15_app_main_Holder l1_f) {
    lyr_ty_app_main_Holder l2_first = {0};
    LyrArr *l3_whole = NULL;
    int64_t l4_i = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    uint8_t t6 = 0;
    LyrArr *t7 = NULL;
    lyr_fn_i64_to_ty15_app_main_Holder t8 = {0};
    int64_t t9 = 0;
    lyr_ty_app_main_Holder t10_s = {0};
    lyr_ty_app_main_Holder *t10 = &t10_s;
    int64_t t11 = 0;
    lyr_ty_app_main_Holder t12_s = {0};
    lyr_ty_app_main_Holder *t12 = &t12_s;
    lyr_ty_app_main_Holder t13_s = {0};
    lyr_ty_app_main_Holder *t13 = &t13_s;
    LyrArr *t14 = NULL;
    LyrArr *t15 = NULL;
    int64_t t16 = 0;
    int64_t t17 = 0;
    int64_t t18 = 0;
    uint8_t t19 = 0;
    LyrArr *t20 = NULL;
    int64_t t21 = 0;
    lyr_fn_i64_to_ty15_app_main_Holder t22 = {0};
    int64_t t23 = 0;
    lyr_ty_app_main_Holder t24_s = {0};
    lyr_ty_app_main_Holder *t24 = &t24_s;
    int64_t t25 = 0;
    int64_t t26 = 0;
    int64_t t27 = 0;
    LyrArr *t28 = NULL;
bb0:;
#line 65
    t0 = l0_n;
#line 65
    t1 = (int64_t)INT64_C(0);
#line 65
    t2 = (uint8_t)(t0 < t1);
#line 65
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 66
    t3 = (LyrStr *)&lyr_lit0;
#line 66
    lyr_panic_message(t3);
#line 66
    LYR_UNREACHABLE();
bb2:;
#line 68
    t4 = l0_n;
#line 68
    t5 = (int64_t)INT64_C(0);
#line 68
    t6 = (uint8_t)(t4 == t5);
#line 68
    if (t6) goto bb3; else goto bb4;
bb3:;
#line 69
    t7 = lyr_alloc_array(&lyr_desc_arr_ty15_app_main_Holder, 0);
#line 69
    return t7;
bb4:;
#line 74
    t8 = l1_f;
#line 74
    t9 = (int64_t)INT64_C(0);
#line 74
    t10_s = t8.fn(t8.env, t9, NULL); t10 = &t10_s;
#line 74
    l2_first = *t10;
#line 75
    t11 = l0_n;
#line 75
    t12 = &l2_first;
#line 75
    t13_s = *t12; t13 = &t13_s;
#line 75
    t14 = lyr_alloc_array(&lyr_desc_arr_ty15_app_main_Holder, 1); LYR_ARR_DATA(t14, lyr_ty_app_main_Holder)[0] = *t13;
#line 75
    t15 = lyr_arr_repeat(&lyr_desc_arr_ty15_app_main_Holder, t14, t11);
#line 75
    l3_whole = t15;
#line 76
    t16 = (int64_t)INT64_C(1);
#line 76
    l4_i = t16;
#line 77
    goto bb5;
bb5:;
#line 77
    t17 = l4_i;
#line 77
    t18 = l0_n;
#line 77
    t19 = (uint8_t)(t17 < t18);
#line 77
    if (t19) goto bb6; else goto bb7;
bb6:;
#line 78
    t20 = l3_whole;
#line 78
    t21 = l4_i;
#line 78
    t22 = l1_f;
#line 78
    t23 = l4_i;
#line 78
    t24_s = t22.fn(t22.env, t23, NULL); t24 = &t24_s;
#line 78
    LYR_CHECK_INDEX(t21, t20->len); LYR_WRITE_BARRIER_VALUE(t20, &LYR_ARR_DATA(t20, lyr_ty_app_main_Holder)[t21], *t24);
#line 79
    t25 = l4_i;
#line 79
    t26 = (int64_t)INT64_C(1);
#line 79
    t27 = LYR_CHECKED_ADD(t25, t26);
#line 79
    l4_i = t27;
#line 77
    goto bb5;
bb7:;
#line 81
    t28 = l3_whole;
#line 81
    return t28;
}


/* ==== unit: std.core.arrayOf<int> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.arrayOf<int>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct { int64_t (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_i64;
_Static_assert(sizeof(lyr_fn_i64_to_i64) == 16, "layout of lyr_fn_i64_to_i64");
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;

/* string literals */
static const LyrStaticStr(27) lyr_lit0 = LYR_STR_INIT("arrayOf: a negative length");

/* prototypes */
LyrArr * lyr_std_core_arrayOf_int__e7ec54de(int64_t l0_n, lyr_fn_i64_to_i64 l1_f);

#line 65 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_arrayOf_int__e7ec54de(int64_t l0_n, lyr_fn_i64_to_i64 l1_f) {
    int64_t l2_first = 0;
    LyrArr *l3_whole = NULL;
    int64_t l4_i = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    uint8_t t6 = 0;
    LyrArr *t7 = NULL;
    lyr_fn_i64_to_i64 t8 = {0};
    int64_t t9 = 0;
    int64_t t10 = 0;
    int64_t t11 = 0;
    int64_t t12 = 0;
    LyrArr *t13 = NULL;
    LyrArr *t14 = NULL;
    int64_t t15 = 0;
    int64_t t16 = 0;
    int64_t t17 = 0;
    uint8_t t18 = 0;
    LyrArr *t19 = NULL;
    int64_t t20 = 0;
    lyr_fn_i64_to_i64 t21 = {0};
    int64_t t22 = 0;
    int64_t t23 = 0;
    int64_t t24 = 0;
    int64_t t25 = 0;
    int64_t t26 = 0;
    LyrArr *t27 = NULL;
bb0:;
#line 65
    t0 = l0_n;
#line 65
    t1 = (int64_t)INT64_C(0);
#line 65
    t2 = (uint8_t)(t0 < t1);
#line 65
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 66
    t3 = (LyrStr *)&lyr_lit0;
#line 66
    lyr_panic_message(t3);
#line 66
    LYR_UNREACHABLE();
bb2:;
#line 68
    t4 = l0_n;
#line 68
    t5 = (int64_t)INT64_C(0);
#line 68
    t6 = (uint8_t)(t4 == t5);
#line 68
    if (t6) goto bb3; else goto bb4;
bb3:;
#line 69
    t7 = lyr_alloc_array(&lyr_desc_arr_i64, 0);
#line 69
    return t7;
bb4:;
#line 74
    t8 = l1_f;
#line 74
    t9 = (int64_t)INT64_C(0);
#line 74
    t10 = t8.fn(t8.env, t9, NULL);
#line 74
    l2_first = t10;
#line 75
    t11 = l0_n;
#line 75
    t12 = l2_first;
#line 75
    t13 = lyr_alloc_array(&lyr_desc_arr_i64, 1); LYR_ARR_DATA(t13, int64_t)[0] = t12;
#line 75
    t14 = lyr_arr_repeat(&lyr_desc_arr_i64, t13, t11);
#line 75
    l3_whole = t14;
#line 76
    t15 = (int64_t)INT64_C(1);
#line 76
    l4_i = t15;
#line 77
    goto bb5;
bb5:;
#line 77
    t16 = l4_i;
#line 77
    t17 = l0_n;
#line 77
    t18 = (uint8_t)(t16 < t17);
#line 77
    if (t18) goto bb6; else goto bb7;
bb6:;
#line 78
    t19 = l3_whole;
#line 78
    t20 = l4_i;
#line 78
    t21 = l1_f;
#line 78
    t22 = l4_i;
#line 78
    t23 = t21.fn(t21.env, t22, NULL);
#line 78
    LYR_CHECK_INDEX(t20, t19->len); LYR_ARR_DATA(t19, int64_t)[t20] = t23;
#line 79
    t24 = l4_i;
#line 79
    t25 = (int64_t)INT64_C(1);
#line 79
    t26 = LYR_CHECKED_ADD(t24, t25);
#line 79
    l4_i = t26;
#line 77
    goto bb5;
bb7:;
#line 81
    t27 = l3_whole;
#line 81
    return t27;
}


/* ==== unit: std.core.cloneArray<int> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.cloneArray<int>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b;
struct lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b {
    LyrObj header;
    LyrArr *f_xs;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b) == 16, "layout of lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b");
_Static_assert(offsetof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b, f_xs) == 8, "layout of lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b");
extern const LyrDesc lyr_desc_ty_0_env_std_core_cloneArray_int___2e4e7f9b;
typedef struct { int64_t (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_i64;
_Static_assert(sizeof(lyr_fn_i64_to_i64) == 16, "layout of lyr_fn_i64_to_i64");
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;

/* prototypes */
int64_t lyr_std_core__extend__int_clone_535f4ead(int64_t l0_this);
LyrArr * lyr_std_core_cloneArray_int__c18945da(LyrArr *l0_xs);
LyrArr * lyr_std_core_arrayOf_int__e7ec54de(int64_t l0_n, lyr_fn_i64_to_i64 l1_f);
int64_t lyr_std_core_cloneArray_int___lambda15__5355ad0d(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);

#line 4299 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_cloneArray_int__c18945da(LyrArr *l0_xs) {
    LyrArr *t0 = NULL;
    int64_t t1 = 0;
    LyrArr *t2 = NULL;
    lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *t3 = NULL;
    lyr_fn_i64_to_i64 t4 = {0};
    LyrArr *t5 = NULL;
bb0:;
#line 4299
    t0 = l0_xs;
#line 4299
    t1 = t0->len;
#line 4299
    t2 = l0_xs;
#line 4299
    t3 = (lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *)lyr_alloc(&lyr_desc_ty_0_env_std_core_cloneArray_int___2e4e7f9b);
#line 4299
    LYR_WRITE_BARRIER(t3, &t3->f_xs, t2);
#line 4299
    t4 = (lyr_fn_i64_to_i64){ lyr_std_core_cloneArray_int___lambda15__5355ad0d, t3 };
#line 4299
    t5 = lyr_std_core_arrayOf_int__e7ec54de(t1, t4);
#line 4299
    return t5;
}

#line 4299 "stdlib5/std/core.lyr"
int64_t lyr_std_core_cloneArray_int___lambda15__5355ad0d(void *lyr_env, int64_t l1_i, LyrErr **lyr_err) {
    lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *l0__env_ = (lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *)lyr_env;
    (void)lyr_err;
    lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *t0 = NULL;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    int64_t t3 = 0;
    int64_t t4 = 0;
bb0:;
#line 4299
    t0 = l0__env_;
#line 4299
    t1 = t0->f_xs;
#line 4299
    t2 = l1_i;
#line 4299
    LYR_CHECK_INDEX(t2, t1->len); t3 = LYR_ARR_DATA(t1, int64_t)[t2];
#line 4299
    t4 = lyr_std_core__extend__int_clone_535f4ead(t3);
#line 4299
    return t4;
}


/* ==== unit: std.core.equalOptionals<app.main.P> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.equalOptionals<app.main.P>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_P lyr_ty_app_main_P;
struct lyr_ty_app_main_P {
    int64_t f_x;
    int64_t f_y;
};
typedef struct { lyr_ty_app_main_P value; uint8_t has; } lyr_opt_ty10_app_main_P;

/* prototypes */
uint8_t lyr_std_core_equalOptionals_app_main_P__492af87c(lyr_opt_ty10_app_main_P l0_a, lyr_opt_ty10_app_main_P l1_b);
uint8_t lyr_app_main__extend__P_equals_f1e3d682(lyr_ty_app_main_P *l0_this, lyr_ty_app_main_P l1_o);

#line 4273 "stdlib5/std/core.lyr"
uint8_t lyr_std_core_equalOptionals_app_main_P__492af87c(lyr_opt_ty10_app_main_P l0_a, lyr_opt_ty10_app_main_P l1_b) {
    lyr_opt_ty10_app_main_P t0_s = {0};
    lyr_opt_ty10_app_main_P *t0 = &t0_s;
    uint8_t t1 = 0;
    uint8_t t2 = 0;
    lyr_opt_ty10_app_main_P t3_s = {0};
    lyr_opt_ty10_app_main_P *t3 = &t3_s;
    uint8_t t4 = 0;
    uint8_t t5 = 0;
    lyr_opt_ty10_app_main_P t6_s = {0};
    lyr_opt_ty10_app_main_P *t6 = &t6_s;
    uint8_t t7 = 0;
    uint8_t t8 = 0;
    uint8_t t9 = 0;
    lyr_opt_ty10_app_main_P t10_s = {0};
    lyr_opt_ty10_app_main_P *t10 = &t10_s;
    lyr_ty_app_main_P t11_s = {0};
    lyr_ty_app_main_P *t11 = &t11_s;
    lyr_ty_app_main_P t12_s = {0};
    lyr_ty_app_main_P *t12 = &t12_s;
    lyr_opt_ty10_app_main_P t13_s = {0};
    lyr_opt_ty10_app_main_P *t13 = &t13_s;
    lyr_ty_app_main_P t14_s = {0};
    lyr_ty_app_main_P *t14 = &t14_s;
    uint8_t t15 = 0;
bb0:;
#line 4273
    t0 = &l0_a;
#line 4273
    t1 = t0->has;
#line 4273
    t2 = (uint8_t)!t1;
#line 4273
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 4273
    t3 = &l1_b;
#line 4273
    t4 = t3->has;
#line 4273
    t5 = (uint8_t)!t4;
#line 4273
    return t5;
bb2:;
#line 4274
    t6 = &l1_b;
#line 4274
    t7 = t6->has;
#line 4274
    t8 = (uint8_t)!t7;
#line 4274
    if (t8) goto bb3; else goto bb4;
bb3:;
#line 4274
    t9 = 0;
#line 4274
    return t9;
bb4:;
#line 4275
    t10 = &l1_b;
#line 4275
    t11 = &t10->value;
#line 4275
    t12_s = *t11; t12 = &t12_s;
#line 4275
    t13 = &l0_a;
#line 4275
    t14 = &t13->value;
#line 4275
    t15 = lyr_app_main__extend__P_equals_f1e3d682(t14, *t12);
#line 4275
    return t15;
}


/* ==== unit: std.core.equalOptionals<int> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.equalOptionals<int>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct { int64_t value; uint8_t has; } lyr_opt_i64;

/* prototypes */
uint8_t lyr_std_core_equalOptionals_int__f326e1e3(lyr_opt_i64 l0_a, lyr_opt_i64 l1_b);
uint8_t lyr_std_core__extend__int_equals_12f53381(int64_t l0_this, int64_t l1_o);

#line 4273 "stdlib5/std/core.lyr"
uint8_t lyr_std_core_equalOptionals_int__f326e1e3(lyr_opt_i64 l0_a, lyr_opt_i64 l1_b) {
    lyr_opt_i64 t0_s = {0};
    lyr_opt_i64 *t0 = &t0_s;
    uint8_t t1 = 0;
    uint8_t t2 = 0;
    lyr_opt_i64 t3_s = {0};
    lyr_opt_i64 *t3 = &t3_s;
    uint8_t t4 = 0;
    uint8_t t5 = 0;
    lyr_opt_i64 t6_s = {0};
    lyr_opt_i64 *t6 = &t6_s;
    uint8_t t7 = 0;
    uint8_t t8 = 0;
    uint8_t t9 = 0;
    lyr_opt_i64 t10_s = {0};
    lyr_opt_i64 *t10 = &t10_s;
    int64_t t11 = 0;
    lyr_opt_i64 t12_s = {0};
    lyr_opt_i64 *t12 = &t12_s;
    int64_t t13 = 0;
    uint8_t t14 = 0;
bb0:;
#line 4273
    t0 = &l0_a;
#line 4273
    t1 = t0->has;
#line 4273
    t2 = (uint8_t)!t1;
#line 4273
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 4273
    t3 = &l1_b;
#line 4273
    t4 = t3->has;
#line 4273
    t5 = (uint8_t)!t4;
#line 4273
    return t5;
bb2:;
#line 4274
    t6 = &l1_b;
#line 4274
    t7 = t6->has;
#line 4274
    t8 = (uint8_t)!t7;
#line 4274
    if (t8) goto bb3; else goto bb4;
bb3:;
#line 4274
    t9 = 0;
#line 4274
    return t9;
bb4:;
#line 4275
    t10 = &l0_a;
#line 4275
    t11 = t10->value;
#line 4275
    t12 = &l1_b;
#line 4275
    t13 = t12->value;
#line 4275
    t14 = lyr_std_core__extend__int_equals_12f53381(t11, t13);
#line 4275
    return t14;
}


/* ==== unit: std.core.repeatArray<app.main.Cell> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.repeatArray<app.main.Cell>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Cell lyr_ty_app_main_Cell;
typedef struct lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc;
struct lyr_ty_app_main_Cell {
    LyrObj header;
    int64_t f_v;
};
_Static_assert(sizeof(lyr_ty_app_main_Cell) == 16, "layout of lyr_ty_app_main_Cell");
_Static_assert(offsetof(lyr_ty_app_main_Cell, f_v) == 8, "layout of lyr_ty_app_main_Cell");
extern const LyrDesc lyr_desc_ty_app_main_Cell;
struct lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc {
    LyrObj header;
    LyrArr *f_xs;
    int64_t f_m;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc) == 24, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, f_xs) == 8, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, f_m) == 16, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
extern const LyrDesc lyr_desc_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc;
typedef struct { lyr_ty_app_main_Cell * (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ref13_app_main_Cell;
_Static_assert(sizeof(lyr_fn_i64_to_ref13_app_main_Cell) == 16, "layout of lyr_fn_i64_to_ref13_app_main_Cell");
_Static_assert(sizeof(lyr_ty_app_main_Cell *) == 8, "layout of app.main.Cell[]");
extern const LyrDesc lyr_desc_arr_ref13_app_main_Cell;

/* string literals */
static const LyrStaticStr(22) lyr_lit0 = LYR_STR_INIT("negative repeat count");

/* prototypes */
LyrArr * lyr_std_core_repeatArray_app_main_Cell__85adea75(LyrArr *l0_xs, int64_t l1_n);
LyrArr * lyr_std_core_arrayOf_app_main_Cell__b07c39ad(int64_t l0_n, lyr_fn_i64_to_ref13_app_main_Cell l1_f);
lyr_ty_app_main_Cell * lyr_std_core_repeatArray_app_main_Cell___lambda7__8ed5daf1(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);
lyr_ty_app_main_Cell * lyr_app_main__extend__Cell_clone_ea0d1aaa(lyr_ty_app_main_Cell *l0_this);

#line 94 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_repeatArray_app_main_Cell__85adea75(LyrArr *l0_xs, int64_t l1_n) {
    int64_t l2_m = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    LyrArr *t4 = NULL;
    int64_t t5 = 0;
    int64_t t6 = 0;
    int64_t t7 = 0;
    int64_t t8 = 0;
    LyrArr *t9 = NULL;
    int64_t t10 = 0;
    lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *t11 = NULL;
    lyr_fn_i64_to_ref13_app_main_Cell t12 = {0};
    LyrArr *t13 = NULL;
bb0:;
#line 94
    t0 = l1_n;
#line 94
    t1 = (int64_t)INT64_C(0);
#line 94
    t2 = (uint8_t)(t0 < t1);
#line 94
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 94
    t3 = (LyrStr *)&lyr_lit0;
#line 94
    lyr_panic_message(t3);
#line 94
    LYR_UNREACHABLE();
bb2:;
#line 95
    t4 = l0_xs;
#line 95
    t5 = t4->len;
#line 95
    l2_m = t5;
#line 96
    t6 = l2_m;
#line 96
    t7 = l1_n;
#line 96
    t8 = LYR_CHECKED_MUL(t6, t7);
#line 96
    t9 = l0_xs;
#line 96
    t10 = l2_m;
#line 96
    t11 = (lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *)lyr_alloc(&lyr_desc_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc);
#line 96
    LYR_WRITE_BARRIER(t11, &t11->f_xs, t9);
#line 96
    t11->f_m = t10;
#line 96
    t12 = (lyr_fn_i64_to_ref13_app_main_Cell){ lyr_std_core_repeatArray_app_main_Cell___lambda7__8ed5daf1, t11 };
#line 96
    t13 = lyr_std_core_arrayOf_app_main_Cell__b07c39ad(t8, t12);
#line 96
    return t13;
}

#line 96 "stdlib5/std/core.lyr"
lyr_ty_app_main_Cell * lyr_std_core_repeatArray_app_main_Cell___lambda7__8ed5daf1(void *lyr_env, int64_t l1_i, LyrErr **lyr_err) {
    lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *l0__env_ = (lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *)lyr_env;
    (void)lyr_err;
    lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *t0 = NULL;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    lyr_ty_app_main_Cell *t6 = NULL;
    lyr_ty_app_main_Cell *t7 = NULL;
bb0:;
#line 96
    t0 = l0__env_;
#line 96
    t1 = t0->f_xs;
#line 96
    t2 = l1_i;
#line 96
    t3 = l0__env_;
#line 96
    t4 = t3->f_m;
#line 96
    t5 = LYR_CHECKED_REM(t2, t4);
#line 96
    LYR_CHECK_INDEX(t5, t1->len); t6 = LYR_ARR_DATA(t1, lyr_ty_app_main_Cell *)[t5];
#line 96
    t7 = lyr_app_main__extend__Cell_clone_ea0d1aaa(t6);
#line 96
    return t7;
}


/* ==== unit: std.core.repeatArray<app.main.Holder> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.repeatArray<app.main.Holder>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Holder lyr_ty_app_main_Holder;
typedef struct lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6;
struct lyr_ty_app_main_Holder {
    LyrArr *f_items;
    int64_t f_n;
};
struct lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 {
    LyrObj header;
    LyrArr *f_xs;
    int64_t f_m;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6) == 24, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, f_xs) == 8, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, f_m) == 16, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
extern const LyrDesc lyr_desc_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6;
typedef struct { lyr_ty_app_main_Holder (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ty15_app_main_Holder;
_Static_assert(sizeof(lyr_fn_i64_to_ty15_app_main_Holder) == 16, "layout of lyr_fn_i64_to_ty15_app_main_Holder");
_Static_assert(sizeof(lyr_ty_app_main_Holder) == 16, "layout of app.main.Holder[]");
extern const LyrDesc lyr_desc_arr_ty15_app_main_Holder;
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;

/* string literals */
static const LyrStaticStr(22) lyr_lit0 = LYR_STR_INIT("negative repeat count");

/* prototypes */
LyrArr * lyr_std_core_repeatArray_app_main_Holder__0f62b54f(LyrArr *l0_xs, int64_t l1_n);
LyrArr * lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(int64_t l0_n, lyr_fn_i64_to_ty15_app_main_Holder l1_f);
lyr_ty_app_main_Holder lyr_std_core_repeatArray_app_main_Holder___lambda8__3dde6010(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);
lyr_ty_app_main_Holder lyr_app_main__extend__Holder_clone_5e124274(lyr_ty_app_main_Holder *l0_this);

#line 94 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_repeatArray_app_main_Holder__0f62b54f(LyrArr *l0_xs, int64_t l1_n) {
    int64_t l2_m = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    LyrArr *t4 = NULL;
    int64_t t5 = 0;
    int64_t t6 = 0;
    int64_t t7 = 0;
    int64_t t8 = 0;
    LyrArr *t9 = NULL;
    int64_t t10 = 0;
    lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *t11 = NULL;
    lyr_fn_i64_to_ty15_app_main_Holder t12 = {0};
    LyrArr *t13 = NULL;
bb0:;
#line 94
    t0 = l1_n;
#line 94
    t1 = (int64_t)INT64_C(0);
#line 94
    t2 = (uint8_t)(t0 < t1);
#line 94
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 94
    t3 = (LyrStr *)&lyr_lit0;
#line 94
    lyr_panic_message(t3);
#line 94
    LYR_UNREACHABLE();
bb2:;
#line 95
    t4 = l0_xs;
#line 95
    t5 = t4->len;
#line 95
    l2_m = t5;
#line 96
    t6 = l2_m;
#line 96
    t7 = l1_n;
#line 96
    t8 = LYR_CHECKED_MUL(t6, t7);
#line 96
    t9 = l0_xs;
#line 96
    t10 = l2_m;
#line 96
    t11 = (lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *)lyr_alloc(&lyr_desc_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6);
#line 96
    LYR_WRITE_BARRIER(t11, &t11->f_xs, t9);
#line 96
    t11->f_m = t10;
#line 96
    t12 = (lyr_fn_i64_to_ty15_app_main_Holder){ lyr_std_core_repeatArray_app_main_Holder___lambda8__3dde6010, t11 };
#line 96
    t13 = lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(t8, t12);
#line 96
    return t13;
}

#line 96 "stdlib5/std/core.lyr"
lyr_ty_app_main_Holder lyr_std_core_repeatArray_app_main_Holder___lambda8__3dde6010(void *lyr_env, int64_t l1_i, LyrErr **lyr_err) {
    lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *l0__env_ = (lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *)lyr_env;
    (void)lyr_err;
    lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *t0 = NULL;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    lyr_ty_app_main_Holder t6_s = {0};
    lyr_ty_app_main_Holder *t6 = &t6_s;
    lyr_ty_app_main_Holder t7_s = {0};
    lyr_ty_app_main_Holder *t7 = &t7_s;
bb0:;
#line 96
    t0 = l0__env_;
#line 96
    t1 = t0->f_xs;
#line 96
    t2 = l1_i;
#line 96
    t3 = l0__env_;
#line 96
    t4 = t3->f_m;
#line 96
    t5 = LYR_CHECKED_REM(t2, t4);
#line 96
    LYR_CHECK_INDEX(t5, t1->len); t6 = &LYR_ARR_DATA(t1, lyr_ty_app_main_Holder)[t5];
#line 96
    t7_s = lyr_app_main__extend__Holder_clone_5e124274(t6); t7 = &t7_s;
#line 96
    return *t7;
}


/* ==== unit: std.io.println<string> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.io.println<string>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct { uint8_t *ptr; int64_t len; } lyr_slice_u8;
_Static_assert(sizeof(lyr_slice_u8) == 16, "layout of lyr_slice_u8");

/* string literals */
static const LyrStaticStr(2) lyr_lit0 = LYR_STR_INIT("\012");

/* prototypes */
void lyr_std_io_put(int64_t l0_stream, lyr_slice_u8 l1_text);
void lyr_std_io_println_string__d598c8ee(LyrStr *l0_v);
LyrStr * lyr_std_core__extend__string_show_1c50ef57(LyrStr *l0_this);

#line 30 "stdlib5/std/io.lyr"
void lyr_std_io_println_string__d598c8ee(LyrStr *l0_v) {
    int64_t t0 = 0;
    LyrStr *t1 = NULL;
    LyrStr *t2 = NULL;
    int64_t t3 = 0;
    lyr_slice_u8 t4 = {0};
    int64_t t5 = 0;
    int64_t t6 = 0;
    LyrStr *t7 = NULL;
    int64_t t8 = 0;
    lyr_slice_u8 t9 = {0};
    int64_t t10 = 0;
bb0:;
#line 30
    t0 = (int64_t)INT64_C(1);
#line 30
    t1 = l0_v;
#line 30
    t2 = lyr_std_core__extend__string_show_1c50ef57(t1);
#line 30
    t3 = t2->len;
#line 30
    t5 = (int64_t)INT64_C(0);
#line 30
    LYR_CHECK_RANGE(t5, t3, t2->len); t4 = (lyr_slice_u8){ (uint8_t *)t2->bytes + t5, t3 - t5 };
#line 30
    lyr_std_io_put(t0, t4);
#line 31
    t6 = (int64_t)INT64_C(1);
#line 31
    t7 = (LyrStr *)&lyr_lit0;
#line 31
    t8 = t7->len;
#line 31
    t10 = (int64_t)INT64_C(0);
#line 31
    LYR_CHECK_RANGE(t10, t8, t7->len); t9 = (lyr_slice_u8){ (uint8_t *)t7->bytes + t10, t8 - t10 };
#line 31
    lyr_std_io_put(t6, t9);
#line 29
    return;
}

