/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_P lyr_ty_app_main_P;
typedef struct lyr_ty_app_main_Cell lyr_ty_app_main_Cell;
typedef struct lyr_ty_app_main_Holder lyr_ty_app_main_Holder;
typedef struct lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc;
typedef struct lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6;
typedef struct lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b;
struct lyr_ty_app_main_P {
    int64_t f_x;
    int64_t f_y;
};
struct lyr_ty_app_main_Cell {
    LyrObj header;
    int64_t f_v;
};
_Static_assert(sizeof(lyr_ty_app_main_Cell) == 16, "layout of lyr_ty_app_main_Cell");
_Static_assert(offsetof(lyr_ty_app_main_Cell, f_v) == 8, "layout of lyr_ty_app_main_Cell");
const LyrDesc lyr_desc_ty_app_main_Cell = { sizeof(lyr_ty_app_main_Cell), 0, 0, 0, NULL, "app.main.Cell", NULL };
struct lyr_ty_app_main_Holder {
    LyrArr *f_items;
    int64_t f_n;
};
struct lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc {
    LyrObj header;
    LyrArr *f_xs;
    int64_t f_m;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc) == 24, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, f_xs) == 8, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, f_m) == 16, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
static const uint64_t lyr_refmap_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc = { sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, "<env:std.core.repeatArray<app.main.Cell>>", NULL };
struct lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 {
    LyrObj header;
    LyrArr *f_xs;
    int64_t f_m;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6) == 24, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, f_xs) == 8, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, f_m) == 16, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
static const uint64_t lyr_refmap_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 = { sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, "<env:std.core.repeatArray<app.main.Holder>>", NULL };
struct lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b {
    LyrObj header;
    LyrArr *f_xs;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b) == 16, "layout of lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b");
_Static_assert(offsetof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b, f_xs) == 8, "layout of lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b");
static const uint64_t lyr_refmap_ty_0_env_std_core_cloneArray_int___2e4e7f9b[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty_0_env_std_core_cloneArray_int___2e4e7f9b = { sizeof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_0_env_std_core_cloneArray_int___2e4e7f9b, "<env:std.core.cloneArray<int>>", NULL };
typedef struct { int64_t value; uint8_t has; } lyr_opt_i64;
typedef struct { lyr_ty_app_main_P value; uint8_t has; } lyr_opt_ty10_app_main_P;
typedef struct { lyr_ty_app_main_Cell * (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ref13_app_main_Cell;
_Static_assert(sizeof(lyr_fn_i64_to_ref13_app_main_Cell) == 16, "layout of lyr_fn_i64_to_ref13_app_main_Cell");
typedef struct { lyr_ty_app_main_Holder (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ty15_app_main_Holder;
_Static_assert(sizeof(lyr_fn_i64_to_ty15_app_main_Holder) == 16, "layout of lyr_fn_i64_to_ty15_app_main_Holder");
typedef struct { int64_t (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_i64;
_Static_assert(sizeof(lyr_fn_i64_to_i64) == 16, "layout of lyr_fn_i64_to_i64");
_Static_assert(sizeof(lyr_ty_app_main_Cell *) == 8, "layout of app.main.Cell[]");
static const uint64_t lyr_refmap_arr_ref13_app_main_Cell[] = { UINT64_C(0x1) };
const LyrDesc lyr_desc_arr_ref13_app_main_Cell = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY | LYR_DESC_HAS_REFS, sizeof(lyr_ty_app_main_Cell *), 1, lyr_refmap_arr_ref13_app_main_Cell, "app.main.Cell[]", NULL };
_Static_assert(sizeof(lyr_ty_app_main_Holder) == 16, "layout of app.main.Holder[]");
static const uint64_t lyr_refmap_arr_ty15_app_main_Holder[] = { UINT64_C(0x1) };
const LyrDesc lyr_desc_arr_ty15_app_main_Holder = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY | LYR_DESC_HAS_REFS, sizeof(lyr_ty_app_main_Holder), 1, lyr_refmap_arr_ty15_app_main_Holder, "app.main.Holder[]", NULL };
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
const LyrDesc lyr_desc_arr_i64 = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY, sizeof(int64_t), 0, NULL, "int[]", NULL };

/* module-level bindings */
uint64_t lyr_g_std_collections_emptyGroup = 0;
uint64_t lyr_g_std_collections_lowBits = 0;
uint64_t lyr_g_std_collections_highBits = 0;

/* string literals */
static const LyrStaticStr(5) lyr_lit0 = LYR_STR_INIT("opt ");
static const LyrStaticStr(2) lyr_lit1 = LYR_STR_INIT(" ");
static const LyrStaticStr(7) lyr_lit2 = LYR_STR_INIT("mixed ");
static const LyrStaticStr(8) lyr_lit3 = LYR_STR_INIT("struct ");
static const LyrStaticStr(8) lyr_lit4 = LYR_STR_INIT("repeat ");
static const LyrStaticStr(8) lyr_lit5 = LYR_STR_INIT("nested ");

/* prototypes */
LYR_NOINLINE int64_t lyr_app_main_main(void);
uint8_t lyr_std_core_equalOptionals_int__f326e1e3(lyr_opt_i64 l0_a, lyr_opt_i64 l1_b);
uint8_t lyr_std_core_equalOptionals_app_main_P__492af87c(lyr_opt_ty10_app_main_P l0_a, lyr_opt_ty10_app_main_P l1_b);
LyrArr * lyr_std_core_repeatArray_app_main_Cell__85adea75(LyrArr *l0_xs, int64_t l1_n);
LyrArr * lyr_std_core_repeatArray_app_main_Holder__0f62b54f(LyrArr *l0_xs, int64_t l1_n);
void lyr__globals__9ee5f9b5(void);
uint8_t lyr_std_core__extend__int_equals_12f53381(int64_t l0_this, int64_t l1_o);
uint8_t lyr_app_main__extend__P_equals_f1e3d682(lyr_ty_app_main_P *l0_this, lyr_ty_app_main_P l1_o);
LyrArr * lyr_std_core_arrayOf_app_main_Cell__b07c39ad(int64_t l0_n, lyr_fn_i64_to_ref13_app_main_Cell l1_f);
lyr_ty_app_main_Cell * lyr_std_core_repeatArray_app_main_Cell___lambda0__8cc48eaa(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);
LyrArr * lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(int64_t l0_n, lyr_fn_i64_to_ty15_app_main_Holder l1_f);
lyr_ty_app_main_Holder lyr_std_core_repeatArray_app_main_Holder___lambda1__3fcd1a15(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);
lyr_ty_app_main_Cell * lyr_app_main__extend__Cell_clone_ea0d1aaa(lyr_ty_app_main_Cell *l0_this);
lyr_ty_app_main_Holder lyr_app_main__extend__Holder_clone_5e124274(lyr_ty_app_main_Holder *l0_this);
int64_t lyr_std_core__extend__int_clone_535f4ead(int64_t l0_this);
LyrArr * lyr_std_core_cloneArray_int__c18945da(LyrArr *l0_xs);
LyrArr * lyr_std_core_arrayOf_int__e7ec54de(int64_t l0_n, lyr_fn_i64_to_i64 l1_f);
int64_t lyr_std_core_cloneArray_int___lambda2__d2c0249f(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);

#line 11 "programs/cloning.lyr"
LYR_NOINLINE int64_t lyr_app_main_main(void) {
    lyr_opt_i64 l0_a = {0};
    lyr_opt_i64 l1_b = {0};
    lyr_opt_i64 l2_c = {0};
    lyr_opt_i64 l3_none = {0};
    lyr_opt_ty10_app_main_P l4_p = {0};
    lyr_opt_ty10_app_main_P l5_q = {0};
    lyr_opt_ty10_app_main_P l6_r = {0};
    LyrArr *l7_cells = NULL;
    LyrArr *l8_hs = NULL;
    int64_t t0 = 0;
    lyr_opt_i64 t1_s = {0};
    lyr_opt_i64 *t1 = &t1_s;
    int64_t t2 = 0;
    lyr_opt_i64 t3_s = {0};
    lyr_opt_i64 *t3 = &t3_s;
    int64_t t4 = 0;
    lyr_opt_i64 t5_s = {0};
    lyr_opt_i64 *t5 = &t5_s;
    lyr_opt_i64 t6_s = {0};
    lyr_opt_i64 *t6 = &t6_s;
    LyrStr *t7 = NULL;
    lyr_opt_i64 t8_s = {0};
    lyr_opt_i64 *t8 = &t8_s;
    lyr_opt_i64 t9_s = {0};
    lyr_opt_i64 *t9 = &t9_s;
    uint8_t t10 = 0;
    LyrStr *t11 = NULL;
    LyrStr *t12 = NULL;
    lyr_opt_i64 t13_s = {0};
    lyr_opt_i64 *t13 = &t13_s;
    lyr_opt_i64 t14_s = {0};
    lyr_opt_i64 *t14 = &t14_s;
    uint8_t t15 = 0;
    LyrStr *t16 = NULL;
    LyrStr *t17 = NULL;
    lyr_opt_i64 t18_s = {0};
    lyr_opt_i64 *t18 = &t18_s;
    uint8_t t19 = 0;
    uint8_t t20 = 0;
    LyrStr *t21 = NULL;
    LyrStr *t22 = NULL;
    lyr_opt_i64 t23_s = {0};
    lyr_opt_i64 *t23 = &t23_s;
    lyr_opt_i64 t24_s = {0};
    lyr_opt_i64 *t24 = &t24_s;
    uint8_t t25 = 0;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    lyr_opt_i64 t28_s = {0};
    lyr_opt_i64 *t28 = &t28_s;
    lyr_opt_i64 t29_s = {0};
    lyr_opt_i64 *t29 = &t29_s;
    uint8_t t30 = 0;
    uint8_t t31 = 0;
    LyrStr *t32 = NULL;
    LyrStr *t33 = NULL;
    lyr_opt_i64 t34_s = {0};
    lyr_opt_i64 *t34 = &t34_s;
    lyr_opt_i64 t35_s = {0};
    lyr_opt_i64 *t35 = &t35_s;
    uint8_t t36 = 0;
    uint8_t t37 = 0;
    LyrStr *t38 = NULL;
    LyrStr *t39 = NULL;
    LyrStr *t40 = NULL;
    LyrStr *t41 = NULL;
    LyrStr *t42 = NULL;
    LyrStr *t43 = NULL;
    LyrStr *t44 = NULL;
    LyrStr *t45 = NULL;
    LyrStr *t46 = NULL;
    LyrStr *t47 = NULL;
    LyrStr *t48 = NULL;
    LyrStr *t49 = NULL;
    LyrStr *t50 = NULL;
    lyr_opt_i64 t51_s = {0};
    lyr_opt_i64 *t51 = &t51_s;
    int64_t t52 = 0;
    lyr_opt_i64 t53_s = {0};
    lyr_opt_i64 *t53 = &t53_s;
    uint8_t t54 = 0;
    LyrStr *t55 = NULL;
    LyrStr *t56 = NULL;
    lyr_opt_i64 t57_s = {0};
    lyr_opt_i64 *t57 = &t57_s;
    int64_t t58 = 0;
    lyr_opt_i64 t59_s = {0};
    lyr_opt_i64 *t59 = &t59_s;
    uint8_t t60 = 0;
    LyrStr *t61 = NULL;
    LyrStr *t62 = NULL;
    int64_t t63 = 0;
    lyr_opt_i64 t64_s = {0};
    lyr_opt_i64 *t64 = &t64_s;
    lyr_opt_i64 t65_s = {0};
    lyr_opt_i64 *t65 = &t65_s;
    uint8_t t66 = 0;
    LyrStr *t67 = NULL;
    LyrStr *t68 = NULL;
    LyrStr *t69 = NULL;
    LyrStr *t70 = NULL;
    LyrStr *t71 = NULL;
    LyrStr *t72 = NULL;
    int64_t t73 = 0;
    int64_t t74 = 0;
    lyr_ty_app_main_P t75_s = {0};
    lyr_ty_app_main_P *t75 = &t75_s;
    lyr_opt_ty10_app_main_P t76_s = {0};
    lyr_opt_ty10_app_main_P *t76 = &t76_s;
    int64_t t77 = 0;
    int64_t t78 = 0;
    lyr_ty_app_main_P t79_s = {0};
    lyr_ty_app_main_P *t79 = &t79_s;
    lyr_opt_ty10_app_main_P t80_s = {0};
    lyr_opt_ty10_app_main_P *t80 = &t80_s;
    lyr_opt_ty10_app_main_P t81_s = {0};
    lyr_opt_ty10_app_main_P *t81 = &t81_s;
    LyrStr *t82 = NULL;
    lyr_opt_ty10_app_main_P t83_s = {0};
    lyr_opt_ty10_app_main_P *t83 = &t83_s;
    lyr_opt_ty10_app_main_P t84_s = {0};
    lyr_opt_ty10_app_main_P *t84 = &t84_s;
    uint8_t t85 = 0;
    LyrStr *t86 = NULL;
    LyrStr *t87 = NULL;
    lyr_opt_ty10_app_main_P t88_s = {0};
    lyr_opt_ty10_app_main_P *t88 = &t88_s;
    lyr_opt_ty10_app_main_P t89_s = {0};
    lyr_opt_ty10_app_main_P *t89 = &t89_s;
    uint8_t t90 = 0;
    LyrStr *t91 = NULL;
    LyrStr *t92 = NULL;
    LyrStr *t93 = NULL;
    LyrStr *t94 = NULL;
    int64_t t95 = 0;
    lyr_ty_app_main_Cell *t96 = NULL;
    LyrArr *t97 = NULL;
    int64_t t98 = 0;
    LyrArr *t99 = NULL;
    LyrArr *t100 = NULL;
    int64_t t101 = 0;
    lyr_ty_app_main_Cell *t102 = NULL;
    int64_t t103 = 0;
    LyrStr *t104 = NULL;
    LyrArr *t105 = NULL;
    int64_t t106 = 0;
    LyrStr *t107 = NULL;
    LyrStr *t108 = NULL;
    LyrArr *t109 = NULL;
    int64_t t110 = 0;
    lyr_ty_app_main_Cell *t111 = NULL;
    int64_t t112 = 0;
    LyrStr *t113 = NULL;
    LyrStr *t114 = NULL;
    LyrArr *t115 = NULL;
    int64_t t116 = 0;
    lyr_ty_app_main_Cell *t117 = NULL;
    int64_t t118 = 0;
    LyrStr *t119 = NULL;
    LyrStr *t120 = NULL;
    LyrArr *t121 = NULL;
    int64_t t122 = 0;
    lyr_ty_app_main_Cell *t123 = NULL;
    int64_t t124 = 0;
    int64_t t125 = 0;
    int64_t t126 = 0;
    LyrStr *t127 = NULL;
    LyrStr *t128 = NULL;
    LyrArr *t129 = NULL;
    int64_t t130 = 0;
    lyr_ty_app_main_Cell *t131 = NULL;
    LyrArr *t132 = NULL;
    int64_t t133 = 0;
    lyr_ty_app_main_Cell *t134 = NULL;
    uint8_t t135 = 0;
    LyrStr *t136 = NULL;
    LyrStr *t137 = NULL;
    LyrStr *t138 = NULL;
    LyrStr *t139 = NULL;
    LyrStr *t140 = NULL;
    LyrStr *t141 = NULL;
    LyrStr *t142 = NULL;
    LyrStr *t143 = NULL;
    LyrStr *t144 = NULL;
    LyrStr *t145 = NULL;
    int64_t t146 = 0;
    int64_t t147 = 0;
    LyrArr *t148 = NULL;
    int64_t t149 = 0;
    lyr_ty_app_main_Holder t150_s = {0};
    lyr_ty_app_main_Holder *t150 = &t150_s;
    LyrArr *t151 = NULL;
    int64_t t152 = 0;
    LyrArr *t153 = NULL;
    LyrArr *t154 = NULL;
    int64_t t155 = 0;
    lyr_ty_app_main_Holder t156_s = {0};
    lyr_ty_app_main_Holder *t156 = &t156_s;
    LyrArr *t157 = NULL;
    int64_t t158 = 0;
    int64_t t159 = 0;
    LyrStr *t160 = NULL;
    LyrArr *t161 = NULL;
    int64_t t162 = 0;
    LyrStr *t163 = NULL;
    LyrStr *t164 = NULL;
    LyrArr *t165 = NULL;
    int64_t t166 = 0;
    lyr_ty_app_main_Holder t167_s = {0};
    lyr_ty_app_main_Holder *t167 = &t167_s;
    int64_t t168 = 0;
    LyrStr *t169 = NULL;
    LyrStr *t170 = NULL;
    LyrArr *t171 = NULL;
    int64_t t172 = 0;
    lyr_ty_app_main_Holder t173_s = {0};
    lyr_ty_app_main_Holder *t173 = &t173_s;
    LyrArr *t174 = NULL;
    int64_t t175 = 0;
    int64_t t176 = 0;
    LyrArr *t177 = NULL;
    int64_t t178 = 0;
    lyr_ty_app_main_Holder t179_s = {0};
    lyr_ty_app_main_Holder *t179 = &t179_s;
    LyrArr *t180 = NULL;
    int64_t t181 = 0;
    int64_t t182 = 0;
    int64_t t183 = 0;
    int64_t t184 = 0;
    int64_t t185 = 0;
    LyrStr *t186 = NULL;
    LyrStr *t187 = NULL;
    LyrStr *t188 = NULL;
    LyrStr *t189 = NULL;
    LyrStr *t190 = NULL;
    LyrStr *t191 = NULL;
    int64_t t192 = 0;
bb0:;
#line 11
    t0 = (int64_t)INT64_C(5);
#line 11
    t1_s = (lyr_opt_i64){ .value = t0, .has = 1 }; t1 = &t1_s;
#line 11
    l0_a = *t1;
#line 12
    t2 = (int64_t)INT64_C(5);
#line 12
    t3_s = (lyr_opt_i64){ .value = t2, .has = 1 }; t3 = &t3_s;
#line 12
    l1_b = *t3;
#line 13
    t4 = (int64_t)INT64_C(6);
#line 13
    t5_s = (lyr_opt_i64){ .value = t4, .has = 1 }; t5 = &t5_s;
#line 13
    l2_c = *t5;
#line 14
    t6_s = (lyr_opt_i64){0}; t6 = &t6_s;
#line 14
    l3_none = *t6;
#line 15
    t7 = (LyrStr *)&lyr_lit0;
#line 15
    t8 = &l0_a;
#line 15
    t9 = &l1_b;
#line 15
    t10 = lyr_std_core_equalOptionals_int__f326e1e3(*t8, *t9);
#line 15
    t11 = lyr_str_from_bool(t10);
#line 15
    t12 = (LyrStr *)&lyr_lit1;
#line 15
    t13 = &l0_a;
#line 15
    t14 = &l2_c;
#line 15
    t15 = lyr_std_core_equalOptionals_int__f326e1e3(*t13, *t14);
#line 15
    t16 = lyr_str_from_bool(t15);
#line 15
    t17 = (LyrStr *)&lyr_lit1;
#line 15
    t18 = &l3_none;
#line 15
    t19 = t18->has;
#line 15
    t20 = (uint8_t)!t19;
#line 15
    t21 = lyr_str_from_bool(t20);
#line 15
    t22 = (LyrStr *)&lyr_lit1;
#line 15
    t23 = &l0_a;
#line 15
    t24 = &l3_none;
#line 15
    t25 = lyr_std_core_equalOptionals_int__f326e1e3(*t23, *t24);
#line 15
    t26 = lyr_str_from_bool(t25);
#line 15
    t27 = (LyrStr *)&lyr_lit1;
#line 15
    t28 = &l0_a;
#line 15
    t29 = &l2_c;
#line 15
    t30 = lyr_std_core_equalOptionals_int__f326e1e3(*t28, *t29);
#line 15
    t31 = (uint8_t)!t30;
#line 15
    t32 = lyr_str_from_bool(t31);
#line 15
    t33 = (LyrStr *)&lyr_lit1;
#line 15
    t34 = &l0_a;
#line 15
    t35 = &l1_b;
#line 15
    t36 = lyr_std_core_equalOptionals_int__f326e1e3(*t34, *t35);
#line 15
    t37 = (uint8_t)!t36;
#line 15
    t38 = lyr_str_from_bool(t37);
#line 15
    t39 = lyr_str_concat(t7, t11);
#line 15
    t40 = lyr_str_concat(t39, t12);
#line 15
    t41 = lyr_str_concat(t40, t16);
#line 15
    t42 = lyr_str_concat(t41, t17);
#line 15
    t43 = lyr_str_concat(t42, t21);
#line 15
    t44 = lyr_str_concat(t43, t22);
#line 15
    t45 = lyr_str_concat(t44, t26);
#line 15
    t46 = lyr_str_concat(t45, t27);
#line 15
    t47 = lyr_str_concat(t46, t32);
#line 15
    t48 = lyr_str_concat(t47, t33);
#line 15
    t49 = lyr_str_concat(t48, t38);
#line 15
    lyr_println(t49);
#line 16
    t50 = (LyrStr *)&lyr_lit2;
#line 16
    t51 = &l0_a;
#line 16
    t52 = (int64_t)INT64_C(5);
#line 16
    t53_s = (lyr_opt_i64){ .value = t52, .has = 1 }; t53 = &t53_s;
#line 16
    t54 = lyr_std_core_equalOptionals_int__f326e1e3(*t51, *t53);
#line 16
    t55 = lyr_str_from_bool(t54);
#line 16
    t56 = (LyrStr *)&lyr_lit1;
#line 16
    t57 = &l0_a;
#line 16
    t58 = (int64_t)INT64_C(6);
#line 16
    t59_s = (lyr_opt_i64){ .value = t58, .has = 1 }; t59 = &t59_s;
#line 16
    t60 = lyr_std_core_equalOptionals_int__f326e1e3(*t57, *t59);
#line 16
    t61 = lyr_str_from_bool(t60);
#line 16
    t62 = (LyrStr *)&lyr_lit1;
#line 16
    t63 = (int64_t)INT64_C(5);
#line 16
    t64_s = (lyr_opt_i64){ .value = t63, .has = 1 }; t64 = &t64_s;
#line 16
    t65 = &l0_a;
#line 16
    t66 = lyr_std_core_equalOptionals_int__f326e1e3(*t64, *t65);
#line 16
    t67 = lyr_str_from_bool(t66);
#line 16
    t68 = lyr_str_concat(t50, t55);
#line 16
    t69 = lyr_str_concat(t68, t56);
#line 16
    t70 = lyr_str_concat(t69, t61);
#line 16
    t71 = lyr_str_concat(t70, t62);
#line 16
    t72 = lyr_str_concat(t71, t67);
#line 16
    lyr_println(t72);
#line 17
    t73 = (int64_t)INT64_C(1);
#line 17
    t74 = (int64_t)INT64_C(2);
#line 17
    t75_s = (lyr_ty_app_main_P){0}; t75 = &t75_s;
#line 17
    t75->f_x = t73;
#line 17
    t75->f_y = t74;
#line 17
    t76_s = (lyr_opt_ty10_app_main_P){ .value = *t75, .has = 1 }; t76 = &t76_s;
#line 17
    l4_p = *t76;
#line 18
    t77 = (int64_t)INT64_C(1);
#line 18
    t78 = (int64_t)INT64_C(2);
#line 18
    t79_s = (lyr_ty_app_main_P){0}; t79 = &t79_s;
#line 18
    t79->f_x = t77;
#line 18
    t79->f_y = t78;
#line 18
    t80_s = (lyr_opt_ty10_app_main_P){ .value = *t79, .has = 1 }; t80 = &t80_s;
#line 18
    l5_q = *t80;
#line 19
    t81_s = (lyr_opt_ty10_app_main_P){0}; t81 = &t81_s;
#line 19
    l6_r = *t81;
#line 20
    t82 = (LyrStr *)&lyr_lit3;
#line 20
    t83 = &l4_p;
#line 20
    t84 = &l5_q;
#line 20
    t85 = lyr_std_core_equalOptionals_app_main_P__492af87c(*t83, *t84);
#line 20
    t86 = lyr_str_from_bool(t85);
#line 20
    t87 = (LyrStr *)&lyr_lit1;
#line 20
    t88 = &l4_p;
#line 20
    t89 = &l6_r;
#line 20
    t90 = lyr_std_core_equalOptionals_app_main_P__492af87c(*t88, *t89);
#line 20
    t91 = lyr_str_from_bool(t90);
#line 20
    t92 = lyr_str_concat(t82, t86);
#line 20
    t93 = lyr_str_concat(t92, t87);
#line 20
    t94 = lyr_str_concat(t93, t91);
#line 20
    lyr_println(t94);
#line 21
    t95 = (int64_t)INT64_C(1);
#line 21
    t96 = (lyr_ty_app_main_Cell *)lyr_alloc(&lyr_desc_ty_app_main_Cell);
#line 21
    t96->f_v = t95;
#line 21
    t97 = lyr_alloc_array(&lyr_desc_arr_ref13_app_main_Cell, 1); LYR_ARR_DATA(t97, lyr_ty_app_main_Cell *)[0] = t96;
#line 21
    t98 = (int64_t)INT64_C(3);
#line 21
    t99 = lyr_std_core_repeatArray_app_main_Cell__85adea75(t97, t98);
#line 21
    l7_cells = t99;
#line 22
    t100 = l7_cells;
#line 22
    t101 = (int64_t)INT64_C(0);
#line 22
    LYR_CHECK_INDEX(t101, t100->len); t102 = LYR_ARR_DATA(t100, lyr_ty_app_main_Cell *)[t101];
#line 22
    t103 = (int64_t)INT64_C(0);
#line 22
    t102->f_v = t103;
#line 23
    t104 = (LyrStr *)&lyr_lit4;
#line 23
    t105 = l7_cells;
#line 23
    t106 = t105->len;
#line 23
    t107 = lyr_str_from_int(t106);
#line 23
    t108 = (LyrStr *)&lyr_lit1;
#line 23
    t109 = l7_cells;
#line 23
    t110 = (int64_t)INT64_C(1);
#line 23
    LYR_CHECK_INDEX(t110, t109->len); t111 = LYR_ARR_DATA(t109, lyr_ty_app_main_Cell *)[t110];
#line 23
    t112 = t111->f_v;
#line 23
    t113 = lyr_str_from_int(t112);
#line 23
    t114 = (LyrStr *)&lyr_lit1;
#line 23
    t115 = l7_cells;
#line 23
    t116 = (int64_t)INT64_C(0);
#line 23
    LYR_CHECK_INDEX(t116, t115->len); t117 = LYR_ARR_DATA(t115, lyr_ty_app_main_Cell *)[t116];
#line 23
    t118 = t117->f_v;
#line 23
    t119 = lyr_str_from_int(t118);
#line 23
    t120 = (LyrStr *)&lyr_lit1;
#line 23
    t121 = l7_cells;
#line 23
    t122 = (int64_t)INT64_C(2);
#line 23
    LYR_CHECK_INDEX(t122, t121->len); t123 = LYR_ARR_DATA(t121, lyr_ty_app_main_Cell *)[t122];
#line 23
    t124 = t123->f_v;
#line 23
    t125 = (int64_t)INT64_C(1);
#line 23
    t126 = LYR_CHECKED_SUB(t124, t125);
#line 23
    t127 = lyr_str_from_int(t126);
#line 23
    t128 = (LyrStr *)&lyr_lit1;
#line 23
    t129 = l7_cells;
#line 23
    t130 = (int64_t)INT64_C(1);
#line 23
    LYR_CHECK_INDEX(t130, t129->len); t131 = LYR_ARR_DATA(t129, lyr_ty_app_main_Cell *)[t130];
#line 23
    t132 = l7_cells;
#line 23
    t133 = (int64_t)INT64_C(1);
#line 23
    LYR_CHECK_INDEX(t133, t132->len); t134 = LYR_ARR_DATA(t132, lyr_ty_app_main_Cell *)[t133];
#line 23
    t135 = (uint8_t)(t131 == t134);
#line 23
    t136 = lyr_str_from_bool(t135);
#line 23
    t137 = lyr_str_concat(t104, t107);
#line 23
    t138 = lyr_str_concat(t137, t108);
#line 23
    t139 = lyr_str_concat(t138, t113);
#line 23
    t140 = lyr_str_concat(t139, t114);
#line 23
    t141 = lyr_str_concat(t140, t119);
#line 23
    t142 = lyr_str_concat(t141, t120);
#line 23
    t143 = lyr_str_concat(t142, t127);
#line 23
    t144 = lyr_str_concat(t143, t128);
#line 23
    t145 = lyr_str_concat(t144, t136);
#line 23
    lyr_println(t145);
#line 24
    t146 = (int64_t)INT64_C(1);
#line 24
    t147 = (int64_t)INT64_C(2);
#line 24
    t148 = lyr_alloc_array(&lyr_desc_arr_i64, 2); LYR_ARR_DATA(t148, int64_t)[0] = t146; LYR_ARR_DATA(t148, int64_t)[1] = t147;
#line 24
    t149 = (int64_t)INT64_C(5);
#line 24
    t150_s = (lyr_ty_app_main_Holder){0}; t150 = &t150_s;
#line 24
    LYR_WRITE_BARRIER(t150, &t150->f_items, t148);
#line 24
    t150->f_n = t149;
#line 24
    t151 = lyr_alloc_array(&lyr_desc_arr_ty15_app_main_Holder, 1); LYR_ARR_DATA(t151, lyr_ty_app_main_Holder)[0] = *t150;
#line 24
    t152 = (int64_t)INT64_C(2);
#line 24
    t153 = lyr_std_core_repeatArray_app_main_Holder__0f62b54f(t151, t152);
#line 24
    l8_hs = t153;
#line 25
    t154 = l8_hs;
#line 25
    t155 = (int64_t)INT64_C(0);
#line 25
    LYR_CHECK_INDEX(t155, t154->len); t156 = &LYR_ARR_DATA(t154, lyr_ty_app_main_Holder)[t155];
#line 25
    t157 = t156->f_items;
#line 25
    t158 = (int64_t)INT64_C(0);
#line 25
    t159 = (int64_t)INT64_C(0);
#line 25
    LYR_CHECK_INDEX(t158, t157->len); LYR_ARR_DATA(t157, int64_t)[t158] = t159;
#line 26
    t160 = (LyrStr *)&lyr_lit5;
#line 26
    t161 = l8_hs;
#line 26
    t162 = t161->len;
#line 26
    t163 = lyr_str_from_int(t162);
#line 26
    t164 = (LyrStr *)&lyr_lit1;
#line 26
    t165 = l8_hs;
#line 26
    t166 = (int64_t)INT64_C(1);
#line 26
    LYR_CHECK_INDEX(t166, t165->len); t167 = &LYR_ARR_DATA(t165, lyr_ty_app_main_Holder)[t166];
#line 26
    t168 = t167->f_n;
#line 26
    t169 = lyr_str_from_int(t168);
#line 26
    t170 = (LyrStr *)&lyr_lit1;
#line 26
    t171 = l8_hs;
#line 26
    t172 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_INDEX(t172, t171->len); t173 = &LYR_ARR_DATA(t171, lyr_ty_app_main_Holder)[t172];
#line 26
    t174 = t173->f_items;
#line 26
    t175 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_INDEX(t175, t174->len); t176 = LYR_ARR_DATA(t174, int64_t)[t175];
#line 26
    t177 = l8_hs;
#line 26
    t178 = (int64_t)INT64_C(1);
#line 26
    LYR_CHECK_INDEX(t178, t177->len); t179 = &LYR_ARR_DATA(t177, lyr_ty_app_main_Holder)[t178];
#line 26
    t180 = t179->f_items;
#line 26
    t181 = (int64_t)INT64_C(0);
#line 26
    LYR_CHECK_INDEX(t181, t180->len); t182 = LYR_ARR_DATA(t180, int64_t)[t181];
#line 26
    t183 = (int64_t)INT64_C(1);
#line 26
    t184 = LYR_CHECKED_SUB(t182, t183);
#line 26
    t185 = LYR_CHECKED_ADD(t176, t184);
#line 26
    t186 = lyr_str_from_int(t185);
#line 26
    t187 = lyr_str_concat(t160, t163);
#line 26
    t188 = lyr_str_concat(t187, t164);
#line 26
    t189 = lyr_str_concat(t188, t169);
#line 26
    t190 = lyr_str_concat(t189, t170);
#line 26
    t191 = lyr_str_concat(t190, t186);
#line 26
    lyr_println(t191);
#line 27
    t192 = (int64_t)INT64_C(0);
#line 27
    return t192;
}

#line 247 "stdlib5/std/collections.lyr"
void lyr__globals__9ee5f9b5(void) {
    uint64_t t0 = 0;
    uint64_t t1 = 0;
    uint64_t t2 = 0;
bb0:;
#line 247
    t0 = (uint64_t)UINT64_C(9259542123273814144);
#line 247
    lyr_g_std_collections_emptyGroup = t0;
#line 248
    t1 = (uint64_t)UINT64_C(72340172838076673);
#line 248
    lyr_g_std_collections_lowBits = t1;
#line 249
    t2 = (uint64_t)UINT64_C(9259542123273814144);
#line 249
    lyr_g_std_collections_highBits = t2;
    return;
}

#line 358 "stdlib5/std/core.lyr"
uint8_t lyr_std_core__extend__int_equals_12f53381(int64_t l0_this, int64_t l1_o) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
bb0:;
#line 358
    t0 = l0_this;
#line 358
    t1 = l1_o;
#line 358
    t2 = (uint8_t)(t0 == t1);
#line 358
    return t2;
}

#line 3 "<synthesized Equatable for app.main.P>"
uint8_t lyr_app_main__extend__P_equals_f1e3d682(lyr_ty_app_main_P *l0_this, lyr_ty_app_main_P l1_o) {
    uint8_t l2__and0 = 0;
    lyr_ty_app_main_P t0_s = {0};
    lyr_ty_app_main_P *t0 = &t0_s;
    int64_t t1 = 0;
    lyr_ty_app_main_P t2_s = {0};
    lyr_ty_app_main_P *t2 = &t2_s;
    int64_t t3 = 0;
    uint8_t t4 = 0;
    lyr_ty_app_main_P t5_s = {0};
    lyr_ty_app_main_P *t5 = &t5_s;
    int64_t t6 = 0;
    lyr_ty_app_main_P t7_s = {0};
    lyr_ty_app_main_P *t7 = &t7_s;
    int64_t t8 = 0;
    uint8_t t9 = 0;
    uint8_t t10 = 0;
bb0:;
#line 3
    t0 = l0_this;
#line 3
    t1 = t0->f_x;
#line 3
    t2 = &l1_o;
#line 3
    t3 = t2->f_x;
#line 3
    t4 = (uint8_t)(t1 == t3);
#line 3
    l2__and0 = t4;
#line 3
    if (t4) goto bb1; else goto bb2;
bb1:;
#line 4
    t5 = l0_this;
#line 4
    t6 = t5->f_y;
#line 4
    t7 = &l1_o;
#line 4
    t8 = t7->f_y;
#line 4
    t9 = (uint8_t)(t6 == t8);
#line 4
    l2__and0 = t9;
#line 4
    goto bb2;
bb2:;
#line 3
    t10 = l2__and0;
#line 3
    return t10;
}

#line 4 "<synthesized Clone for app.main.Cell>"
lyr_ty_app_main_Cell * lyr_app_main__extend__Cell_clone_ea0d1aaa(lyr_ty_app_main_Cell *l0_this) {
    lyr_ty_app_main_Cell *t0 = NULL;
    int64_t t1 = 0;
    int64_t t2 = 0;
    lyr_ty_app_main_Cell *t3 = NULL;
bb0:;
#line 4
    t0 = l0_this;
#line 4
    t1 = t0->f_v;
#line 4
    t2 = lyr_std_core__extend__int_clone_535f4ead(t1);
#line 3
    t3 = (lyr_ty_app_main_Cell *)lyr_alloc(&lyr_desc_ty_app_main_Cell);
#line 3
    t3->f_v = t2;
#line 3
    return t3;
}

#line 4 "<synthesized Clone for app.main.Holder>"
lyr_ty_app_main_Holder lyr_app_main__extend__Holder_clone_5e124274(lyr_ty_app_main_Holder *l0_this) {
    lyr_ty_app_main_Holder t0_s = {0};
    lyr_ty_app_main_Holder *t0 = &t0_s;
    LyrArr *t1 = NULL;
    LyrArr *t2 = NULL;
    lyr_ty_app_main_Holder t3_s = {0};
    lyr_ty_app_main_Holder *t3 = &t3_s;
    int64_t t4 = 0;
    int64_t t5 = 0;
    lyr_ty_app_main_Holder t6_s = {0};
    lyr_ty_app_main_Holder *t6 = &t6_s;
bb0:;
#line 4
    t0 = l0_this;
#line 4
    t1 = t0->f_items;
#line 4
    t2 = lyr_std_core_cloneArray_int__c18945da(t1);
#line 5
    t3 = l0_this;
#line 5
    t4 = t3->f_n;
#line 5
    t5 = lyr_std_core__extend__int_clone_535f4ead(t4);
#line 3
    t6_s = (lyr_ty_app_main_Holder){0}; t6 = &t6_s;
#line 3
    LYR_WRITE_BARRIER(t6, &t6->f_items, t2);
#line 3
    t6->f_n = t5;
#line 3
    return *t6;
}

#line 664 "stdlib5/std/core.lyr"
int64_t lyr_std_core__extend__int_clone_535f4ead(int64_t l0_this) {
    int64_t t0 = 0;
bb0:;
#line 664
    t0 = l0_this;
#line 664
    return t0;
}


/* the program */
static int64_t lyr_entry(void) { lyr__globals__9ee5f9b5(); return lyr_app_main_main(); }
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_entry); }

/* ==== unit: std.core.arrayOf<app.main.Cell> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.arrayOf<app.main.Cell>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Cell lyr_ty_app_main_Cell;
struct lyr_ty_app_main_Cell {
    LyrObj header;
    int64_t f_v;
};
_Static_assert(sizeof(lyr_ty_app_main_Cell) == 16, "layout of lyr_ty_app_main_Cell");
_Static_assert(offsetof(lyr_ty_app_main_Cell, f_v) == 8, "layout of lyr_ty_app_main_Cell");
extern const LyrDesc lyr_desc_ty_app_main_Cell;
typedef struct { lyr_ty_app_main_Cell * (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ref13_app_main_Cell;
_Static_assert(sizeof(lyr_fn_i64_to_ref13_app_main_Cell) == 16, "layout of lyr_fn_i64_to_ref13_app_main_Cell");
_Static_assert(sizeof(lyr_ty_app_main_Cell *) == 8, "layout of app.main.Cell[]");
extern const LyrDesc lyr_desc_arr_ref13_app_main_Cell;

/* string literals */
static const LyrStaticStr(27) lyr_lit0 = LYR_STR_INIT("arrayOf: a negative length");

/* prototypes */
LyrArr * lyr_std_core_arrayOf_app_main_Cell__b07c39ad(int64_t l0_n, lyr_fn_i64_to_ref13_app_main_Cell l1_f);

#line 65 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_arrayOf_app_main_Cell__b07c39ad(int64_t l0_n, lyr_fn_i64_to_ref13_app_main_Cell l1_f) {
    lyr_ty_app_main_Cell *l2_first = NULL;
    LyrArr *l3_whole = NULL;
    LyrArr *l4_block = NULL;
    int64_t l5_left = 0;
    int64_t l6_i = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    uint8_t t6 = 0;
    LyrArr *t7 = NULL;
    lyr_fn_i64_to_ref13_app_main_Cell t8 = {0};
    int64_t t9 = 0;
    lyr_ty_app_main_Cell *t10 = NULL;
    LyrArr *t11 = NULL;
    lyr_ty_app_main_Cell *t12 = NULL;
    LyrArr *t13 = NULL;
    int64_t t14 = 0;
    int64_t t15 = 0;
    int64_t t16 = 0;
    uint8_t t17 = 0;
    int64_t t18 = 0;
    int64_t t19 = 0;
    int64_t t20 = 0;
    int64_t t21 = 0;
    uint8_t t22 = 0;
    LyrArr *t23 = NULL;
    LyrArr *t24 = NULL;
    LyrArr *t25 = NULL;
    int64_t t26 = 0;
    int64_t t27 = 0;
    int64_t t28 = 0;
    int64_t t29 = 0;
    int64_t t30 = 0;
    uint8_t t31 = 0;
    LyrArr *t32 = NULL;
    LyrArr *t33 = NULL;
    LyrArr *t34 = NULL;
    int64_t t35 = 0;
    int64_t t36 = 0;
    int64_t t37 = 0;
    uint8_t t38 = 0;
    LyrArr *t39 = NULL;
    int64_t t40 = 0;
    lyr_fn_i64_to_ref13_app_main_Cell t41 = {0};
    int64_t t42 = 0;
    lyr_ty_app_main_Cell *t43 = NULL;
    int64_t t44 = 0;
    int64_t t45 = 0;
    int64_t t46 = 0;
    LyrArr *t47 = NULL;
bb0:;
#line 65
    t0 = l0_n;
#line 65
    t1 = (int64_t)INT64_C(0);
#line 65
    t2 = (uint8_t)(t0 < t1);
#line 65
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 66
    t3 = (LyrStr *)&lyr_lit0;
#line 66
    lyr_panic_message(t3);
#line 66
    LYR_UNREACHABLE();
bb2:;
#line 68
    t4 = l0_n;
#line 68
    t5 = (int64_t)INT64_C(0);
#line 68
    t6 = (uint8_t)(t4 == t5);
#line 68
    if (t6) goto bb3; else goto bb4;
bb3:;
#line 69
    t7 = lyr_alloc_array(&lyr_desc_arr_ref13_app_main_Cell, 0);
#line 69
    return t7;
bb4:;
#line 73
    t8 = l1_f;
#line 73
    t9 = (int64_t)INT64_C(0);
#line 73
    t10 = t8.fn(t8.env, t9, NULL);
#line 73
    l2_first = t10;
#line 74
    t11 = lyr_alloc_array(&lyr_desc_arr_ref13_app_main_Cell, 0);
#line 74
    l3_whole = t11;
#line 75
    t12 = l2_first;
#line 75
    t13 = lyr_alloc_array(&lyr_desc_arr_ref13_app_main_Cell, 1); LYR_ARR_DATA(t13, lyr_ty_app_main_Cell *)[0] = t12;
#line 75
    l4_block = t13;
#line 76
    t14 = l0_n;
#line 76
    l5_left = t14;
#line 77
    goto bb5;
bb5:;
#line 77
    t15 = l5_left;
#line 77
    t16 = (int64_t)INT64_C(0);
#line 77
    t17 = (uint8_t)(t15 > t16);
#line 77
    if (t17) goto bb6; else goto bb7;
bb6:;
#line 78
    t18 = l5_left;
#line 78
    t19 = (int64_t)INT64_C(2);
#line 78
    t20 = LYR_CHECKED_REM(t18, t19);
#line 78
    t21 = (int64_t)INT64_C(1);
#line 78
    t22 = (uint8_t)(t20 == t21);
#line 78
    if (t22) goto bb8; else goto bb9;
bb7:;
#line 86
    t35 = (int64_t)INT64_C(1);
#line 86
    l6_i = t35;
#line 87
    goto bb12;
bb8:;
#line 79
    t23 = l3_whole;
#line 79
    t24 = l4_block;
#line 79
    t25 = lyr_arr_concat(&lyr_desc_arr_ref13_app_main_Cell, t23, t24);
#line 79
    l3_whole = t25;
#line 78
    goto bb9;
bb9:;
#line 81
    t26 = l5_left;
#line 81
    t27 = (int64_t)INT64_C(2);
#line 81
    t28 = LYR_CHECKED_DIV(t26, t27);
#line 81
    l5_left = t28;
#line 82
    t29 = l5_left;
#line 82
    t30 = (int64_t)INT64_C(0);
#line 82
    t31 = (uint8_t)(t29 > t30);
#line 82
    if (t31) goto bb10; else goto bb11;
bb10:;
#line 83
    t32 = l4_block;
#line 83
    t33 = l4_block;
#line 83
    t34 = lyr_arr_concat(&lyr_desc_arr_ref13_app_main_Cell, t32, t33);
#line 83
    l4_block = t34;
#line 82
    goto bb11;
bb11:;
#line 77
    goto bb5;
bb12:;
#line 87
    t36 = l6_i;
#line 87
    t37 = l0_n;
#line 87
    t38 = (uint8_t)(t36 < t37);
#line 87
    if (t38) goto bb13; else goto bb14;
bb13:;
#line 88
    t39 = l3_whole;
#line 88
    t40 = l6_i;
#line 88
    t41 = l1_f;
#line 88
    t42 = l6_i;
#line 88
    t43 = t41.fn(t41.env, t42, NULL);
#line 88
    LYR_CHECK_INDEX(t40, t39->len); LYR_WRITE_BARRIER(t39, &LYR_ARR_DATA(t39, lyr_ty_app_main_Cell *)[t40], t43);
#line 89
    t44 = l6_i;
#line 89
    t45 = (int64_t)INT64_C(1);
#line 89
    t46 = LYR_CHECKED_ADD(t44, t45);
#line 89
    l6_i = t46;
#line 87
    goto bb12;
bb14:;
#line 91
    t47 = l3_whole;
#line 91
    return t47;
}


/* ==== unit: std.core.arrayOf<app.main.Holder> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.arrayOf<app.main.Holder>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Holder lyr_ty_app_main_Holder;
struct lyr_ty_app_main_Holder {
    LyrArr *f_items;
    int64_t f_n;
};
typedef struct { lyr_ty_app_main_Holder (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ty15_app_main_Holder;
_Static_assert(sizeof(lyr_fn_i64_to_ty15_app_main_Holder) == 16, "layout of lyr_fn_i64_to_ty15_app_main_Holder");
_Static_assert(sizeof(lyr_ty_app_main_Holder) == 16, "layout of app.main.Holder[]");
extern const LyrDesc lyr_desc_arr_ty15_app_main_Holder;
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;

/* string literals */
static const LyrStaticStr(27) lyr_lit0 = LYR_STR_INIT("arrayOf: a negative length");

/* prototypes */
LyrArr * lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(int64_t l0_n, lyr_fn_i64_to_ty15_app_main_Holder l1_f);

#line 65 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(int64_t l0_n, lyr_fn_i64_to_ty15_app_main_Holder l1_f) {
    lyr_ty_app_main_Holder l2_first = {0};
    LyrArr *l3_whole = NULL;
    LyrArr *l4_block = NULL;
    int64_t l5_left = 0;
    int64_t l6_i = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    uint8_t t6 = 0;
    LyrArr *t7 = NULL;
    lyr_fn_i64_to_ty15_app_main_Holder t8 = {0};
    int64_t t9 = 0;
    lyr_ty_app_main_Holder t10_s = {0};
    lyr_ty_app_main_Holder *t10 = &t10_s;
    LyrArr *t11 = NULL;
    lyr_ty_app_main_Holder t12_s = {0};
    lyr_ty_app_main_Holder *t12 = &t12_s;
    lyr_ty_app_main_Holder t13_s = {0};
    lyr_ty_app_main_Holder *t13 = &t13_s;
    LyrArr *t14 = NULL;
    int64_t t15 = 0;
    int64_t t16 = 0;
    int64_t t17 = 0;
    uint8_t t18 = 0;
    int64_t t19 = 0;
    int64_t t20 = 0;
    int64_t t21 = 0;
    int64_t t22 = 0;
    uint8_t t23 = 0;
    LyrArr *t24 = NULL;
    LyrArr *t25 = NULL;
    LyrArr *t26 = NULL;
    int64_t t27 = 0;
    int64_t t28 = 0;
    int64_t t29 = 0;
    int64_t t30 = 0;
    int64_t t31 = 0;
    uint8_t t32 = 0;
    LyrArr *t33 = NULL;
    LyrArr *t34 = NULL;
    LyrArr *t35 = NULL;
    int64_t t36 = 0;
    int64_t t37 = 0;
    int64_t t38 = 0;
    uint8_t t39 = 0;
    LyrArr *t40 = NULL;
    int64_t t41 = 0;
    lyr_fn_i64_to_ty15_app_main_Holder t42 = {0};
    int64_t t43 = 0;
    lyr_ty_app_main_Holder t44_s = {0};
    lyr_ty_app_main_Holder *t44 = &t44_s;
    int64_t t45 = 0;
    int64_t t46 = 0;
    int64_t t47 = 0;
    LyrArr *t48 = NULL;
bb0:;
#line 65
    t0 = l0_n;
#line 65
    t1 = (int64_t)INT64_C(0);
#line 65
    t2 = (uint8_t)(t0 < t1);
#line 65
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 66
    t3 = (LyrStr *)&lyr_lit0;
#line 66
    lyr_panic_message(t3);
#line 66
    LYR_UNREACHABLE();
bb2:;
#line 68
    t4 = l0_n;
#line 68
    t5 = (int64_t)INT64_C(0);
#line 68
    t6 = (uint8_t)(t4 == t5);
#line 68
    if (t6) goto bb3; else goto bb4;
bb3:;
#line 69
    t7 = lyr_alloc_array(&lyr_desc_arr_ty15_app_main_Holder, 0);
#line 69
    return t7;
bb4:;
#line 73
    t8 = l1_f;
#line 73
    t9 = (int64_t)INT64_C(0);
#line 73
    t10_s = t8.fn(t8.env, t9, NULL); t10 = &t10_s;
#line 73
    l2_first = *t10;
#line 74
    t11 = lyr_alloc_array(&lyr_desc_arr_ty15_app_main_Holder, 0);
#line 74
    l3_whole = t11;
#line 75
    t12 = &l2_first;
#line 75
    t13_s = *t12; t13 = &t13_s;
#line 75
    t14 = lyr_alloc_array(&lyr_desc_arr_ty15_app_main_Holder, 1); LYR_ARR_DATA(t14, lyr_ty_app_main_Holder)[0] = *t13;
#line 75
    l4_block = t14;
#line 76
    t15 = l0_n;
#line 76
    l5_left = t15;
#line 77
    goto bb5;
bb5:;
#line 77
    t16 = l5_left;
#line 77
    t17 = (int64_t)INT64_C(0);
#line 77
    t18 = (uint8_t)(t16 > t17);
#line 77
    if (t18) goto bb6; else goto bb7;
bb6:;
#line 78
    t19 = l5_left;
#line 78
    t20 = (int64_t)INT64_C(2);
#line 78
    t21 = LYR_CHECKED_REM(t19, t20);
#line 78
    t22 = (int64_t)INT64_C(1);
#line 78
    t23 = (uint8_t)(t21 == t22);
#line 78
    if (t23) goto bb8; else goto bb9;
bb7:;
#line 86
    t36 = (int64_t)INT64_C(1);
#line 86
    l6_i = t36;
#line 87
    goto bb12;
bb8:;
#line 79
    t24 = l3_whole;
#line 79
    t25 = l4_block;
#line 79
    t26 = lyr_arr_concat(&lyr_desc_arr_ty15_app_main_Holder, t24, t25);
#line 79
    l3_whole = t26;
#line 78
    goto bb9;
bb9:;
#line 81
    t27 = l5_left;
#line 81
    t28 = (int64_t)INT64_C(2);
#line 81
    t29 = LYR_CHECKED_DIV(t27, t28);
#line 81
    l5_left = t29;
#line 82
    t30 = l5_left;
#line 82
    t31 = (int64_t)INT64_C(0);
#line 82
    t32 = (uint8_t)(t30 > t31);
#line 82
    if (t32) goto bb10; else goto bb11;
bb10:;
#line 83
    t33 = l4_block;
#line 83
    t34 = l4_block;
#line 83
    t35 = lyr_arr_concat(&lyr_desc_arr_ty15_app_main_Holder, t33, t34);
#line 83
    l4_block = t35;
#line 82
    goto bb11;
bb11:;
#line 77
    goto bb5;
bb12:;
#line 87
    t37 = l6_i;
#line 87
    t38 = l0_n;
#line 87
    t39 = (uint8_t)(t37 < t38);
#line 87
    if (t39) goto bb13; else goto bb14;
bb13:;
#line 88
    t40 = l3_whole;
#line 88
    t41 = l6_i;
#line 88
    t42 = l1_f;
#line 88
    t43 = l6_i;
#line 88
    t44_s = t42.fn(t42.env, t43, NULL); t44 = &t44_s;
#line 88
    LYR_CHECK_INDEX(t41, t40->len); LYR_WRITE_BARRIER_VALUE(t40, &LYR_ARR_DATA(t40, lyr_ty_app_main_Holder)[t41], *t44);
#line 89
    t45 = l6_i;
#line 89
    t46 = (int64_t)INT64_C(1);
#line 89
    t47 = LYR_CHECKED_ADD(t45, t46);
#line 89
    l6_i = t47;
#line 87
    goto bb12;
bb14:;
#line 91
    t48 = l3_whole;
#line 91
    return t48;
}


/* ==== unit: std.core.arrayOf<int> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.arrayOf<int>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct { int64_t (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_i64;
_Static_assert(sizeof(lyr_fn_i64_to_i64) == 16, "layout of lyr_fn_i64_to_i64");
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;

/* string literals */
static const LyrStaticStr(27) lyr_lit0 = LYR_STR_INIT("arrayOf: a negative length");

/* prototypes */
LyrArr * lyr_std_core_arrayOf_int__e7ec54de(int64_t l0_n, lyr_fn_i64_to_i64 l1_f);

#line 65 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_arrayOf_int__e7ec54de(int64_t l0_n, lyr_fn_i64_to_i64 l1_f) {
    int64_t l2_first = 0;
    LyrArr *l3_whole = NULL;
    LyrArr *l4_block = NULL;
    int64_t l5_left = 0;
    int64_t l6_i = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    uint8_t t6 = 0;
    LyrArr *t7 = NULL;
    lyr_fn_i64_to_i64 t8 = {0};
    int64_t t9 = 0;
    int64_t t10 = 0;
    LyrArr *t11 = NULL;
    int64_t t12 = 0;
    LyrArr *t13 = NULL;
    int64_t t14 = 0;
    int64_t t15 = 0;
    int64_t t16 = 0;
    uint8_t t17 = 0;
    int64_t t18 = 0;
    int64_t t19 = 0;
    int64_t t20 = 0;
    int64_t t21 = 0;
    uint8_t t22 = 0;
    LyrArr *t23 = NULL;
    LyrArr *t24 = NULL;
    LyrArr *t25 = NULL;
    int64_t t26 = 0;
    int64_t t27 = 0;
    int64_t t28 = 0;
    int64_t t29 = 0;
    int64_t t30 = 0;
    uint8_t t31 = 0;
    LyrArr *t32 = NULL;
    LyrArr *t33 = NULL;
    LyrArr *t34 = NULL;
    int64_t t35 = 0;
    int64_t t36 = 0;
    int64_t t37 = 0;
    uint8_t t38 = 0;
    LyrArr *t39 = NULL;
    int64_t t40 = 0;
    lyr_fn_i64_to_i64 t41 = {0};
    int64_t t42 = 0;
    int64_t t43 = 0;
    int64_t t44 = 0;
    int64_t t45 = 0;
    int64_t t46 = 0;
    LyrArr *t47 = NULL;
bb0:;
#line 65
    t0 = l0_n;
#line 65
    t1 = (int64_t)INT64_C(0);
#line 65
    t2 = (uint8_t)(t0 < t1);
#line 65
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 66
    t3 = (LyrStr *)&lyr_lit0;
#line 66
    lyr_panic_message(t3);
#line 66
    LYR_UNREACHABLE();
bb2:;
#line 68
    t4 = l0_n;
#line 68
    t5 = (int64_t)INT64_C(0);
#line 68
    t6 = (uint8_t)(t4 == t5);
#line 68
    if (t6) goto bb3; else goto bb4;
bb3:;
#line 69
    t7 = lyr_alloc_array(&lyr_desc_arr_i64, 0);
#line 69
    return t7;
bb4:;
#line 73
    t8 = l1_f;
#line 73
    t9 = (int64_t)INT64_C(0);
#line 73
    t10 = t8.fn(t8.env, t9, NULL);
#line 73
    l2_first = t10;
#line 74
    t11 = lyr_alloc_array(&lyr_desc_arr_i64, 0);
#line 74
    l3_whole = t11;
#line 75
    t12 = l2_first;
#line 75
    t13 = lyr_alloc_array(&lyr_desc_arr_i64, 1); LYR_ARR_DATA(t13, int64_t)[0] = t12;
#line 75
    l4_block = t13;
#line 76
    t14 = l0_n;
#line 76
    l5_left = t14;
#line 77
    goto bb5;
bb5:;
#line 77
    t15 = l5_left;
#line 77
    t16 = (int64_t)INT64_C(0);
#line 77
    t17 = (uint8_t)(t15 > t16);
#line 77
    if (t17) goto bb6; else goto bb7;
bb6:;
#line 78
    t18 = l5_left;
#line 78
    t19 = (int64_t)INT64_C(2);
#line 78
    t20 = LYR_CHECKED_REM(t18, t19);
#line 78
    t21 = (int64_t)INT64_C(1);
#line 78
    t22 = (uint8_t)(t20 == t21);
#line 78
    if (t22) goto bb8; else goto bb9;
bb7:;
#line 86
    t35 = (int64_t)INT64_C(1);
#line 86
    l6_i = t35;
#line 87
    goto bb12;
bb8:;
#line 79
    t23 = l3_whole;
#line 79
    t24 = l4_block;
#line 79
    t25 = lyr_arr_concat(&lyr_desc_arr_i64, t23, t24);
#line 79
    l3_whole = t25;
#line 78
    goto bb9;
bb9:;
#line 81
    t26 = l5_left;
#line 81
    t27 = (int64_t)INT64_C(2);
#line 81
    t28 = LYR_CHECKED_DIV(t26, t27);
#line 81
    l5_left = t28;
#line 82
    t29 = l5_left;
#line 82
    t30 = (int64_t)INT64_C(0);
#line 82
    t31 = (uint8_t)(t29 > t30);
#line 82
    if (t31) goto bb10; else goto bb11;
bb10:;
#line 83
    t32 = l4_block;
#line 83
    t33 = l4_block;
#line 83
    t34 = lyr_arr_concat(&lyr_desc_arr_i64, t32, t33);
#line 83
    l4_block = t34;
#line 82
    goto bb11;
bb11:;
#line 77
    goto bb5;
bb12:;
#line 87
    t36 = l6_i;
#line 87
    t37 = l0_n;
#line 87
    t38 = (uint8_t)(t36 < t37);
#line 87
    if (t38) goto bb13; else goto bb14;
bb13:;
#line 88
    t39 = l3_whole;
#line 88
    t40 = l6_i;
#line 88
    t41 = l1_f;
#line 88
    t42 = l6_i;
#line 88
    t43 = t41.fn(t41.env, t42, NULL);
#line 88
    LYR_CHECK_INDEX(t40, t39->len); LYR_ARR_DATA(t39, int64_t)[t40] = t43;
#line 89
    t44 = l6_i;
#line 89
    t45 = (int64_t)INT64_C(1);
#line 89
    t46 = LYR_CHECKED_ADD(t44, t45);
#line 89
    l6_i = t46;
#line 87
    goto bb12;
bb14:;
#line 91
    t47 = l3_whole;
#line 91
    return t47;
}


/* ==== unit: std.core.cloneArray<int> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.cloneArray<int>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b;
struct lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b {
    LyrObj header;
    LyrArr *f_xs;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b) == 16, "layout of lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b");
_Static_assert(offsetof(lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b, f_xs) == 8, "layout of lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b");
extern const LyrDesc lyr_desc_ty_0_env_std_core_cloneArray_int___2e4e7f9b;
typedef struct { int64_t (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_i64;
_Static_assert(sizeof(lyr_fn_i64_to_i64) == 16, "layout of lyr_fn_i64_to_i64");
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;

/* prototypes */
int64_t lyr_std_core__extend__int_clone_535f4ead(int64_t l0_this);
LyrArr * lyr_std_core_cloneArray_int__c18945da(LyrArr *l0_xs);
LyrArr * lyr_std_core_arrayOf_int__e7ec54de(int64_t l0_n, lyr_fn_i64_to_i64 l1_f);
int64_t lyr_std_core_cloneArray_int___lambda2__d2c0249f(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);

#line 3878 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_cloneArray_int__c18945da(LyrArr *l0_xs) {
    LyrArr *t0 = NULL;
    int64_t t1 = 0;
    LyrArr *t2 = NULL;
    lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *t3 = NULL;
    lyr_fn_i64_to_i64 t4 = {0};
    LyrArr *t5 = NULL;
bb0:;
#line 3878
    t0 = l0_xs;
#line 3878
    t1 = t0->len;
#line 3878
    t2 = l0_xs;
#line 3878
    t3 = (lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *)lyr_alloc(&lyr_desc_ty_0_env_std_core_cloneArray_int___2e4e7f9b);
#line 3878
    LYR_WRITE_BARRIER(t3, &t3->f_xs, t2);
#line 3878
    t4 = (lyr_fn_i64_to_i64){ lyr_std_core_cloneArray_int___lambda2__d2c0249f, t3 };
#line 3878
    t5 = lyr_std_core_arrayOf_int__e7ec54de(t1, t4);
#line 3878
    return t5;
}

#line 3878 "stdlib5/std/core.lyr"
int64_t lyr_std_core_cloneArray_int___lambda2__d2c0249f(void *lyr_env, int64_t l1_i, LyrErr **lyr_err) {
    lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *l0__env_ = (lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *)lyr_env;
    (void)lyr_err;
    lyr_ty_0_env_std_core_cloneArray_int___2e4e7f9b *t0 = NULL;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    int64_t t3 = 0;
    int64_t t4 = 0;
bb0:;
#line 3878
    t0 = l0__env_;
#line 3878
    t1 = t0->f_xs;
#line 3878
    t2 = l1_i;
#line 3878
    LYR_CHECK_INDEX(t2, t1->len); t3 = LYR_ARR_DATA(t1, int64_t)[t2];
#line 3878
    t4 = lyr_std_core__extend__int_clone_535f4ead(t3);
#line 3878
    return t4;
}


/* ==== unit: std.core.equalOptionals<app.main.P> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.equalOptionals<app.main.P>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_P lyr_ty_app_main_P;
struct lyr_ty_app_main_P {
    int64_t f_x;
    int64_t f_y;
};
typedef struct { lyr_ty_app_main_P value; uint8_t has; } lyr_opt_ty10_app_main_P;

/* prototypes */
uint8_t lyr_std_core_equalOptionals_app_main_P__492af87c(lyr_opt_ty10_app_main_P l0_a, lyr_opt_ty10_app_main_P l1_b);
uint8_t lyr_app_main__extend__P_equals_f1e3d682(lyr_ty_app_main_P *l0_this, lyr_ty_app_main_P l1_o);

#line 3860 "stdlib5/std/core.lyr"
uint8_t lyr_std_core_equalOptionals_app_main_P__492af87c(lyr_opt_ty10_app_main_P l0_a, lyr_opt_ty10_app_main_P l1_b) {
    lyr_opt_ty10_app_main_P t0_s = {0};
    lyr_opt_ty10_app_main_P *t0 = &t0_s;
    uint8_t t1 = 0;
    uint8_t t2 = 0;
    lyr_opt_ty10_app_main_P t3_s = {0};
    lyr_opt_ty10_app_main_P *t3 = &t3_s;
    uint8_t t4 = 0;
    uint8_t t5 = 0;
    lyr_opt_ty10_app_main_P t6_s = {0};
    lyr_opt_ty10_app_main_P *t6 = &t6_s;
    uint8_t t7 = 0;
    uint8_t t8 = 0;
    uint8_t t9 = 0;
    lyr_opt_ty10_app_main_P t10_s = {0};
    lyr_opt_ty10_app_main_P *t10 = &t10_s;
    lyr_ty_app_main_P t11_s = {0};
    lyr_ty_app_main_P *t11 = &t11_s;
    lyr_ty_app_main_P t12_s = {0};
    lyr_ty_app_main_P *t12 = &t12_s;
    lyr_opt_ty10_app_main_P t13_s = {0};
    lyr_opt_ty10_app_main_P *t13 = &t13_s;
    lyr_ty_app_main_P t14_s = {0};
    lyr_ty_app_main_P *t14 = &t14_s;
    uint8_t t15 = 0;
bb0:;
#line 3860
    t0 = &l0_a;
#line 3860
    t1 = t0->has;
#line 3860
    t2 = (uint8_t)!t1;
#line 3860
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 3860
    t3 = &l1_b;
#line 3860
    t4 = t3->has;
#line 3860
    t5 = (uint8_t)!t4;
#line 3860
    return t5;
bb2:;
#line 3861
    t6 = &l1_b;
#line 3861
    t7 = t6->has;
#line 3861
    t8 = (uint8_t)!t7;
#line 3861
    if (t8) goto bb3; else goto bb4;
bb3:;
#line 3861
    t9 = 0;
#line 3861
    return t9;
bb4:;
#line 3862
    t10 = &l1_b;
#line 3862
    t11 = &t10->value;
#line 3862
    t12_s = *t11; t12 = &t12_s;
#line 3862
    t13 = &l0_a;
#line 3862
    t14 = &t13->value;
#line 3862
    t15 = lyr_app_main__extend__P_equals_f1e3d682(t14, *t12);
#line 3862
    return t15;
}


/* ==== unit: std.core.equalOptionals<int> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.equalOptionals<int>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct { int64_t value; uint8_t has; } lyr_opt_i64;

/* prototypes */
uint8_t lyr_std_core_equalOptionals_int__f326e1e3(lyr_opt_i64 l0_a, lyr_opt_i64 l1_b);
uint8_t lyr_std_core__extend__int_equals_12f53381(int64_t l0_this, int64_t l1_o);

#line 3860 "stdlib5/std/core.lyr"
uint8_t lyr_std_core_equalOptionals_int__f326e1e3(lyr_opt_i64 l0_a, lyr_opt_i64 l1_b) {
    lyr_opt_i64 t0_s = {0};
    lyr_opt_i64 *t0 = &t0_s;
    uint8_t t1 = 0;
    uint8_t t2 = 0;
    lyr_opt_i64 t3_s = {0};
    lyr_opt_i64 *t3 = &t3_s;
    uint8_t t4 = 0;
    uint8_t t5 = 0;
    lyr_opt_i64 t6_s = {0};
    lyr_opt_i64 *t6 = &t6_s;
    uint8_t t7 = 0;
    uint8_t t8 = 0;
    uint8_t t9 = 0;
    lyr_opt_i64 t10_s = {0};
    lyr_opt_i64 *t10 = &t10_s;
    int64_t t11 = 0;
    lyr_opt_i64 t12_s = {0};
    lyr_opt_i64 *t12 = &t12_s;
    int64_t t13 = 0;
    uint8_t t14 = 0;
bb0:;
#line 3860
    t0 = &l0_a;
#line 3860
    t1 = t0->has;
#line 3860
    t2 = (uint8_t)!t1;
#line 3860
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 3860
    t3 = &l1_b;
#line 3860
    t4 = t3->has;
#line 3860
    t5 = (uint8_t)!t4;
#line 3860
    return t5;
bb2:;
#line 3861
    t6 = &l1_b;
#line 3861
    t7 = t6->has;
#line 3861
    t8 = (uint8_t)!t7;
#line 3861
    if (t8) goto bb3; else goto bb4;
bb3:;
#line 3861
    t9 = 0;
#line 3861
    return t9;
bb4:;
#line 3862
    t10 = &l0_a;
#line 3862
    t11 = t10->value;
#line 3862
    t12 = &l1_b;
#line 3862
    t13 = t12->value;
#line 3862
    t14 = lyr_std_core__extend__int_equals_12f53381(t11, t13);
#line 3862
    return t14;
}


/* ==== unit: std.core.repeatArray<app.main.Cell> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.repeatArray<app.main.Cell>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Cell lyr_ty_app_main_Cell;
typedef struct lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc;
struct lyr_ty_app_main_Cell {
    LyrObj header;
    int64_t f_v;
};
_Static_assert(sizeof(lyr_ty_app_main_Cell) == 16, "layout of lyr_ty_app_main_Cell");
_Static_assert(offsetof(lyr_ty_app_main_Cell, f_v) == 8, "layout of lyr_ty_app_main_Cell");
extern const LyrDesc lyr_desc_ty_app_main_Cell;
struct lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc {
    LyrObj header;
    LyrArr *f_xs;
    int64_t f_m;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc) == 24, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, f_xs) == 8, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc, f_m) == 16, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc");
extern const LyrDesc lyr_desc_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc;
typedef struct { lyr_ty_app_main_Cell * (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ref13_app_main_Cell;
_Static_assert(sizeof(lyr_fn_i64_to_ref13_app_main_Cell) == 16, "layout of lyr_fn_i64_to_ref13_app_main_Cell");
_Static_assert(sizeof(lyr_ty_app_main_Cell *) == 8, "layout of app.main.Cell[]");
extern const LyrDesc lyr_desc_arr_ref13_app_main_Cell;

/* string literals */
static const LyrStaticStr(22) lyr_lit0 = LYR_STR_INIT("negative repeat count");

/* prototypes */
LyrArr * lyr_std_core_repeatArray_app_main_Cell__85adea75(LyrArr *l0_xs, int64_t l1_n);
LyrArr * lyr_std_core_arrayOf_app_main_Cell__b07c39ad(int64_t l0_n, lyr_fn_i64_to_ref13_app_main_Cell l1_f);
lyr_ty_app_main_Cell * lyr_std_core_repeatArray_app_main_Cell___lambda0__8cc48eaa(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);
lyr_ty_app_main_Cell * lyr_app_main__extend__Cell_clone_ea0d1aaa(lyr_ty_app_main_Cell *l0_this);

#line 98 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_repeatArray_app_main_Cell__85adea75(LyrArr *l0_xs, int64_t l1_n) {
    int64_t l2_m = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    LyrArr *t4 = NULL;
    int64_t t5 = 0;
    int64_t t6 = 0;
    int64_t t7 = 0;
    int64_t t8 = 0;
    LyrArr *t9 = NULL;
    int64_t t10 = 0;
    lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *t11 = NULL;
    lyr_fn_i64_to_ref13_app_main_Cell t12 = {0};
    LyrArr *t13 = NULL;
bb0:;
#line 98
    t0 = l1_n;
#line 98
    t1 = (int64_t)INT64_C(0);
#line 98
    t2 = (uint8_t)(t0 < t1);
#line 98
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 98
    t3 = (LyrStr *)&lyr_lit0;
#line 98
    lyr_panic_message(t3);
#line 98
    LYR_UNREACHABLE();
bb2:;
#line 99
    t4 = l0_xs;
#line 99
    t5 = t4->len;
#line 99
    l2_m = t5;
#line 100
    t6 = l2_m;
#line 100
    t7 = l1_n;
#line 100
    t8 = LYR_CHECKED_MUL(t6, t7);
#line 100
    t9 = l0_xs;
#line 100
    t10 = l2_m;
#line 100
    t11 = (lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *)lyr_alloc(&lyr_desc_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc);
#line 100
    LYR_WRITE_BARRIER(t11, &t11->f_xs, t9);
#line 100
    t11->f_m = t10;
#line 100
    t12 = (lyr_fn_i64_to_ref13_app_main_Cell){ lyr_std_core_repeatArray_app_main_Cell___lambda0__8cc48eaa, t11 };
#line 100
    t13 = lyr_std_core_arrayOf_app_main_Cell__b07c39ad(t8, t12);
#line 100
    return t13;
}

#line 100 "stdlib5/std/core.lyr"
lyr_ty_app_main_Cell * lyr_std_core_repeatArray_app_main_Cell___lambda0__8cc48eaa(void *lyr_env, int64_t l1_i, LyrErr **lyr_err) {
    lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *l0__env_ = (lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *)lyr_env;
    (void)lyr_err;
    lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *t0 = NULL;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    lyr_ty_0_env_std_core_repeatArray_app_main_Cell___112ca3dc *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    lyr_ty_app_main_Cell *t6 = NULL;
    lyr_ty_app_main_Cell *t7 = NULL;
bb0:;
#line 100
    t0 = l0__env_;
#line 100
    t1 = t0->f_xs;
#line 100
    t2 = l1_i;
#line 100
    t3 = l0__env_;
#line 100
    t4 = t3->f_m;
#line 100
    t5 = LYR_CHECKED_REM(t2, t4);
#line 100
    LYR_CHECK_INDEX(t5, t1->len); t6 = LYR_ARR_DATA(t1, lyr_ty_app_main_Cell *)[t5];
#line 100
    t7 = lyr_app_main__extend__Cell_clone_ea0d1aaa(t6);
#line 100
    return t7;
}


/* ==== unit: std.core.repeatArray<app.main.Holder> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'std.core.repeatArray<app.main.Holder>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Holder lyr_ty_app_main_Holder;
typedef struct lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6;
struct lyr_ty_app_main_Holder {
    LyrArr *f_items;
    int64_t f_n;
};
struct lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 {
    LyrObj header;
    LyrArr *f_xs;
    int64_t f_m;
};
_Static_assert(sizeof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6) == 24, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, f_xs) == 8, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
_Static_assert(offsetof(lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6, f_m) == 16, "layout of lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6");
extern const LyrDesc lyr_desc_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6;
typedef struct { lyr_ty_app_main_Holder (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_ty15_app_main_Holder;
_Static_assert(sizeof(lyr_fn_i64_to_ty15_app_main_Holder) == 16, "layout of lyr_fn_i64_to_ty15_app_main_Holder");
_Static_assert(sizeof(lyr_ty_app_main_Holder) == 16, "layout of app.main.Holder[]");
extern const LyrDesc lyr_desc_arr_ty15_app_main_Holder;
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;

/* string literals */
static const LyrStaticStr(22) lyr_lit0 = LYR_STR_INIT("negative repeat count");

/* prototypes */
LyrArr * lyr_std_core_repeatArray_app_main_Holder__0f62b54f(LyrArr *l0_xs, int64_t l1_n);
LyrArr * lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(int64_t l0_n, lyr_fn_i64_to_ty15_app_main_Holder l1_f);
lyr_ty_app_main_Holder lyr_std_core_repeatArray_app_main_Holder___lambda1__3fcd1a15(void *lyr_env, int64_t l1_i, LyrErr **lyr_err);
lyr_ty_app_main_Holder lyr_app_main__extend__Holder_clone_5e124274(lyr_ty_app_main_Holder *l0_this);

#line 98 "stdlib5/std/core.lyr"
LyrArr * lyr_std_core_repeatArray_app_main_Holder__0f62b54f(LyrArr *l0_xs, int64_t l1_n) {
    int64_t l2_m = 0;
    int64_t t0 = 0;
    int64_t t1 = 0;
    uint8_t t2 = 0;
    LyrStr *t3 = NULL;
    LyrArr *t4 = NULL;
    int64_t t5 = 0;
    int64_t t6 = 0;
    int64_t t7 = 0;
    int64_t t8 = 0;
    LyrArr *t9 = NULL;
    int64_t t10 = 0;
    lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *t11 = NULL;
    lyr_fn_i64_to_ty15_app_main_Holder t12 = {0};
    LyrArr *t13 = NULL;
bb0:;
#line 98
    t0 = l1_n;
#line 98
    t1 = (int64_t)INT64_C(0);
#line 98
    t2 = (uint8_t)(t0 < t1);
#line 98
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 98
    t3 = (LyrStr *)&lyr_lit0;
#line 98
    lyr_panic_message(t3);
#line 98
    LYR_UNREACHABLE();
bb2:;
#line 99
    t4 = l0_xs;
#line 99
    t5 = t4->len;
#line 99
    l2_m = t5;
#line 100
    t6 = l2_m;
#line 100
    t7 = l1_n;
#line 100
    t8 = LYR_CHECKED_MUL(t6, t7);
#line 100
    t9 = l0_xs;
#line 100
    t10 = l2_m;
#line 100
    t11 = (lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *)lyr_alloc(&lyr_desc_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6);
#line 100
    LYR_WRITE_BARRIER(t11, &t11->f_xs, t9);
#line 100
    t11->f_m = t10;
#line 100
    t12 = (lyr_fn_i64_to_ty15_app_main_Holder){ lyr_std_core_repeatArray_app_main_Holder___lambda1__3fcd1a15, t11 };
#line 100
    t13 = lyr_std_core_arrayOf_app_main_Holder__a6cd6d37(t8, t12);
#line 100
    return t13;
}

#line 100 "stdlib5/std/core.lyr"
lyr_ty_app_main_Holder lyr_std_core_repeatArray_app_main_Holder___lambda1__3fcd1a15(void *lyr_env, int64_t l1_i, LyrErr **lyr_err) {
    lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *l0__env_ = (lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *)lyr_env;
    (void)lyr_err;
    lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *t0 = NULL;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    lyr_ty_0_env_std_core_repeatArray_app_main_Holder___5bbd50d6 *t3 = NULL;
    int64_t t4 = 0;
    int64_t t5 = 0;
    lyr_ty_app_main_Holder t6_s = {0};
    lyr_ty_app_main_Holder *t6 = &t6_s;
    lyr_ty_app_main_Holder t7_s = {0};
    lyr_ty_app_main_Holder *t7 = &t7_s;
bb0:;
#line 100
    t0 = l0__env_;
#line 100
    t1 = t0->f_xs;
#line 100
    t2 = l1_i;
#line 100
    t3 = l0__env_;
#line 100
    t4 = t3->f_m;
#line 100
    t5 = LYR_CHECKED_REM(t2, t4);
#line 100
    LYR_CHECK_INDEX(t5, t1->len); t6 = &LYR_ARR_DATA(t1, lyr_ty_app_main_Holder)[t5];
#line 100
    t7_s = lyr_app_main__extend__Holder_clone_5e124274(t6); t7 = &t7_s;
#line 100
    return *t7;
}

