/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_vt_ty0 lyr_vt_ty0;
const char lyr_ifid_ty0[] = "main.Source";
typedef struct lyr_ty1_Good lyr_ty1_Good;
typedef struct lyr_ty2_Fails lyr_ty2_Fails;
typedef struct lyr_vt_ty3 lyr_vt_ty3;
const char lyr_ifid_ty3[] = "std.core.Error";
typedef struct lyr_ty4_Bad lyr_ty4_Bad;
typedef struct lyr_ty5_Bad_It lyr_ty5_Bad_It;
typedef struct lyr_ty6_Counter lyr_ty6_Counter;
typedef struct lyr_ty7_BoxErr_int_ lyr_ty7_BoxErr_int_;
typedef struct lyr_ty8_Exception lyr_ty8_Exception;
struct lyr_vt_ty0 {
    const LyrDesc *desc;
    int64_t (*s0)(LyrIface, int64_t, LyrErr **);
};
struct lyr_ty1_Good {
    uint8_t lyr_unit;
};
struct lyr_ty2_Fails {
    uint8_t lyr_unit;
};
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface3;
struct lyr_vt_ty3 {
    const LyrDesc *desc;
    LyrStr * (*s0)(LyrIface);
    lyr_opt_iface3 (*s1)(LyrIface);
};
struct lyr_ty5_Bad_It {
    uint8_t lyr_unit;
};
struct lyr_ty4_Bad { uint32_t tag; };
_Static_assert(sizeof(lyr_ty4_Bad) == 4, "layout of lyr_ty4_Bad");
struct lyr_ty6_Counter {
    int64_t f_n;
};
struct lyr_ty7_BoxErr_int_ {
    int64_t f_v;
};
struct lyr_ty8_Exception {
    LyrObj header;
    LyrStr *f_text;
    lyr_opt_iface3 f_inner;
};
_Static_assert(sizeof(lyr_ty8_Exception) == 40, "layout of lyr_ty8_Exception");
_Static_assert(offsetof(lyr_ty8_Exception, f_text) == 8, "layout of lyr_ty8_Exception");
_Static_assert(offsetof(lyr_ty8_Exception, f_inner) == 16, "layout of lyr_ty8_Exception");
static const uint64_t lyr_refmap_ty8[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty8_Exception = { sizeof(lyr_ty8_Exception), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty8, "std.core.Exception", NULL };
typedef struct { int64_t (*fn)(void *, int64_t, LyrErr **); void *env; } lyr_fn_i64_to_i64;
_Static_assert(sizeof(lyr_fn_i64_to_i64) == 16, "layout of lyr_fn_i64_to_i64");
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
const LyrDesc lyr_desc_arr_i64 = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY, sizeof(int64_t), 0, NULL, "int[]", NULL };
typedef struct { LyrObj header; lyr_ty1_Good value; } lyr_box_ty1_Good;
_Static_assert(sizeof(lyr_box_ty1_Good) == 16, "layout of lyr_box_ty1_Good");
_Static_assert(offsetof(lyr_box_ty1_Good, value) == 8, "layout of lyr_box_ty1_Good");
extern const LyrItable lyr_itab_ty1[];
const LyrDesc lyr_desc_box_ty1_Good = { sizeof(lyr_box_ty1_Good), 0, 0, 0, NULL, "box<main.Good>", lyr_itab_ty1 };
typedef struct { LyrObj header; lyr_ty2_Fails value; } lyr_box_ty2_Fails;
_Static_assert(sizeof(lyr_box_ty2_Fails) == 16, "layout of lyr_box_ty2_Fails");
_Static_assert(offsetof(lyr_box_ty2_Fails, value) == 8, "layout of lyr_box_ty2_Fails");
extern const LyrItable lyr_itab_ty2[];
const LyrDesc lyr_desc_box_ty2_Fails = { sizeof(lyr_box_ty2_Fails), 0, 0, 0, NULL, "box<main.Fails>", lyr_itab_ty2 };
typedef struct { LyrObj header; lyr_ty4_Bad value; } lyr_box_ty4_Bad;
_Static_assert(sizeof(lyr_box_ty4_Bad) == 16, "layout of lyr_box_ty4_Bad");
_Static_assert(offsetof(lyr_box_ty4_Bad, value) == 8, "layout of lyr_box_ty4_Bad");
extern const LyrItable lyr_itab_ty4[];
const LyrDesc lyr_desc_box_ty4_Bad = { sizeof(lyr_box_ty4_Bad), 0, 0, 0, NULL, "box<Bad>", lyr_itab_ty4 };
typedef struct { LyrObj header; lyr_ty7_BoxErr_int_ value; } lyr_box_ty7_BoxErr_int_;
_Static_assert(sizeof(lyr_box_ty7_BoxErr_int_) == 16, "layout of lyr_box_ty7_BoxErr_int_");
_Static_assert(offsetof(lyr_box_ty7_BoxErr_int_, value) == 8, "layout of lyr_box_ty7_BoxErr_int_");
extern const LyrItable lyr_itab_ty7[];
const LyrDesc lyr_desc_box_ty7_BoxErr_int_ = { sizeof(lyr_box_ty7_BoxErr_int_), 0, 0, 0, NULL, "box<main.BoxErr<int>>", lyr_itab_ty7 };

/* string literals */
static const LyrStaticStr(6) lyr_lit0 = LYR_STR_INIT("slot:");
static const LyrStaticStr(2) lyr_lit1 = LYR_STR_INIT(" ");
static const LyrStaticStr(14) lyr_lit2 = LYR_STR_INIT(" then caught ");
static const LyrStaticStr(8) lyr_lit3 = LYR_STR_INIT("method:");
static const LyrStaticStr(9) lyr_lit4 = LYR_STR_INIT("generic:");
static const LyrStaticStr(7) lyr_lit5 = LYR_STR_INIT("chain:");
static const LyrStaticStr(3) lyr_lit6 = LYR_STR_INIT(" a");
static const LyrStaticStr(3) lyr_lit7 = LYR_STR_INIT(" b");
static const LyrStaticStr(3) lyr_lit8 = LYR_STR_INIT(" c");
static const LyrStaticStr(8) lyr_lit9 = LYR_STR_INIT(" caught");
static const LyrStaticStr(6) lyr_lit10 = LYR_STR_INIT("loop:");
static const LyrStaticStr(6) lyr_lit11 = LYR_STR_INIT(" done");
static const LyrStaticStr(6) lyr_lit12 = LYR_STR_INIT(" skip");
static const LyrStaticStr(23) lyr_lit13 = LYR_STR_INIT("lambda: caught inside ");
static const LyrStaticStr(8) lyr_lit14 = LYR_STR_INIT("nested:");
static const LyrStaticStr(21) lyr_lit15 = LYR_STR_INIT(" inner clause caught");
static const LyrStaticStr(19) lyr_lit16 = LYR_STR_INIT("clausereturn defer");
static const LyrStaticStr(15) lyr_lit17 = LYR_STR_INIT("clausereturn: ");
static const LyrStaticStr(4) lyr_lit18 = LYR_STR_INIT("bad");

/* prototypes */
LyrStr * lyr_main_slot(void);
LyrStr * lyr_main_method(void);
LyrStr * lyr_main_generic(void);
LyrStr * lyr_main_chain(void);
LyrStr * lyr_main_loop(void);
int64_t lyr_main_apply(lyr_fn_i64_to_i64 l0_f, int64_t l1_x);
LyrStr * lyr_main_lambda(void);
LyrStr * lyr_main_nested(void);
int64_t lyr_main_clauseReturn(void);
int64_t lyr_main_main(void);
LyrStr * lyr_main_Bad_message(lyr_ty4_Bad *l0_this);
int64_t lyr_main_Good_read(lyr_ty1_Good *l0_this, int64_t l1_n);
int64_t lyr_main_Fails_read(lyr_ty2_Fails *l0_this, int64_t l1_n, LyrErr **lyr_err);
int64_t lyr_main_Counter_bump(lyr_ty6_Counter *l0_this, int64_t l1_limit, LyrErr **lyr_err);
lyr_opt_iface3 lyr_std_core_Error_cause(LyrIface l0_this);
int64_t lyr_main_pick_int__e6b63dd8(LyrArr *l0_xs, int64_t l1_i, LyrErr **lyr_err);
LyrStr * lyr_main_BoxErr_int__message_e630ecb2(lyr_ty7_BoxErr_int_ *l0_this);
int64_t lyr_main_lambda__lambda0__1c85569e(int64_t l0_x);

/* thunks: a function as a value, without an environment */
static int64_t lyr_thunk_main_lambda__lambda0__1c85569e(void *lyr_env, int64_t l0_x, LyrErr **lyr_err) { (void)lyr_env; (void)lyr_err; return lyr_main_lambda__lambda0__1c85569e(l0_x); }

/* interface tables: the descriptor, then the implementation of every slot */
static int64_t lyr_vt_ty0_ty1_s0(LyrIface self, int64_t a0, LyrErr **lyr_err) { return lyr_main_Good_read(&((lyr_box_ty1_Good *)self.data)->value, a0); }
const lyr_vt_ty0 lyr_vt_ty0_ty1 = { &lyr_desc_box_ty1_Good, lyr_vt_ty0_ty1_s0 };
static int64_t lyr_vt_ty0_ty2_s0(LyrIface self, int64_t a0, LyrErr **lyr_err) { return lyr_main_Fails_read(&((lyr_box_ty2_Fails *)self.data)->value, a0, lyr_err); }
const lyr_vt_ty0 lyr_vt_ty0_ty2 = { &lyr_desc_box_ty2_Fails, lyr_vt_ty0_ty2_s0 };
static LyrStr * lyr_vt_ty3_ty4_s0(LyrIface self) { return lyr_main_Bad_message(&((lyr_box_ty4_Bad *)self.data)->value); }
const lyr_vt_ty3 lyr_vt_ty3_ty4 = { &lyr_desc_box_ty4_Bad, lyr_vt_ty3_ty4_s0, lyr_std_core_Error_cause };
static LyrStr * lyr_vt_ty3_ty7_s0(LyrIface self) { return lyr_main_BoxErr_int__message_e630ecb2(&((lyr_box_ty7_BoxErr_int_ *)self.data)->value); }
const lyr_vt_ty3 lyr_vt_ty3_ty7 = { &lyr_desc_box_ty7_BoxErr_int_, lyr_vt_ty3_ty7_s0, lyr_std_core_Error_cause };
const LyrItable lyr_itab_ty1[] = { { lyr_ifid_ty0, &lyr_vt_ty0_ty1 } , { NULL, NULL } };
const LyrItable lyr_itab_ty2[] = { { lyr_ifid_ty0, &lyr_vt_ty0_ty2 } , { NULL, NULL } };
const LyrItable lyr_itab_ty4[] = { { lyr_ifid_ty3, &lyr_vt_ty3_ty4 } , { NULL, NULL } };
const LyrItable lyr_itab_ty7[] = { { lyr_ifid_ty3, &lyr_vt_ty3_ty7 } , { NULL, NULL } };

#line 15 "programs/error_paths.lyr"
LyrStr * lyr_main_slot(void) {
    LyrIface l0_a = {0};
    LyrIface l1_b = {0};
    LyrStr *l2_log = NULL;
    lyr_ty4_Bad l3_e = {0};
    LyrErr *lyr_e = NULL;
    lyr_ty1_Good t0_s = {0};
    lyr_ty1_Good *t0 = &t0_s;
    LyrIface t1 = {0};
    lyr_ty2_Fails t2_s = {0};
    lyr_ty2_Fails *t2 = &t2_s;
    LyrIface t3 = {0};
    LyrStr *t4 = NULL;
    LyrStr *t5 = NULL;
    LyrStr *t6 = NULL;
    LyrIface t7 = {0};
    int64_t t8 = 0;
    int64_t t9 = 0;
    LyrStr *t10 = NULL;
    LyrStr *t11 = NULL;
    LyrStr *t12 = NULL;
    LyrStr *t13 = NULL;
    LyrStr *t14 = NULL;
    LyrIface t15 = {0};
    int64_t t16 = 0;
    int64_t t17 = 0;
    LyrStr *t18 = NULL;
    LyrStr *t19 = NULL;
    LyrStr *t20 = NULL;
    LyrIface t21 = {0};
    uint8_t t22 = 0;
    lyr_ty4_Bad t23_s = {0};
    lyr_ty4_Bad *t23 = &t23_s;
    LyrStr *t24 = NULL;
    LyrStr *t25 = NULL;
    lyr_ty4_Bad t26_s = {0};
    lyr_ty4_Bad *t26 = &t26_s;
    LyrStr *t27 = NULL;
    LyrStr *t28 = NULL;
    LyrStr *t29 = NULL;
    LyrStr *t30 = NULL;
bb0:;
#line 15
    t0_s = (lyr_ty1_Good){0}; t0 = &t0_s;
#line 15
    { lyr_box_ty1_Good *lyr_box = lyr_alloc(&lyr_desc_box_ty1_Good); lyr_box->value = *t0; t1 = (LyrIface){ lyr_box, &lyr_vt_ty0_ty1 }; }
#line 15
    l0_a = t1;
#line 16
    t2_s = (lyr_ty2_Fails){0}; t2 = &t2_s;
#line 16
    { lyr_box_ty2_Fails *lyr_box = lyr_alloc(&lyr_desc_box_ty2_Fails); lyr_box->value = *t2; t3 = (LyrIface){ lyr_box, &lyr_vt_ty0_ty2 }; }
#line 16
    l1_b = t3;
#line 17
    t4 = (LyrStr *)&lyr_lit0;
#line 17
    l2_log = t4;
#line 19
    t5 = l2_log;
#line 19
    t6 = (LyrStr *)&lyr_lit1;
#line 19
    t7 = l0_a;
#line 19
    t8 = (int64_t)INT64_C(7);
#line 19
    t9 = ((const lyr_vt_ty0 *)t7.vt)->s0(t7, t8, &lyr_e);
#line 19
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 18
    t21 = lyr_e->value;
#line 21
    t22 = ((*(const LyrDesc *const *)t21.vt) == &lyr_desc_box_ty4_Bad);
#line 21
    if (t22) goto bb4; else goto bb5;
bb2:;
#line 19
    t10 = lyr_str_from_int(t9);
#line 19
    t11 = lyr_str_concat(t6, t10);
#line 19
    t12 = lyr_str_concat(t5, t11);
#line 19
    l2_log = t12;
#line 20
    t13 = l2_log;
#line 20
    t14 = (LyrStr *)&lyr_lit1;
#line 20
    t15 = l1_b;
#line 20
    t16 = (int64_t)INT64_C(1);
#line 20
    t17 = ((const lyr_vt_ty0 *)t15.vt)->s0(t15, t16, &lyr_e);
#line 20
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb3;
bb3:;
#line 20
    t18 = lyr_str_from_int(t17);
#line 20
    t19 = lyr_str_concat(t14, t18);
#line 20
    t20 = lyr_str_concat(t13, t19);
#line 20
    l2_log = t20;
#line 18
    goto bb7;
bb4:;
#line 21
    lyr_e = NULL;
#line 21
    t23_s = ((lyr_box_ty4_Bad *)t21.data)->value; t23 = &t23_s;
#line 21
    l3_e = *t23;
#line 21
    t24 = l2_log;
#line 21
    t25 = (LyrStr *)&lyr_lit2;
#line 21
    t26 = &l3_e;
#line 21
    t27 = lyr_main_Bad_message(t26);
#line 21
    t28 = lyr_str_concat(t25, t27);
#line 21
    t29 = lyr_str_concat(t24, t28);
#line 21
    l2_log = t29;
#line 18
    goto bb7;
bb5:;
#line 18
    goto bb6;
bb6:;
#line 18
    __builtin_unreachable();
bb7:;
#line 22
    t30 = l2_log;
#line 22
    return t30;
}

#line 33 "programs/error_paths.lyr"
LyrStr * lyr_main_method(void) {
    lyr_ty6_Counter l0_c = {0};
    LyrStr *l1_log = NULL;
    lyr_ty4_Bad l2_e = {0};
    LyrErr *lyr_e = NULL;
    int64_t t0 = 0;
    lyr_ty6_Counter t1_s = {0};
    lyr_ty6_Counter *t1 = &t1_s;
    LyrStr *t2 = NULL;
    LyrStr *t3 = NULL;
    LyrStr *t4 = NULL;
    lyr_ty6_Counter t5_s = {0};
    lyr_ty6_Counter *t5 = &t5_s;
    int64_t t6 = 0;
    int64_t t7 = 0;
    LyrStr *t8 = NULL;
    LyrStr *t9 = NULL;
    LyrStr *t10 = NULL;
    LyrStr *t11 = NULL;
    LyrStr *t12 = NULL;
    lyr_ty6_Counter t13_s = {0};
    lyr_ty6_Counter *t13 = &t13_s;
    int64_t t14 = 0;
    int64_t t15 = 0;
    LyrStr *t16 = NULL;
    LyrStr *t17 = NULL;
    LyrStr *t18 = NULL;
    LyrIface t19 = {0};
    uint8_t t20 = 0;
    lyr_ty4_Bad t21_s = {0};
    lyr_ty4_Bad *t21 = &t21_s;
    LyrStr *t22 = NULL;
    LyrStr *t23 = NULL;
    lyr_ty4_Bad t24_s = {0};
    lyr_ty4_Bad *t24 = &t24_s;
    LyrStr *t25 = NULL;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    LyrStr *t28 = NULL;
bb0:;
#line 33
    t0 = (int64_t)INT64_C(2);
#line 33
    t1_s = (lyr_ty6_Counter){0}; t1 = &t1_s;
#line 33
    t1->f_n = t0;
#line 33
    l0_c = *t1;
#line 34
    t2 = (LyrStr *)&lyr_lit3;
#line 34
    l1_log = t2;
#line 36
    t3 = l1_log;
#line 36
    t4 = (LyrStr *)&lyr_lit1;
#line 36
    t5 = &l0_c;
#line 36
    t6 = (int64_t)INT64_C(5);
#line 36
    t7 = lyr_main_Counter_bump(t5, t6, &lyr_e);
#line 36
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 35
    t19 = lyr_e->value;
#line 38
    t20 = ((*(const LyrDesc *const *)t19.vt) == &lyr_desc_box_ty4_Bad);
#line 38
    if (t20) goto bb4; else goto bb5;
bb2:;
#line 36
    t8 = lyr_str_from_int(t7);
#line 36
    t9 = lyr_str_concat(t4, t8);
#line 36
    t10 = lyr_str_concat(t3, t9);
#line 36
    l1_log = t10;
#line 37
    t11 = l1_log;
#line 37
    t12 = (LyrStr *)&lyr_lit1;
#line 37
    t13 = &l0_c;
#line 37
    t14 = (int64_t)INT64_C(3);
#line 37
    t15 = lyr_main_Counter_bump(t13, t14, &lyr_e);
#line 37
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb3;
bb3:;
#line 37
    t16 = lyr_str_from_int(t15);
#line 37
    t17 = lyr_str_concat(t12, t16);
#line 37
    t18 = lyr_str_concat(t11, t17);
#line 37
    l1_log = t18;
#line 35
    goto bb7;
bb4:;
#line 38
    lyr_e = NULL;
#line 38
    t21_s = ((lyr_box_ty4_Bad *)t19.data)->value; t21 = &t21_s;
#line 38
    l2_e = *t21;
#line 38
    t22 = l1_log;
#line 38
    t23 = (LyrStr *)&lyr_lit2;
#line 38
    t24 = &l2_e;
#line 38
    t25 = lyr_main_Bad_message(t24);
#line 38
    t26 = lyr_str_concat(t23, t25);
#line 38
    t27 = lyr_str_concat(t22, t26);
#line 38
    l1_log = t27;
#line 35
    goto bb7;
bb5:;
#line 35
    goto bb6;
bb6:;
#line 35
    __builtin_unreachable();
bb7:;
#line 39
    t28 = l1_log;
#line 39
    return t28;
}

#line 47 "programs/error_paths.lyr"
LyrStr * lyr_main_generic(void) {
    LyrStr *l0_log = NULL;
    lyr_ty7_BoxErr_int_ l1_e = {0};
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    LyrStr *t1 = NULL;
    LyrStr *t2 = NULL;
    int64_t t3 = 0;
    int64_t t4 = 0;
    int64_t t5 = 0;
    LyrArr *t6 = NULL;
    int64_t t7 = 0;
    int64_t t8 = 0;
    LyrStr *t9 = NULL;
    LyrStr *t10 = NULL;
    LyrStr *t11 = NULL;
    LyrStr *t12 = NULL;
    LyrStr *t13 = NULL;
    int64_t t14 = 0;
    int64_t t15 = 0;
    int64_t t16 = 0;
    LyrArr *t17 = NULL;
    int64_t t18 = 0;
    int64_t t19 = 0;
    LyrStr *t20 = NULL;
    LyrStr *t21 = NULL;
    LyrStr *t22 = NULL;
    LyrIface t23 = {0};
    uint8_t t24 = 0;
    lyr_ty7_BoxErr_int_ t25_s = {0};
    lyr_ty7_BoxErr_int_ *t25 = &t25_s;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    lyr_ty7_BoxErr_int_ t28_s = {0};
    lyr_ty7_BoxErr_int_ *t28 = &t28_s;
    LyrStr *t29 = NULL;
    LyrStr *t30 = NULL;
    LyrStr *t31 = NULL;
    LyrStr *t32 = NULL;
bb0:;
#line 47
    t0 = (LyrStr *)&lyr_lit4;
#line 47
    l0_log = t0;
#line 49
    t1 = l0_log;
#line 49
    t2 = (LyrStr *)&lyr_lit1;
#line 49
    t3 = (int64_t)INT64_C(4);
#line 49
    t4 = (int64_t)INT64_C(5);
#line 49
    t5 = (int64_t)INT64_C(6);
#line 49
    t6 = lyr_alloc_array(&lyr_desc_arr_i64, 3); LYR_ARR_DATA(t6, int64_t)[0] = t3; LYR_ARR_DATA(t6, int64_t)[1] = t4; LYR_ARR_DATA(t6, int64_t)[2] = t5;
#line 49
    t7 = (int64_t)INT64_C(1);
#line 49
    t8 = lyr_main_pick_int__e6b63dd8(t6, t7, &lyr_e);
#line 49
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 48
    t23 = lyr_e->value;
#line 51
    t24 = ((*(const LyrDesc *const *)t23.vt) == &lyr_desc_box_ty7_BoxErr_int_);
#line 51
    if (t24) goto bb4; else goto bb5;
bb2:;
#line 49
    t9 = lyr_str_from_int(t8);
#line 49
    t10 = lyr_str_concat(t2, t9);
#line 49
    t11 = lyr_str_concat(t1, t10);
#line 49
    l0_log = t11;
#line 50
    t12 = l0_log;
#line 50
    t13 = (LyrStr *)&lyr_lit1;
#line 50
    t14 = (int64_t)INT64_C(4);
#line 50
    t15 = (int64_t)INT64_C(5);
#line 50
    t16 = (int64_t)INT64_C(6);
#line 50
    t17 = lyr_alloc_array(&lyr_desc_arr_i64, 3); LYR_ARR_DATA(t17, int64_t)[0] = t14; LYR_ARR_DATA(t17, int64_t)[1] = t15; LYR_ARR_DATA(t17, int64_t)[2] = t16;
#line 50
    t18 = (int64_t)INT64_C(9);
#line 50
    t19 = lyr_main_pick_int__e6b63dd8(t17, t18, &lyr_e);
#line 50
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb3;
bb3:;
#line 50
    t20 = lyr_str_from_int(t19);
#line 50
    t21 = lyr_str_concat(t13, t20);
#line 50
    t22 = lyr_str_concat(t12, t21);
#line 50
    l0_log = t22;
#line 48
    goto bb7;
bb4:;
#line 51
    lyr_e = NULL;
#line 51
    t25_s = ((lyr_box_ty7_BoxErr_int_ *)t23.data)->value; t25 = &t25_s;
#line 51
    l1_e = *t25;
#line 51
    t26 = l0_log;
#line 51
    t27 = (LyrStr *)&lyr_lit2;
#line 51
    t28 = &l1_e;
#line 51
    t29 = lyr_main_BoxErr_int__message_e630ecb2(t28);
#line 51
    t30 = lyr_str_concat(t27, t29);
#line 51
    t31 = lyr_str_concat(t26, t30);
#line 51
    l0_log = t31;
#line 48
    goto bb7;
bb5:;
#line 48
    goto bb6;
bb6:;
#line 48
    __builtin_unreachable();
bb7:;
#line 52
    t32 = l0_log;
#line 52
    return t32;
}

#line 56 "programs/error_paths.lyr"
LyrStr * lyr_main_chain(void) {
    LyrStr *l0_log = NULL;
    int64_t l1_n = 0;
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    int64_t t1 = 0;
    LyrArr *t2 = NULL;
    int64_t t3 = 0;
    int64_t t4 = 0;
    LyrStr *t5 = NULL;
    LyrStr *t6 = NULL;
    LyrStr *t7 = NULL;
    LyrStr *t8 = NULL;
    LyrStr *t9 = NULL;
    LyrStr *t10 = NULL;
    LyrStr *t11 = NULL;
    LyrStr *t12 = NULL;
    LyrStr *t13 = NULL;
    LyrStr *t14 = NULL;
    LyrStr *t15 = NULL;
    int64_t t16 = 0;
    LyrStr *t17 = NULL;
    LyrStr *t18 = NULL;
    LyrStr *t19 = NULL;
    LyrStr *t20 = NULL;
    LyrStr *t21 = NULL;
    LyrStr *t22 = NULL;
    LyrStr *t23 = NULL;
    LyrStr *t24 = NULL;
    LyrStr *t25 = NULL;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    LyrStr *t28 = NULL;
    LyrIface t29 = {0};
    uint8_t t30 = 0;
    LyrStr *t31 = NULL;
    LyrStr *t32 = NULL;
    LyrStr *t33 = NULL;
    LyrStr *t34 = NULL;
bb0:;
#line 56
    t0 = (LyrStr *)&lyr_lit5;
#line 56
    l0_log = t0;
#line 63
    t1 = (int64_t)INT64_C(1);
#line 63
    t2 = lyr_alloc_array(&lyr_desc_arr_i64, 1); LYR_ARR_DATA(t2, int64_t)[0] = t1;
#line 63
    t3 = (int64_t)INT64_C(5);
#line 63
    t4 = lyr_main_pick_int__e6b63dd8(t2, t3, &lyr_e);
#line 63
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb5;
bb1:;
#line 62
    t5 = l0_log;
#line 62
    t6 = (LyrStr *)&lyr_lit6;
#line 62
    t7 = lyr_str_concat(t5, t6);
#line 62
    l0_log = t7;
#line 63
    goto bb2;
bb2:;
#line 60
    t8 = l0_log;
#line 60
    t9 = (LyrStr *)&lyr_lit7;
#line 60
    t10 = lyr_str_concat(t8, t9);
#line 60
    l0_log = t10;
#line 63
    goto bb3;
bb3:;
#line 58
    t11 = l0_log;
#line 58
    t12 = (LyrStr *)&lyr_lit8;
#line 58
    t13 = lyr_str_concat(t11, t12);
#line 58
    l0_log = t13;
#line 63
    goto bb4;
bb4:;
#line 57
    t29 = lyr_e->value;
#line 67
    t30 = ((*(const LyrDesc *const *)t29.vt) == &lyr_desc_box_ty7_BoxErr_int_);
#line 67
    if (t30) goto bb6; else goto bb7;
bb5:;
#line 63
    l1_n = t4;
#line 64
    t14 = l0_log;
#line 64
    t15 = (LyrStr *)&lyr_lit1;
#line 64
    t16 = l1_n;
#line 64
    t17 = lyr_str_from_int(t16);
#line 64
    t18 = lyr_str_concat(t15, t17);
#line 64
    t19 = lyr_str_concat(t14, t18);
#line 64
    l0_log = t19;
#line 62
    t20 = l0_log;
#line 62
    t21 = (LyrStr *)&lyr_lit6;
#line 62
    t22 = lyr_str_concat(t20, t21);
#line 62
    l0_log = t22;
#line 60
    t23 = l0_log;
#line 60
    t24 = (LyrStr *)&lyr_lit7;
#line 60
    t25 = lyr_str_concat(t23, t24);
#line 60
    l0_log = t25;
#line 58
    t26 = l0_log;
#line 58
    t27 = (LyrStr *)&lyr_lit8;
#line 58
    t28 = lyr_str_concat(t26, t27);
#line 58
    l0_log = t28;
#line 57
    goto bb9;
bb6:;
#line 67
    lyr_e = NULL;
#line 67
    t31 = l0_log;
#line 67
    t32 = (LyrStr *)&lyr_lit9;
#line 67
    t33 = lyr_str_concat(t31, t32);
#line 67
    l0_log = t33;
#line 57
    goto bb9;
bb7:;
#line 57
    goto bb8;
bb8:;
#line 57
    __builtin_unreachable();
bb9:;
#line 68
    t34 = l0_log;
#line 68
    return t34;
}

#line 72 "programs/error_paths.lyr"
LyrStr * lyr_main_loop(void) {
    LyrStr *l0_log = NULL;
    int64_t l1__range0 = 0;
    int64_t l2__last1 = 0;
    int64_t l3_i = 0;
    int64_t l4_x = 0;
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    int64_t t1 = 0;
    int64_t t2 = 0;
    int64_t t3 = 0;
    int64_t t4 = 0;
    uint8_t t5 = 0;
    int64_t t6 = 0;
    int64_t t7 = 0;
    uint8_t t8 = 0;
    int64_t t9 = 0;
    LyrArr *t10 = NULL;
    int64_t t11 = 0;
    int64_t t12 = 0;
    LyrStr *t13 = NULL;
    LyrStr *t14 = NULL;
    int64_t t15 = 0;
    LyrStr *t16 = NULL;
    LyrStr *t17 = NULL;
    LyrStr *t18 = NULL;
    int64_t t19 = 0;
    int64_t t20 = 0;
    uint8_t t21 = 0;
    LyrStr *t22 = NULL;
    LyrStr *t23 = NULL;
    int64_t t24 = 0;
    LyrStr *t25 = NULL;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    LyrIface t28 = {0};
    uint8_t t29 = 0;
    LyrStr *t30 = NULL;
    LyrStr *t31 = NULL;
    LyrStr *t32 = NULL;
    int64_t t33 = 0;
    int64_t t34 = 0;
    int64_t t35 = 0;
    LyrStr *t36 = NULL;
    LyrStr *t37 = NULL;
    LyrStr *t38 = NULL;
bb0:;
#line 72
    t0 = (LyrStr *)&lyr_lit10;
#line 72
    l0_log = t0;
#line 73
    t1 = (int64_t)INT64_C(1);
#line 73
    t2 = (int64_t)INT64_C(6);
#line 73
    l1__range0 = t1;
#line 73
    l2__last1 = t2;
#line 73
    goto bb1;
bb1:;
#line 73
    t3 = l1__range0;
#line 73
    t4 = l2__last1;
#line 73
    t5 = (uint8_t)(t3 < t4);
#line 73
    if (t5) goto bb2; else goto bb4;
bb2:;
#line 73
    l3_i = t3;
#line 75
    t6 = l3_i;
#line 75
    t7 = (int64_t)INT64_C(3);
#line 75
    t8 = (uint8_t)(t6 == t7);
#line 75
    if (t8) goto bb5; else goto bb6;
bb3:;
#line 73
    t33 = l1__range0;
#line 73
    t34 = (int64_t)INT64_C(1);
#line 73
    t35 = LYR_CHECKED_ADD(t33, t34);
#line 73
    l1__range0 = t35;
#line 73
    goto bb1;
bb4:;
#line 80
    t36 = l0_log;
#line 80
    t37 = (LyrStr *)&lyr_lit11;
#line 80
    t38 = lyr_str_concat(t36, t37);
#line 80
    return t38;
bb5:;
#line 75
    t9 = (int64_t)INT64_C(0);
#line 75
    t10 = lyr_alloc_array(&lyr_desc_arr_i64, 1); LYR_ARR_DATA(t10, int64_t)[0] = t9;
#line 75
    t11 = (int64_t)INT64_C(7);
#line 75
    t12 = lyr_main_pick_int__e6b63dd8(t10, t11, &lyr_e);
#line 75
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb7; goto bb8;
bb6:;
#line 76
    t19 = l3_i;
#line 76
    t20 = (int64_t)INT64_C(5);
#line 76
    t21 = (uint8_t)(t19 == t20);
#line 76
    if (t21) goto bb9; else goto bb10;
bb7:;
#line 74
    t28 = lyr_e->value;
#line 78
    t29 = ((*(const LyrDesc *const *)t28.vt) == &lyr_desc_box_ty7_BoxErr_int_);
#line 78
    if (t29) goto bb11; else goto bb12;
bb8:;
#line 75
    l4_x = t12;
#line 75
    t13 = l0_log;
#line 75
    t14 = (LyrStr *)&lyr_lit1;
#line 75
    t15 = l4_x;
#line 75
    t16 = lyr_str_from_int(t15);
#line 75
    t17 = lyr_str_concat(t14, t16);
#line 75
    t18 = lyr_str_concat(t13, t17);
#line 75
    l0_log = t18;
#line 75
    goto bb6;
bb9:;
#line 76
    goto bb4;
bb10:;
#line 77
    t22 = l0_log;
#line 77
    t23 = (LyrStr *)&lyr_lit1;
#line 77
    t24 = l3_i;
#line 77
    t25 = lyr_str_from_int(t24);
#line 77
    t26 = lyr_str_concat(t23, t25);
#line 77
    t27 = lyr_str_concat(t22, t26);
#line 77
    l0_log = t27;
#line 74
    goto bb14;
bb11:;
#line 78
    lyr_e = NULL;
#line 78
    t30 = l0_log;
#line 78
    t31 = (LyrStr *)&lyr_lit12;
#line 78
    t32 = lyr_str_concat(t30, t31);
#line 78
    l0_log = t32;
#line 78
    goto bb3;
bb12:;
#line 74
    goto bb13;
bb13:;
#line 74
    __builtin_unreachable();
bb14:;
#line 73
    goto bb3;
}

#line 83 "programs/error_paths.lyr"
int64_t lyr_main_apply(lyr_fn_i64_to_i64 l0_f, int64_t l1_x) {
    lyr_fn_i64_to_i64 t0 = {0};
    int64_t t1 = 0;
    int64_t t2 = 0;
bb0:;
#line 83
    t0 = l0_f;
#line 83
    t1 = l1_x;
#line 83
    t2 = t0.fn(t0.env, t1, NULL);
#line 83
    return t2;
}

#line 85 "programs/error_paths.lyr"
LyrStr * lyr_main_lambda(void) {
    int64_t l0_r = 0;
    lyr_fn_i64_to_i64 t0 = {0};
    int64_t t1 = 0;
    int64_t t2 = 0;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    LyrStr *t5 = NULL;
    LyrStr *t6 = NULL;
bb0:;
#line 85
    t0 = (lyr_fn_i64_to_i64){ lyr_thunk_main_lambda__lambda0__1c85569e, NULL };
#line 87
    t1 = (int64_t)INT64_C(0);
#line 85
    t2 = lyr_main_apply(t0, t1);
#line 85
    l0_r = t2;
#line 88
    t3 = (LyrStr *)&lyr_lit13;
#line 88
    t4 = l0_r;
#line 88
    t5 = lyr_str_from_int(t4);
#line 88
    t6 = lyr_str_concat(t3, t5);
#line 88
    return t6;
}

#line 92 "programs/error_paths.lyr"
LyrStr * lyr_main_nested(void) {
    LyrStr *l0_log = NULL;
    int64_t l1_x = 0;
    int64_t l2_y = 0;
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    int64_t t1 = 0;
    LyrArr *t2 = NULL;
    int64_t t3 = 0;
    int64_t t4 = 0;
    LyrStr *t5 = NULL;
    LyrStr *t6 = NULL;
    int64_t t7 = 0;
    LyrStr *t8 = NULL;
    LyrStr *t9 = NULL;
    LyrStr *t10 = NULL;
    LyrIface t11 = {0};
    uint8_t t12 = 0;
    int64_t t13 = 0;
    LyrArr *t14 = NULL;
    int64_t t15 = 0;
    int64_t t16 = 0;
    LyrStr *t17 = NULL;
    LyrStr *t18 = NULL;
    int64_t t19 = 0;
    LyrStr *t20 = NULL;
    LyrStr *t21 = NULL;
    LyrStr *t22 = NULL;
    LyrIface t23 = {0};
    uint8_t t24 = 0;
    LyrStr *t25 = NULL;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    LyrStr *t28 = NULL;
bb0:;
#line 92
    t0 = (LyrStr *)&lyr_lit14;
#line 92
    l0_log = t0;
#line 94
    t1 = (int64_t)INT64_C(1);
#line 94
    t2 = lyr_alloc_array(&lyr_desc_arr_i64, 1); LYR_ARR_DATA(t2, int64_t)[0] = t1;
#line 94
    t3 = (int64_t)INT64_C(3);
#line 94
    t4 = lyr_main_pick_int__e6b63dd8(t2, t3, &lyr_e);
#line 94
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 93
    t11 = lyr_e->value;
#line 96
    t12 = ((*(const LyrDesc *const *)t11.vt) == &lyr_desc_box_ty7_BoxErr_int_);
#line 96
    if (t12) goto bb3; else goto bb4;
bb2:;
#line 94
    l1_x = t4;
#line 95
    t5 = l0_log;
#line 95
    t6 = (LyrStr *)&lyr_lit1;
#line 95
    t7 = l1_x;
#line 95
    t8 = lyr_str_from_int(t7);
#line 95
    t9 = lyr_str_concat(t6, t8);
#line 95
    t10 = lyr_str_concat(t5, t9);
#line 95
    l0_log = t10;
#line 93
    goto bb11;
bb3:;
#line 96
    lyr_e = NULL;
#line 97
    t13 = (int64_t)INT64_C(1);
#line 97
    t14 = lyr_alloc_array(&lyr_desc_arr_i64, 1); LYR_ARR_DATA(t14, int64_t)[0] = t13;
#line 97
    t15 = (int64_t)INT64_C(4);
#line 97
    t16 = lyr_main_pick_int__e6b63dd8(t14, t15, &lyr_e);
#line 97
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb5; goto bb6;
bb4:;
#line 93
    goto bb9;
bb5:;
#line 97
    t23 = lyr_e->value;
#line 98
    t24 = ((*(const LyrDesc *const *)t23.vt) == &lyr_desc_box_ty7_BoxErr_int_);
#line 98
    if (t24) goto bb7; else goto bb8;
bb6:;
#line 97
    l2_y = t16;
#line 97
    t17 = l0_log;
#line 97
    t18 = (LyrStr *)&lyr_lit1;
#line 97
    t19 = l2_y;
#line 97
    t20 = lyr_str_from_int(t19);
#line 97
    t21 = lyr_str_concat(t18, t20);
#line 97
    t22 = lyr_str_concat(t17, t21);
#line 97
    l0_log = t22;
#line 97
    goto bb10;
bb7:;
#line 98
    lyr_e = NULL;
#line 98
    t25 = l0_log;
#line 98
    t26 = (LyrStr *)&lyr_lit15;
#line 98
    t27 = lyr_str_concat(t25, t26);
#line 98
    l0_log = t27;
#line 97
    goto bb10;
bb8:;
#line 97
    goto bb9;
bb9:;
#line 97
    __builtin_unreachable();
bb10:;
#line 93
    goto bb11;
bb11:;
#line 100
    t28 = l0_log;
#line 100
    return t28;
}

#line 105 "programs/error_paths.lyr"
int64_t lyr_main_clauseReturn(void) {
    lyr_ty7_BoxErr_int_ l0_e = {0};
    LyrErr *lyr_e = NULL;
    int64_t t0 = 0;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    int64_t t3 = 0;
    LyrStr *t4 = NULL;
    LyrIface t5 = {0};
    uint8_t t6 = 0;
    lyr_ty7_BoxErr_int_ t7_s = {0};
    lyr_ty7_BoxErr_int_ *t7 = &t7_s;
    int64_t t8 = 0;
    lyr_ty7_BoxErr_int_ t9_s = {0};
    lyr_ty7_BoxErr_int_ *t9 = &t9_s;
    int64_t t10 = 0;
    int64_t t11 = 0;
    LyrStr *t12 = NULL;
    LyrStr *t13 = NULL;
bb0:;
#line 105
    t0 = (int64_t)INT64_C(1);
#line 105
    t1 = lyr_alloc_array(&lyr_desc_arr_i64, 1); LYR_ARR_DATA(t1, int64_t)[0] = t0;
#line 105
    t2 = (int64_t)INT64_C(2);
#line 105
    t3 = lyr_main_pick_int__e6b63dd8(t1, t2, &lyr_e);
#line 105
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 105
    t5 = lyr_e->value;
#line 105
    t6 = ((*(const LyrDesc *const *)t5.vt) == &lyr_desc_box_ty7_BoxErr_int_);
#line 105
    if (t6) goto bb3; else goto bb4;
bb2:;
#line 104
    t4 = (LyrStr *)&lyr_lit16;
#line 104
    lyr_println(t4);
#line 105
    return t3;
bb3:;
#line 105
    lyr_e = NULL;
#line 105
    t7_s = ((lyr_box_ty7_BoxErr_int_ *)t5.data)->value; t7 = &t7_s;
#line 105
    l0_e = *t7;
#line 105
    t8 = (int64_t)INT64_C(40);
#line 105
    t9 = &l0_e;
#line 105
    t10 = t9->f_v;
#line 105
    t11 = LYR_CHECKED_ADD(t8, t10);
#line 104
    t12 = (LyrStr *)&lyr_lit16;
#line 104
    lyr_println(t12);
#line 105
    return t11;
bb4:;
#line 105
    goto bb5;
bb5:;
#line 104
    t13 = (LyrStr *)&lyr_lit16;
#line 104
    lyr_println(t13);
#line 105
    goto bb6;
bb6:;
#line 105
    __builtin_unreachable();
}

#line 109 "programs/error_paths.lyr"
int64_t lyr_main_main(void) {
    LyrStr *t0 = NULL;
    LyrStr *t1 = NULL;
    LyrStr *t2 = NULL;
    LyrStr *t3 = NULL;
    LyrStr *t4 = NULL;
    LyrStr *t5 = NULL;
    LyrStr *t6 = NULL;
    LyrStr *t7 = NULL;
    int64_t t8 = 0;
    LyrStr *t9 = NULL;
    LyrStr *t10 = NULL;
    int64_t t11 = 0;
bb0:;
#line 109
    t0 = lyr_main_slot();
#line 109
    lyr_println(t0);
#line 110
    t1 = lyr_main_method();
#line 110
    lyr_println(t1);
#line 111
    t2 = lyr_main_generic();
#line 111
    lyr_println(t2);
#line 112
    t3 = lyr_main_chain();
#line 112
    lyr_println(t3);
#line 113
    t4 = lyr_main_loop();
#line 113
    lyr_println(t4);
#line 114
    t5 = lyr_main_lambda();
#line 114
    lyr_println(t5);
#line 115
    t6 = lyr_main_nested();
#line 115
    lyr_println(t6);
#line 116
    t7 = (LyrStr *)&lyr_lit17;
#line 116
    t8 = lyr_main_clauseReturn();
#line 116
    t9 = lyr_str_from_int(t8);
#line 116
    t10 = lyr_str_concat(t7, t9);
#line 116
    lyr_println(t10);
#line 117
    t11 = (int64_t)INT64_C(0);
#line 117
    return t11;
}

#line 7 "programs/error_paths.lyr"
LyrStr * lyr_main_Bad_message(lyr_ty4_Bad *l0_this) {
    LyrStr *t0 = NULL;
bb0:;
#line 7
    t0 = (LyrStr *)&lyr_lit18;
#line 7
    return t0;
}

#line 11 "programs/error_paths.lyr"
int64_t lyr_main_Good_read(lyr_ty1_Good *l0_this, int64_t l1_n) {
    int64_t t0 = 0;
bb0:;
#line 11
    t0 = l1_n;
#line 11
    return t0;
}

#line 12 "programs/error_paths.lyr"
int64_t lyr_main_Fails_read(lyr_ty2_Fails *l0_this, int64_t l1_n, LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    lyr_ty4_Bad t0_s = {0};
    lyr_ty4_Bad *t0 = &t0_s;
    LyrIface t1 = {0};
bb0:;
#line 12
    t0_s = (lyr_ty4_Bad){ .tag = 0 }; t0 = &t0_s;
#line 12
    { lyr_box_ty4_Bad *lyr_box = lyr_alloc(&lyr_desc_box_ty4_Bad); lyr_box->value = *t0; t1 = (LyrIface){ lyr_box, &lyr_vt_ty3_ty4 }; }
#line 12
    lyr_e = lyr_err_new(t1); goto bb1;
bb1:;
#line 12
    *lyr_err = lyr_e; return 0;
}

#line 27 "programs/error_paths.lyr"
int64_t lyr_main_Counter_bump(lyr_ty6_Counter *l0_this, int64_t l1_limit, LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    lyr_ty6_Counter t0_s = {0};
    lyr_ty6_Counter *t0 = &t0_s;
    int64_t t1 = 0;
    int64_t t2 = 0;
    int64_t t3 = 0;
    lyr_ty6_Counter t4_s = {0};
    lyr_ty6_Counter *t4 = &t4_s;
    int64_t t5 = 0;
    int64_t t6 = 0;
    uint8_t t7 = 0;
    lyr_ty4_Bad t8_s = {0};
    lyr_ty4_Bad *t8 = &t8_s;
    LyrIface t9 = {0};
    lyr_ty6_Counter t10_s = {0};
    lyr_ty6_Counter *t10 = &t10_s;
    int64_t t11 = 0;
bb0:;
#line 27
    t0 = l0_this;
#line 27
    t1 = t0->f_n;
#line 27
    t2 = (int64_t)INT64_C(1);
#line 27
    t3 = LYR_CHECKED_ADD(t1, t2);
#line 27
    t0->f_n = t3;
#line 28
    t4 = l0_this;
#line 28
    t5 = t4->f_n;
#line 28
    t6 = l1_limit;
#line 28
    t7 = (uint8_t)(t5 > t6);
#line 28
    if (t7) goto bb1; else goto bb2;
bb1:;
#line 28
    t8_s = (lyr_ty4_Bad){ .tag = 0 }; t8 = &t8_s;
#line 28
    { lyr_box_ty4_Bad *lyr_box = lyr_alloc(&lyr_desc_box_ty4_Bad); lyr_box->value = *t8; t9 = (LyrIface){ lyr_box, &lyr_vt_ty3_ty4 }; }
#line 28
    lyr_e = lyr_err_new(t9); goto bb3;
bb2:;
#line 29
    t10 = l0_this;
#line 29
    t11 = t10->f_n;
#line 29
    return t11;
bb3:;
#line 28
    *lyr_err = lyr_e; return 0;
}

#line 86 "stdlib5/std/core.lyr"
lyr_opt_iface3 lyr_std_core_Error_cause(LyrIface l0_this) {
    lyr_opt_iface3 t0_s = {0};
    lyr_opt_iface3 *t0 = &t0_s;
bb0:;
#line 86
    t0_s = (lyr_opt_iface3){0}; t0 = &t0_s;
#line 86
    return *t0;
}

#line 86 "programs/error_paths.lyr"
int64_t lyr_main_lambda__lambda0__1c85569e(int64_t l0_x) {
    LyrErr *lyr_e = NULL;
    int64_t t0 = 0;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    int64_t t3 = 0;
    LyrIface t4 = {0};
    uint8_t t5 = 0;
    int64_t t6 = 0;
bb0:;
#line 86
    t0 = (int64_t)INT64_C(9);
#line 86
    t1 = lyr_alloc_array(&lyr_desc_arr_i64, 1); LYR_ARR_DATA(t1, int64_t)[0] = t0;
#line 86
    t2 = l0_x;
#line 86
    t3 = lyr_main_pick_int__e6b63dd8(t1, t2, &lyr_e);
#line 86
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 86
    t4 = lyr_e->value;
#line 86
    t5 = ((*(const LyrDesc *const *)t4.vt) == &lyr_desc_box_ty7_BoxErr_int_);
#line 86
    if (t5) goto bb3; else goto bb4;
bb2:;
#line 86
    return t3;
bb3:;
#line 86
    lyr_e = NULL;
#line 86
    t6 = (int64_t)INT64_C(-1);
#line 86
    return t6;
bb4:;
#line 86
    goto bb5;
bb5:;
#line 86
    __builtin_unreachable();
}


/* the program */
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_main_main); }

/* ==== unit: main.BoxErr<int> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'main.BoxErr<int>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty7_BoxErr_int_ lyr_ty7_BoxErr_int_;
struct lyr_ty7_BoxErr_int_ {
    int64_t f_v;
};

/* string literals */
static const LyrStaticStr(4) lyr_lit0 = LYR_STR_INIT("Box");

/* prototypes */
LyrStr * lyr_main_BoxErr_int__message_e630ecb2(lyr_ty7_BoxErr_int_ *l0_this);

#line 8 "programs/error_paths.lyr"
LyrStr * lyr_main_BoxErr_int__message_e630ecb2(lyr_ty7_BoxErr_int_ *l0_this) {
    LyrStr *t0 = NULL;
bb0:;
#line 8
    t0 = (LyrStr *)&lyr_lit0;
#line 8
    return t0;
}


/* ==== unit: main.pick<int> ==== */
/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
/* The unit of the generic instance 'main.pick<int>' (01 C3): its functions, the types they reach, and nothing else. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_vt_ty3 lyr_vt_ty3;
extern const char lyr_ifid_ty3[];
typedef struct lyr_ty7_BoxErr_int_ lyr_ty7_BoxErr_int_;
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface3;
struct lyr_vt_ty3 {
    const LyrDesc *desc;
    LyrStr * (*s0)(LyrIface);
    lyr_opt_iface3 (*s1)(LyrIface);
};
struct lyr_ty7_BoxErr_int_ {
    int64_t f_v;
};
_Static_assert(sizeof(int64_t) == 8, "layout of int[]");
extern const LyrDesc lyr_desc_arr_i64;
typedef struct { LyrObj header; lyr_ty7_BoxErr_int_ value; } lyr_box_ty7_BoxErr_int_;
_Static_assert(sizeof(lyr_box_ty7_BoxErr_int_) == 16, "layout of lyr_box_ty7_BoxErr_int_");
_Static_assert(offsetof(lyr_box_ty7_BoxErr_int_, value) == 8, "layout of lyr_box_ty7_BoxErr_int_");
extern const LyrDesc lyr_desc_box_ty7_BoxErr_int_;

/* prototypes */
int64_t lyr_main_pick_int__e6b63dd8(LyrArr *l0_xs, int64_t l1_i, LyrErr **lyr_err);

/* interface tables, defined by the module's unit */
extern const lyr_vt_ty3 lyr_vt_ty3_ty7;

#line 43 "programs/error_paths.lyr"
int64_t lyr_main_pick_int__e6b63dd8(LyrArr *l0_xs, int64_t l1_i, LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    int64_t t0 = 0;
    LyrArr *t1 = NULL;
    int64_t t2 = 0;
    uint8_t t3 = 0;
    int64_t t4 = 0;
    lyr_ty7_BoxErr_int_ t5_s = {0};
    lyr_ty7_BoxErr_int_ *t5 = &t5_s;
    LyrIface t6 = {0};
    LyrArr *t7 = NULL;
    int64_t t8 = 0;
    int64_t t9 = 0;
bb0:;
#line 43
    t0 = l1_i;
#line 43
    t1 = l0_xs;
#line 43
    t2 = t1->len;
#line 43
    t3 = (uint8_t)(t0 >= t2);
#line 43
    if (t3) goto bb1; else goto bb2;
bb1:;
#line 43
    t4 = l1_i;
#line 43
    t5_s = (lyr_ty7_BoxErr_int_){0}; t5 = &t5_s;
#line 43
    t5->f_v = t4;
#line 43
    { lyr_box_ty7_BoxErr_int_ *lyr_box = lyr_alloc(&lyr_desc_box_ty7_BoxErr_int_); lyr_box->value = *t5; t6 = (LyrIface){ lyr_box, &lyr_vt_ty3_ty7 }; }
#line 43
    lyr_e = lyr_err_new(t6); goto bb3;
bb2:;
#line 44
    t7 = l0_xs;
#line 44
    t8 = l1_i;
#line 44
    LYR_CHECK_INDEX(t8, t7->len); t9 = LYR_ARR_DATA(t7, int64_t)[t8];
#line 44
    return t9;
bb3:;
#line 43
    *lyr_err = lyr_e; return 0;
}

