/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty0_Scheduler lyr_ty0_Scheduler;
typedef struct lyr_ty1_Context lyr_ty1_Context;
typedef struct lyr_ty2_Waiters lyr_ty2_Waiters;
typedef struct lyr_ty3_TaskScope lyr_ty3_TaskScope;
typedef struct lyr_vt_ty4 lyr_vt_ty4;
const char lyr_ifid_ty4[] = "std.core.Error";
typedef struct lyr_ty5_Cancelled lyr_ty5_Cancelled;
typedef struct lyr_ty6_Oops lyr_ty6_Oops;
typedef struct lyr_ty7_Oops_Bad lyr_ty7_Oops_Bad;
typedef struct lyr_ty8_Exception lyr_ty8_Exception;
typedef struct lyr_ty9_Duration lyr_ty9_Duration;
typedef struct lyr_ty10__env_std_task_spawnDetached_ lyr_ty10__env_std_task_spawnDetached_;
struct lyr_ty0_Scheduler {
    LyrObj header;
    lyr_ty1_Context *f_first;
    lyr_ty1_Context *f_last;
    lyr_ty1_Context *f_sleepers;
    int64_t f_fallenAsleep;
    lyr_ty1_Context *f_running;
};
_Static_assert(sizeof(lyr_ty0_Scheduler) == 48, "layout of lyr_ty0_Scheduler");
_Static_assert(offsetof(lyr_ty0_Scheduler, f_first) == 8, "layout of lyr_ty0_Scheduler");
_Static_assert(offsetof(lyr_ty0_Scheduler, f_last) == 16, "layout of lyr_ty0_Scheduler");
_Static_assert(offsetof(lyr_ty0_Scheduler, f_sleepers) == 24, "layout of lyr_ty0_Scheduler");
_Static_assert(offsetof(lyr_ty0_Scheduler, f_fallenAsleep) == 32, "layout of lyr_ty0_Scheduler");
_Static_assert(offsetof(lyr_ty0_Scheduler, f_running) == 40, "layout of lyr_ty0_Scheduler");
static const uint64_t lyr_refmap_ty0[] = { UINT64_C(0x2e) };
const LyrDesc lyr_desc_ty0_Scheduler = { sizeof(lyr_ty0_Scheduler), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty0, "std.task.Scheduler", NULL };
struct lyr_ty1_Context {
    LyrObj header;
    LyrCoro *f_body;
    lyr_ty1_Context *f_next;
    lyr_ty1_Context *f_prev;
    lyr_ty2_Waiters *f_waitingOn;
    uint8_t f_asleep;
    int64_t f_deadline;
    int64_t f_order;
    lyr_ty1_Context *f_left;
    lyr_ty1_Context *f_right;
    lyr_ty1_Context *f_up;
    int64_t f_rank;
    uint8_t f_cancelled;
    lyr_ty3_TaskScope *f_scope;
    lyr_ty1_Context *f_nextChild;
    lyr_ty1_Context *f_prevChild;
};
_Static_assert(sizeof(lyr_ty1_Context) == 128, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_body) == 8, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_next) == 16, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_prev) == 24, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_waitingOn) == 32, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_asleep) == 40, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_deadline) == 48, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_order) == 56, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_left) == 64, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_right) == 72, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_up) == 80, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_rank) == 88, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_cancelled) == 96, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_scope) == 104, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_nextChild) == 112, "layout of lyr_ty1_Context");
_Static_assert(offsetof(lyr_ty1_Context, f_prevChild) == 120, "layout of lyr_ty1_Context");
static const uint64_t lyr_refmap_ty1[] = { UINT64_C(0xe71e) };
const LyrDesc lyr_desc_ty1_Context = { sizeof(lyr_ty1_Context), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty1, "std.task.Context", NULL };
struct lyr_ty2_Waiters {
    LyrObj header;
    lyr_ty1_Context *f_first;
    lyr_ty1_Context *f_last;
};
_Static_assert(sizeof(lyr_ty2_Waiters) == 24, "layout of lyr_ty2_Waiters");
_Static_assert(offsetof(lyr_ty2_Waiters, f_first) == 8, "layout of lyr_ty2_Waiters");
_Static_assert(offsetof(lyr_ty2_Waiters, f_last) == 16, "layout of lyr_ty2_Waiters");
static const uint64_t lyr_refmap_ty2[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty2_Waiters = { sizeof(lyr_ty2_Waiters), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty2, "std.task.Waiters", NULL };
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface4;
struct lyr_vt_ty4 {
    const LyrDesc *desc;
    LyrStr * (*s0)(LyrIface);
    lyr_opt_iface4 (*s1)(LyrIface);
};
struct lyr_ty3_TaskScope {
    LyrObj header;
    lyr_ty1_Context *f_firstChild;
    lyr_ty1_Context *f_lastChild;
    int64_t f_open;
    lyr_opt_iface4 f_failure;
    lyr_ty2_Waiters *f_closing;
};
_Static_assert(sizeof(lyr_ty3_TaskScope) == 64, "layout of lyr_ty3_TaskScope");
_Static_assert(offsetof(lyr_ty3_TaskScope, f_firstChild) == 8, "layout of lyr_ty3_TaskScope");
_Static_assert(offsetof(lyr_ty3_TaskScope, f_lastChild) == 16, "layout of lyr_ty3_TaskScope");
_Static_assert(offsetof(lyr_ty3_TaskScope, f_open) == 24, "layout of lyr_ty3_TaskScope");
_Static_assert(offsetof(lyr_ty3_TaskScope, f_failure) == 32, "layout of lyr_ty3_TaskScope");
_Static_assert(offsetof(lyr_ty3_TaskScope, f_closing) == 56, "layout of lyr_ty3_TaskScope");
static const uint64_t lyr_refmap_ty3[] = { UINT64_C(0x96) };
const LyrDesc lyr_desc_ty3_TaskScope = { sizeof(lyr_ty3_TaskScope), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty3, "std.task.TaskScope", NULL };
struct lyr_ty5_Cancelled {
    LyrObj header;
};
_Static_assert(sizeof(lyr_ty5_Cancelled) == 8, "layout of lyr_ty5_Cancelled");
extern const LyrItable lyr_itab_ty5[];
const LyrDesc lyr_desc_ty5_Cancelled = { sizeof(lyr_ty5_Cancelled), 0, 0, 0, NULL, "std.task.Cancelled", lyr_itab_ty5 };
struct lyr_ty7_Oops_Bad {
    uint8_t lyr_unit;
};
struct lyr_ty6_Oops { uint32_t tag; };
_Static_assert(sizeof(lyr_ty6_Oops) == 4, "layout of lyr_ty6_Oops");
struct lyr_ty8_Exception {
    LyrObj header;
    LyrStr *f_text;
    lyr_opt_iface4 f_inner;
};
_Static_assert(sizeof(lyr_ty8_Exception) == 40, "layout of lyr_ty8_Exception");
_Static_assert(offsetof(lyr_ty8_Exception, f_text) == 8, "layout of lyr_ty8_Exception");
_Static_assert(offsetof(lyr_ty8_Exception, f_inner) == 16, "layout of lyr_ty8_Exception");
static const uint64_t lyr_refmap_ty8[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty8_Exception = { sizeof(lyr_ty8_Exception), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty8, "std.core.Exception", NULL };
struct lyr_ty9_Duration {
    int64_t f_ns;
};
typedef struct { void (*fn)(void *, LyrErr **); void *env; } lyr_fn_to_void;
_Static_assert(sizeof(lyr_fn_to_void) == 16, "layout of lyr_fn_to_void");
struct lyr_ty10__env_std_task_spawnDetached_ {
    LyrObj header;
    lyr_fn_to_void f_body;
};
_Static_assert(sizeof(lyr_ty10__env_std_task_spawnDetached_) == 24, "layout of lyr_ty10__env_std_task_spawnDetached_");
_Static_assert(offsetof(lyr_ty10__env_std_task_spawnDetached_, f_body) == 8, "layout of lyr_ty10__env_std_task_spawnDetached_");
static const uint64_t lyr_refmap_ty10[] = { UINT64_C(0x4) };
const LyrDesc lyr_desc_ty10__env_std_task_spawnDetached_ = { sizeof(lyr_ty10__env_std_task_spawnDetached_), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty10, "<env:std.task.spawnDetached>", NULL };
typedef struct { int64_t value; uint8_t has; } lyr_opt_i64;
typedef struct { LyrObj header; lyr_ty6_Oops value; } lyr_box_ty6_Oops;
_Static_assert(sizeof(lyr_box_ty6_Oops) == 16, "layout of lyr_box_ty6_Oops");
_Static_assert(offsetof(lyr_box_ty6_Oops, value) == 8, "layout of lyr_box_ty6_Oops");
extern const LyrItable lyr_itab_ty6[];
const LyrDesc lyr_desc_box_ty6_Oops = { sizeof(lyr_box_ty6_Oops), 0, 0, 0, NULL, "box<Oops>", lyr_itab_ty6 };

/* string literals */
static const LyrStaticStr(2) lyr_lit0 = LYR_STR_INIT("w");
static const LyrStaticStr(6) lyr_lit1 = LYR_STR_INIT("walk ");
static const LyrStaticStr(2) lyr_lit2 = LYR_STR_INIT(" ");
static const LyrStaticStr(7) lyr_lit3 = LYR_STR_INIT(" done ");
static const LyrStaticStr(7) lyr_lit4 = LYR_STR_INIT(" next ");
static const LyrStaticStr(6) lyr_lit5 = LYR_STR_INIT("fresh");
static const LyrStaticStr(7) lyr_lit6 = LYR_STR_INIT("fresh ");
static const LyrStaticStr(5) lyr_lit7 = LYR_STR_INIT("none");
static const LyrStaticStr(9) lyr_lit8 = LYR_STR_INIT("careful ");
static const LyrStaticStr(2) lyr_lit9 = LYR_STR_INIT("u");
static const LyrStaticStr(7) lyr_lit10 = LYR_STR_INIT("using ");
static const LyrStaticStr(13) lyr_lit11 = LYR_STR_INIT("not reached ");
static const LyrStaticStr(13) lyr_lit12 = LYR_STR_INIT("close threw ");
static const LyrStaticStr(7) lyr_lit13 = LYR_STR_INIT("again ");
static const LyrStaticStr(19) lyr_lit14 = LYR_STR_INIT("not reached either");
static const LyrStaticStr(5) lyr_lit15 = LYR_STR_INIT("oops");
static const LyrStaticStr(10) lyr_lit16 = LYR_STR_INIT("cancelled");
static const LyrStaticStr(10) lyr_lit17 = LYR_STR_INIT(": cleaned");
static const LyrStaticStr(26) lyr_lit18 = LYR_STR_INIT("careful: caught cancelled");
static const LyrStaticStr(8) lyr_lit19 = LYR_STR_INIT("stopped");
static const LyrStaticStr(8) lyr_lit20 = LYR_STR_INIT("ran out");

/* prototypes */
LyrCoro * lyr_main_walk(LyrStr *l0_name);
LyrCoro * lyr_main_careful(void);
LyrCoro * lyr_main_angry(void);
int64_t lyr_main_main(void);
LyrStr * lyr_main_Oops_message(lyr_ty6_Oops *l0_this);
lyr_opt_iface4 lyr_std_core_Error_cause(LyrIface l0_this);
LyrStr * lyr_std_task_Cancelled_message(lyr_ty5_Cancelled *l0_this);
void lyr_main_walk__body__1e9ceef5(LyrStr *l0_name, LyrErr **lyr_err);
LyrStr * lyr_main_careful__body__df091f8a(LyrErr **lyr_err);
void lyr_main_angry__body__5d538b59(LyrErr **lyr_err);

/* coroutines: the environment a body starts from, and the body as the runtime runs it */
static const LyrDesc lyr_desc_coro_i64_to_void = { 0, 0, 0, 0, NULL, "Coroutine<int>", NULL };
static const LyrDesc lyr_desc_coro_i64_to_str = { 0, 0, 0, 0, NULL, "Coroutine<int, string>", NULL };
typedef struct { LyrObj header; LyrStr *a0; } lyr_coenv7;
_Static_assert(sizeof(lyr_coenv7) == 16, "layout of lyr_coenv7");
_Static_assert(offsetof(lyr_coenv7, a0) == 8, "layout of lyr_coenv7");
static const uint64_t lyr_coenv7_refmap[] = { UINT64_C(0x2) };
static const LyrDesc lyr_coenv7_desc = { sizeof(lyr_coenv7), LYR_DESC_HAS_REFS, 0, 1, lyr_coenv7_refmap, "main.walk.<body>", NULL };
static void lyr_corun7(void *lyr_arg) { lyr_coenv7 *lyr_env = lyr_arg; LyrErr *lyr_e = NULL; lyr_main_walk__body__1e9ceef5(lyr_env->a0, &lyr_e); LyrCoro *lyr_co = lyr_coro_current(); if (LYR_UNLIKELY(lyr_e != NULL)) { lyr_coro_set_error(lyr_co, lyr_e); lyr_coro_set_transfer(lyr_co, NULL); return; } lyr_coro_set_transfer(lyr_co, NULL); }
typedef struct { LyrObj header; LyrStr *result; } lyr_coenv8;
_Static_assert(sizeof(lyr_coenv8) == 16, "layout of lyr_coenv8");
_Static_assert(offsetof(lyr_coenv8, result) == 8, "layout of lyr_coenv8");
static const uint64_t lyr_coenv8_refmap[] = { UINT64_C(0x2) };
static const LyrDesc lyr_coenv8_desc = { sizeof(lyr_coenv8), LYR_DESC_HAS_REFS, 0, 1, lyr_coenv8_refmap, "main.careful.<body>", NULL };
static void lyr_corun8(void *lyr_arg) { lyr_coenv8 *lyr_env = lyr_arg; LyrErr *lyr_e = NULL; LyrStr *lyr_r = lyr_main_careful__body__df091f8a(&lyr_e); LyrCoro *lyr_co = lyr_coro_current(); if (LYR_UNLIKELY(lyr_e != NULL)) { lyr_coro_set_error(lyr_co, lyr_e); lyr_coro_set_transfer(lyr_co, NULL); return; } LYR_WRITE_BARRIER(lyr_env, &lyr_env->result, lyr_r); lyr_coro_set_transfer(lyr_co, &lyr_env->result); }
static void lyr_corun9(void *lyr_arg) { (void)lyr_arg; LyrErr *lyr_e = NULL; lyr_main_angry__body__5d538b59(&lyr_e); LyrCoro *lyr_co = lyr_coro_current(); if (LYR_UNLIKELY(lyr_e != NULL)) { lyr_coro_set_error(lyr_co, lyr_e); lyr_coro_set_transfer(lyr_co, NULL); return; } lyr_coro_set_transfer(lyr_co, NULL); }

/* interface tables: the descriptor, then the implementation of every slot */
static LyrStr * lyr_vt_ty4_ty5_s0(LyrIface self) { return lyr_std_task_Cancelled_message((lyr_ty5_Cancelled *)self.data); }
const lyr_vt_ty4 lyr_vt_ty4_ty5 = { &lyr_desc_ty5_Cancelled, lyr_vt_ty4_ty5_s0, lyr_std_core_Error_cause };
static LyrStr * lyr_vt_ty4_ty6_s0(LyrIface self) { return lyr_main_Oops_message(&((lyr_box_ty6_Oops *)self.data)->value); }
const lyr_vt_ty4 lyr_vt_ty4_ty6 = { &lyr_desc_box_ty6_Oops, lyr_vt_ty4_ty6_s0, lyr_std_core_Error_cause };
const LyrItable lyr_itab_ty5[] = { { lyr_ifid_ty4, &lyr_vt_ty4_ty5 } , { NULL, NULL } };
const LyrItable lyr_itab_ty6[] = { { lyr_ifid_ty4, &lyr_vt_ty4_ty6 } , { NULL, NULL } };

#line 20 "programs/generators_close.lyr"
LyrCoro * lyr_main_walk(LyrStr *l0_name) {
    LyrStr *t0 = NULL;
    LyrCoro *t1 = NULL;
bb0:;
#line 20
    t0 = l0_name;
#line 20
    { lyr_coenv7 *lyr_ce = lyr_alloc(&lyr_coenv7_desc); LYR_WRITE_BARRIER(lyr_ce, &lyr_ce->a0, t0); t1 = lyr_coro_new(&lyr_desc_coro_i64_to_void, lyr_corun7, lyr_ce, 0); } lyr_coro_set_cleanup(t1);
#line 20
    return t1;
}

#line 29 "programs/generators_close.lyr"
LyrCoro * lyr_main_careful(void) {
    LyrCoro *t0 = NULL;
bb0:;
#line 29
    { lyr_coenv8 *lyr_ce = lyr_alloc(&lyr_coenv8_desc); t0 = lyr_coro_new(&lyr_desc_coro_i64_to_str, lyr_corun8, lyr_ce, 0); }
#line 29
    return t0;
}

#line 40 "programs/generators_close.lyr"
LyrCoro * lyr_main_angry(void) {
    LyrCoro *t0 = NULL;
bb0:;
#line 40
    t0 = lyr_coro_new(&lyr_desc_coro_i64_to_void, lyr_corun9, NULL, 0);
#line 40
    return t0;
}

#line 49 "programs/generators_close.lyr"
int64_t lyr_main_main(void) {
    LyrCoro *l0_w = NULL;
    int64_t l1_a = 0;
    int64_t l2_b = 0;
    lyr_opt_i64 l3_after = {0};
    LyrCoro *l4_fresh = NULL;
    LyrCoro *l5_c = NULL;
    int64_t l6_c1 = 0;
    LyrStr *l7_r = NULL;
    LyrStr *l8__coalesce0 = NULL;
    LyrCoro *l9_u = NULL;
    int64_t l10_u0 = 0;
    LyrCoro *l11_x = NULL;
    int64_t l12_v = 0;
    int64_t l13__coalesce1 = 0;
    lyr_ty6_Oops l14_e = {0};
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    LyrCoro *t1 = NULL;
    LyrCoro *t2 = NULL;
    lyr_opt_i64 t3_s = {0};
    lyr_opt_i64 *t3 = &t3_s;
    int64_t t4 = 0;
    LyrCoro *t5 = NULL;
    lyr_opt_i64 t6_s = {0};
    lyr_opt_i64 *t6 = &t6_s;
    int64_t t7 = 0;
    LyrCoro *t8 = NULL;
    LyrCoro *t9 = NULL;
    lyr_opt_i64 t10_s = {0};
    lyr_opt_i64 *t10 = &t10_s;
    LyrStr *t11 = NULL;
    int64_t t12 = 0;
    LyrStr *t13 = NULL;
    LyrStr *t14 = NULL;
    int64_t t15 = 0;
    LyrStr *t16 = NULL;
    LyrStr *t17 = NULL;
    LyrCoro *t18 = NULL;
    uint8_t t19 = 0;
    LyrStr *t20 = NULL;
    LyrStr *t21 = NULL;
    lyr_opt_i64 t22_s = {0};
    lyr_opt_i64 *t22 = &t22_s;
    uint8_t t23 = 0;
    uint8_t t24 = 0;
    LyrStr *t25 = NULL;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    LyrStr *t28 = NULL;
    LyrStr *t29 = NULL;
    LyrStr *t30 = NULL;
    LyrStr *t31 = NULL;
    LyrStr *t32 = NULL;
    LyrStr *t33 = NULL;
    LyrCoro *t34 = NULL;
    LyrCoro *t35 = NULL;
    LyrStr *t36 = NULL;
    LyrCoro *t37 = NULL;
    uint8_t t38 = 0;
    LyrStr *t39 = NULL;
    LyrStr *t40 = NULL;
    LyrCoro *t41 = NULL;
    LyrCoro *t42 = NULL;
    lyr_opt_i64 t43_s = {0};
    lyr_opt_i64 *t43 = &t43_s;
    int64_t t44 = 0;
    LyrCoro *t45 = NULL;
    LyrCoro *t46 = NULL;
    LyrStr *t47 = NULL;
    uint8_t t48 = 0;
    LyrStr *t49 = NULL;
    LyrStr *t50 = NULL;
    LyrStr *t51 = NULL;
    LyrStr *t52 = NULL;
    int64_t t53 = 0;
    LyrStr *t54 = NULL;
    LyrStr *t55 = NULL;
    LyrStr *t56 = NULL;
    LyrStr *t57 = NULL;
    LyrStr *t58 = NULL;
    LyrStr *t59 = NULL;
    LyrStr *t60 = NULL;
    LyrCoro *t61 = NULL;
    LyrCoro *t62 = NULL;
    lyr_opt_i64 t63_s = {0};
    lyr_opt_i64 *t63 = &t63_s;
    int64_t t64 = 0;
    LyrStr *t65 = NULL;
    int64_t t66 = 0;
    LyrStr *t67 = NULL;
    LyrStr *t68 = NULL;
    LyrCoro *t69 = NULL;
    LyrCoro *t70 = NULL;
    LyrCoro *t71 = NULL;
    lyr_opt_i64 t72_s = {0};
    lyr_opt_i64 *t72 = &t72_s;
    uint8_t t73 = 0;
    int64_t t74 = 0;
    int64_t t75 = 0;
    int64_t t76 = 0;
    LyrCoro *t77 = NULL;
    LyrStr *t78 = NULL;
    int64_t t79 = 0;
    LyrStr *t80 = NULL;
    LyrStr *t81 = NULL;
    LyrIface t82 = {0};
    uint8_t t83 = 0;
    lyr_ty6_Oops t84_s = {0};
    lyr_ty6_Oops *t84 = &t84_s;
    LyrStr *t85 = NULL;
    lyr_ty6_Oops t86_s = {0};
    lyr_ty6_Oops *t86 = &t86_s;
    LyrStr *t87 = NULL;
    LyrStr *t88 = NULL;
    LyrCoro *t89 = NULL;
    LyrStr *t90 = NULL;
    LyrCoro *t91 = NULL;
    uint8_t t92 = 0;
    LyrStr *t93 = NULL;
    LyrStr *t94 = NULL;
    LyrIface t95 = {0};
    uint8_t t96 = 0;
    LyrStr *t97 = NULL;
    int64_t t98 = 0;
bb0:;
#line 49
    t0 = (LyrStr *)&lyr_lit0;
#line 49
    t1 = lyr_main_walk(t0);
#line 49
    l0_w = t1;
#line 50
    t2 = l0_w;
#line 50
    if (lyr_coro_status(t2) != LYR_CORO_DONE) lyr_coro_resume(t2); if (lyr_coro_status(t2) == LYR_CORO_DONE) { t3_s = (lyr_opt_i64){0}; t3 = &t3_s; } else { t3_s = (lyr_opt_i64){ .value = *(int64_t *)lyr_coro_transfer(t2), .has = 1 }; t3 = &t3_s; }
#line 50
    if (LYR_UNLIKELY(!t3->has)) lyr_panic_null(); t4 = t3->value;
#line 50
    l1_a = t4;
#line 51
    t5 = l0_w;
#line 51
    if (lyr_coro_status(t5) != LYR_CORO_DONE) lyr_coro_resume(t5); if (lyr_coro_status(t5) == LYR_CORO_DONE) { t6_s = (lyr_opt_i64){0}; t6 = &t6_s; } else { t6_s = (lyr_opt_i64){ .value = *(int64_t *)lyr_coro_transfer(t5), .has = 1 }; t6 = &t6_s; }
#line 51
    if (LYR_UNLIKELY(!t6->has)) lyr_panic_null(); t7 = t6->value;
#line 51
    l2_b = t7;
#line 52
    t8 = l0_w;
#line 52
    lyr_coro_close(t8); (void)lyr_coro_take_error(t8);
#line 53
    t9 = l0_w;
#line 53
    if (lyr_coro_status(t9) != LYR_CORO_DONE) lyr_coro_resume(t9); if (lyr_coro_status(t9) == LYR_CORO_DONE) { t10_s = (lyr_opt_i64){0}; t10 = &t10_s; } else { t10_s = (lyr_opt_i64){ .value = *(int64_t *)lyr_coro_transfer(t9), .has = 1 }; t10 = &t10_s; }
#line 53
    l3_after = *t10;
#line 54
    t11 = (LyrStr *)&lyr_lit1;
#line 54
    t12 = l1_a;
#line 54
    t13 = lyr_str_from_int(t12);
#line 54
    t14 = (LyrStr *)&lyr_lit2;
#line 54
    t15 = l2_b;
#line 54
    t16 = lyr_str_from_int(t15);
#line 54
    t17 = (LyrStr *)&lyr_lit3;
#line 54
    t18 = l0_w;
#line 54
    t19 = (uint8_t)(lyr_coro_status(t18) == LYR_CORO_DONE);
#line 54
    t20 = lyr_str_from_bool(t19);
#line 54
    t21 = (LyrStr *)&lyr_lit4;
#line 54
    t22 = &l3_after;
#line 54
    t23 = t22->has;
#line 54
    t24 = (uint8_t)!t23;
#line 54
    t25 = lyr_str_from_bool(t24);
#line 54
    t26 = lyr_str_concat(t11, t13);
#line 54
    t27 = lyr_str_concat(t26, t14);
#line 54
    t28 = lyr_str_concat(t27, t16);
#line 54
    t29 = lyr_str_concat(t28, t17);
#line 54
    t30 = lyr_str_concat(t29, t20);
#line 54
    t31 = lyr_str_concat(t30, t21);
#line 54
    t32 = lyr_str_concat(t31, t25);
#line 54
    lyr_println(t32);
#line 56
    t33 = (LyrStr *)&lyr_lit5;
#line 56
    t34 = lyr_main_walk(t33);
#line 56
    l4_fresh = t34;
#line 57
    t35 = l4_fresh;
#line 57
    lyr_coro_close(t35); (void)lyr_coro_take_error(t35);
#line 58
    t36 = (LyrStr *)&lyr_lit6;
#line 58
    t37 = l4_fresh;
#line 58
    t38 = (uint8_t)(lyr_coro_status(t37) == LYR_CORO_DONE);
#line 58
    t39 = lyr_str_from_bool(t38);
#line 58
    t40 = lyr_str_concat(t36, t39);
#line 58
    lyr_println(t40);
#line 60
    t41 = lyr_main_careful();
#line 60
    l5_c = t41;
#line 61
    t42 = l5_c;
#line 61
    if (lyr_coro_status(t42) != LYR_CORO_DONE) lyr_coro_resume(t42); if (lyr_coro_status(t42) == LYR_CORO_DONE) { t43_s = (lyr_opt_i64){0}; t43 = &t43_s; } else { t43_s = (lyr_opt_i64){ .value = *(int64_t *)lyr_coro_transfer(t42), .has = 1 }; t43 = &t43_s; }
#line 61
    if (LYR_UNLIKELY(!t43->has)) lyr_panic_null(); t44 = t43->value;
#line 61
    l6_c1 = t44;
#line 62
    t45 = l5_c;
#line 62
    lyr_coro_close(t45); (void)lyr_coro_take_error(t45);
#line 63
    t46 = l5_c;
#line 63
    if (lyr_coro_status(t46) == LYR_CORO_DONE && lyr_coro_transfer(t46) != NULL) { t47 = *(LyrStr * *)lyr_coro_transfer(t46); } else { t47 = NULL; }
#line 63
    t48 = (uint8_t)(t47 != NULL);
#line 63
    if (t48) goto bb1; else goto bb2;
bb1:;
#line 63
    t49 = t47;
#line 63
    l8__coalesce0 = t49;
#line 63
    goto bb3;
bb2:;
#line 63
    t50 = (LyrStr *)&lyr_lit7;
#line 63
    l8__coalesce0 = t50;
#line 63
    goto bb3;
bb3:;
#line 63
    t51 = l8__coalesce0;
#line 63
    l7_r = t51;
#line 64
    t52 = (LyrStr *)&lyr_lit8;
#line 64
    t53 = l6_c1;
#line 64
    t54 = lyr_str_from_int(t53);
#line 64
    t55 = (LyrStr *)&lyr_lit2;
#line 64
    t56 = l7_r;
#line 64
    t57 = lyr_str_concat(t52, t54);
#line 64
    t58 = lyr_str_concat(t57, t55);
#line 64
    t59 = lyr_str_concat(t58, t56);
#line 64
    lyr_println(t59);
#line 67
    t60 = (LyrStr *)&lyr_lit9;
#line 67
    t61 = lyr_main_walk(t60);
#line 67
    l9_u = t61;
#line 68
    t62 = l9_u;
#line 68
    if (lyr_coro_status(t62) != LYR_CORO_DONE) lyr_coro_resume(t62); if (lyr_coro_status(t62) == LYR_CORO_DONE) { t63_s = (lyr_opt_i64){0}; t63 = &t63_s; } else { t63_s = (lyr_opt_i64){ .value = *(int64_t *)lyr_coro_transfer(t62), .has = 1 }; t63 = &t63_s; }
#line 68
    if (LYR_UNLIKELY(!t63->has)) lyr_panic_null(); t64 = t63->value;
#line 68
    l10_u0 = t64;
#line 69
    t65 = (LyrStr *)&lyr_lit10;
#line 69
    t66 = l10_u0;
#line 69
    t67 = lyr_str_from_int(t66);
#line 69
    t68 = lyr_str_concat(t65, t67);
#line 69
    lyr_println(t68);
#line 67
    t69 = l9_u;
#line 67
    lyr_coro_close(t69); (void)lyr_coro_take_error(t69);
#line 72
    t70 = lyr_main_angry();
#line 72
    l11_x = t70;
#line 74
    t71 = l11_x;
#line 74
    if (lyr_coro_status(t71) != LYR_CORO_DONE) lyr_coro_resume(t71); if (lyr_coro_status(t71) == LYR_CORO_DONE) { lyr_e = lyr_coro_take_error(t71); t72_s = (lyr_opt_i64){0}; t72 = &t72_s; } else { t72_s = (lyr_opt_i64){ .value = *(int64_t *)lyr_coro_transfer(t71), .has = 1 }; t72 = &t72_s; }
#line 74
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb4; goto bb5;
bb4:;
#line 73
    t82 = lyr_e->value;
#line 77
    t83 = ((*(const LyrDesc *const *)t82.vt) == &lyr_desc_box_ty6_Oops);
#line 77
    if (t83) goto bb10; else goto bb11;
bb5:;
#line 74
    t73 = t72->has;
#line 74
    if (t73) goto bb6; else goto bb7;
bb6:;
#line 74
    t74 = t72->value;
#line 74
    l13__coalesce1 = t74;
#line 74
    goto bb8;
bb7:;
#line 74
    t75 = (int64_t)INT64_C(0);
#line 74
    l13__coalesce1 = t75;
#line 74
    goto bb8;
bb8:;
#line 74
    t76 = l13__coalesce1;
#line 74
    l12_v = t76;
#line 75
    t77 = l11_x;
#line 75
    lyr_coro_close(t77); lyr_e = lyr_coro_take_error(t77); if (lyr_e != NULL && *(const LyrDesc *const *)lyr_e->value.vt == &lyr_desc_ty5_Cancelled) lyr_e = NULL;
#line 75
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb4; goto bb9;
bb9:;
#line 76
    t78 = (LyrStr *)&lyr_lit11;
#line 76
    t79 = l12_v;
#line 76
    t80 = lyr_str_from_int(t79);
#line 76
    t81 = lyr_str_concat(t78, t80);
#line 76
    lyr_println(t81);
#line 73
    goto bb13;
bb10:;
#line 77
    lyr_e = NULL;
#line 77
    t84_s = ((lyr_box_ty6_Oops *)t82.data)->value; t84 = &t84_s;
#line 77
    l14_e = *t84;
#line 78
    t85 = (LyrStr *)&lyr_lit12;
#line 78
    t86 = &l14_e;
#line 78
    t87 = lyr_main_Oops_message(t86);
#line 78
    t88 = lyr_str_concat(t85, t87);
#line 78
    lyr_println(t88);
#line 73
    goto bb13;
bb11:;
#line 73
    goto bb12;
bb12:;
#line 73
    __builtin_unreachable();
bb13:;
#line 81
    t89 = l11_x;
#line 81
    lyr_coro_close(t89); lyr_e = lyr_coro_take_error(t89); if (lyr_e != NULL && *(const LyrDesc *const *)lyr_e->value.vt == &lyr_desc_ty5_Cancelled) lyr_e = NULL;
#line 81
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb14; goto bb15;
bb14:;
#line 80
    t95 = lyr_e->value;
#line 83
    t96 = ((*(const LyrDesc *const *)t95.vt) == &lyr_desc_box_ty6_Oops);
#line 83
    if (t96) goto bb16; else goto bb17;
bb15:;
#line 82
    t90 = (LyrStr *)&lyr_lit13;
#line 82
    t91 = l11_x;
#line 82
    t92 = (uint8_t)(lyr_coro_status(t91) == LYR_CORO_DONE);
#line 82
    t93 = lyr_str_from_bool(t92);
#line 82
    t94 = lyr_str_concat(t90, t93);
#line 82
    lyr_println(t94);
#line 80
    goto bb18;
bb16:;
#line 83
    lyr_e = NULL;
#line 84
    t97 = (LyrStr *)&lyr_lit14;
#line 84
    lyr_println(t97);
#line 80
    goto bb18;
bb17:;
#line 80
    goto bb12;
bb18:;
#line 86
    t98 = (int64_t)INT64_C(0);
#line 86
    return t98;
}

#line 18 "programs/generators_close.lyr"
LyrStr * lyr_main_Oops_message(lyr_ty6_Oops *l0_this) {
    LyrStr *t0 = NULL;
bb0:;
#line 18
    t0 = (LyrStr *)&lyr_lit15;
#line 18
    return t0;
}

#line 86 "stdlib5/std/core.lyr"
lyr_opt_iface4 lyr_std_core_Error_cause(LyrIface l0_this) {
    lyr_opt_iface4 t0_s = {0};
    lyr_opt_iface4 *t0 = &t0_s;
bb0:;
#line 86
    t0_s = (lyr_opt_iface4){0}; t0 = &t0_s;
#line 86
    return *t0;
}

#line 13 "stdlib5/std/task.lyr"
LyrStr * lyr_std_task_Cancelled_message(lyr_ty5_Cancelled *l0_this) {
    LyrStr *t0 = NULL;
bb0:;
#line 13
    t0 = (LyrStr *)&lyr_lit16;
#line 13
    return t0;
}

#line 22 "programs/generators_close.lyr"
void lyr_main_walk__body__1e9ceef5(LyrStr *l0_name, LyrErr **lyr_err) {
    int64_t l1_i = 0;
    LyrErr *lyr_e = NULL;
    int64_t t0 = 0;
    uint8_t t1 = 0;
    int64_t t2 = 0;
    uint8_t t3 = 0;
    lyr_ty5_Cancelled *t4 = NULL;
    LyrIface t5 = {0};
    LyrStr *t6 = NULL;
    LyrStr *t7 = NULL;
    LyrStr *t8 = NULL;
    int64_t t9 = 0;
    int64_t t10 = 0;
    int64_t t11 = 0;
    LyrStr *t12 = NULL;
    LyrStr *t13 = NULL;
    LyrStr *t14 = NULL;
bb0:;
#line 22
    t0 = (int64_t)INT64_C(0);
#line 22
    l1_i = t0;
#line 23
    goto bb1;
bb1:;
#line 23
    t1 = 1;
#line 23
    if (t1) goto bb2; else goto bb3;
bb2:;
#line 24
    t2 = l1_i;
#line 24
    lyr_coro_yield_value(&t2);
#line 24
    t3 = (uint8_t)lyr_coro_closing();
#line 24
    if (t3) goto bb4; else goto bb5;
bb3:;
#line 21
    t12 = l0_name;
#line 21
    t13 = (LyrStr *)&lyr_lit17;
#line 21
    t14 = lyr_str_concat(t12, t13);
#line 21
    lyr_println(t14);
#line 20
    return;
bb4:;
#line 24
    t4 = (lyr_ty5_Cancelled *)lyr_alloc(&lyr_desc_ty5_Cancelled);
#line 24
    t5 = (LyrIface){ t4, &lyr_vt_ty4_ty5 };
#line 24
    lyr_e = lyr_err_new(t5); goto bb6;
bb5:;
#line 25
    t9 = l1_i;
#line 25
    t10 = (int64_t)INT64_C(1);
#line 25
    t11 = LYR_CHECKED_ADD(t9, t10);
#line 25
    l1_i = t11;
#line 23
    goto bb1;
bb6:;
#line 21
    t6 = l0_name;
#line 21
    t7 = (LyrStr *)&lyr_lit17;
#line 21
    t8 = lyr_str_concat(t6, t7);
#line 21
    lyr_println(t8);
#line 24
    goto bb7;
bb7:;
#line 24
    *lyr_err = lyr_e; return;
}

#line 31 "programs/generators_close.lyr"
LyrStr * lyr_main_careful__body__df091f8a(LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    int64_t t0 = 0;
    uint8_t t1 = 0;
    lyr_ty5_Cancelled *t2 = NULL;
    LyrIface t3 = {0};
    int64_t t4 = 0;
    uint8_t t5 = 0;
    lyr_ty5_Cancelled *t6 = NULL;
    LyrIface t7 = {0};
    LyrIface t8 = {0};
    uint8_t t9 = 0;
    LyrStr *t10 = NULL;
    LyrStr *t11 = NULL;
    LyrStr *t12 = NULL;
bb0:;
#line 31
    t0 = (int64_t)INT64_C(1);
#line 31
    lyr_coro_yield_value(&t0);
#line 31
    t1 = (uint8_t)lyr_coro_closing();
#line 31
    if (t1) goto bb1; else goto bb2;
bb1:;
#line 31
    t2 = (lyr_ty5_Cancelled *)lyr_alloc(&lyr_desc_ty5_Cancelled);
#line 31
    t3 = (LyrIface){ t2, &lyr_vt_ty4_ty5 };
#line 31
    lyr_e = lyr_err_new(t3); goto bb3;
bb2:;
#line 32
    t4 = (int64_t)INT64_C(2);
#line 32
    lyr_coro_yield_value(&t4);
#line 32
    t5 = (uint8_t)lyr_coro_closing();
#line 32
    if (t5) goto bb4; else goto bb5;
bb3:;
#line 30
    t8 = lyr_e->value;
#line 33
    t9 = ((*(const LyrDesc *const *)t8.vt) == &lyr_desc_ty5_Cancelled);
#line 33
    if (t9) goto bb6; else goto bb7;
bb4:;
#line 32
    t6 = (lyr_ty5_Cancelled *)lyr_alloc(&lyr_desc_ty5_Cancelled);
#line 32
    t7 = (LyrIface){ t6, &lyr_vt_ty4_ty5 };
#line 32
    lyr_e = lyr_err_new(t7); goto bb3;
bb5:;
#line 30
    goto bb9;
bb6:;
#line 33
    lyr_e = NULL;
#line 34
    t10 = (LyrStr *)&lyr_lit18;
#line 34
    lyr_println(t10);
#line 35
    t11 = (LyrStr *)&lyr_lit19;
#line 35
    return t11;
bb7:;
#line 30
    goto bb8;
bb8:;
#line 30
    *lyr_err = lyr_e; return NULL;
bb9:;
#line 37
    t12 = (LyrStr *)&lyr_lit20;
#line 37
    return t12;
}

#line 42 "programs/generators_close.lyr"
void lyr_main_angry__body__5d538b59(LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    int64_t t0 = 0;
    uint8_t t1 = 0;
    lyr_ty5_Cancelled *t2 = NULL;
    LyrIface t3 = {0};
    LyrIface t4 = {0};
    uint8_t t5 = 0;
    lyr_ty6_Oops t6_s = {0};
    lyr_ty6_Oops *t6 = &t6_s;
    LyrIface t7 = {0};
bb0:;
#line 42
    t0 = (int64_t)INT64_C(1);
#line 42
    lyr_coro_yield_value(&t0);
#line 42
    t1 = (uint8_t)lyr_coro_closing();
#line 42
    if (t1) goto bb1; else goto bb2;
bb1:;
#line 42
    t2 = (lyr_ty5_Cancelled *)lyr_alloc(&lyr_desc_ty5_Cancelled);
#line 42
    t3 = (LyrIface){ t2, &lyr_vt_ty4_ty5 };
#line 42
    lyr_e = lyr_err_new(t3); goto bb3;
bb2:;
#line 41
    goto bb7;
bb3:;
#line 41
    t4 = lyr_e->value;
#line 43
    t5 = ((*(const LyrDesc *const *)t4.vt) == &lyr_desc_ty5_Cancelled);
#line 43
    if (t5) goto bb4; else goto bb5;
bb4:;
#line 43
    lyr_e = NULL;
#line 44
    t6_s = (lyr_ty6_Oops){ .tag = 0 }; t6 = &t6_s;
#line 44
    { lyr_box_ty6_Oops *lyr_box = lyr_alloc(&lyr_desc_box_ty6_Oops); lyr_box->value = *t6; t7 = (LyrIface){ lyr_box, &lyr_vt_ty4_ty6 }; }
#line 44
    lyr_e = lyr_err_new(t7); goto bb6;
bb5:;
#line 41
    goto bb6;
bb6:;
#line 44
    *lyr_err = lyr_e; return;
bb7:;
#line 40
    return;
}


/* the program */
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_main_main); }
