/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty0_Point lyr_ty0_Point;
typedef struct lyr_ty1_Log lyr_ty1_Log;
typedef struct lyr_ty2_ParseError lyr_ty2_ParseError;
typedef struct lyr_ty3_ParseErrorKind lyr_ty3_ParseErrorKind;
typedef struct lyr_ty4_ParseErrorKind_Empty lyr_ty4_ParseErrorKind_Empty;
typedef struct lyr_ty5_ParseErrorKind_Invalid lyr_ty5_ParseErrorKind_Invalid;
typedef struct lyr_ty6_ParseErrorKind_Overflow lyr_ty6_ParseErrorKind_Overflow;
typedef struct lyr_vt_ty7 lyr_vt_ty7;
const char lyr_ifid_ty7[] = "std.core.Error";
typedef struct lyr_ty8_Exception lyr_ty8_Exception;
struct lyr_ty0_Point {
    int64_t f_x;
    int64_t f_y;
};
struct lyr_ty1_Log {
    LyrObj header;
    int64_t f_lines;
    LyrStr *f_last;
};
_Static_assert(sizeof(lyr_ty1_Log) == 24, "layout of lyr_ty1_Log");
_Static_assert(offsetof(lyr_ty1_Log, f_lines) == 8, "layout of lyr_ty1_Log");
_Static_assert(offsetof(lyr_ty1_Log, f_last) == 16, "layout of lyr_ty1_Log");
static const uint64_t lyr_refmap_ty1[] = { UINT64_C(0x4) };
const LyrDesc lyr_desc_ty1_Log = { sizeof(lyr_ty1_Log), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty1, "main.Log", NULL };
struct lyr_ty4_ParseErrorKind_Empty {
    uint8_t lyr_unit;
};
struct lyr_ty5_ParseErrorKind_Invalid {
    uint8_t lyr_unit;
};
struct lyr_ty6_ParseErrorKind_Overflow {
    uint8_t lyr_unit;
};
struct lyr_ty3_ParseErrorKind { uint32_t tag; };
_Static_assert(sizeof(lyr_ty3_ParseErrorKind) == 4, "layout of lyr_ty3_ParseErrorKind");
struct lyr_ty2_ParseError {
    lyr_ty3_ParseErrorKind f_kind;
};
struct lyr_vt_ty7 {
    const LyrDesc *desc;
    void (*s0)(LyrIface);
    void (*s1)(LyrIface);
};
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface7;
struct lyr_ty8_Exception {
    LyrObj header;
    LyrStr *f_text;
    lyr_opt_iface7 f_inner;
};
_Static_assert(sizeof(lyr_ty8_Exception) == 40, "layout of lyr_ty8_Exception");
_Static_assert(offsetof(lyr_ty8_Exception, f_text) == 8, "layout of lyr_ty8_Exception");
_Static_assert(offsetof(lyr_ty8_Exception, f_inner) == 16, "layout of lyr_ty8_Exception");
static const uint64_t lyr_refmap_ty8[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty8_Exception = { sizeof(lyr_ty8_Exception), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty8, "std.core.Exception", NULL };
_Static_assert(sizeof(lyr_ty0_Point) == 16, "layout of main.Point[]");
const LyrDesc lyr_desc_arr_ty0 = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY, sizeof(lyr_ty0_Point), 0, NULL, "main.Point[]", NULL };

/* module-level bindings */
lyr_ty0_Point lyr_g0_Point_ORIGIN = {0};
int64_t lyr_g1_base = 0;
int64_t lyr_g2_twice = 0;
LyrStr *lyr_g3_greeting = NULL;
int64_t lyr_g4_counter = 0;
lyr_ty1_Log *lyr_g5_log = NULL;
LyrArr *lyr_g6_points = NULL;

/* string literals */
static const LyrStaticStr(7) lyr_lit0 = LYR_STR_INIT("start ");
static const LyrStaticStr(2) lyr_lit1 = LYR_STR_INIT(" ");
static const LyrStaticStr(9) lyr_lit2 = LYR_STR_INIT("counter ");
static const LyrStaticStr(8) lyr_lit3 = LYR_STR_INIT("static ");
static const LyrStaticStr(2) lyr_lit4 = LYR_STR_INIT(",");
static const LyrStaticStr(6) lyr_lit5 = LYR_STR_INIT("alice");
static const LyrStaticStr(4) lyr_lit6 = LYR_STR_INIT("bob");
static const LyrStaticStr(8) lyr_lit7 = LYR_STR_INIT("object ");
static const LyrStaticStr(6) lyr_lit8 = LYR_STR_INIT("hello");
static const LyrStaticStr(2) lyr_lit9 = LYR_STR_INIT("!");
static const LyrStaticStr(1) lyr_lit10 = LYR_STR_INIT("");

/* prototypes */
void lyr_main_bump(void);
void lyr_main_note(LyrStr *l0_s);
int64_t lyr_main_main(void);
void lyr__globals__9ee5f9b5(void);

#line 27 "programs/globals.lyr"
void lyr_main_bump(void) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    int64_t t2 = 0;
bb0:;
#line 27
    t0 = lyr_g4_counter;
#line 27
    t1 = (int64_t)INT64_C(1);
#line 27
    t2 = LYR_CHECKED_ADD(t0, t1);
#line 27
    lyr_g4_counter = t2;
#line 27
    return;
}

#line 30 "programs/globals.lyr"
void lyr_main_note(LyrStr *l0_s) {
    lyr_ty1_Log *t0 = NULL;
    int64_t t1 = 0;
    int64_t t2 = 0;
    int64_t t3 = 0;
    lyr_ty1_Log *t4 = NULL;
    LyrStr *t5 = NULL;
bb0:;
#line 30
    t0 = lyr_g5_log;
#line 30
    t1 = t0->f_lines;
#line 30
    t2 = (int64_t)INT64_C(1);
#line 30
    t3 = LYR_CHECKED_ADD(t1, t2);
#line 30
    t0->f_lines = t3;
#line 31
    t4 = lyr_g5_log;
#line 31
    t5 = l0_s;
#line 31
    LYR_WRITE_BARRIER(t4, &t4->f_last, t5);
#line 29
    return;
}

#line 35 "programs/globals.lyr"
int64_t lyr_main_main(void) {
    int64_t l0_before = 0;
    int64_t l1_mid = 0;
    LyrStr *t0 = NULL;
    int64_t t1 = 0;
    LyrStr *t2 = NULL;
    LyrStr *t3 = NULL;
    int64_t t4 = 0;
    LyrStr *t5 = NULL;
    LyrStr *t6 = NULL;
    LyrStr *t7 = NULL;
    LyrStr *t8 = NULL;
    LyrStr *t9 = NULL;
    LyrStr *t10 = NULL;
    LyrStr *t11 = NULL;
    LyrStr *t12 = NULL;
    int64_t t13 = 0;
    int64_t t14 = 0;
    int64_t t15 = 0;
    int64_t t16 = 0;
    int64_t t17 = 0;
    LyrStr *t18 = NULL;
    int64_t t19 = 0;
    LyrStr *t20 = NULL;
    LyrStr *t21 = NULL;
    int64_t t22 = 0;
    LyrStr *t23 = NULL;
    LyrStr *t24 = NULL;
    int64_t t25 = 0;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    LyrStr *t28 = NULL;
    LyrStr *t29 = NULL;
    LyrStr *t30 = NULL;
    LyrStr *t31 = NULL;
    LyrStr *t32 = NULL;
    lyr_ty0_Point t33_s = {0};
    lyr_ty0_Point *t33 = &t33_s;
    int64_t t34 = 0;
    LyrStr *t35 = NULL;
    LyrStr *t36 = NULL;
    lyr_ty0_Point t37_s = {0};
    lyr_ty0_Point *t37 = &t37_s;
    int64_t t38 = 0;
    LyrStr *t39 = NULL;
    LyrStr *t40 = NULL;
    int64_t t41 = 0;
    LyrStr *t42 = NULL;
    LyrStr *t43 = NULL;
    LyrStr *t44 = NULL;
    LyrStr *t45 = NULL;
    LyrStr *t46 = NULL;
    LyrStr *t47 = NULL;
    LyrStr *t48 = NULL;
    LyrStr *t49 = NULL;
    LyrArr *t50 = NULL;
    int64_t t51 = 0;
    lyr_ty0_Point t52_s = {0};
    lyr_ty0_Point *t52 = &t52_s;
    int64_t t53 = 0;
    LyrStr *t54 = NULL;
    lyr_ty1_Log *t55 = NULL;
    int64_t t56 = 0;
    LyrStr *t57 = NULL;
    LyrStr *t58 = NULL;
    lyr_ty1_Log *t59 = NULL;
    LyrStr *t60 = NULL;
    LyrStr *t61 = NULL;
    LyrArr *t62 = NULL;
    int64_t t63 = 0;
    lyr_ty0_Point t64_s = {0};
    lyr_ty0_Point *t64 = &t64_s;
    int64_t t65 = 0;
    LyrStr *t66 = NULL;
    LyrStr *t67 = NULL;
    LyrArr *t68 = NULL;
    int64_t t69 = 0;
    lyr_ty0_Point t70_s = {0};
    lyr_ty0_Point *t70 = &t70_s;
    int64_t t71 = 0;
    LyrStr *t72 = NULL;
    LyrStr *t73 = NULL;
    LyrStr *t74 = NULL;
    LyrStr *t75 = NULL;
    LyrStr *t76 = NULL;
    LyrStr *t77 = NULL;
    LyrStr *t78 = NULL;
    LyrStr *t79 = NULL;
    int64_t t80 = 0;
bb0:;
#line 35
    t0 = (LyrStr *)&lyr_lit0;
#line 35
    t1 = lyr_g1_base;
#line 35
    t2 = lyr_str_from_int(t1);
#line 35
    t3 = (LyrStr *)&lyr_lit1;
#line 35
    t4 = lyr_g2_twice;
#line 35
    t5 = lyr_str_from_int(t4);
#line 35
    t6 = (LyrStr *)&lyr_lit1;
#line 35
    t7 = lyr_g3_greeting;
#line 35
    t8 = lyr_str_concat(t0, t2);
#line 35
    t9 = lyr_str_concat(t8, t3);
#line 35
    t10 = lyr_str_concat(t9, t5);
#line 35
    t11 = lyr_str_concat(t10, t6);
#line 35
    t12 = lyr_str_concat(t11, t7);
#line 35
    lyr_println(t12);
#line 36
    t13 = lyr_g4_counter;
#line 36
    l0_before = t13;
#line 37
    lyr_main_bump();
#line 38
    lyr_main_bump();
#line 39
    lyr_main_bump();
#line 40
    t14 = lyr_g4_counter;
#line 40
    l1_mid = t14;
#line 41
    t15 = lyr_g4_counter;
#line 41
    t16 = (int64_t)INT64_C(1);
#line 41
    t17 = LYR_CHECKED_ADD(t15, t16);
#line 41
    lyr_g4_counter = t17;
#line 42
    t18 = (LyrStr *)&lyr_lit2;
#line 42
    t19 = l0_before;
#line 42
    t20 = lyr_str_from_int(t19);
#line 42
    t21 = (LyrStr *)&lyr_lit1;
#line 42
    t22 = l1_mid;
#line 42
    t23 = lyr_str_from_int(t22);
#line 42
    t24 = (LyrStr *)&lyr_lit1;
#line 42
    t25 = lyr_g4_counter;
#line 42
    t26 = lyr_str_from_int(t25);
#line 42
    t27 = lyr_str_concat(t18, t20);
#line 42
    t28 = lyr_str_concat(t27, t21);
#line 42
    t29 = lyr_str_concat(t28, t23);
#line 42
    t30 = lyr_str_concat(t29, t24);
#line 42
    t31 = lyr_str_concat(t30, t26);
#line 42
    lyr_println(t31);
#line 43
    t32 = (LyrStr *)&lyr_lit3;
#line 43
    t33 = &lyr_g0_Point_ORIGIN;
#line 43
    t34 = t33->f_x;
#line 43
    t35 = lyr_str_from_int(t34);
#line 43
    t36 = (LyrStr *)&lyr_lit4;
#line 43
    t37 = &lyr_g0_Point_ORIGIN;
#line 43
    t38 = t37->f_y;
#line 43
    t39 = lyr_str_from_int(t38);
#line 43
    t40 = (LyrStr *)&lyr_lit1;
#line 15
    t41 = (int64_t)INT64_C(100);
#line 43
    t42 = lyr_str_from_int(t41);
#line 43
    t43 = lyr_str_concat(t32, t35);
#line 43
    t44 = lyr_str_concat(t43, t36);
#line 43
    t45 = lyr_str_concat(t44, t39);
#line 43
    t46 = lyr_str_concat(t45, t40);
#line 43
    t47 = lyr_str_concat(t46, t42);
#line 43
    lyr_println(t47);
#line 44
    t48 = (LyrStr *)&lyr_lit5;
#line 44
    lyr_main_note(t48);
#line 45
    t49 = (LyrStr *)&lyr_lit6;
#line 45
    lyr_main_note(t49);
#line 46
    t50 = lyr_g6_points;
#line 46
    t51 = (int64_t)INT64_C(1);
#line 46
    LYR_CHECK_INDEX(t51, t50->len); t52 = &LYR_ARR_DATA(t50, lyr_ty0_Point)[t51];
#line 46
    t53 = (int64_t)INT64_C(9);
#line 46
    t52->f_x = t53;
#line 47
    t54 = (LyrStr *)&lyr_lit7;
#line 47
    t55 = lyr_g5_log;
#line 47
    t56 = t55->f_lines;
#line 47
    t57 = lyr_str_from_int(t56);
#line 47
    t58 = (LyrStr *)&lyr_lit1;
#line 47
    t59 = lyr_g5_log;
#line 47
    t60 = t59->f_last;
#line 47
    t61 = (LyrStr *)&lyr_lit1;
#line 47
    t62 = lyr_g6_points;
#line 47
    t63 = (int64_t)INT64_C(1);
#line 47
    LYR_CHECK_INDEX(t63, t62->len); t64 = &LYR_ARR_DATA(t62, lyr_ty0_Point)[t63];
#line 47
    t65 = t64->f_x;
#line 47
    t66 = lyr_str_from_int(t65);
#line 47
    t67 = (LyrStr *)&lyr_lit1;
#line 47
    t68 = lyr_g6_points;
#line 47
    t69 = (int64_t)INT64_C(0);
#line 47
    LYR_CHECK_INDEX(t69, t68->len); t70 = &LYR_ARR_DATA(t68, lyr_ty0_Point)[t69];
#line 47
    t71 = t70->f_x;
#line 47
    t72 = lyr_str_from_int(t71);
#line 47
    t73 = lyr_str_concat(t54, t57);
#line 47
    t74 = lyr_str_concat(t73, t58);
#line 47
    t75 = lyr_str_concat(t74, t60);
#line 47
    t76 = lyr_str_concat(t75, t61);
#line 47
    t77 = lyr_str_concat(t76, t66);
#line 47
    t78 = lyr_str_concat(t77, t67);
#line 47
    t79 = lyr_str_concat(t78, t72);
#line 47
    lyr_println(t79);
#line 48
    t80 = (int64_t)INT64_C(0);
#line 48
    return t80;
}

#line 14 "programs/globals.lyr"
void lyr__globals__9ee5f9b5(void) {
    int64_t t0 = 0;
    int64_t t1 = 0;
    lyr_ty0_Point t2_s = {0};
    lyr_ty0_Point *t2 = &t2_s;
    int64_t t3 = 0;
    int64_t t4 = 0;
    int64_t t5 = 0;
    int64_t t6 = 0;
    LyrStr *t7 = NULL;
    LyrStr *t8 = NULL;
    LyrStr *t9 = NULL;
    int64_t t10 = 0;
    int64_t t11 = 0;
    LyrStr *t12 = NULL;
    lyr_ty1_Log *t13 = NULL;
    int64_t t14 = 0;
    int64_t t15 = 0;
    lyr_ty0_Point t16_s = {0};
    lyr_ty0_Point *t16 = &t16_s;
    LyrArr *t17 = NULL;
    int64_t t18 = 0;
    LyrArr *t19 = NULL;
bb0:;
#line 14
    t0 = (int64_t)INT64_C(0);
#line 14
    t1 = (int64_t)INT64_C(0);
#line 14
    t2_s = (lyr_ty0_Point){0}; t2 = &t2_s;
#line 14
    t2->f_x = t0;
#line 14
    t2->f_y = t1;
#line 14
    lyr_g0_Point_ORIGIN = *t2;
#line 20
    t3 = (int64_t)INT64_C(3);
#line 20
    lyr_g1_base = t3;
#line 21
    t4 = lyr_g1_base;
#line 21
    t5 = (int64_t)INT64_C(2);
#line 21
    t6 = LYR_CHECKED_MUL(t4, t5);
#line 21
    lyr_g2_twice = t6;
#line 22
    t7 = (LyrStr *)&lyr_lit8;
#line 22
    t8 = (LyrStr *)&lyr_lit9;
#line 22
    t9 = lyr_str_concat(t7, t8);
#line 22
    lyr_g3_greeting = t9;
#line 23
    t10 = (int64_t)INT64_C(0);
#line 23
    lyr_g4_counter = t10;
#line 24
    t11 = (int64_t)INT64_C(0);
#line 24
    t12 = (LyrStr *)&lyr_lit10;
#line 24
    t13 = (lyr_ty1_Log *)lyr_alloc(&lyr_desc_ty1_Log);
#line 24
    t13->f_lines = t11;
#line 24
    LYR_WRITE_BARRIER(t13, &t13->f_last, t12);
#line 24
    lyr_g5_log = t13;
#line 25
    t14 = (int64_t)INT64_C(1);
#line 25
    t15 = (int64_t)INT64_C(2);
#line 25
    t16_s = (lyr_ty0_Point){0}; t16 = &t16_s;
#line 25
    t16->f_x = t14;
#line 25
    t16->f_y = t15;
#line 25
    t17 = lyr_alloc_array(&lyr_desc_arr_ty0, 1); LYR_ARR_DATA(t17, lyr_ty0_Point)[0] = *t16;
#line 25
    t18 = (int64_t)INT64_C(2);
#line 25
    t19 = lyr_arr_repeat(&lyr_desc_arr_ty0, t17, t18);
#line 25
    lyr_g6_points = t19;
    return;
}


/* the program */
static int64_t lyr_entry(void) { lyr__globals__9ee5f9b5(); return lyr_main_main(); }
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_entry); }
