/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty0_Res lyr_ty0_Res;
typedef struct lyr_ty1_Exception lyr_ty1_Exception;
typedef struct lyr_vt_ty2 lyr_vt_ty2;
const char lyr_ifid_ty2[] = "std.core.Error";
typedef struct lyr_ty3_ParseError lyr_ty3_ParseError;
typedef struct lyr_ty4_ParseErrorKind lyr_ty4_ParseErrorKind;
typedef struct lyr_ty5_ParseErrorKind_Empty lyr_ty5_ParseErrorKind_Empty;
typedef struct lyr_ty6_ParseErrorKind_Invalid lyr_ty6_ParseErrorKind_Invalid;
typedef struct lyr_ty7_ParseErrorKind_Overflow lyr_ty7_ParseErrorKind_Overflow;
typedef struct lyr_ty8_Ordering lyr_ty8_Ordering;
typedef struct lyr_ty9_Ordering_Less lyr_ty9_Ordering_Less;
typedef struct lyr_ty10_Ordering_Equal lyr_ty10_Ordering_Equal;
typedef struct lyr_ty11_Ordering_Greater lyr_ty11_Ordering_Greater;
typedef struct lyr_vt_ty12 lyr_vt_ty12;
const char lyr_ifid_ty12[] = "std.core.Hasher";
typedef struct lyr_ty13_Sip lyr_ty13_Sip;
typedef struct lyr_ty14_DefaultHasher lyr_ty14_DefaultHasher;
typedef struct lyr_ty15_FixedHasher lyr_ty15_FixedHasher;
typedef struct lyr_ty16_Fnv1a64 lyr_ty16_Fnv1a64;
struct lyr_ty0_Res {
    LyrObj header;
    LyrStr *f_name;
    uint8_t f_failing;
};
_Static_assert(sizeof(lyr_ty0_Res) == 24, "layout of lyr_ty0_Res");
_Static_assert(offsetof(lyr_ty0_Res, f_name) == 8, "layout of lyr_ty0_Res");
_Static_assert(offsetof(lyr_ty0_Res, f_failing) == 16, "layout of lyr_ty0_Res");
static const uint64_t lyr_refmap_ty0[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty0_Res = { sizeof(lyr_ty0_Res), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty0, "main.Res", NULL };
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface2;
struct lyr_vt_ty2 {
    const LyrDesc *desc;
    LyrStr * (*s0)(LyrIface);
    lyr_opt_iface2 (*s1)(LyrIface);
};
struct lyr_ty1_Exception {
    LyrObj header;
    LyrStr *f_text;
    lyr_opt_iface2 f_inner;
};
_Static_assert(sizeof(lyr_ty1_Exception) == 40, "layout of lyr_ty1_Exception");
_Static_assert(offsetof(lyr_ty1_Exception, f_text) == 8, "layout of lyr_ty1_Exception");
_Static_assert(offsetof(lyr_ty1_Exception, f_inner) == 16, "layout of lyr_ty1_Exception");
extern const LyrItable lyr_itab_ty1[];
static const uint64_t lyr_refmap_ty1[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty1_Exception = { sizeof(lyr_ty1_Exception), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty1, "std.core.Exception", lyr_itab_ty1 };
struct lyr_ty5_ParseErrorKind_Empty {
    uint8_t lyr_unit;
};
struct lyr_ty6_ParseErrorKind_Invalid {
    uint8_t lyr_unit;
};
struct lyr_ty7_ParseErrorKind_Overflow {
    uint8_t lyr_unit;
};
struct lyr_ty4_ParseErrorKind { uint32_t tag; };
_Static_assert(sizeof(lyr_ty4_ParseErrorKind) == 4, "layout of lyr_ty4_ParseErrorKind");
struct lyr_ty3_ParseError {
    lyr_ty4_ParseErrorKind f_kind;
};
struct lyr_ty9_Ordering_Less {
    uint8_t lyr_unit;
};
struct lyr_ty10_Ordering_Equal {
    uint8_t lyr_unit;
};
struct lyr_ty11_Ordering_Greater {
    uint8_t lyr_unit;
};
struct lyr_ty8_Ordering { uint32_t tag; };
_Static_assert(sizeof(lyr_ty8_Ordering) == 4, "layout of lyr_ty8_Ordering");
struct lyr_vt_ty12 {
    const LyrDesc *desc;
    void (*s0)(LyrIface);
    void (*s1)(LyrIface);
    void (*s2)(LyrIface);
    void (*s3)(LyrIface);
    void (*s4)(LyrIface);
};
struct lyr_ty13_Sip {
    uint64_t f_v0;
    uint64_t f_v1;
    uint64_t f_v2;
    uint64_t f_v3;
    uint64_t f_tail;
    int64_t f_pending;
    int64_t f_length;
};
struct lyr_ty14_DefaultHasher {
    lyr_ty13_Sip f_state;
};
struct lyr_ty15_FixedHasher {
    lyr_ty13_Sip f_state;
};
struct lyr_ty16_Fnv1a64 {
    uint64_t f_state;
};

/* module-level bindings */
double lyr_g0_float_infinity = 0;
double lyr_g1_float_nan = 0;
float lyr_g2_float32_infinity = 0;
float lyr_g3_float32_nan = 0;
uint64_t lyr_g4_emptyGroup = 0;
uint64_t lyr_g5_lowBits = 0;
uint64_t lyr_g6_highBits = 0;

/* string literals */
static const LyrStaticStr(2) lyr_lit0 = LYR_STR_INIT("a");
static const LyrStaticStr(2) lyr_lit1 = LYR_STR_INIT("b");
static const LyrStaticStr(5) lyr_lit2 = LYR_STR_INIT("body");
static const LyrStaticStr(14) lyr_lit3 = LYR_STR_INIT("defer between");
static const LyrStaticStr(2) lyr_lit4 = LYR_STR_INIT("x");
static const LyrStaticStr(5) lyr_lit5 = LYR_STR_INIT("work");
static const LyrStaticStr(2) lyr_lit6 = LYR_STR_INIT("y");
static const LyrStaticStr(12) lyr_lit7 = LYR_STR_INIT("body failed");
static const LyrStaticStr(8) lyr_lit8 = LYR_STR_INIT("wrapped");
static const LyrStaticStr(11) lyr_lit9 = LYR_STR_INIT("unexpected");
static const LyrStaticStr(8) lyr_lit10 = LYR_STR_INIT("caught ");
static const LyrStaticStr(10) lyr_lit11 = LYR_STR_INIT(" because ");
static const LyrStaticStr(7) lyr_lit12 = LYR_STR_INIT("close ");
static const LyrStaticStr(8) lyr_lit13 = LYR_STR_INIT(" failed");

/* prototypes */
lyr_ty0_Res * lyr_main_open(LyrStr *l0_name);
lyr_ty0_Res * lyr_main_openFailing(LyrStr *l0_name);
void lyr_main_scope(LyrErr **lyr_err);
void lyr_main_closeFails(LyrErr **lyr_err);
void lyr_main_bodyFails(LyrErr **lyr_err);
void lyr_main_wrapped(LyrErr **lyr_err);
LYR_NOINLINE void lyr_main_main(void);
void lyr_main_Res_close(lyr_ty0_Res *l0_this, LyrErr **lyr_err);
LyrStr * lyr_std_core_Exception_message(lyr_ty1_Exception *l0_this);
lyr_opt_iface2 lyr_std_core_Exception_cause(lyr_ty1_Exception *l0_this);
void lyr__globals__9ee5f9b5(void);
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b);
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b);

/* interface tables: the descriptor, then the implementation of every slot */
static LyrStr * lyr_vt_ty2_ty1_s0(LyrIface self) { return lyr_std_core_Exception_message((lyr_ty1_Exception *)self.data); }
static lyr_opt_iface2 lyr_vt_ty2_ty1_s1(LyrIface self) { return lyr_std_core_Exception_cause((lyr_ty1_Exception *)self.data); }
const lyr_vt_ty2 lyr_vt_ty2_ty1 = { &lyr_desc_ty1_Exception, lyr_vt_ty2_ty1_s0, lyr_vt_ty2_ty1_s1 };
const LyrItable lyr_itab_ty1[] = { { lyr_ifid_ty2, &lyr_vt_ty2_ty1 } , { NULL, NULL } };

#line 16 "programs/resources.lyr"
lyr_ty0_Res * lyr_main_open(LyrStr *l0_name) {
    LyrStr *t0 = NULL;
    uint8_t t1 = 0;
    lyr_ty0_Res *t2 = NULL;
bb0:;
#line 16
    t0 = l0_name;
#line 8
    t1 = 0;
#line 16
    t2 = (lyr_ty0_Res *)lyr_alloc(&lyr_desc_ty0_Res);
#line 16
    LYR_WRITE_BARRIER(t2, &t2->f_name, t0);
#line 16
    t2->f_failing = t1;
#line 16
    return t2;
}

#line 17 "programs/resources.lyr"
lyr_ty0_Res * lyr_main_openFailing(LyrStr *l0_name) {
    LyrStr *t0 = NULL;
    uint8_t t1 = 0;
    lyr_ty0_Res *t2 = NULL;
bb0:;
#line 17
    t0 = l0_name;
#line 17
    t1 = 1;
#line 17
    t2 = (lyr_ty0_Res *)lyr_alloc(&lyr_desc_ty0_Res);
#line 17
    LYR_WRITE_BARRIER(t2, &t2->f_name, t0);
#line 17
    t2->f_failing = t1;
#line 17
    return t2;
}

#line 20 "programs/resources.lyr"
void lyr_main_scope(LyrErr **lyr_err) {
    lyr_ty0_Res *l0_a = NULL;
    lyr_ty0_Res *l1_b = NULL;
    LyrErr *lyr_e = NULL;
    LyrErr *lyr_s0 = NULL;
    LyrStr *t0 = NULL;
    lyr_ty0_Res *t1 = NULL;
    LyrStr *t2 = NULL;
    lyr_ty0_Res *t3 = NULL;
    LyrStr *t4 = NULL;
    lyr_ty0_Res *t5 = NULL;
    LyrStr *t6 = NULL;
    lyr_ty0_Res *t7 = NULL;
    LyrStr *t8 = NULL;
    lyr_ty0_Res *t9 = NULL;
bb0:;
#line 20
    t0 = (LyrStr *)&lyr_lit0;
#line 20
    t1 = lyr_main_open(t0);
#line 20
    l0_a = t1;
#line 22
    t2 = (LyrStr *)&lyr_lit1;
#line 22
    t3 = lyr_main_open(t2);
#line 22
    l1_b = t3;
#line 23
    t4 = (LyrStr *)&lyr_lit2;
#line 23
    lyr_println(t4);
#line 22
    t5 = l1_b;
#line 22
    lyr_main_Res_close(t5, &lyr_e);
#line 22
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb6;
bb1:;
#line 21
    t6 = (LyrStr *)&lyr_lit3;
#line 21
    lyr_println(t6);
#line 22
    goto bb2;
bb2:;
#line 22
    lyr_s0 = lyr_e; lyr_e = NULL;
#line 20
    t7 = l0_a;
#line 20
    lyr_main_Res_close(t7, &lyr_e);
#line 20
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb3; goto bb4;
bb3:;
#line 22
    lyr_err_suppress(lyr_s0, lyr_e); lyr_e = lyr_s0;
#line 22
    goto bb5;
bb4:;
#line 22
    lyr_e = lyr_s0;
#line 22
    goto bb5;
bb5:;
#line 22
    *lyr_err = lyr_e; return;
bb6:;
#line 21
    t8 = (LyrStr *)&lyr_lit3;
#line 21
    lyr_println(t8);
#line 20
    t9 = l0_a;
#line 20
    lyr_main_Res_close(t9, &lyr_e);
#line 19
    return;
}

#line 27 "programs/resources.lyr"
void lyr_main_closeFails(LyrErr **lyr_err) {
    lyr_ty0_Res *l0_x = NULL;
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    lyr_ty0_Res *t1 = NULL;
    LyrStr *t2 = NULL;
    lyr_ty0_Res *t3 = NULL;
bb0:;
#line 27
    t0 = (LyrStr *)&lyr_lit4;
#line 27
    t1 = lyr_main_openFailing(t0);
#line 27
    l0_x = t1;
#line 28
    t2 = (LyrStr *)&lyr_lit5;
#line 28
    lyr_println(t2);
#line 27
    t3 = l0_x;
#line 27
    lyr_main_Res_close(t3, &lyr_e);
#line 27
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 27
    *lyr_err = lyr_e; return;
bb2:;
#line 26
    return;
}

#line 32 "programs/resources.lyr"
void lyr_main_bodyFails(LyrErr **lyr_err) {
    lyr_ty0_Res *l0_y = NULL;
    LyrErr *lyr_e = NULL;
    LyrErr *lyr_s0 = NULL;
    LyrStr *t0 = NULL;
    lyr_ty0_Res *t1 = NULL;
    LyrStr *t2 = NULL;
    lyr_opt_iface2 t3_s = {0};
    lyr_opt_iface2 *t3 = &t3_s;
    lyr_ty1_Exception *t4 = NULL;
    LyrIface t5 = {0};
    lyr_ty0_Res *t6 = NULL;
bb0:;
#line 32
    t0 = (LyrStr *)&lyr_lit6;
#line 32
    t1 = lyr_main_openFailing(t0);
#line 32
    l0_y = t1;
#line 33
    t2 = (LyrStr *)&lyr_lit7;
#line 120 "stdlib5/std/core.lyr"
    t3_s = (lyr_opt_iface2){0}; t3 = &t3_s;
#line 33 "programs/resources.lyr"
    t4 = (lyr_ty1_Exception *)lyr_alloc(&lyr_desc_ty1_Exception);
#line 33
    LYR_WRITE_BARRIER(t4, &t4->f_text, t2);
#line 33
    LYR_WRITE_BARRIER_VALUE(t4, &t4->f_inner, *t3);
#line 33
    t5 = (LyrIface){ t4, &lyr_vt_ty2_ty1 };
#line 33
    lyr_e = lyr_err_new(t5); goto bb1;
bb1:;
#line 33
    lyr_s0 = lyr_e; lyr_e = NULL;
#line 32
    t6 = l0_y;
#line 32
    lyr_main_Res_close(t6, &lyr_e);
#line 32
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb2; goto bb3;
bb2:;
#line 33
    lyr_err_suppress(lyr_s0, lyr_e); lyr_e = lyr_s0;
#line 33
    goto bb4;
bb3:;
#line 33
    lyr_e = lyr_s0;
#line 33
    goto bb4;
bb4:;
#line 33
    *lyr_err = lyr_e; return;
}

#line 37 "programs/resources.lyr"
void lyr_main_wrapped(LyrErr **lyr_err) {
    LyrIface l0_e = {0};
    LyrErr *lyr_e = NULL;
    LyrIface t0 = {0};
    LyrStr *t1 = NULL;
    LyrIface t2 = {0};
    lyr_opt_iface2 t3_s = {0};
    lyr_opt_iface2 *t3 = &t3_s;
    lyr_ty1_Exception *t4 = NULL;
    LyrIface t5 = {0};
bb0:;
#line 37
    lyr_main_closeFails(&lyr_e);
#line 37
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 37
    t0 = lyr_e->value;
#line 38
    lyr_e = NULL;
#line 38
    l0_e = t0;
#line 38
    t1 = (LyrStr *)&lyr_lit8;
#line 38
    t2 = l0_e;
#line 38
    t3_s = (lyr_opt_iface2){ .value = t2, .has = 1 }; t3 = &t3_s;
#line 38
    t4 = (lyr_ty1_Exception *)lyr_alloc(&lyr_desc_ty1_Exception);
#line 38
    LYR_WRITE_BARRIER(t4, &t4->f_text, t1);
#line 38
    LYR_WRITE_BARRIER_VALUE(t4, &t4->f_inner, *t3);
#line 38
    t5 = (LyrIface){ t4, &lyr_vt_ty2_ty1 };
#line 38
    lyr_e = lyr_err_new(t5); goto bb3;
bb2:;
#line 37
    goto bb4;
bb3:;
#line 38
    *lyr_err = lyr_e; return;
bb4:;
#line 36
    return;
}

#line 42 "programs/resources.lyr"
LYR_NOINLINE void lyr_main_main(void) {
    LyrIface l0_e = {0};
    LyrIface l1_e = {0};
    LyrIface l2_e = {0};
    LyrStr *l3_because = NULL;
    LyrErr *lyr_e = NULL;
    LyrIface t0 = {0};
    LyrStr *t1 = NULL;
    LyrIface t2 = {0};
    LyrStr *t3 = NULL;
    LyrIface t4 = {0};
    LyrStr *t5 = NULL;
    LyrStr *t6 = NULL;
    LyrIface t7 = {0};
    LyrStr *t8 = NULL;
    LyrIface t9 = {0};
    LyrStr *t10 = NULL;
    LyrStr *t11 = NULL;
    LyrIface t12 = {0};
    LyrIface t13 = {0};
    lyr_opt_iface2 t14_s = {0};
    lyr_opt_iface2 *t14 = &t14_s;
    LyrIface t15 = {0};
    LyrStr *t16 = NULL;
    LyrStr *t17 = NULL;
    LyrIface t18 = {0};
    LyrStr *t19 = NULL;
    LyrStr *t20 = NULL;
    LyrStr *t21 = NULL;
    LyrStr *t22 = NULL;
    LyrStr *t23 = NULL;
    LyrStr *t24 = NULL;
bb0:;
#line 42
    lyr_main_scope(&lyr_e);
#line 42
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 42
    t0 = lyr_e->value;
#line 42
    lyr_e = NULL;
#line 42
    t1 = (LyrStr *)&lyr_lit9;
#line 42
    lyr_println(t1);
#line 42
    goto bb3;
bb2:;
#line 42
    goto bb3;
bb3:;
#line 43
    lyr_main_closeFails(&lyr_e);
#line 43
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb4; goto bb5;
bb4:;
#line 43
    t2 = lyr_e->value;
#line 43
    lyr_e = NULL;
#line 43
    l0_e = t2;
#line 43
    t3 = (LyrStr *)&lyr_lit10;
#line 43
    t4 = l0_e;
#line 43
    t5 = ((const lyr_vt_ty2 *)t4.vt)->s0(t4);
#line 43
    t6 = lyr_str_concat(t3, t5);
#line 43
    lyr_println(t6);
#line 43
    goto bb6;
bb5:;
#line 43
    goto bb6;
bb6:;
#line 44
    lyr_main_bodyFails(&lyr_e);
#line 44
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb7; goto bb8;
bb7:;
#line 44
    t7 = lyr_e->value;
#line 44
    lyr_e = NULL;
#line 44
    l1_e = t7;
#line 44
    t8 = (LyrStr *)&lyr_lit10;
#line 44
    t9 = l1_e;
#line 44
    t10 = ((const lyr_vt_ty2 *)t9.vt)->s0(t9);
#line 44
    t11 = lyr_str_concat(t8, t10);
#line 44
    lyr_println(t11);
#line 44
    goto bb9;
bb8:;
#line 44
    goto bb9;
bb9:;
#line 45
    lyr_main_wrapped(&lyr_e);
#line 45
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb10; goto bb11;
bb10:;
#line 45
    t12 = lyr_e->value;
#line 45
    lyr_e = NULL;
#line 45
    l2_e = t12;
#line 46
    t13 = l2_e;
#line 46
    t14_s = ((const lyr_vt_ty2 *)t13.vt)->s1(t13); t14 = &t14_s;
#line 46
    if (LYR_UNLIKELY(!t14->has)) lyr_panic_null(); t15 = t14->value;
#line 46
    t16 = ((const lyr_vt_ty2 *)t15.vt)->s0(t15);
#line 46
    l3_because = t16;
#line 47
    t17 = (LyrStr *)&lyr_lit10;
#line 47
    t18 = l2_e;
#line 47
    t19 = ((const lyr_vt_ty2 *)t18.vt)->s0(t18);
#line 47
    t20 = (LyrStr *)&lyr_lit11;
#line 47
    t21 = l3_because;
#line 47
    t22 = lyr_str_concat(t17, t19);
#line 47
    t23 = lyr_str_concat(t22, t20);
#line 47
    t24 = lyr_str_concat(t23, t21);
#line 47
    lyr_println(t24);
#line 45
    goto bb12;
bb11:;
#line 45
    goto bb12;
bb12:;
#line 41
    return;
}

#line 11 "programs/resources.lyr"
void lyr_main_Res_close(lyr_ty0_Res *l0_this, LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    lyr_ty0_Res *t1 = NULL;
    LyrStr *t2 = NULL;
    LyrStr *t3 = NULL;
    lyr_ty0_Res *t4 = NULL;
    uint8_t t5 = 0;
    LyrStr *t6 = NULL;
    lyr_ty0_Res *t7 = NULL;
    LyrStr *t8 = NULL;
    LyrStr *t9 = NULL;
    LyrStr *t10 = NULL;
    LyrStr *t11 = NULL;
    lyr_opt_iface2 t12_s = {0};
    lyr_opt_iface2 *t12 = &t12_s;
    lyr_ty1_Exception *t13 = NULL;
    LyrIface t14 = {0};
bb0:;
#line 11
    t0 = (LyrStr *)&lyr_lit12;
#line 11
    t1 = l0_this;
#line 11
    t2 = t1->f_name;
#line 11
    t3 = lyr_str_concat(t0, t2);
#line 11
    lyr_println(t3);
#line 12
    t4 = l0_this;
#line 12
    t5 = t4->f_failing;
#line 12
    if (t5) goto bb1; else goto bb2;
bb1:;
#line 12
    t6 = (LyrStr *)&lyr_lit12;
#line 12
    t7 = l0_this;
#line 12
    t8 = t7->f_name;
#line 12
    t9 = (LyrStr *)&lyr_lit13;
#line 12
    t10 = lyr_str_concat(t6, t8);
#line 12
    t11 = lyr_str_concat(t10, t9);
#line 120 "stdlib5/std/core.lyr"
    t12_s = (lyr_opt_iface2){0}; t12 = &t12_s;
#line 12 "programs/resources.lyr"
    t13 = (lyr_ty1_Exception *)lyr_alloc(&lyr_desc_ty1_Exception);
#line 12
    LYR_WRITE_BARRIER(t13, &t13->f_text, t11);
#line 12
    LYR_WRITE_BARRIER_VALUE(t13, &t13->f_inner, *t12);
#line 12
    t14 = (LyrIface){ t13, &lyr_vt_ty2_ty1 };
#line 12
    lyr_e = lyr_err_new(t14); goto bb3;
bb2:;
#line 10
    return;
bb3:;
#line 12
    *lyr_err = lyr_e; return;
}

#line 123 "stdlib5/std/core.lyr"
LyrStr * lyr_std_core_Exception_message(lyr_ty1_Exception *l0_this) {
    lyr_ty1_Exception *t0 = NULL;
    LyrStr *t1 = NULL;
bb0:;
#line 123
    t0 = l0_this;
#line 123
    t1 = t0->f_text;
#line 123
    return t1;
}

#line 127 "stdlib5/std/core.lyr"
lyr_opt_iface2 lyr_std_core_Exception_cause(lyr_ty1_Exception *l0_this) {
    lyr_ty1_Exception *t0 = NULL;
    lyr_opt_iface2 t1_s = {0};
    lyr_opt_iface2 *t1 = &t1_s;
bb0:;
#line 127
    t0 = l0_this;
#line 127
    t1 = &t0->f_inner;
#line 127
    return *t1;
}

#line 1387 "stdlib5/std/core.lyr"
void lyr__globals__9ee5f9b5(void) {
    uint64_t t0 = 0;
    double t1 = 0;
    uint64_t t2 = 0;
    double t3 = 0;
    uint64_t t4 = 0;
    float t5 = 0;
    uint64_t t6 = 0;
    float t7 = 0;
    uint64_t t8 = 0;
    uint64_t t9 = 0;
    uint64_t t10 = 0;
bb0:;
#line 1387
    t0 = (uint64_t)UINT64_C(9218868437227405312);
#line 1387
    t1 = lyr_std_core__extend__float_fromBits_3825afc5(t0);
#line 1387
    lyr_g0_float_infinity = t1;
#line 1388
    t2 = (uint64_t)UINT64_C(9221120237041090560);
#line 1388
    t3 = lyr_std_core__extend__float_fromBits_3825afc5(t2);
#line 1388
    lyr_g1_float_nan = t3;
#line 1408
    t4 = (uint64_t)UINT64_C(2139095040);
#line 1408
    t5 = lyr_std_core__extend__float32_fromBits_bc3641ce(t4);
#line 1408
    lyr_g2_float32_infinity = t5;
#line 1409
    t6 = (uint64_t)UINT64_C(2143289344);
#line 1409
    t7 = lyr_std_core__extend__float32_fromBits_bc3641ce(t6);
#line 1409
    lyr_g3_float32_nan = t7;
#line 14 "stdlib5/std/collections.lyr"
    t8 = (uint64_t)UINT64_C(9259542123273814144);
#line 14
    lyr_g4_emptyGroup = t8;
#line 15
    t9 = (uint64_t)UINT64_C(72340172838076673);
#line 15
    lyr_g5_lowBits = t9;
#line 16
    t10 = (uint64_t)UINT64_C(9259542123273814144);
#line 16
    lyr_g6_highBits = t10;
    return;
}

#line 1394 "stdlib5/std/core.lyr"
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b) {
    uint64_t t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 1394
    t0 = l0_b;
#line 1384
    t1 = (double)0.0;
#line 1394
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1394
    return t2;
}

#line 1415 "stdlib5/std/core.lyr"
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b) {
    uint64_t t0 = 0;
    float t1 = 0;
    float t2 = 0;
bb0:;
#line 1415
    t0 = l0_b;
#line 1405
    t1 = (float)0.0;
#line 1415
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1415
    return t2;
}


/* the program */
static int64_t lyr_entry(void) { lyr__globals__9ee5f9b5(); lyr_main_main(); return 0; }
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_entry); }
