/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>

/* structs, by value */
typedef struct lyr_ty0_Point {
    int64_t f_x;
    int64_t f_y;
} lyr_ty0_Point;
typedef struct lyr_ty1_Segment {
    lyr_ty0_Point f_a;
    lyr_ty0_Point f_b;
} lyr_ty1_Segment;

/* prototypes */
static lyr_ty0_Point lyr_main_shift(lyr_ty0_Point l0_p, int64_t l1_dx);
static int64_t lyr_main_main(void);

#line 7 "programs/structs.lyr"
static lyr_ty0_Point lyr_main_shift(lyr_ty0_Point l0_p, int64_t l1_dx) {
    lyr_ty0_Point l2_q = {0};
    lyr_ty0_Point t0_s = {0};
    lyr_ty0_Point *t0 = &t0_s;
    lyr_ty0_Point t1_s = {0};
    lyr_ty0_Point *t1 = &t1_s;
    lyr_ty0_Point t2_s = {0};
    lyr_ty0_Point *t2 = &t2_s;
    lyr_ty0_Point t3_s = {0};
    lyr_ty0_Point *t3 = &t3_s;
    int64_t t4 = 0;
    int64_t t5 = 0;
    int64_t t6 = 0;
    lyr_ty0_Point t7_s = {0};
    lyr_ty0_Point *t7 = &t7_s;
    lyr_ty0_Point t8_s = {0};
    lyr_ty0_Point *t8 = &t8_s;
bb0:;
#line 7
    t0 = &l0_p;
#line 7
    t1_s = *t0; t1 = &t1_s;
#line 7
    l2_q = *t1;
#line 8
    t2 = &l2_q;
#line 8
    t3 = &l2_q;
#line 8
    t4 = t3->f_x;
#line 8
    t5 = l1_dx;
#line 8
    t6 = LYR_CHECKED_ADD(t4, t5);
#line 8
    t2->f_x = t6;
#line 9
    t7 = &l2_q;
#line 9
    t8_s = *t7; t8 = &t8_s;
#line 9
    return *t8;
}

#line 13 "programs/structs.lyr"
static int64_t lyr_main_main(void) {
    lyr_ty0_Point l0_p = {0};
    lyr_ty1_Segment l1_s = {0};
    int64_t t0 = 0;
    int64_t t1 = 0;
    lyr_ty0_Point t2_s = {0};
    lyr_ty0_Point *t2 = &t2_s;
    lyr_ty0_Point t3_s = {0};
    lyr_ty0_Point *t3 = &t3_s;
    lyr_ty0_Point t4_s = {0};
    lyr_ty0_Point *t4 = &t4_s;
    lyr_ty0_Point t5_s = {0};
    lyr_ty0_Point *t5 = &t5_s;
    lyr_ty0_Point t6_s = {0};
    lyr_ty0_Point *t6 = &t6_s;
    int64_t t7 = 0;
    lyr_ty0_Point t8_s = {0};
    lyr_ty0_Point *t8 = &t8_s;
    lyr_ty1_Segment t9_s = {0};
    lyr_ty1_Segment *t9 = &t9_s;
    lyr_ty0_Point t10_s = {0};
    lyr_ty0_Point *t10 = &t10_s;
    int64_t t11 = 0;
    lyr_ty1_Segment t12_s = {0};
    lyr_ty1_Segment *t12 = &t12_s;
    lyr_ty0_Point t13_s = {0};
    lyr_ty0_Point *t13 = &t13_s;
    int64_t t14 = 0;
    int64_t t15 = 0;
    uint8_t t16 = 0;
    int64_t t17 = 0;
    lyr_ty1_Segment t18_s = {0};
    lyr_ty1_Segment *t18 = &t18_s;
    lyr_ty0_Point t19_s = {0};
    lyr_ty0_Point *t19 = &t19_s;
    int64_t t20 = 0;
    lyr_ty1_Segment t21_s = {0};
    lyr_ty1_Segment *t21 = &t21_s;
    lyr_ty0_Point t22_s = {0};
    lyr_ty0_Point *t22 = &t22_s;
    int64_t t23 = 0;
    int64_t t24 = 0;
    lyr_ty0_Point t25_s = {0};
    lyr_ty0_Point *t25 = &t25_s;
    int64_t t26 = 0;
    int64_t t27 = 0;
bb0:;
#line 13
    t0 = (int64_t)INT64_C(1);
#line 13
    t1 = (int64_t)INT64_C(2);
#line 13
    t2_s = (lyr_ty0_Point){0}; t2 = &t2_s;
#line 13
    t2->f_x = t0;
#line 13
    t2->f_y = t1;
#line 13
    l0_p = *t2;
#line 14
    t3 = &l0_p;
#line 14
    t4_s = *t3; t4 = &t4_s;
#line 14
    t5 = &l0_p;
#line 14
    t6_s = *t5; t6 = &t6_s;
#line 14
    t7 = (int64_t)INT64_C(10);
#line 14
    t8_s = lyr_main_shift(*t6, t7); t8 = &t8_s;
#line 14
    t9_s = (lyr_ty1_Segment){0}; t9 = &t9_s;
#line 14
    t9->f_a = *t4;
#line 14
    t9->f_b = *t8;
#line 14
    l1_s = *t9;
#line 15
    t10 = &l0_p;
#line 15
    t11 = (int64_t)INT64_C(5);
#line 15
    t10->f_y = t11;
#line 16
    t12 = &l1_s;
#line 16
    t13 = &t12->f_a;
#line 16
    t14 = t13->f_y;
#line 16
    t15 = (int64_t)INT64_C(2);
#line 16
    t16 = (uint8_t)(t14 != t15);
#line 16
    if (t16) goto bb1; else goto bb2;
bb1:;
#line 16
    t17 = (int64_t)INT64_C(1);
#line 16
    return t17;
bb2:;
#line 17
    t18 = &l1_s;
#line 17
    t19 = &t18->f_b;
#line 17
    t20 = t19->f_x;
#line 17
    t21 = &l1_s;
#line 17
    t22 = &t21->f_a;
#line 17
    t23 = t22->f_y;
#line 17
    t24 = LYR_CHECKED_ADD(t20, t23);
#line 17
    t25 = &l0_p;
#line 17
    t26 = t25->f_y;
#line 17
    t27 = LYR_CHECKED_ADD(t24, t26);
#line 17
    return t27;
}


/* the program */
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_main_main); }
