/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty0_ParseError lyr_ty0_ParseError;
typedef struct lyr_ty1_ParseError_Empty lyr_ty1_ParseError_Empty;
typedef struct lyr_ty2_ParseError_BadDigit lyr_ty2_ParseError_BadDigit;
typedef struct lyr_vt_ty3 lyr_vt_ty3;
const char lyr_ifid_ty3[] = "std.core.Error";
typedef struct lyr_ty4_Disk lyr_ty4_Disk;
typedef struct lyr_vt_ty5 lyr_vt_ty5;
const char lyr_ifid_ty5[] = "main.IoError";
typedef struct lyr_ty6_ParseError lyr_ty6_ParseError;
typedef struct lyr_ty7_ParseErrorKind lyr_ty7_ParseErrorKind;
typedef struct lyr_ty8_ParseErrorKind_Empty lyr_ty8_ParseErrorKind_Empty;
typedef struct lyr_ty9_ParseErrorKind_Invalid lyr_ty9_ParseErrorKind_Invalid;
typedef struct lyr_ty10_ParseErrorKind_Overflow lyr_ty10_ParseErrorKind_Overflow;
typedef struct lyr_ty11_FormatSpec lyr_ty11_FormatSpec;
typedef struct lyr_ty12_Chars lyr_ty12_Chars;
typedef struct lyr_ty13_StringBuilder lyr_ty13_StringBuilder;
typedef struct lyr_ty14_Ordering lyr_ty14_Ordering;
typedef struct lyr_ty15_Ordering_Less lyr_ty15_Ordering_Less;
typedef struct lyr_ty16_Ordering_Equal lyr_ty16_Ordering_Equal;
typedef struct lyr_ty17_Ordering_Greater lyr_ty17_Ordering_Greater;
typedef struct lyr_ty18_Exception lyr_ty18_Exception;
typedef struct lyr_vt_ty19 lyr_vt_ty19;
const char lyr_ifid_ty19[] = "std.core.Hasher";
typedef struct lyr_ty20_Split lyr_ty20_Split;
typedef struct lyr_ty21_Lines lyr_ty21_Lines;
typedef struct lyr_ty22__env_std_core_StringBuilder_reserve_ lyr_ty22__env_std_core_StringBuilder_reserve_;
typedef struct lyr_ty23_Sip lyr_ty23_Sip;
typedef struct lyr_ty24_DefaultHasher lyr_ty24_DefaultHasher;
typedef struct lyr_ty25_FixedHasher lyr_ty25_FixedHasher;
typedef struct lyr_ty26_Fnv1a64 lyr_ty26_Fnv1a64;
struct lyr_ty1_ParseError_Empty {
    uint8_t lyr_unit;
};
struct lyr_ty2_ParseError_BadDigit {
    uint32_t f_0;
    int64_t f_1;
};
struct lyr_ty0_ParseError { uint32_t tag; union { lyr_ty2_ParseError_BadDigit v1; } as; };
_Static_assert(sizeof(lyr_ty0_ParseError) == 24, "layout of lyr_ty0_ParseError");
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface3;
struct lyr_vt_ty3 {
    const LyrDesc *desc;
    LyrStr * (*s0)(LyrIface);
    lyr_opt_iface3 (*s1)(LyrIface);
};
struct lyr_ty4_Disk {
    LyrObj header;
};
_Static_assert(sizeof(lyr_ty4_Disk) == 8, "layout of lyr_ty4_Disk");
extern const LyrItable lyr_itab_ty4[];
const LyrDesc lyr_desc_ty4_Disk = { sizeof(lyr_ty4_Disk), 0, 0, 0, NULL, "main.Disk", lyr_itab_ty4 };
struct lyr_vt_ty5 {
    const LyrDesc *desc;
    LyrStr * (*s0)(LyrIface);
    lyr_opt_iface3 (*s1)(LyrIface);
};
struct lyr_ty8_ParseErrorKind_Empty {
    uint8_t lyr_unit;
};
struct lyr_ty9_ParseErrorKind_Invalid {
    uint8_t lyr_unit;
};
struct lyr_ty10_ParseErrorKind_Overflow {
    uint8_t lyr_unit;
};
struct lyr_ty7_ParseErrorKind { uint32_t tag; };
_Static_assert(sizeof(lyr_ty7_ParseErrorKind) == 4, "layout of lyr_ty7_ParseErrorKind");
struct lyr_ty6_ParseError {
    lyr_ty7_ParseErrorKind f_kind;
};
struct lyr_ty11_FormatSpec {
    uint32_t f_fill;
    uint32_t f_align;
    uint8_t f_plus;
    uint8_t f_alternate;
    int64_t f_width;
    uint32_t f_grouping;
    int64_t f_precision;
    uint32_t f_kind;
};
struct lyr_ty12_Chars {
    LyrStr *f_s;
    int64_t f_at;
};
struct lyr_ty13_StringBuilder {
    LyrObj header;
    LyrArr *f_bytes;
    int64_t f_count;
};
_Static_assert(sizeof(lyr_ty13_StringBuilder) == 24, "layout of lyr_ty13_StringBuilder");
_Static_assert(offsetof(lyr_ty13_StringBuilder, f_bytes) == 8, "layout of lyr_ty13_StringBuilder");
_Static_assert(offsetof(lyr_ty13_StringBuilder, f_count) == 16, "layout of lyr_ty13_StringBuilder");
static const uint64_t lyr_refmap_ty13[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty13_StringBuilder = { sizeof(lyr_ty13_StringBuilder), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty13, "std.core.StringBuilder", NULL };
struct lyr_ty15_Ordering_Less {
    uint8_t lyr_unit;
};
struct lyr_ty16_Ordering_Equal {
    uint8_t lyr_unit;
};
struct lyr_ty17_Ordering_Greater {
    uint8_t lyr_unit;
};
struct lyr_ty14_Ordering { uint32_t tag; };
_Static_assert(sizeof(lyr_ty14_Ordering) == 4, "layout of lyr_ty14_Ordering");
struct lyr_ty18_Exception {
    LyrObj header;
    LyrStr *f_text;
    lyr_opt_iface3 f_inner;
};
_Static_assert(sizeof(lyr_ty18_Exception) == 40, "layout of lyr_ty18_Exception");
_Static_assert(offsetof(lyr_ty18_Exception, f_text) == 8, "layout of lyr_ty18_Exception");
_Static_assert(offsetof(lyr_ty18_Exception, f_inner) == 16, "layout of lyr_ty18_Exception");
static const uint64_t lyr_refmap_ty18[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty18_Exception = { sizeof(lyr_ty18_Exception), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty18, "std.core.Exception", NULL };
struct lyr_vt_ty19 {
    const LyrDesc *desc;
    void (*s0)(LyrIface);
    void (*s1)(LyrIface);
    void (*s2)(LyrIface);
    void (*s3)(LyrIface);
    void (*s4)(LyrIface);
};
struct lyr_ty20_Split {
    LyrStr *f_s;
    LyrStr *f_sep;
    int64_t f_at;
    uint8_t f_done;
};
struct lyr_ty21_Lines {
    LyrStr *f_s;
    int64_t f_at;
};
struct lyr_ty22__env_std_core_StringBuilder_reserve_ {
    LyrObj header;
    int64_t f_kept;
    LyrArr *f_old;
};
_Static_assert(sizeof(lyr_ty22__env_std_core_StringBuilder_reserve_) == 24, "layout of lyr_ty22__env_std_core_StringBuilder_reserve_");
_Static_assert(offsetof(lyr_ty22__env_std_core_StringBuilder_reserve_, f_kept) == 8, "layout of lyr_ty22__env_std_core_StringBuilder_reserve_");
_Static_assert(offsetof(lyr_ty22__env_std_core_StringBuilder_reserve_, f_old) == 16, "layout of lyr_ty22__env_std_core_StringBuilder_reserve_");
static const uint64_t lyr_refmap_ty22[] = { UINT64_C(0x4) };
const LyrDesc lyr_desc_ty22__env_std_core_StringBuilder_reserve_ = { sizeof(lyr_ty22__env_std_core_StringBuilder_reserve_), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty22, "<env:std.core.StringBuilder.reserve>", NULL };
struct lyr_ty23_Sip {
    uint64_t f_v0;
    uint64_t f_v1;
    uint64_t f_v2;
    uint64_t f_v3;
    uint64_t f_tail;
    int64_t f_pending;
    int64_t f_length;
};
struct lyr_ty24_DefaultHasher {
    lyr_ty23_Sip f_state;
};
struct lyr_ty25_FixedHasher {
    lyr_ty23_Sip f_state;
};
struct lyr_ty26_Fnv1a64 {
    uint64_t f_state;
};
typedef struct { int64_t value; uint8_t has; } lyr_opt_i64;
typedef struct { lyr_opt_i64 value; uint8_t has; } lyr_opt_opt_i64;
_Static_assert(sizeof(LyrStr *) == 8, "layout of string[]");
static const uint64_t lyr_refmap_arr_str[] = { UINT64_C(0x1) };
const LyrDesc lyr_desc_arr_str = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY | LYR_DESC_HAS_REFS, sizeof(LyrStr *), 1, lyr_refmap_arr_str, "string[]", NULL };
_Static_assert(sizeof(uint8_t) == 1, "layout of u8[]");
const LyrDesc lyr_desc_arr_u8 = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY, sizeof(uint8_t), 0, NULL, "u8[]", NULL };
typedef struct { LyrObj header; lyr_ty0_ParseError value; } lyr_box_ty0_ParseError;
_Static_assert(sizeof(lyr_box_ty0_ParseError) == 32, "layout of lyr_box_ty0_ParseError");
_Static_assert(offsetof(lyr_box_ty0_ParseError, value) == 8, "layout of lyr_box_ty0_ParseError");
extern const LyrItable lyr_itab_ty0[];
const LyrDesc lyr_desc_box_ty0_ParseError = { sizeof(lyr_box_ty0_ParseError), 0, 0, 0, NULL, "box<ParseError>", lyr_itab_ty0 };

/* module-level bindings */
double lyr_g0_float_infinity = 0;
double lyr_g1_float_nan = 0;
float lyr_g2_float32_infinity = 0;
float lyr_g3_float32_nan = 0;
uint64_t lyr_g4_emptyGroup = 0;
uint64_t lyr_g5_lowBits = 0;
uint64_t lyr_g6_highBits = 0;

/* string literals */
static const LyrStaticStr(1) lyr_lit0 = LYR_STR_INIT("");
static const LyrStaticStr(2) lyr_lit1 = LYR_STR_INIT("x");
static const LyrStaticStr(5) lyr_lit2 = LYR_STR_INIT("none");
static const LyrStaticStr(5) lyr_lit3 = LYR_STR_INIT("data");
static const LyrStaticStr(6) lyr_lit4 = LYR_STR_INIT("saved");
static const LyrStaticStr(16) lyr_lit5 = LYR_STR_INIT("defer in callee");
static const LyrStaticStr(2) lyr_lit6 = LYR_STR_INIT("1");
static const LyrStaticStr(3) lyr_lit7 = LYR_STR_INIT("a ");
static const LyrStaticStr(4) lyr_lit8 = LYR_STR_INIT(" b ");
static const LyrStaticStr(2) lyr_lit9 = LYR_STR_INIT("2");
static const LyrStaticStr(3) lyr_lit10 = LYR_STR_INIT("c ");
static const LyrStaticStr(2) lyr_lit11 = LYR_STR_INIT(" ");
static const LyrStaticStr(3) lyr_lit12 = LYR_STR_INIT("d ");
static const LyrStaticStr(3) lyr_lit13 = LYR_STR_INIT("e ");
static const LyrStaticStr(2) lyr_lit14 = LYR_STR_INIT("3");
static const LyrStaticStr(3) lyr_lit15 = LYR_STR_INIT("f ");
static const LyrStaticStr(3) lyr_lit16 = LYR_STR_INIT("g ");
static const LyrStaticStr(10) lyr_lit17 = LYR_STR_INIT("h caught ");
static const LyrStaticStr(9) lyr_lit18 = LYR_STR_INIT("fallback");
static const LyrStaticStr(3) lyr_lit19 = LYR_STR_INIT("h ");
static const LyrStaticStr(6) lyr_lit20 = LYR_STR_INIT("never");
static const LyrStaticStr(3) lyr_lit21 = LYR_STR_INIT("i ");
static const LyrStaticStr(3) lyr_lit22 = LYR_STR_INIT("j ");
static const LyrStaticStr(3) lyr_lit23 = LYR_STR_INIT("k ");
static const LyrStaticStr(14) lyr_lit24 = LYR_STR_INIT("save failed: ");
static const LyrStaticStr(2) lyr_lit25 = LYR_STR_INIT("4");
static const LyrStaticStr(5) lyr_lit26 = LYR_STR_INIT("sum ");
static const LyrStaticStr(3) lyr_lit27 = LYR_STR_INIT("m ");
static const LyrStaticStr(6) lyr_lit28 = LYR_STR_INIT("parse");
static const LyrStaticStr(5) lyr_lit29 = LYR_STR_INIT("disk");

/* prototypes */
int64_t lyr_main_parse(LyrStr *l0_s, LyrErr **lyr_err);
lyr_opt_i64 lyr_main_maybe(LyrStr *l0_s, LyrErr **lyr_err);
LyrStr * lyr_main_read(uint8_t l0_ok, LyrErr **lyr_err);
void lyr_main_save(uint8_t l0_ok, LyrErr **lyr_err);
int64_t lyr_main_withDefer(LyrErr **lyr_err);
LYR_NOINLINE void lyr_main_main(void);
LyrStr * lyr_main_ParseError_message(lyr_ty0_ParseError *l0_this);
LyrStr * lyr_main_Disk_message(lyr_ty4_Disk *l0_this);
lyr_opt_iface3 lyr_std_core_Error_cause(LyrIface l0_this);
void lyr__globals__9ee5f9b5(void);
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b);
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b);

/* interface tables: the descriptor, then the implementation of every slot */
static LyrStr * lyr_vt_ty3_ty0_s0(LyrIface self) { return lyr_main_ParseError_message(&((lyr_box_ty0_ParseError *)self.data)->value); }
const lyr_vt_ty3 lyr_vt_ty3_ty0 = { &lyr_desc_box_ty0_ParseError, lyr_vt_ty3_ty0_s0, lyr_std_core_Error_cause };
static LyrStr * lyr_vt_ty3_ty4_s0(LyrIface self) { return lyr_main_Disk_message((lyr_ty4_Disk *)self.data); }
const lyr_vt_ty3 lyr_vt_ty3_ty4 = { &lyr_desc_ty4_Disk, lyr_vt_ty3_ty4_s0, lyr_std_core_Error_cause };
static LyrStr * lyr_vt_ty5_ty4_s0(LyrIface self) { return lyr_main_Disk_message((lyr_ty4_Disk *)self.data); }
const lyr_vt_ty5 lyr_vt_ty5_ty4 = { &lyr_desc_ty4_Disk, lyr_vt_ty5_ty4_s0, lyr_std_core_Error_cause };
const LyrItable lyr_itab_ty0[] = { { lyr_ifid_ty3, &lyr_vt_ty3_ty0 } , { NULL, NULL } };
const LyrItable lyr_itab_ty4[] = { { lyr_ifid_ty3, &lyr_vt_ty3_ty4 }, { lyr_ifid_ty5, &lyr_vt_ty5_ty4 } , { NULL, NULL } };

/* the members of Error the runtime reports through */
const LyrStr *lyr_error_message(LyrIface e) { return ((const lyr_vt_ty3 *)e.vt)->s0(e); }
int lyr_error_cause(LyrIface e, LyrIface *next) { lyr_opt_iface3 c = ((const lyr_vt_ty3 *)e.vt)->s1(e); *next = c.value; return c.has; }

#line 11 "programs/try_forms.lyr"
int64_t lyr_main_parse(LyrStr *l0_s, LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    LyrStr *t1 = NULL;
    uint8_t t2 = 0;
    lyr_ty0_ParseError t3_s = {0};
    lyr_ty0_ParseError *t3 = &t3_s;
    LyrIface t4 = {0};
    LyrStr *t5 = NULL;
    LyrStr *t6 = NULL;
    uint8_t t7 = 0;
    uint32_t t8 = 0;
    int64_t t9 = 0;
    lyr_ty0_ParseError t10_s = {0};
    lyr_ty0_ParseError *t10 = &t10_s;
    LyrIface t11 = {0};
    int64_t t12 = 0;
bb0:;
#line 11
    t0 = l0_s;
#line 11
    t1 = (LyrStr *)&lyr_lit0;
#line 11
    t2 = (uint8_t)lyr_str_eq(t0, t1);
#line 11
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 11
    t3_s = (lyr_ty0_ParseError){ .tag = 0 }; t3 = &t3_s;
#line 11
    { lyr_box_ty0_ParseError *lyr_box = lyr_alloc(&lyr_desc_box_ty0_ParseError); lyr_box->value = *t3; t4 = (LyrIface){ lyr_box, &lyr_vt_ty3_ty0 }; }
#line 11
    lyr_e = lyr_err_new(t4); goto bb3;
bb2:;
#line 12
    t5 = l0_s;
#line 12
    t6 = (LyrStr *)&lyr_lit1;
#line 12
    t7 = (uint8_t)lyr_str_eq(t5, t6);
#line 12
    if (t7) goto bb4; else goto bb5;
bb3:;
#line 11
    *lyr_err = lyr_e; return 0;
bb4:;
#line 12
    t8 = (uint32_t)120;
#line 12
    t9 = (int64_t)INT64_C(0);
#line 12
    t10_s = (lyr_ty0_ParseError){ .tag = 1, .as.v1 = { .f_0 = t8, .f_1 = t9 } }; t10 = &t10_s;
#line 12
    { lyr_box_ty0_ParseError *lyr_box = lyr_alloc(&lyr_desc_box_ty0_ParseError); lyr_box->value = *t10; t11 = (LyrIface){ lyr_box, &lyr_vt_ty3_ty0 }; }
#line 12
    lyr_e = lyr_err_new(t11); goto bb3;
bb5:;
#line 13
    t12 = (int64_t)INT64_C(42);
#line 13
    return t12;
}

#line 17 "programs/try_forms.lyr"
lyr_opt_i64 lyr_main_maybe(LyrStr *l0_s, LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    LyrStr *t1 = NULL;
    uint8_t t2 = 0;
    lyr_opt_i64 t3_s = {0};
    lyr_opt_i64 *t3 = &t3_s;
    LyrStr *t4 = NULL;
    int64_t t5 = 0;
    lyr_opt_i64 t6_s = {0};
    lyr_opt_i64 *t6 = &t6_s;
bb0:;
#line 17
    t0 = l0_s;
#line 17
    t1 = (LyrStr *)&lyr_lit2;
#line 17
    t2 = (uint8_t)lyr_str_eq(t0, t1);
#line 17
    if (t2) goto bb1; else goto bb2;
bb1:;
#line 17
    t3_s = (lyr_opt_i64){0}; t3 = &t3_s;
#line 17
    return *t3;
bb2:;
#line 18
    t4 = l0_s;
#line 18
    t5 = lyr_main_parse(t4, &lyr_e);
#line 18
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb3; goto bb4;
bb3:;
#line 18
    *lyr_err = lyr_e; return (lyr_opt_i64){0};
bb4:;
#line 18
    t6_s = (lyr_opt_i64){ .value = t5, .has = 1 }; t6 = &t6_s;
#line 18
    return *t6;
}

#line 22 "programs/try_forms.lyr"
LyrStr * lyr_main_read(uint8_t l0_ok, LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    uint8_t t0 = 0;
    uint8_t t1 = 0;
    lyr_ty4_Disk *t2 = NULL;
    LyrIface t3 = {0};
    LyrStr *t4 = NULL;
bb0:;
#line 22
    t0 = l0_ok;
#line 22
    t1 = (uint8_t)!t0;
#line 22
    if (t1) goto bb1; else goto bb2;
bb1:;
#line 22
    t2 = (lyr_ty4_Disk *)lyr_alloc(&lyr_desc_ty4_Disk);
#line 22
    t3 = (LyrIface){ t2, &lyr_vt_ty3_ty4 };
#line 22
    lyr_e = lyr_err_new(t3); goto bb3;
bb2:;
#line 23
    t4 = (LyrStr *)&lyr_lit3;
#line 23
    return t4;
bb3:;
#line 22
    *lyr_err = lyr_e; return NULL;
}

#line 27 "programs/try_forms.lyr"
void lyr_main_save(uint8_t l0_ok, LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    uint8_t t0 = 0;
    uint8_t t1 = 0;
    lyr_ty4_Disk *t2 = NULL;
    LyrIface t3 = {0};
    LyrStr *t4 = NULL;
bb0:;
#line 27
    t0 = l0_ok;
#line 27
    t1 = (uint8_t)!t0;
#line 27
    if (t1) goto bb1; else goto bb2;
bb1:;
#line 27
    t2 = (lyr_ty4_Disk *)lyr_alloc(&lyr_desc_ty4_Disk);
#line 27
    t3 = (LyrIface){ t2, &lyr_vt_ty3_ty4 };
#line 27
    lyr_e = lyr_err_new(t3); goto bb3;
bb2:;
#line 28
    t4 = (LyrStr *)&lyr_lit4;
#line 28
    lyr_println(t4);
#line 26
    return;
bb3:;
#line 27
    *lyr_err = lyr_e; return;
}

#line 33 "programs/try_forms.lyr"
int64_t lyr_main_withDefer(LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    lyr_ty4_Disk *t0 = NULL;
    LyrIface t1 = {0};
    LyrStr *t2 = NULL;
bb0:;
#line 33
    t0 = (lyr_ty4_Disk *)lyr_alloc(&lyr_desc_ty4_Disk);
#line 33
    t1 = (LyrIface){ t0, &lyr_vt_ty3_ty4 };
#line 33
    lyr_e = lyr_err_new(t1); goto bb1;
bb1:;
#line 32
    t2 = (LyrStr *)&lyr_lit5;
#line 32
    lyr_println(t2);
#line 33
    goto bb2;
bb2:;
#line 33
    *lyr_err = lyr_e; return 0;
}

#line 37 "programs/try_forms.lyr"
LYR_NOINLINE void lyr_main_main(void) {
    lyr_opt_i64 l0_a = {0};
    lyr_opt_i64 l1__try0 = {0};
    lyr_opt_i64 l2_b = {0};
    lyr_opt_i64 l3__try1 = {0};
    int64_t l4__coalesce2 = 0;
    int64_t l5__coalesce3 = 0;
    lyr_opt_opt_i64 l6_c = {0};
    lyr_opt_opt_i64 l7__try4 = {0};
    lyr_opt_opt_i64 l8_d = {0};
    lyr_opt_opt_i64 l9__try5 = {0};
    lyr_opt_opt_i64 l10_e = {0};
    lyr_opt_opt_i64 l11__try6 = {0};
    int64_t l12__coalesce7 = 0;
    int64_t l13__coalesce8 = 0;
    int64_t l14_f = 0;
    int64_t l15_g = 0;
    int64_t l16__try9 = 0;
    LyrStr *l17_h = NULL;
    LyrStr *l18__try10 = NULL;
    LyrIface l19_err = {0};
    LyrStr *l20_i = NULL;
    LyrStr *l21__try11 = NULL;
    int64_t l22_j = 0;
    int64_t l23__try12 = 0;
    LyrStr *l24_none = NULL;
    LyrStr *l25_k = NULL;
    LyrStr *l26__try13 = NULL;
    LyrStr *l27__try14 = NULL;
    LyrStr *l28__coalesce15 = NULL;
    LyrIface l29_err = {0};
    LyrArr *l30_inputs = NULL;
    int64_t l31_sum = 0;
    int64_t l32_at = 0;
    LyrStr *l33_s = NULL;
    int64_t l34_n = 0;
    int64_t l35__try16 = 0;
    int64_t l36_m = 0;
    int64_t l37__try17 = 0;
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    int64_t t1 = 0;
    lyr_opt_i64 t2_s = {0};
    lyr_opt_i64 *t2 = &t2_s;
    lyr_opt_i64 t3_s = {0};
    lyr_opt_i64 *t3 = &t3_s;
    lyr_opt_i64 t4_s = {0};
    lyr_opt_i64 *t4 = &t4_s;
    LyrStr *t5 = NULL;
    int64_t t6 = 0;
    lyr_opt_i64 t7_s = {0};
    lyr_opt_i64 *t7 = &t7_s;
    lyr_opt_i64 t8_s = {0};
    lyr_opt_i64 *t8 = &t8_s;
    lyr_opt_i64 t9_s = {0};
    lyr_opt_i64 *t9 = &t9_s;
    LyrStr *t10 = NULL;
    lyr_opt_i64 t11_s = {0};
    lyr_opt_i64 *t11 = &t11_s;
    uint8_t t12 = 0;
    int64_t t13 = 0;
    int64_t t14 = 0;
    int64_t t15 = 0;
    LyrStr *t16 = NULL;
    LyrStr *t17 = NULL;
    lyr_opt_i64 t18_s = {0};
    lyr_opt_i64 *t18 = &t18_s;
    uint8_t t19 = 0;
    int64_t t20 = 0;
    int64_t t21 = 0;
    int64_t t22 = 0;
    LyrStr *t23 = NULL;
    LyrStr *t24 = NULL;
    LyrStr *t25 = NULL;
    LyrStr *t26 = NULL;
    LyrStr *t27 = NULL;
    lyr_opt_i64 t28_s = {0};
    lyr_opt_i64 *t28 = &t28_s;
    lyr_opt_opt_i64 t29_s = {0};
    lyr_opt_opt_i64 *t29 = &t29_s;
    lyr_opt_opt_i64 t30_s = {0};
    lyr_opt_opt_i64 *t30 = &t30_s;
    lyr_opt_opt_i64 t31_s = {0};
    lyr_opt_opt_i64 *t31 = &t31_s;
    LyrStr *t32 = NULL;
    lyr_opt_i64 t33_s = {0};
    lyr_opt_i64 *t33 = &t33_s;
    lyr_opt_opt_i64 t34_s = {0};
    lyr_opt_opt_i64 *t34 = &t34_s;
    lyr_opt_opt_i64 t35_s = {0};
    lyr_opt_opt_i64 *t35 = &t35_s;
    lyr_opt_opt_i64 t36_s = {0};
    lyr_opt_opt_i64 *t36 = &t36_s;
    LyrStr *t37 = NULL;
    lyr_opt_i64 t38_s = {0};
    lyr_opt_i64 *t38 = &t38_s;
    lyr_opt_opt_i64 t39_s = {0};
    lyr_opt_opt_i64 *t39 = &t39_s;
    lyr_opt_opt_i64 t40_s = {0};
    lyr_opt_opt_i64 *t40 = &t40_s;
    lyr_opt_opt_i64 t41_s = {0};
    lyr_opt_opt_i64 *t41 = &t41_s;
    LyrStr *t42 = NULL;
    lyr_opt_opt_i64 t43_s = {0};
    lyr_opt_opt_i64 *t43 = &t43_s;
    uint8_t t44 = 0;
    LyrStr *t45 = NULL;
    LyrStr *t46 = NULL;
    lyr_opt_opt_i64 t47_s = {0};
    lyr_opt_opt_i64 *t47 = &t47_s;
    lyr_opt_i64 t48_s = {0};
    lyr_opt_i64 *t48 = &t48_s;
    uint8_t t49 = 0;
    int64_t t50 = 0;
    int64_t t51 = 0;
    int64_t t52 = 0;
    LyrStr *t53 = NULL;
    LyrStr *t54 = NULL;
    LyrStr *t55 = NULL;
    LyrStr *t56 = NULL;
    LyrStr *t57 = NULL;
    lyr_opt_opt_i64 t58_s = {0};
    lyr_opt_opt_i64 *t58 = &t58_s;
    uint8_t t59 = 0;
    LyrStr *t60 = NULL;
    LyrStr *t61 = NULL;
    LyrStr *t62 = NULL;
    lyr_opt_opt_i64 t63_s = {0};
    lyr_opt_opt_i64 *t63 = &t63_s;
    uint8_t t64 = 0;
    LyrStr *t65 = NULL;
    LyrStr *t66 = NULL;
    lyr_opt_opt_i64 t67_s = {0};
    lyr_opt_opt_i64 *t67 = &t67_s;
    lyr_opt_i64 t68_s = {0};
    lyr_opt_i64 *t68 = &t68_s;
    uint8_t t69 = 0;
    int64_t t70 = 0;
    int64_t t71 = 0;
    int64_t t72 = 0;
    LyrStr *t73 = NULL;
    LyrStr *t74 = NULL;
    LyrStr *t75 = NULL;
    LyrStr *t76 = NULL;
    LyrStr *t77 = NULL;
    int64_t t78 = 0;
    LyrStr *t79 = NULL;
    int64_t t80 = 0;
    LyrStr *t81 = NULL;
    LyrStr *t82 = NULL;
    LyrStr *t83 = NULL;
    int64_t t84 = 0;
    LyrIface t85 = {0};
    uint8_t t86 = 0;
    int64_t t87 = 0;
    int64_t t88 = 0;
    LyrStr *t89 = NULL;
    int64_t t90 = 0;
    LyrStr *t91 = NULL;
    LyrStr *t92 = NULL;
    uint8_t t93 = 0;
    LyrStr *t94 = NULL;
    LyrIface t95 = {0};
    uint8_t t96 = 0;
    LyrIface t97 = {0};
    LyrStr *t98 = NULL;
    LyrIface t99 = {0};
    LyrStr *t100 = NULL;
    LyrStr *t101 = NULL;
    LyrStr *t102 = NULL;
    LyrStr *t103 = NULL;
    LyrStr *t104 = NULL;
    LyrStr *t105 = NULL;
    LyrStr *t106 = NULL;
    uint8_t t107 = 0;
    LyrStr *t108 = NULL;
    LyrIface t109 = {0};
    LyrStr *t110 = NULL;
    LyrStr *t111 = NULL;
    LyrStr *t112 = NULL;
    LyrStr *t113 = NULL;
    LyrStr *t114 = NULL;
    LyrStr *t115 = NULL;
    int64_t t116 = 0;
    LyrIface t117 = {0};
    uint8_t t118 = 0;
    int64_t t119 = 0;
    uint8_t t120 = 0;
    int64_t t121 = 0;
    int64_t t122 = 0;
    int64_t t123 = 0;
    LyrStr *t124 = NULL;
    int64_t t125 = 0;
    LyrStr *t126 = NULL;
    LyrStr *t127 = NULL;
    LyrStr *t128 = NULL;
    uint8_t t129 = 0;
    LyrStr *t130 = NULL;
    LyrIface t131 = {0};
    uint8_t t132 = 0;
    lyr_ty0_ParseError t133_s = {0};
    lyr_ty0_ParseError *t133 = &t133_s;
    LyrIface t134 = {0};
    LyrStr *t135 = NULL;
    LyrStr *t136 = NULL;
    LyrStr *t137 = NULL;
    LyrStr *t138 = NULL;
    LyrStr *t139 = NULL;
    LyrStr *t140 = NULL;
    uint8_t t141 = 0;
    LyrStr *t142 = NULL;
    LyrStr *t143 = NULL;
    LyrStr *t144 = NULL;
    LyrStr *t145 = NULL;
    uint8_t t146 = 0;
    uint8_t t147 = 0;
    uint8_t t148 = 0;
    LyrIface t149 = {0};
    LyrStr *t150 = NULL;
    LyrIface t151 = {0};
    LyrStr *t152 = NULL;
    LyrStr *t153 = NULL;
    LyrStr *t154 = NULL;
    LyrStr *t155 = NULL;
    LyrStr *t156 = NULL;
    LyrStr *t157 = NULL;
    LyrArr *t158 = NULL;
    int64_t t159 = 0;
    int64_t t160 = 0;
    int64_t t161 = 0;
    int64_t t162 = 0;
    uint8_t t163 = 0;
    LyrArr *t164 = NULL;
    int64_t t165 = 0;
    LyrStr *t166 = NULL;
    int64_t t167 = 0;
    int64_t t168 = 0;
    int64_t t169 = 0;
    LyrStr *t170 = NULL;
    int64_t t171 = 0;
    LyrIface t172 = {0};
    int64_t t173 = 0;
    int64_t t174 = 0;
    int64_t t175 = 0;
    int64_t t176 = 0;
    LyrStr *t177 = NULL;
    int64_t t178 = 0;
    LyrStr *t179 = NULL;
    LyrStr *t180 = NULL;
    int64_t t181 = 0;
    LyrIface t182 = {0};
    int64_t t183 = 0;
    int64_t t184 = 0;
    LyrStr *t185 = NULL;
    int64_t t186 = 0;
    LyrStr *t187 = NULL;
    LyrStr *t188 = NULL;
bb0:;
#line 37
    t0 = (LyrStr *)&lyr_lit6;
#line 37
    t1 = lyr_main_parse(t0, &lyr_e);
#line 37
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 37
    lyr_e = NULL;
#line 37
    t3_s = (lyr_opt_i64){0}; t3 = &t3_s;
#line 37
    l1__try0 = *t3;
#line 37
    goto bb3;
bb2:;
#line 37
    t2_s = (lyr_opt_i64){ .value = t1, .has = 1 }; t2 = &t2_s;
#line 37
    l1__try0 = *t2;
#line 37
    goto bb3;
bb3:;
#line 37
    t4 = &l1__try0;
#line 37
    l0_a = *t4;
#line 38
    t5 = (LyrStr *)&lyr_lit0;
#line 38
    t6 = lyr_main_parse(t5, &lyr_e);
#line 38
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb4; goto bb5;
bb4:;
#line 38
    lyr_e = NULL;
#line 38
    t8_s = (lyr_opt_i64){0}; t8 = &t8_s;
#line 38
    l3__try1 = *t8;
#line 38
    goto bb6;
bb5:;
#line 38
    t7_s = (lyr_opt_i64){ .value = t6, .has = 1 }; t7 = &t7_s;
#line 38
    l3__try1 = *t7;
#line 38
    goto bb6;
bb6:;
#line 38
    t9 = &l3__try1;
#line 38
    l2_b = *t9;
#line 39
    t10 = (LyrStr *)&lyr_lit7;
#line 39
    t11 = &l0_a;
#line 39
    t12 = t11->has;
#line 39
    if (t12) goto bb7; else goto bb8;
bb7:;
#line 39
    t13 = t11->value;
#line 39
    l4__coalesce2 = t13;
#line 39
    goto bb9;
bb8:;
#line 39
    t14 = (int64_t)INT64_C(-1);
#line 39
    l4__coalesce2 = t14;
#line 39
    goto bb9;
bb9:;
#line 39
    t15 = l4__coalesce2;
#line 39
    t16 = lyr_str_from_int(t15);
#line 39
    t17 = (LyrStr *)&lyr_lit8;
#line 39
    t18 = &l2_b;
#line 39
    t19 = t18->has;
#line 39
    if (t19) goto bb10; else goto bb11;
bb10:;
#line 39
    t20 = t18->value;
#line 39
    l5__coalesce3 = t20;
#line 39
    goto bb12;
bb11:;
#line 39
    t21 = (int64_t)INT64_C(-1);
#line 39
    l5__coalesce3 = t21;
#line 39
    goto bb12;
bb12:;
#line 39
    t22 = l5__coalesce3;
#line 39
    t23 = lyr_str_from_int(t22);
#line 39
    t24 = lyr_str_concat(t10, t16);
#line 39
    t25 = lyr_str_concat(t24, t17);
#line 39
    t26 = lyr_str_concat(t25, t23);
#line 39
    lyr_println(t26);
#line 41
    t27 = (LyrStr *)&lyr_lit2;
#line 41
    t28_s = lyr_main_maybe(t27, &lyr_e); t28 = &t28_s;
#line 41
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb13; goto bb14;
bb13:;
#line 41
    lyr_e = NULL;
#line 41
    t30_s = (lyr_opt_opt_i64){0}; t30 = &t30_s;
#line 41
    l7__try4 = *t30;
#line 41
    goto bb15;
bb14:;
#line 41
    t29_s = (lyr_opt_opt_i64){ .value = *t28, .has = 1 }; t29 = &t29_s;
#line 41
    l7__try4 = *t29;
#line 41
    goto bb15;
bb15:;
#line 41
    t31 = &l7__try4;
#line 41
    l6_c = *t31;
#line 42
    t32 = (LyrStr *)&lyr_lit0;
#line 42
    t33_s = lyr_main_maybe(t32, &lyr_e); t33 = &t33_s;
#line 42
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb16; goto bb17;
bb16:;
#line 42
    lyr_e = NULL;
#line 42
    t35_s = (lyr_opt_opt_i64){0}; t35 = &t35_s;
#line 42
    l9__try5 = *t35;
#line 42
    goto bb18;
bb17:;
#line 42
    t34_s = (lyr_opt_opt_i64){ .value = *t33, .has = 1 }; t34 = &t34_s;
#line 42
    l9__try5 = *t34;
#line 42
    goto bb18;
bb18:;
#line 42
    t36 = &l9__try5;
#line 42
    l8_d = *t36;
#line 43
    t37 = (LyrStr *)&lyr_lit9;
#line 43
    t38_s = lyr_main_maybe(t37, &lyr_e); t38 = &t38_s;
#line 43
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb19; goto bb20;
bb19:;
#line 43
    lyr_e = NULL;
#line 43
    t40_s = (lyr_opt_opt_i64){0}; t40 = &t40_s;
#line 43
    l11__try6 = *t40;
#line 43
    goto bb21;
bb20:;
#line 43
    t39_s = (lyr_opt_opt_i64){ .value = *t38, .has = 1 }; t39 = &t39_s;
#line 43
    l11__try6 = *t39;
#line 43
    goto bb21;
bb21:;
#line 43
    t41 = &l11__try6;
#line 43
    l10_e = *t41;
#line 44
    t42 = (LyrStr *)&lyr_lit10;
#line 44
    t43 = &l6_c;
#line 44
    t44 = t43->has;
#line 44
    t45 = lyr_str_from_bool(t44);
#line 44
    t46 = (LyrStr *)&lyr_lit11;
#line 44
    t47 = &l6_c;
#line 44
    if (LYR_UNLIKELY(!t47->has)) lyr_panic_null(); t48 = &t47->value;
#line 44
    t49 = t48->has;
#line 44
    if (t49) goto bb22; else goto bb23;
bb22:;
#line 44
    t50 = t48->value;
#line 44
    l12__coalesce7 = t50;
#line 44
    goto bb24;
bb23:;
#line 44
    t51 = (int64_t)INT64_C(-7);
#line 44
    l12__coalesce7 = t51;
#line 44
    goto bb24;
bb24:;
#line 44
    t52 = l12__coalesce7;
#line 44
    t53 = lyr_str_from_int(t52);
#line 44
    t54 = lyr_str_concat(t42, t45);
#line 44
    t55 = lyr_str_concat(t54, t46);
#line 44
    t56 = lyr_str_concat(t55, t53);
#line 44
    lyr_println(t56);
#line 45
    t57 = (LyrStr *)&lyr_lit12;
#line 45
    t58 = &l8_d;
#line 45
    t59 = t58->has;
#line 45
    t60 = lyr_str_from_bool(t59);
#line 45
    t61 = lyr_str_concat(t57, t60);
#line 45
    lyr_println(t61);
#line 46
    t62 = (LyrStr *)&lyr_lit13;
#line 46
    t63 = &l10_e;
#line 46
    t64 = t63->has;
#line 46
    t65 = lyr_str_from_bool(t64);
#line 46
    t66 = (LyrStr *)&lyr_lit11;
#line 46
    t67 = &l10_e;
#line 46
    if (LYR_UNLIKELY(!t67->has)) lyr_panic_null(); t68 = &t67->value;
#line 46
    t69 = t68->has;
#line 46
    if (t69) goto bb25; else goto bb26;
bb25:;
#line 46
    t70 = t68->value;
#line 46
    l13__coalesce8 = t70;
#line 46
    goto bb27;
bb26:;
#line 46
    t71 = (int64_t)INT64_C(-7);
#line 46
    l13__coalesce8 = t71;
#line 46
    goto bb27;
bb27:;
#line 46
    t72 = l13__coalesce8;
#line 46
    t73 = lyr_str_from_int(t72);
#line 46
    t74 = lyr_str_concat(t62, t65);
#line 46
    t75 = lyr_str_concat(t74, t66);
#line 46
    t76 = lyr_str_concat(t75, t73);
#line 46
    lyr_println(t76);
#line 48
    t77 = (LyrStr *)&lyr_lit14;
#line 48
    t78 = lyr_main_parse(t77, &lyr_e);
#line 48
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb28; goto bb29;
bb28:;
#line 48
    lyr_panic_error(lyr_e, lyr_error_message);
bb29:;
#line 48
    l14_f = t78;
#line 49
    t79 = (LyrStr *)&lyr_lit15;
#line 49
    t80 = l14_f;
#line 49
    t81 = lyr_str_from_int(t80);
#line 49
    t82 = lyr_str_concat(t79, t81);
#line 49
    lyr_println(t82);
#line 51
    t83 = (LyrStr *)&lyr_lit1;
#line 51
    t84 = lyr_main_parse(t83, &lyr_e);
#line 51
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb30; goto bb31;
bb30:;
#line 51
    t85 = lyr_e->value;
#line 51
    t86 = ((*(const LyrDesc *const *)t85.vt) == &lyr_desc_box_ty0_ParseError);
#line 51
    if (t86) goto bb32; else goto bb33;
bb31:;
#line 51
    l16__try9 = t84;
#line 51
    goto bb35;
bb32:;
#line 51
    lyr_e = NULL;
#line 51
    t87 = (int64_t)INT64_C(-1);
#line 51
    l16__try9 = t87;
#line 51
    goto bb35;
bb33:;
#line 51
    goto bb34;
bb34:;
#line 51
    __builtin_unreachable();
bb35:;
#line 51
    t88 = l16__try9;
#line 51
    l15_g = t88;
#line 52
    t89 = (LyrStr *)&lyr_lit16;
#line 52
    t90 = l15_g;
#line 52
    t91 = lyr_str_from_int(t90);
#line 52
    t92 = lyr_str_concat(t89, t91);
#line 52
    lyr_println(t92);
#line 53
    t93 = 0;
#line 53
    t94 = lyr_main_read(t93, &lyr_e);
#line 53
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb36; goto bb37;
bb36:;
#line 53
    t95 = lyr_e->value;
#line 53
    t96 = (lyr_iface_find((*(const LyrDesc *const *)t95.vt), lyr_ifid_ty5) != NULL);
#line 53
    if (t96) goto bb38; else goto bb39;
bb37:;
#line 53
    l18__try10 = t94;
#line 53
    goto bb40;
bb38:;
#line 53
    lyr_e = NULL;
#line 53
    t97 = (LyrIface){ t95.data, lyr_iface_find((*(const LyrDesc *const *)t95.vt), lyr_ifid_ty5) };
#line 53
    l19_err = t97;
#line 53
    t98 = (LyrStr *)&lyr_lit17;
#line 53
    t99 = l19_err;
#line 53
    t100 = ((const lyr_vt_ty5 *)t99.vt)->s0(t99);
#line 53
    t101 = lyr_str_concat(t98, t100);
#line 53
    lyr_println(t101);
#line 53
    t102 = (LyrStr *)&lyr_lit18;
#line 53
    l18__try10 = t102;
#line 53
    goto bb40;
bb39:;
#line 53
    goto bb34;
bb40:;
#line 53
    t103 = l18__try10;
#line 53
    l17_h = t103;
#line 54
    t104 = (LyrStr *)&lyr_lit19;
#line 54
    t105 = l17_h;
#line 54
    t106 = lyr_str_concat(t104, t105);
#line 54
    lyr_println(t106);
#line 55
    t107 = 1;
#line 55
    t108 = lyr_main_read(t107, &lyr_e);
#line 55
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb41; goto bb42;
bb41:;
#line 55
    t109 = lyr_e->value;
#line 55
    lyr_e = NULL;
#line 55
    t110 = (LyrStr *)&lyr_lit20;
#line 55
    l21__try11 = t110;
#line 55
    goto bb43;
bb42:;
#line 55
    l21__try11 = t108;
#line 55
    goto bb43;
bb43:;
#line 55
    t111 = l21__try11;
#line 55
    l20_i = t111;
#line 56
    t112 = (LyrStr *)&lyr_lit21;
#line 56
    t113 = l20_i;
#line 56
    t114 = lyr_str_concat(t112, t113);
#line 56
    lyr_println(t114);
#line 58
    t115 = (LyrStr *)&lyr_lit0;
#line 58
    t116 = lyr_main_parse(t115, &lyr_e);
#line 58
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb44; goto bb45;
bb44:;
#line 58
    t117 = lyr_e->value;
#line 58
    t118 = (lyr_iface_find((*(const LyrDesc *const *)t117.vt), lyr_ifid_ty5) != NULL);
#line 58
    if (t118) goto bb46; else goto bb47;
bb45:;
#line 58
    l23__try12 = t116;
#line 58
    goto bb50;
bb46:;
#line 58
    lyr_e = NULL;
#line 58
    t119 = (int64_t)INT64_C(1);
#line 58
    l23__try12 = t119;
#line 58
    goto bb50;
bb47:;
#line 58
    t120 = ((*(const LyrDesc *const *)t117.vt) == &lyr_desc_box_ty0_ParseError);
#line 58
    if (t120) goto bb48; else goto bb49;
bb48:;
#line 58
    lyr_e = NULL;
#line 58
    t121 = (int64_t)INT64_C(2);
#line 58
    l23__try12 = t121;
#line 58
    goto bb50;
bb49:;
#line 58
    lyr_e = NULL;
#line 58
    t122 = (int64_t)INT64_C(3);
#line 58
    l23__try12 = t122;
#line 58
    goto bb50;
bb50:;
#line 58
    t123 = l23__try12;
#line 58
    l22_j = t123;
#line 59
    t124 = (LyrStr *)&lyr_lit22;
#line 59
    t125 = l22_j;
#line 59
    t126 = lyr_str_from_int(t125);
#line 59
    t127 = lyr_str_concat(t124, t126);
#line 59
    lyr_println(t127);
#line 61
    t128 = (LyrStr *)&lyr_lit2;
#line 61
    l24_none = t128;
#line 62
    t129 = 0;
#line 62
    t130 = lyr_main_read(t129, &lyr_e);
#line 62
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb51; goto bb52;
bb51:;
#line 62
    t131 = lyr_e->value;
#line 62
    t132 = ((*(const LyrDesc *const *)t131.vt) == &lyr_desc_ty4_Disk);
#line 62
    if (t132) goto bb53; else goto bb54;
bb52:;
#line 62
    l26__try13 = t130;
#line 62
    goto bb56;
bb53:;
#line 62
    lyr_e = NULL;
#line 62
    t133_s = (lyr_ty0_ParseError){ .tag = 0 }; t133 = &t133_s;
#line 62
    { lyr_box_ty0_ParseError *lyr_box = lyr_alloc(&lyr_desc_box_ty0_ParseError); lyr_box->value = *t133; t134 = (LyrIface){ lyr_box, &lyr_vt_ty3_ty0 }; }
#line 62
    lyr_e = lyr_err_new(t134); goto bb55;
bb54:;
#line 62
    goto bb55;
bb55:;
#line 62
    lyr_e = NULL;
#line 62
    t137 = NULL;
#line 62
    l27__try14 = t137;
#line 62
    goto bb57;
bb56:;
#line 62
    t135 = l26__try13;
#line 62
    t136 = t135;
#line 62
    l27__try14 = t136;
#line 62
    goto bb57;
bb57:;
#line 62
    t138 = l27__try14;
#line 62
    l25_k = t138;
#line 63
    t139 = (LyrStr *)&lyr_lit23;
#line 63
    t140 = l25_k;
#line 63
    t141 = (uint8_t)(t140 != NULL);
#line 63
    if (t141) goto bb58; else goto bb59;
bb58:;
#line 63
    t142 = t140;
#line 63
    l28__coalesce15 = t142;
#line 63
    goto bb60;
bb59:;
#line 63
    t143 = l24_none;
#line 63
    l28__coalesce15 = t143;
#line 63
    goto bb60;
bb60:;
#line 63
    t144 = l28__coalesce15;
#line 63
    t145 = lyr_str_concat(t139, t144);
#line 63
    lyr_println(t145);
#line 65
    t146 = 1;
#line 65
    lyr_main_save(t146, &lyr_e);
#line 65
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb61; goto bb62;
bb61:;
#line 65
    lyr_panic_error(lyr_e, lyr_error_message);
bb62:;
#line 66
    t147 = 0;
#line 66
    lyr_main_save(t147, &lyr_e);
#line 66
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb63; goto bb64;
bb63:;
#line 66
    lyr_e = NULL;
#line 66
    goto bb65;
bb64:;
#line 66
    goto bb65;
bb65:;
#line 67
    t148 = 0;
#line 67
    lyr_main_save(t148, &lyr_e);
#line 67
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb66; goto bb67;
bb66:;
#line 67
    t149 = lyr_e->value;
#line 67
    lyr_e = NULL;
#line 67
    l29_err = t149;
#line 67
    t150 = (LyrStr *)&lyr_lit24;
#line 67
    t151 = l29_err;
#line 67
    t152 = ((const lyr_vt_ty3 *)t151.vt)->s0(t151);
#line 67
    t153 = lyr_str_concat(t150, t152);
#line 67
    lyr_println(t153);
#line 67
    goto bb68;
bb67:;
#line 67
    goto bb68;
bb68:;
#line 69
    t154 = (LyrStr *)&lyr_lit6;
#line 69
    t155 = (LyrStr *)&lyr_lit0;
#line 69
    t156 = (LyrStr *)&lyr_lit1;
#line 69
    t157 = (LyrStr *)&lyr_lit25;
#line 69
    t158 = lyr_alloc_array(&lyr_desc_arr_str, 4); LYR_ARR_DATA(t158, LyrStr *)[0] = t154; LYR_ARR_DATA(t158, LyrStr *)[1] = t155; LYR_ARR_DATA(t158, LyrStr *)[2] = t156; LYR_ARR_DATA(t158, LyrStr *)[3] = t157;
#line 69
    l30_inputs = t158;
#line 70
    t159 = (int64_t)INT64_C(0);
#line 70
    l31_sum = t159;
#line 71
    t160 = (int64_t)INT64_C(0);
#line 71
    l32_at = t160;
#line 72
    goto bb69;
bb69:;
#line 72
    t161 = l32_at;
#line 72
    t162 = (int64_t)INT64_C(4);
#line 72
    t163 = (uint8_t)(t161 < t162);
#line 72
    if (t163) goto bb70; else goto bb71;
bb70:;
#line 73
    t164 = l30_inputs;
#line 73
    t165 = l32_at;
#line 73
    LYR_CHECK_INDEX(t165, t164->len); t166 = LYR_ARR_DATA(t164, LyrStr *)[t165];
#line 73
    l33_s = t166;
#line 74
    t167 = l32_at;
#line 74
    t168 = (int64_t)INT64_C(1);
#line 74
    t169 = LYR_CHECKED_ADD(t167, t168);
#line 74
    l32_at = t169;
#line 75
    t170 = l33_s;
#line 75
    t171 = lyr_main_parse(t170, &lyr_e);
#line 75
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb72; goto bb73;
bb71:;
#line 78
    t177 = (LyrStr *)&lyr_lit26;
#line 78
    t178 = l31_sum;
#line 78
    t179 = lyr_str_from_int(t178);
#line 78
    t180 = lyr_str_concat(t177, t179);
#line 78
    lyr_println(t180);
#line 80
    t181 = lyr_main_withDefer(&lyr_e);
#line 80
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb75; goto bb76;
bb72:;
#line 75
    t172 = lyr_e->value;
#line 75
    lyr_e = NULL;
#line 75
    goto bb69;
bb73:;
#line 75
    l35__try16 = t171;
#line 75
    goto bb74;
bb74:;
#line 75
    t173 = l35__try16;
#line 75
    l34_n = t173;
#line 76
    t174 = l31_sum;
#line 76
    t175 = l34_n;
#line 76
    t176 = LYR_CHECKED_ADD(t174, t175);
#line 76
    l31_sum = t176;
#line 72
    goto bb69;
bb75:;
#line 80
    t182 = lyr_e->value;
#line 80
    lyr_e = NULL;
#line 80
    t183 = (int64_t)INT64_C(0);
#line 80
    l37__try17 = t183;
#line 80
    goto bb77;
bb76:;
#line 80
    l37__try17 = t181;
#line 80
    goto bb77;
bb77:;
#line 80
    t184 = l37__try17;
#line 80
    l36_m = t184;
#line 81
    t185 = (LyrStr *)&lyr_lit27;
#line 81
    t186 = l36_m;
#line 81
    t187 = lyr_str_from_int(t186);
#line 81
    t188 = lyr_str_concat(t185, t187);
#line 81
    lyr_println(t188);
#line 36
    return;
}

#line 6 "programs/try_forms.lyr"
LyrStr * lyr_main_ParseError_message(lyr_ty0_ParseError *l0_this) {
    LyrStr *t0 = NULL;
bb0:;
#line 6
    t0 = (LyrStr *)&lyr_lit28;
#line 6
    return t0;
}

#line 8 "programs/try_forms.lyr"
LyrStr * lyr_main_Disk_message(lyr_ty4_Disk *l0_this) {
    LyrStr *t0 = NULL;
bb0:;
#line 8
    t0 = (LyrStr *)&lyr_lit29;
#line 8
    return t0;
}

#line 108 "stdlib5/std/core.lyr"
lyr_opt_iface3 lyr_std_core_Error_cause(LyrIface l0_this) {
    lyr_opt_iface3 t0_s = {0};
    lyr_opt_iface3 *t0 = &t0_s;
bb0:;
#line 108
    t0_s = (lyr_opt_iface3){0}; t0 = &t0_s;
#line 108
    return *t0;
}

#line 1387 "stdlib5/std/core.lyr"
void lyr__globals__9ee5f9b5(void) {
    uint64_t t0 = 0;
    double t1 = 0;
    uint64_t t2 = 0;
    double t3 = 0;
    uint64_t t4 = 0;
    float t5 = 0;
    uint64_t t6 = 0;
    float t7 = 0;
    uint64_t t8 = 0;
    uint64_t t9 = 0;
    uint64_t t10 = 0;
bb0:;
#line 1387
    t0 = (uint64_t)UINT64_C(9218868437227405312);
#line 1387
    t1 = lyr_std_core__extend__float_fromBits_3825afc5(t0);
#line 1387
    lyr_g0_float_infinity = t1;
#line 1388
    t2 = (uint64_t)UINT64_C(9221120237041090560);
#line 1388
    t3 = lyr_std_core__extend__float_fromBits_3825afc5(t2);
#line 1388
    lyr_g1_float_nan = t3;
#line 1408
    t4 = (uint64_t)UINT64_C(2139095040);
#line 1408
    t5 = lyr_std_core__extend__float32_fromBits_bc3641ce(t4);
#line 1408
    lyr_g2_float32_infinity = t5;
#line 1409
    t6 = (uint64_t)UINT64_C(2143289344);
#line 1409
    t7 = lyr_std_core__extend__float32_fromBits_bc3641ce(t6);
#line 1409
    lyr_g3_float32_nan = t7;
#line 247 "stdlib5/std/collections.lyr"
    t8 = (uint64_t)UINT64_C(9259542123273814144);
#line 247
    lyr_g4_emptyGroup = t8;
#line 248
    t9 = (uint64_t)UINT64_C(72340172838076673);
#line 248
    lyr_g5_lowBits = t9;
#line 249
    t10 = (uint64_t)UINT64_C(9259542123273814144);
#line 249
    lyr_g6_highBits = t10;
    return;
}

#line 1394 "stdlib5/std/core.lyr"
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b) {
    uint64_t t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 1394
    t0 = l0_b;
#line 1384
    t1 = (double)0.0;
#line 1394
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1394
    return t2;
}

#line 1415 "stdlib5/std/core.lyr"
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b) {
    uint64_t t0 = 0;
    float t1 = 0;
    float t2 = 0;
bb0:;
#line 1415
    t0 = l0_b;
#line 1405
    t1 = (float)0.0;
#line 1415
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1415
    return t2;
}


/* the program */
static int64_t lyr_entry(void) { lyr__globals__9ee5f9b5(); lyr_main_main(); return 0; }
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_entry); }
