/* Generated by lyric5 from the IR of this module. Do not edit: the source is the .lyr. */
#include "lyr/lyr.h"
#include <stdint.h>
#include <math.h>

/* types: a struct is a value, a class an object behind its header, an enum a tag and a union */
typedef struct lyr_ty_app_main_Disk lyr_ty_app_main_Disk;
typedef struct lyr_vt_ty_std_core_Error lyr_vt_ty_std_core_Error;
const char lyr_ifid_ty_std_core_Error[] = "std.core.Error";
typedef struct lyr_ty_app_main_Wrap lyr_ty_app_main_Wrap;
typedef struct lyr_ty_std_core_ParseError lyr_ty_std_core_ParseError;
typedef struct lyr_ty_std_core_ParseErrorKind lyr_ty_std_core_ParseErrorKind;
typedef struct lyr_ty_23_std_core_ParseErrorKind_Empty lyr_ty_23_std_core_ParseErrorKind_Empty;
typedef struct lyr_ty_23_std_core_ParseErrorKind_Invalid lyr_ty_23_std_core_ParseErrorKind_Invalid;
typedef struct lyr_ty_23_std_core_ParseErrorKind_Overflow lyr_ty_23_std_core_ParseErrorKind_Overflow;
typedef struct lyr_ty_std_core_FormatSpec lyr_ty_std_core_FormatSpec;
typedef struct lyr_ty_std_core_Chars lyr_ty_std_core_Chars;
typedef struct lyr_ty_std_core_StringBuilder lyr_ty_std_core_StringBuilder;
typedef struct lyr_ty_std_core_Ordering lyr_ty_std_core_Ordering;
typedef struct lyr_ty_17_std_core_Ordering_Less lyr_ty_17_std_core_Ordering_Less;
typedef struct lyr_ty_17_std_core_Ordering_Equal lyr_ty_17_std_core_Ordering_Equal;
typedef struct lyr_ty_17_std_core_Ordering_Greater lyr_ty_17_std_core_Ordering_Greater;
typedef struct lyr_ty_std_core_Exception lyr_ty_std_core_Exception;
typedef struct lyr_vt_ty_std_core_Hasher lyr_vt_ty_std_core_Hasher;
const char lyr_ifid_ty_std_core_Hasher[] = "std.core.Hasher";
typedef struct lyr_ty_std_core_Split lyr_ty_std_core_Split;
typedef struct lyr_ty_std_core_Lines lyr_ty_std_core_Lines;
typedef struct lyr_ty_std_hash_Sip lyr_ty_std_hash_Sip;
typedef struct lyr_ty_std_hash_DefaultHasher lyr_ty_std_hash_DefaultHasher;
typedef struct lyr_ty_std_hash_FixedHasher lyr_ty_std_hash_FixedHasher;
typedef struct lyr_ty_std_hash_Fnv1a64 lyr_ty_std_hash_Fnv1a64;
struct lyr_ty_app_main_Disk {
    LyrObj header;
};
_Static_assert(sizeof(lyr_ty_app_main_Disk) == 8, "layout of lyr_ty_app_main_Disk");
extern const LyrItable lyr_itab_ty_app_main_Disk[];
const LyrDesc lyr_desc_ty_app_main_Disk = { sizeof(lyr_ty_app_main_Disk), 0, 0, 0, NULL, "app.main.Disk", lyr_itab_ty_app_main_Disk };
typedef struct { LyrIface value; uint8_t has; } lyr_opt_iface14_std_core_Error;
struct lyr_vt_ty_std_core_Error {
    const LyrDesc *desc;
    LyrStr * (*s0)(LyrIface);
    lyr_opt_iface14_std_core_Error (*s1)(LyrIface);
};
struct lyr_ty_app_main_Wrap {
    LyrObj header;
    LyrStr *f_what;
    LyrIface f_inner;
};
_Static_assert(sizeof(lyr_ty_app_main_Wrap) == 32, "layout of lyr_ty_app_main_Wrap");
_Static_assert(offsetof(lyr_ty_app_main_Wrap, f_what) == 8, "layout of lyr_ty_app_main_Wrap");
_Static_assert(offsetof(lyr_ty_app_main_Wrap, f_inner) == 16, "layout of lyr_ty_app_main_Wrap");
extern const LyrItable lyr_itab_ty_app_main_Wrap[];
static const uint64_t lyr_refmap_ty_app_main_Wrap[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty_app_main_Wrap = { sizeof(lyr_ty_app_main_Wrap), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_app_main_Wrap, "app.main.Wrap", lyr_itab_ty_app_main_Wrap };
struct lyr_ty_23_std_core_ParseErrorKind_Empty {
    uint8_t lyr_unit;
};
struct lyr_ty_23_std_core_ParseErrorKind_Invalid {
    uint8_t lyr_unit;
};
struct lyr_ty_23_std_core_ParseErrorKind_Overflow {
    uint8_t lyr_unit;
};
struct lyr_ty_std_core_ParseErrorKind { uint32_t tag; };
_Static_assert(sizeof(lyr_ty_std_core_ParseErrorKind) == 4, "layout of lyr_ty_std_core_ParseErrorKind");
struct lyr_ty_std_core_ParseError {
    lyr_ty_std_core_ParseErrorKind f_kind;
};
struct lyr_ty_std_core_FormatSpec {
    uint32_t f_fill;
    uint32_t f_align;
    uint8_t f_plus;
    uint8_t f_alternate;
    int64_t f_width;
    uint32_t f_grouping;
    int64_t f_precision;
    uint32_t f_kind;
};
struct lyr_ty_std_core_Chars {
    LyrStr *f_s;
    int64_t f_at;
};
struct lyr_ty_std_core_StringBuilder {
    LyrObj header;
    LyrArr *f_bytes;
    int64_t f_count;
};
_Static_assert(sizeof(lyr_ty_std_core_StringBuilder) == 24, "layout of lyr_ty_std_core_StringBuilder");
_Static_assert(offsetof(lyr_ty_std_core_StringBuilder, f_bytes) == 8, "layout of lyr_ty_std_core_StringBuilder");
_Static_assert(offsetof(lyr_ty_std_core_StringBuilder, f_count) == 16, "layout of lyr_ty_std_core_StringBuilder");
static const uint64_t lyr_refmap_ty_std_core_StringBuilder[] = { UINT64_C(0x2) };
const LyrDesc lyr_desc_ty_std_core_StringBuilder = { sizeof(lyr_ty_std_core_StringBuilder), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_std_core_StringBuilder, "std.core.StringBuilder", NULL };
struct lyr_ty_17_std_core_Ordering_Less {
    uint8_t lyr_unit;
};
struct lyr_ty_17_std_core_Ordering_Equal {
    uint8_t lyr_unit;
};
struct lyr_ty_17_std_core_Ordering_Greater {
    uint8_t lyr_unit;
};
struct lyr_ty_std_core_Ordering { uint32_t tag; };
_Static_assert(sizeof(lyr_ty_std_core_Ordering) == 4, "layout of lyr_ty_std_core_Ordering");
struct lyr_ty_std_core_Exception {
    LyrObj header;
    LyrStr *f_text;
    lyr_opt_iface14_std_core_Error f_inner;
};
_Static_assert(sizeof(lyr_ty_std_core_Exception) == 40, "layout of lyr_ty_std_core_Exception");
_Static_assert(offsetof(lyr_ty_std_core_Exception, f_text) == 8, "layout of lyr_ty_std_core_Exception");
_Static_assert(offsetof(lyr_ty_std_core_Exception, f_inner) == 16, "layout of lyr_ty_std_core_Exception");
static const uint64_t lyr_refmap_ty_std_core_Exception[] = { UINT64_C(0x6) };
const LyrDesc lyr_desc_ty_std_core_Exception = { sizeof(lyr_ty_std_core_Exception), LYR_DESC_HAS_REFS, 0, 1, lyr_refmap_ty_std_core_Exception, "std.core.Exception", NULL };
struct lyr_vt_ty_std_core_Hasher {
    const LyrDesc *desc;
    void (*s0)(LyrIface);
    void (*s1)(LyrIface);
    void (*s2)(LyrIface);
    void (*s3)(LyrIface);
    void (*s4)(LyrIface);
};
struct lyr_ty_std_core_Split {
    LyrStr *f_s;
    LyrStr *f_sep;
    int64_t f_at;
    uint8_t f_done;
};
struct lyr_ty_std_core_Lines {
    LyrStr *f_s;
    int64_t f_at;
};
struct lyr_ty_std_hash_Sip {
    uint64_t f_v0;
    uint64_t f_v1;
    uint64_t f_v2;
    uint64_t f_v3;
    uint64_t f_tail;
    int64_t f_pending;
    int64_t f_length;
};
struct lyr_ty_std_hash_DefaultHasher {
    lyr_ty_std_hash_Sip f_state;
};
struct lyr_ty_std_hash_FixedHasher {
    lyr_ty_std_hash_Sip f_state;
};
struct lyr_ty_std_hash_Fnv1a64 {
    uint64_t f_state;
};
_Static_assert(sizeof(uint8_t) == 1, "layout of u8[]");
const LyrDesc lyr_desc_arr_u8 = { (uint32_t)offsetof(LyrArr, data), LYR_DESC_ARRAY, sizeof(uint8_t), 0, NULL, "u8[]", NULL };

/* module-level bindings */
double lyr_g_std_core_float_infinity = 0;
double lyr_g_std_core_float_nan = 0;
float lyr_g_std_core_float32_infinity = 0;
float lyr_g_std_core_float32_nan = 0;
uint64_t lyr_g_std_collections_emptyGroup = 0;
uint64_t lyr_g_std_collections_lowBits = 0;
uint64_t lyr_g_std_collections_highBits = 0;

/* string literals */
static const LyrStaticStr(7) lyr_lit0 = LYR_STR_INIT("config");
static const LyrStaticStr(7) lyr_lit1 = LYR_STR_INIT("before");
static const LyrStaticStr(5) lyr_lit2 = LYR_STR_INIT("disk");

/* prototypes */
LyrStr * lyr_app_main_read(LyrErr **lyr_err);
LyrStr * lyr_app_main_config(LyrErr **lyr_err);
LYR_NOINLINE int64_t lyr_app_main_main(LyrErr **lyr_err);
LyrStr * lyr_app_main_Disk_message(lyr_ty_app_main_Disk *l0_this);
LyrStr * lyr_app_main_Wrap_message(lyr_ty_app_main_Wrap *l0_this);
lyr_opt_iface14_std_core_Error lyr_app_main_Wrap_cause(lyr_ty_app_main_Wrap *l0_this);
lyr_opt_iface14_std_core_Error lyr_std_core_Error_cause(LyrIface l0_this);
void lyr__globals__9ee5f9b5(void);
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b);
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b);

/* interface tables: the descriptor, then the implementation of every slot */
static LyrStr * lyr_vt_14_std_core_Error_13_app_main_Disk_s0(LyrIface self) { return lyr_app_main_Disk_message((lyr_ty_app_main_Disk *)self.data); }
const lyr_vt_ty_std_core_Error lyr_vt_14_std_core_Error_13_app_main_Disk = { &lyr_desc_ty_app_main_Disk, lyr_vt_14_std_core_Error_13_app_main_Disk_s0, lyr_std_core_Error_cause };
static LyrStr * lyr_vt_14_std_core_Error_13_app_main_Wrap_s0(LyrIface self) { return lyr_app_main_Wrap_message((lyr_ty_app_main_Wrap *)self.data); }
static lyr_opt_iface14_std_core_Error lyr_vt_14_std_core_Error_13_app_main_Wrap_s1(LyrIface self) { return lyr_app_main_Wrap_cause((lyr_ty_app_main_Wrap *)self.data); }
const lyr_vt_ty_std_core_Error lyr_vt_14_std_core_Error_13_app_main_Wrap = { &lyr_desc_ty_app_main_Wrap, lyr_vt_14_std_core_Error_13_app_main_Wrap_s0, lyr_vt_14_std_core_Error_13_app_main_Wrap_s1 };
const LyrItable lyr_itab_ty_app_main_Disk[] = { { lyr_ifid_ty_std_core_Error, &lyr_vt_14_std_core_Error_13_app_main_Disk } , { NULL, NULL } };
const LyrItable lyr_itab_ty_app_main_Wrap[] = { { lyr_ifid_ty_std_core_Error, &lyr_vt_14_std_core_Error_13_app_main_Wrap } , { NULL, NULL } };

/* the members of Error the runtime reports through */
const LyrStr *lyr_error_message(LyrIface e) { return ((const lyr_vt_ty_std_core_Error *)e.vt)->s0(e); }
int lyr_error_cause(LyrIface e, LyrIface *next) { lyr_opt_iface14_std_core_Error c = ((const lyr_vt_ty_std_core_Error *)e.vt)->s1(e); *next = c.value; return c.has; }

#line 12 "programs/uncaught.lyr"
LyrStr * lyr_app_main_read(LyrErr **lyr_err) {
    LyrErr *lyr_e = NULL;
    lyr_ty_app_main_Disk *t0 = NULL;
    LyrIface t1 = {0};
bb0:;
#line 12
    t0 = (lyr_ty_app_main_Disk *)lyr_alloc(&lyr_desc_ty_app_main_Disk);
#line 12
    t1 = (LyrIface){ t0, &lyr_vt_14_std_core_Error_13_app_main_Disk };
#line 12
    lyr_e = lyr_err_new(t1); goto bb1;
bb1:;
#line 12
    *lyr_err = lyr_e; return NULL;
}

#line 14 "programs/uncaught.lyr"
LyrStr * lyr_app_main_config(LyrErr **lyr_err) {
    lyr_ty_app_main_Disk *l0_e = NULL;
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    LyrIface t1 = {0};
    uint8_t t2 = 0;
    lyr_ty_app_main_Disk *t3 = NULL;
    LyrStr *t4 = NULL;
    lyr_ty_app_main_Disk *t5 = NULL;
    LyrIface t6 = {0};
    lyr_ty_app_main_Wrap *t7 = NULL;
    LyrIface t8 = {0};
bb0:;
#line 14
    t0 = lyr_app_main_read(&lyr_e);
#line 14
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 14
    t1 = lyr_e->value;
#line 14
    t2 = ((*(const LyrDesc *const *)t1.vt) == &lyr_desc_ty_app_main_Disk);
#line 14
    if (t2) goto bb3; else goto bb4;
bb2:;
#line 14
    return t0;
bb3:;
#line 14
    lyr_e = NULL;
#line 14
    t3 = (lyr_ty_app_main_Disk *)t1.data;
#line 14
    l0_e = t3;
#line 14
    t4 = (LyrStr *)&lyr_lit0;
#line 14
    t5 = l0_e;
#line 14
    t6 = (LyrIface){ t5, &lyr_vt_14_std_core_Error_13_app_main_Disk };
#line 14
    t7 = (lyr_ty_app_main_Wrap *)lyr_alloc(&lyr_desc_ty_app_main_Wrap);
#line 14
    LYR_WRITE_BARRIER(t7, &t7->f_what, t4);
#line 14
    LYR_WRITE_BARRIER_VALUE(t7, &t7->f_inner, t6);
#line 14
    t8 = (LyrIface){ t7, &lyr_vt_14_std_core_Error_13_app_main_Wrap };
#line 14
    lyr_e = lyr_err_new(t8); goto bb5;
bb4:;
#line 14
    goto bb5;
bb5:;
#line 14
    *lyr_err = lyr_e; return NULL;
}

#line 18 "programs/uncaught.lyr"
LYR_NOINLINE int64_t lyr_app_main_main(LyrErr **lyr_err) {
    LyrStr *l0_s = NULL;
    LyrErr *lyr_e = NULL;
    LyrStr *t0 = NULL;
    LyrStr *t1 = NULL;
    LyrStr *t2 = NULL;
    int64_t t3 = 0;
bb0:;
#line 18
    t0 = (LyrStr *)&lyr_lit1;
#line 18
    lyr_println(t0);
#line 19
    t1 = lyr_app_main_config(&lyr_e);
#line 19
    if (LYR_UNLIKELY(lyr_e != NULL)) goto bb1; goto bb2;
bb1:;
#line 19
    *lyr_err = lyr_e; return 0;
bb2:;
#line 19
    l0_s = t1;
#line 20
    t2 = l0_s;
#line 20
    lyr_println(t2);
#line 21
    t3 = (int64_t)INT64_C(0);
#line 21
    return t3;
}

#line 6 "programs/uncaught.lyr"
LyrStr * lyr_app_main_Disk_message(lyr_ty_app_main_Disk *l0_this) {
    LyrStr *t0 = NULL;
bb0:;
#line 6
    t0 = (LyrStr *)&lyr_lit2;
#line 6
    return t0;
}

#line 8 "programs/uncaught.lyr"
LyrStr * lyr_app_main_Wrap_message(lyr_ty_app_main_Wrap *l0_this) {
    lyr_ty_app_main_Wrap *t0 = NULL;
    LyrStr *t1 = NULL;
bb0:;
#line 8
    t0 = l0_this;
#line 8
    t1 = t0->f_what;
#line 8
    return t1;
}

#line 9 "programs/uncaught.lyr"
lyr_opt_iface14_std_core_Error lyr_app_main_Wrap_cause(lyr_ty_app_main_Wrap *l0_this) {
    lyr_ty_app_main_Wrap *t0 = NULL;
    LyrIface t1 = {0};
    lyr_opt_iface14_std_core_Error t2_s = {0};
    lyr_opt_iface14_std_core_Error *t2 = &t2_s;
bb0:;
#line 9
    t0 = l0_this;
#line 9
    t1 = t0->f_inner;
#line 9
    t2_s = (lyr_opt_iface14_std_core_Error){ .value = t1, .has = 1 }; t2 = &t2_s;
#line 9
    return *t2;
}

#line 108 "stdlib5/std/core.lyr"
lyr_opt_iface14_std_core_Error lyr_std_core_Error_cause(LyrIface l0_this) {
    lyr_opt_iface14_std_core_Error t0_s = {0};
    lyr_opt_iface14_std_core_Error *t0 = &t0_s;
bb0:;
#line 108
    t0_s = (lyr_opt_iface14_std_core_Error){0}; t0 = &t0_s;
#line 108
    return *t0;
}

#line 1387 "stdlib5/std/core.lyr"
void lyr__globals__9ee5f9b5(void) {
    uint64_t t0 = 0;
    double t1 = 0;
    uint64_t t2 = 0;
    double t3 = 0;
    uint64_t t4 = 0;
    float t5 = 0;
    uint64_t t6 = 0;
    float t7 = 0;
    uint64_t t8 = 0;
    uint64_t t9 = 0;
    uint64_t t10 = 0;
bb0:;
#line 1387
    t0 = (uint64_t)UINT64_C(9218868437227405312);
#line 1387
    t1 = lyr_std_core__extend__float_fromBits_3825afc5(t0);
#line 1387
    lyr_g_std_core_float_infinity = t1;
#line 1388
    t2 = (uint64_t)UINT64_C(9221120237041090560);
#line 1388
    t3 = lyr_std_core__extend__float_fromBits_3825afc5(t2);
#line 1388
    lyr_g_std_core_float_nan = t3;
#line 1408
    t4 = (uint64_t)UINT64_C(2139095040);
#line 1408
    t5 = lyr_std_core__extend__float32_fromBits_bc3641ce(t4);
#line 1408
    lyr_g_std_core_float32_infinity = t5;
#line 1409
    t6 = (uint64_t)UINT64_C(2143289344);
#line 1409
    t7 = lyr_std_core__extend__float32_fromBits_bc3641ce(t6);
#line 1409
    lyr_g_std_core_float32_nan = t7;
#line 247 "stdlib5/std/collections.lyr"
    t8 = (uint64_t)UINT64_C(9259542123273814144);
#line 247
    lyr_g_std_collections_emptyGroup = t8;
#line 248
    t9 = (uint64_t)UINT64_C(72340172838076673);
#line 248
    lyr_g_std_collections_lowBits = t9;
#line 249
    t10 = (uint64_t)UINT64_C(9259542123273814144);
#line 249
    lyr_g_std_collections_highBits = t10;
    return;
}

#line 1394 "stdlib5/std/core.lyr"
double lyr_std_core__extend__float_fromBits_3825afc5(uint64_t l0_b) {
    uint64_t t0 = 0;
    double t1 = 0;
    double t2 = 0;
bb0:;
#line 1394
    t0 = l0_b;
#line 1384
    t1 = (double)0.0;
#line 1394
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1394
    return t2;
}

#line 1415 "stdlib5/std/core.lyr"
float lyr_std_core__extend__float32_fromBits_bc3641ce(uint64_t l0_b) {
    uint64_t t0 = 0;
    float t1 = 0;
    float t2 = 0;
bb0:;
#line 1415
    t0 = l0_b;
#line 1405
    t1 = (float)0.0;
#line 1415
    t2 = LYR_FLOAT_FROM_BITS(t0, t1);
#line 1415
    return t2;
}


/* the program */
static int64_t lyr_entry(void) { lyr__globals__9ee5f9b5(); LyrErr *lyr_e = NULL; int64_t lyr_r = lyr_app_main_main(&lyr_e); if (LYR_UNLIKELY(lyr_e != NULL)) return lyr_err_report(lyr_e, lyr_error_message, lyr_error_cause); return lyr_r; }
int main(int argc, char **argv) { return lyr_run_main(argc, argv, lyr_entry); }
