/* The Unicode Character Database's answers std.core's `char` asks (design/v5/spec/10 B9 S4, C2):
 * the general category, the simple case mappings and White_Space — no more. The tables are
 * generated by tooling/unicode/gen.py from runtime/third_party/ucd/, the version pinned there. */
#ifndef LYR_UNICODE_H
#define LYR_UNICODE_H

#include "lyr/types.h"

/* The general category of `c`, an index into UAX #44's order (Lu, Ll, Lt, Lm, Lo, Mn, Mc, Me, Nd,
 * Nl, No, Pc, Pd, Ps, Pe, Pi, Pf, Po, Sm, Sc, Sk, So, Zs, Zl, Zp, Cc, Cf, Cs, Co, Cn) — std.core's
 * UnicodeCategory keeps the same order. */
int64_t lyr_unicode_category(uint32_t c);

/* The simple uppercase and lowercase mappings (UnicodeData.txt fields 12 and 13): one character for
 * one, `c` itself where none is given — `ß` stays `ß`. */
uint32_t lyr_unicode_upper(uint32_t c);
uint32_t lyr_unicode_lower(uint32_t c);

/* Whether `c` has the property White_Space (PropList.txt). */
bool lyr_unicode_white_space(uint32_t c);

#endif
